//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   uint4 DuranteSettings;             // Offset:    0 Size:    16
//   
//   struct
//   {
//       
//       float3 EyePosition;            // Offset:   16
//       float4x4 View;                 // Offset:   32
//       float4x4 Projection;           // Offset:   96
//       float4x4 ViewProjection;       // Offset:  160
//       float4x4 ViewInverse;          // Offset:  224
//       float4x4 ProjectionInverse;    // Offset:  288
//       float2 cameraNearFar;          // Offset:  352
//       float cameraNearTimesFar;      // Offset:  360
//       float cameraFarMinusNear;      // Offset:  364
//       float cameraFarMinusNearInv;   // Offset:  368
//       float2 ViewportWidthHeight;    // Offset:  372
//       float2 screenWidthHeightInv;   // Offset:  384
//       float3 GlobalAmbientColor;     // Offset:  400
//       float Time;                    // Offset:  412
//       float3 FakeRimLightDir;        // Offset:  416
//       float3 FogColor;               // Offset:  432
//       float4 FogRangeParameters;     // Offset:  448
//       float3 MiscParameters1;        // Offset:  464
//       float4 MiscParameters2;        // Offset:  480
//       float3 MonotoneMul;            // Offset:  496
//       float3 MonotoneAdd;            // Offset:  512
//       float3 UserClipPlane2;         // Offset:  528
//       float4 UserClipPlane;          // Offset:  544
//       float4 MiscParameters3;        // Offset:  560
//       float AdditionalShadowOffset;  // Offset:  576
//       float AlphaTestDirection;      // Offset:  580
//       float4 MiscParameters4;        // Offset:  592
//       float3 MiscParameters5;        // Offset:  608
//       float4 light1_attenuation;     // Offset:  624
//       float3 light2_position;        // Offset:  640
//       float3 light2_colorIntensity;  // Offset:  656
//       float4 light2_attenuation;     // Offset:  672
//
//   } scene;                           // Offset:   16 Size:   672
//   bool PhyreContextSwitches;         // Offset:  688 Size:     4 [unused]
//   bool PhyreMaterialSwitches;        // Offset:  692 Size:     4 [unused]
//   float4x4 World;                    // Offset:  704 Size:    64 [unused]
//   float4x4 WorldViewProjection;      // Offset:  768 Size:    64 [unused]
//   float GlobalTexcoordFactor;        // Offset:  832 Size:     4 [unused]
//   
//   struct
//   {
//       
//       float3 m_direction;            // Offset:  848
//       float3 m_colorIntensity;       // Offset:  864
//
//   } Light0;                          // Offset:  848 Size:    28
//   
//   struct
//   {
//       
//       float4x4 m_split0Transform;    // Offset:  880
//       float4x4 m_split1Transform;    // Offset:  944
//       float4 m_splitDistances;       // Offset: 1008
//
//   } LightShadow0;                    // Offset:  880 Size:   144
//   float GameMaterialID;              // Offset: 1024 Size:     4 [unused]
//      = 0x00000000 
//   float4 GameMaterialDiffuse;        // Offset: 1040 Size:    16
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000 
//   float4 GameMaterialEmission;       // Offset: 1056 Size:    16
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//   float GameMaterialMonotone;        // Offset: 1072 Size:     4
//      = 0x00000000 
//   float4 GameMaterialTexcoord;       // Offset: 1088 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 GameDitherParams;           // Offset: 1104 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//   float4 UVaMUvColor;                // Offset: 1120 Size:    16 [unused]
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000 
//   float4 UVaProjTexcoord;            // Offset: 1136 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 UVaMUvTexcoord;             // Offset: 1152 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 UVaMUv2Texcoord;            // Offset: 1168 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 UVaDuDvTexcoord;            // Offset: 1184 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float AlphaThreshold;              // Offset: 1200 Size:     4
//      = 0x3f000000 
//   float3 ShadowColorShift;           // Offset: 1204 Size:    12
//      = 0x3dcccccd 0x3ca3d70a 0x3ca3d70a 
//   float Shininess;                   // Offset: 1216 Size:     4
//      = 0x3f000000 
//   float SpecularPower;               // Offset: 1220 Size:     4
//      = 0x42480000 
//   float2 WindyGrassDirection;        // Offset: 1224 Size:     8 [unused]
//      = 0x00000000 0x00000000 
//   float WindyGrassSpeed;             // Offset: 1232 Size:     4 [unused]
//      = 0x3dcccccd 
//   float WindyGrassHomogenity;        // Offset: 1236 Size:     4 [unused]
//      = 0x40000000 
//   float WindyGrassScale;             // Offset: 1240 Size:     4 [unused]
//      = 0x3f800000 
//   float BloomIntensity;              // Offset: 1244 Size:     4
//      = 0x3f800000 
//   float4 PointLightParams;           // Offset: 1248 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//   float4 PointLightColor;            // Offset: 1264 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PointWrapSamplerState             sampler      NA          NA             s0      1 
// PointClampSamplerState            sampler      NA          NA             s1      1 
// LinearClampCmpSamplerState      sampler_c      NA          NA             s2      1 
// DiffuseMapSamplerSampler          sampler      NA          NA             s3      1 
// SpecularMapSamplerSampler         sampler      NA          NA             s4      1 
// DitherNoiseTexture                texture  float4          2d             t0      1 
// LightShadowMap0                   texture  float4          2d             t1      1 
// DiffuseMapSampler                 texture  float4          2d             t2      1 
// SpecularMapSampler                texture  float4          2d             t3      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xy  
// COLOR                    0   xyzw        1     NONE   float   xyzw
// COLOR                    1   xyzw        2     NONE   float   xyzw
// TEXCOORD                 0   xy          3     NONE   float   xy  
// TEXCOORD                 1   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyz         5     NONE   float   xyz 
// TEXCOORD                 9   xyzw        6     NONE   float   x   
// TEXCOORD                10   xyzw        7     NONE   float     zw
// SV_SampleIndex           0   x           8   SAMPLE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
// SV_TARGET                1   xyzw        1   TARGET   float   xyzw
// SV_TARGET                2   xyzw        2   TARGET   float   xyzw
//
// Pixel Shader runs at sample frequency
//
      0x00000000: ps_4_1
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_immediateConstantBuffer { { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0.250000, 0.250000, 0, 0},
                              { -0.250000, -0.250000, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { -0.125000, -0.375000, 0, 0},
                              { 0.375000, -0.125000, 0, 0},
                              { -0.375000, 0.125000, 0, 0},
                              { 0.125000, 0.375000, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0.062500, -0.187500, 0, 0},
                              { -0.062500, 0.187500, 0, 0},
                              { 0.312500, 0.062500, 0, 0},
                              { -0.187500, -0.312500, 0, 0},
                              { -0.312500, 0.312500, 0, 0},
                              { -0.437500, -0.062500, 0, 0},
                              { 0.187500, 0.437500, 0, 0},
                              { 0.437500, -0.437500, 0, 0} }
      0x00000494: dcl_constantbuffer CB0[78], immediateIndexed
      0x000004A4: dcl_sampler s0, mode_default
      0x000004B0: dcl_sampler s1, mode_default
      0x000004BC: dcl_sampler s2, mode_comparison
      0x000004C8: dcl_sampler s3, mode_default
      0x000004D4: dcl_sampler s4, mode_default
      0x000004E0: dcl_resource_texture2d (float,float,float,float) t0
      0x000004F0: dcl_resource_texture2d (float,float,float,float) t1
      0x00000500: dcl_resource_texture2d (float,float,float,float) t2
      0x00000510: dcl_resource_texture2d (float,float,float,float) t3
      0x00000520: dcl_input_ps_siv linear noperspective v0.xy, position
      0x00000530: dcl_input_ps linear v1.xyzw
      0x0000053C: dcl_input_ps linear v2.xyzw
      0x00000548: dcl_input_ps linear v3.xy
      0x00000554: dcl_input_ps linear v4.xyzw
      0x00000560: dcl_input_ps linear v5.xyz
      0x0000056C: dcl_input_ps linear v6.x
      0x00000578: dcl_input_ps linear v7.zw
      0x00000584: dcl_input_ps_sgv constant v8.x, sampleIndex
      0x00000594: dcl_output o0.xyzw
      0x000005A0: dcl_output o1.xyzw
      0x000005AC: dcl_output o2.xyzw
      0x000005B8: dcl_temps 8
   0  0x000005C0: mul r0.xy, v0.xyxx, l(0.250000, 0.250000, 0.000000, 0.000000)
   1  0x000005E8: sample r0.x, r0.xyxx, t0.xyzw, s0
   2  0x0000060C: add r0.x, -r0.x, v6.x
   3  0x0000062C: lt r0.x, r0.x, l(0.000000)
   4  0x00000648: discard_nz r0.x
   5  0x00000654: and r0.x, cb0[0].x, l(1)
   6  0x00000674: if_nz r0.x
   7  0x00000680:   deriv_rtx r0.xy, v3.xyxx
   8  0x00000694:   deriv_rty r0.zw, v3.xxxy
   9  0x000006A8:   ishl r1.x, cb0[0].y, l(3)
  10  0x000006C8:   iadd r1.x, r1.x, v8.x
  11  0x000006E4:   mul r0.zw, r0.zzzw, icb[r1.x + 0].yyyy
  12  0x00000704:   mad r0.xy, icb[r1.x + 0].xxxx, r0.xyxx, r0.zwzz
  13  0x0000072C:   add r0.xy, r0.xyxx, v3.xyxx
  14  0x00000748: else 
  15  0x0000074C:   mov r0.xy, v3.xyxx
  16  0x00000760: endif 
  17  0x00000764: sample r1.xyzw, r0.xyxx, t2.xyzw, s3
  18  0x00000788: mul r0.z, v1.w, cb0[75].x
  19  0x000007A8: mad r0.z, r1.w, v1.w, -r0.z
  20  0x000007D0: lt r0.z, r0.z, l(0.000000)
  21  0x000007EC: discard_nz r0.z
  22  0x000007F8: ge r0.z, cb0[63].y, v4.w
  23  0x00000818: if_nz r0.z
  24  0x00000824:   mad r2.xyz, cb0[53].xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), v4.xyzx
  25  0x00000858:   mad r2.xyz, v5.xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), r2.xyzx
  26  0x00000888:   lt r0.w, v4.w, cb0[63].x
  27  0x000008A8:   if_nz r0.w
  28  0x000008B4:     mov r2.w, l(1.000000)
  29  0x000008C8:     dp4 r3.x, r2.xyzw, cb0[55].xyzw
  30  0x000008E8:     dp4 r3.y, r2.xyzw, cb0[56].xyzw
  31  0x00000908:     dp4 r3.z, r2.xyzw, cb0[57].xyzw
  32  0x00000928:     and r0.w, cb0[0].x, l(2)
  33  0x00000948:     if_nz r0.w
  34  0x00000954:       sample_c_lz r0.w, r3.xyxx, t1.xxxx, s2, r3.z
  35  0x00000980:     else 
  36  0x00000984:       div r1.w, l(25.000000), cb0[63].y
  37  0x000009A4:       and r3.w, cb0[0].x, l(16)
  38  0x000009C4:       if_nz r3.w
  39  0x000009D0:         mul r4.xy, r1.wwww, l(0.000937, 0.001875, 0.000000, 0.000000)
  40  0x000009F8:         add r3.w, r3.z, l(-6.000000)
  41  0x00000A14:         mul r4.xy, r3.wwww, r4.xyxx
  42  0x00000A30:         div r4.xy, r4.xyxx, r3.zzzz
  43  0x00000A4C:         dp2 r3.w, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
  44  0x00000A74:         frc r3.w, r3.w
  45  0x00000A88:         mul r3.w, r3.w, l(52.982918)
  46  0x00000AA4:         frc r3.w, r3.w
  47  0x00000AB8:         mul r3.w, r3.w, l(6.283185)
  48  0x00000AD4:         mov r4.zw, l(0,0,0,0)
  49  0x00000AF4:         mov r5.x, l(0)
  50  0x00000B08:         loop 
  51  0x00000B0C:           ige r5.y, r5.x, l(16)
  52  0x00000B28:           breakc_nz r5.y
  53  0x00000B34:           itof r5.y, r5.x
  54  0x00000B48:           add r5.z, r5.y, l(0.500000)
  55  0x00000B64:           sqrt r5.z, r5.z
  56  0x00000B78:           mul r5.z, r5.z, l(0.250000)
  57  0x00000B94:           mad r5.y, r5.y, l(2.400000), r3.w
  58  0x00000BB8:           sincos r6.x, r7.x, r5.y
  59  0x00000BD4:           mul r7.x, r5.z, r7.x
  60  0x00000BF0:           mul r7.y, r5.z, r6.x
  61  0x00000C0C:           mad r5.yz, r7.xxyx, r4.xxyx, r3.xxyx
  62  0x00000C30:           sample_l r5.y, r5.yzyy, t1.yxzw, s1, l(0.000000)
  63  0x00000C5C:           lt r5.z, r5.y, r3.z
  64  0x00000C78:           add r6.y, r4.w, r5.y
  65  0x00000C94:           add r6.x, r4.z, l(1.000000)
  66  0x00000CB0:           movc r4.zw, r5.zzzz, r6.xxxy, r4.zzzw
  67  0x00000CD4:           iadd r5.x, r5.x, l(1)
  68  0x00000CF0:         endloop 
  69  0x00000CF4:         ge r4.x, r4.z, l(1.000000)
  70  0x00000D10:         if_nz r4.x
  71  0x00000D1C:           mul r4.xy, r1.wwww, l(0.000625, 0.001250, 0.000000, 0.000000)
  72  0x00000D44:           div r4.z, r4.w, r4.z
  73  0x00000D60:           add r4.z, r3.z, -r4.z
  74  0x00000D80:           min r4.z, r4.z, l(0.070000)
  75  0x00000D9C:           mul r4.z, r4.z, l(60.000000)
  76  0x00000DB8:           mul r4.xy, r4.xyxx, r4.zzzz
  77  0x00000DD4:           resinfo r4.zw, l(0), t1.zwxy
  78  0x00000DF0:           div r4.zw, l(0.000000, 0.000000, 0.500000, 0.500000), r4.zzzw
  79  0x00000E18:           max r4.xy, r4.xyxx, r4.zwzz
  80  0x00000E34:           mov r4.zw, l(0,0,0,0)
  81  0x00000E54:           loop 
  82  0x00000E58:             ige r5.x, r4.w, l(16)
  83  0x00000E74:             breakc_nz r5.x
  84  0x00000E80:             itof r5.x, r4.w
  85  0x00000E94:             add r5.y, r5.x, l(0.500000)
  86  0x00000EB0:             sqrt r5.y, r5.y
  87  0x00000EC4:             mul r5.y, r5.y, l(0.250000)
  88  0x00000EE0:             mad r5.x, r5.x, l(2.400000), r3.w
  89  0x00000F04:             sincos r5.x, r6.x, r5.x
  90  0x00000F20:             mul r6.x, r5.y, r6.x
  91  0x00000F3C:             mul r6.y, r5.x, r5.y
  92  0x00000F58:             mul r5.xy, r4.xyxx, r6.xyxx
  93  0x00000F74:             mad r5.xy, r5.xyxx, l(3.000000, 3.000000, 0.000000, 0.000000), r3.xyxx
  94  0x00000FA4:             sample_c_lz r5.x, r5.xyxx, t1.xxxx, s2, r3.z
  95  0x00000FD0:             add r4.z, r4.z, r5.x
  96  0x00000FEC:             iadd r4.w, r4.w, l(1)
  97  0x00001008:           endloop 
  98  0x0000100C:           mul r0.w, r4.z, l(0.062500)
  99  0x00001028:         else 
 100  0x0000102C:           mov r0.w, l(1.000000)
 101  0x00001040:         endif 
 102  0x00001044:       else 
 103  0x00001048:         and r3.w, cb0[0].x, l(8)
 104  0x00001068:         if_nz r3.w
 105  0x00001074:           mul r4.xy, r1.wwww, l(0.000375, 0.000750, 0.000000, 0.000000)
 106  0x0000109C:           dp2 r3.w, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
 107  0x000010C4:           frc r3.w, r3.w
 108  0x000010D8:           mul r3.w, r3.w, l(52.982918)
 109  0x000010F4:           frc r3.w, r3.w
 110  0x00001108:           mul r3.w, r3.w, l(6.283185)
 111  0x00001124:           mov r4.zw, l(0,0,0,0)
 112  0x00001144:           loop 
 113  0x00001148:             ige r5.x, r4.w, l(16)
 114  0x00001164:             breakc_nz r5.x
 115  0x00001170:             itof r5.x, r4.w
 116  0x00001184:             add r5.y, r5.x, l(0.500000)
 117  0x000011A0:             sqrt r5.y, r5.y
 118  0x000011B4:             mul r5.y, r5.y, l(0.250000)
 119  0x000011D0:             mad r5.x, r5.x, l(2.400000), r3.w
 120  0x000011F4:             sincos r5.x, r6.x, r5.x
 121  0x00001210:             mul r6.x, r5.y, r6.x
 122  0x0000122C:             mul r6.y, r5.x, r5.y
 123  0x00001248:             mul r5.xy, r4.xyxx, r6.xyxx
 124  0x00001264:             mad r5.xy, r5.xyxx, l(3.000000, 3.000000, 0.000000, 0.000000), r3.xyxx
 125  0x00001294:             sample_c_lz r5.x, r5.xyxx, t1.xxxx, s2, r3.z
 126  0x000012C0:             add r4.z, r4.z, r5.x
 127  0x000012DC:             iadd r4.w, r4.w, l(1)
 128  0x000012F8:           endloop 
 129  0x000012FC:           mul r0.w, r4.z, l(0.062500)
 130  0x00001318:         else 
 131  0x0000131C:           dp4 r3.w, r2.xyzw, cb0[58].xyzw
 132  0x0000133C:           and r4.x, cb0[0].x, l(4)
 133  0x0000135C:           if_nz r4.x
 134  0x00001368:             mul r4.xy, r3.wwww, cb0[37].xyxx
 135  0x00001388:             sample_c_lz r4.z, r3.xyxx, t1.xxxx, s2, r3.z
 136  0x000013B4:             mul r5.xy, r1.wwww, -r4.xyxx
 137  0x000013D4:             mov r5.z, l(0)
 138  0x000013E8:             add r5.xyz, r3.xyzx, r5.xyzx
 139  0x00001404:             sample_c_lz r4.w, r5.xyxx, t1.xxxx, s2, r5.z
 140  0x00001430:             mul r4.w, r4.w, l(0.062500)
 141  0x0000144C:             mad r4.z, r4.z, l(0.500000), r4.w
 142  0x00001470:             mul r5.x, r1.w, r4.x
 143  0x0000148C:             mul r5.y, r1.w, -r4.y
 144  0x000014AC:             mov r5.z, l(0)
 145  0x000014C0:             add r6.xyz, r3.xyzx, r5.xyzx
 146  0x000014DC:             sample_c_lz r4.w, r6.xyxx, t1.xxxx, s2, r6.z
 147  0x00001508:             mad r4.z, r4.w, l(0.062500), r4.z
 148  0x0000152C:             mul r6.x, r1.w, -r4.x
 149  0x0000154C:             mul r6.y, r1.w, r4.y
 150  0x00001568:             mov r6.z, l(0)
 151  0x0000157C:             add r7.xyz, r3.xyzx, r6.xyzx
 152  0x00001598:             sample_c_lz r4.w, r7.xyxx, t1.xxxx, s2, r7.z
 153  0x000015C4:             mad r4.z, r4.w, l(0.062500), r4.z
 154  0x000015E8:             mul r7.xy, r1.wwww, r4.xyxx
 155  0x00001604:             mov r7.z, l(0)
 156  0x00001618:             add r4.xyw, r3.xyxz, r7.xyxz
 157  0x00001634:             sample_c_lz r4.x, r4.xyxx, t1.xxxx, s2, r4.w
 158  0x00001660:             mad r4.x, r4.x, l(0.062500), r4.z
 159  0x00001684:             add r4.yzw, r3.xxyz, r5.zzyz
 160  0x000016A0:             sample_c_lz r4.y, r4.yzyy, t1.xxxx, s2, r4.w
 161  0x000016CC:             mad r4.x, r4.y, l(0.062500), r4.x
 162  0x000016F0:             add r4.yzw, r3.xxyz, r6.xxzz
 163  0x0000170C:             sample_c_lz r4.y, r4.yzyy, t1.xxxx, s2, r4.w
 164  0x00001738:             mad r4.x, r4.y, l(0.062500), r4.x
 165  0x0000175C:             add r4.yzw, r3.xxyz, r7.xxzz
 166  0x00001778:             sample_c_lz r4.y, r4.yzyy, t1.xxxx, s2, r4.w
 167  0x000017A4:             mad r4.x, r4.y, l(0.062500), r4.x
 168  0x000017C8:             add r4.yzw, r3.xxyz, r7.zzyz
 169  0x000017E4:             sample_c_lz r4.y, r4.yzyy, t1.xxxx, s2, r4.w
 170  0x00001810:             mad r0.w, r4.y, l(0.062500), r4.x
 171  0x00001834:           else 
 172  0x00001838:             mul r4.xy, r3.wwww, cb0[37].xyxx
 173  0x00001858:             sample_c_lz r3.w, r3.xyxx, t1.xxxx, s2, r3.z
 174  0x00001884:             mul r5.xy, r1.wwww, -r4.xyxx
 175  0x000018A4:             mov r5.z, l(0)
 176  0x000018B8:             add r5.xyz, r3.xyzx, r5.xyzx
 177  0x000018D4:             sample_c_lz r4.z, r5.xyxx, t1.xxxx, s2, r5.z
 178  0x00001900:             mul r4.z, r4.z, cb0[38].y
 179  0x00001920:             mad r3.w, r3.w, cb0[38].x, r4.z
 180  0x00001948:             mul r5.x, r1.w, r4.x
 181  0x00001964:             mul r5.y, r1.w, -r4.y
 182  0x00001984:             mov r5.z, l(0)
 183  0x00001998:             add r5.xyz, r3.xyzx, r5.xyzx
 184  0x000019B4:             sample_c_lz r4.z, r5.xyxx, t1.xxxx, s2, r5.z
 185  0x000019E0:             mad r3.w, r4.z, cb0[38].y, r3.w
 186  0x00001A08:             mul r5.x, r1.w, -r4.x
 187  0x00001A28:             mul r5.y, r1.w, r4.y
 188  0x00001A44:             mov r5.z, l(0)
 189  0x00001A58:             add r5.xyz, r3.xyzx, r5.xyzx
 190  0x00001A74:             sample_c_lz r4.z, r5.xyxx, t1.xxxx, s2, r5.z
 191  0x00001AA0:             mad r3.w, r4.z, cb0[38].y, r3.w
 192  0x00001AC8:             mul r4.xy, r1.wwww, r4.xyxx
 193  0x00001AE4:             mov r4.z, l(0)
 194  0x00001AF8:             add r3.xyz, r3.xyzx, r4.xyzx
 195  0x00001B14:             sample_c_lz r1.w, r3.xyxx, t1.xxxx, s2, r3.z
 196  0x00001B40:             mad r0.w, r1.w, cb0[38].y, r3.w
 197  0x00001B68:           endif 
 198  0x00001B6C:         endif 
 199  0x00001B70:       endif 
 200  0x00001B74:     endif 
 201  0x00001B78:   else 
 202  0x00001B7C:     mov r2.w, l(1.000000)
 203  0x00001B90:     dp4 r3.x, r2.xyzw, cb0[59].xyzw
 204  0x00001BB0:     dp4 r3.y, r2.xyzw, cb0[60].xyzw
 205  0x00001BD0:     dp4 r3.z, r2.xyzw, cb0[61].xyzw
 206  0x00001BF0:     and r1.w, cb0[0].x, l(2)
 207  0x00001C10:     if_nz r1.w
 208  0x00001C1C:       sample_c_lz r0.w, r3.xyxx, t1.xxxx, s2, r3.z
 209  0x00001C48:     else 
 210  0x00001C4C:       div r1.w, l(10.000000), cb0[63].y
 211  0x00001C6C:       and r3.w, cb0[0].x, l(16)
 212  0x00001C8C:       if_nz r3.w
 213  0x00001C98:         mul r4.xy, r1.wwww, l(0.000937, 0.001875, 0.000000, 0.000000)
 214  0x00001CC0:         add r3.w, r3.z, l(-6.000000)
 215  0x00001CDC:         mul r4.xy, r3.wwww, r4.xyxx
 216  0x00001CF8:         div r4.xy, r4.xyxx, r3.zzzz
 217  0x00001D14:         dp2 r3.w, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
 218  0x00001D3C:         frc r3.w, r3.w
 219  0x00001D50:         mul r3.w, r3.w, l(52.982918)
 220  0x00001D6C:         frc r3.w, r3.w
 221  0x00001D80:         mul r3.w, r3.w, l(6.283185)
 222  0x00001D9C:         mov r4.zw, l(0,0,0,0)
 223  0x00001DBC:         mov r5.x, l(0)
 224  0x00001DD0:         loop 
 225  0x00001DD4:           ige r5.y, r5.x, l(16)
 226  0x00001DF0:           breakc_nz r5.y
 227  0x00001DFC:           itof r5.y, r5.x
 228  0x00001E10:           add r5.z, r5.y, l(0.500000)
 229  0x00001E2C:           sqrt r5.z, r5.z
 230  0x00001E40:           mul r5.z, r5.z, l(0.250000)
 231  0x00001E5C:           mad r5.y, r5.y, l(2.400000), r3.w
 232  0x00001E80:           sincos r6.x, r7.x, r5.y
 233  0x00001E9C:           mul r7.x, r5.z, r7.x
 234  0x00001EB8:           mul r7.y, r5.z, r6.x
 235  0x00001ED4:           mad r5.yz, r7.xxyx, r4.xxyx, r3.xxyx
 236  0x00001EF8:           sample_l r5.y, r5.yzyy, t1.yxzw, s1, l(0.000000)
 237  0x00001F24:           lt r5.z, r5.y, r3.z
 238  0x00001F40:           add r6.y, r4.w, r5.y
 239  0x00001F5C:           add r6.x, r4.z, l(1.000000)
 240  0x00001F78:           movc r4.zw, r5.zzzz, r6.xxxy, r4.zzzw
 241  0x00001F9C:           iadd r5.x, r5.x, l(1)
 242  0x00001FB8:         endloop 
 243  0x00001FBC:         ge r4.x, r4.z, l(1.000000)
 244  0x00001FD8:         if_nz r4.x
 245  0x00001FE4:           mul r4.xy, r1.wwww, l(0.000625, 0.001250, 0.000000, 0.000000)
 246  0x0000200C:           div r4.z, r4.w, r4.z
 247  0x00002028:           add r4.z, r3.z, -r4.z
 248  0x00002048:           min r4.z, r4.z, l(0.070000)
 249  0x00002064:           mul r4.z, r4.z, l(60.000000)
 250  0x00002080:           mul r4.xy, r4.xyxx, r4.zzzz
 251  0x0000209C:           resinfo r4.zw, l(0), t1.zwxy
 252  0x000020B8:           div r4.zw, l(0.000000, 0.000000, 0.500000, 0.500000), r4.zzzw
 253  0x000020E0:           max r4.xy, r4.xyxx, r4.zwzz
 254  0x000020FC:           mov r4.zw, l(0,0,0,0)
 255  0x0000211C:           loop 
 256  0x00002120:             ige r5.x, r4.w, l(16)
 257  0x0000213C:             breakc_nz r5.x
 258  0x00002148:             itof r5.x, r4.w
 259  0x0000215C:             add r5.y, r5.x, l(0.500000)
 260  0x00002178:             sqrt r5.y, r5.y
 261  0x0000218C:             mul r5.y, r5.y, l(0.250000)
 262  0x000021A8:             mad r5.x, r5.x, l(2.400000), r3.w
 263  0x000021CC:             sincos r5.x, r6.x, r5.x
 264  0x000021E8:             mul r6.x, r5.y, r6.x
 265  0x00002204:             mul r6.y, r5.x, r5.y
 266  0x00002220:             mul r5.xy, r4.xyxx, r6.xyxx
 267  0x0000223C:             mad r5.xy, r5.xyxx, l(3.000000, 3.000000, 0.000000, 0.000000), r3.xyxx
 268  0x0000226C:             sample_c_lz r5.x, r5.xyxx, t1.xxxx, s2, r3.z
 269  0x00002298:             add r4.z, r4.z, r5.x
 270  0x000022B4:             iadd r4.w, r4.w, l(1)
 271  0x000022D0:           endloop 
 272  0x000022D4:           mul r0.w, r4.z, l(0.062500)
 273  0x000022F0:         else 
 274  0x000022F4:           mov r0.w, l(1.000000)
 275  0x00002308:         endif 
 276  0x0000230C:       else 
 277  0x00002310:         and r3.w, cb0[0].x, l(8)
 278  0x00002330:         if_nz r3.w
 279  0x0000233C:           mul r4.xy, r1.wwww, l(0.000375, 0.000750, 0.000000, 0.000000)
 280  0x00002364:           dp2 r3.w, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
 281  0x0000238C:           frc r3.w, r3.w
 282  0x000023A0:           mul r3.w, r3.w, l(52.982918)
 283  0x000023BC:           frc r3.w, r3.w
 284  0x000023D0:           mul r3.w, r3.w, l(6.283185)
 285  0x000023EC:           mov r4.zw, l(0,0,0,0)
 286  0x0000240C:           loop 
 287  0x00002410:             ige r5.x, r4.w, l(16)
 288  0x0000242C:             breakc_nz r5.x
 289  0x00002438:             itof r5.x, r4.w
 290  0x0000244C:             add r5.y, r5.x, l(0.500000)
 291  0x00002468:             sqrt r5.y, r5.y
 292  0x0000247C:             mul r5.y, r5.y, l(0.250000)
 293  0x00002498:             mad r5.x, r5.x, l(2.400000), r3.w
 294  0x000024BC:             sincos r5.x, r6.x, r5.x
 295  0x000024D8:             mul r6.x, r5.y, r6.x
 296  0x000024F4:             mul r6.y, r5.x, r5.y
 297  0x00002510:             mul r5.xy, r4.xyxx, r6.xyxx
 298  0x0000252C:             mad r5.xy, r5.xyxx, l(3.000000, 3.000000, 0.000000, 0.000000), r3.xyxx
 299  0x0000255C:             sample_c_lz r5.x, r5.xyxx, t1.xxxx, s2, r3.z
 300  0x00002588:             add r4.z, r4.z, r5.x
 301  0x000025A4:             iadd r4.w, r4.w, l(1)
 302  0x000025C0:           endloop 
 303  0x000025C4:           mul r0.w, r4.z, l(0.062500)
 304  0x000025E0:         else 
 305  0x000025E4:           dp4 r2.x, r2.xyzw, cb0[62].xyzw
 306  0x00002604:           and r2.y, cb0[0].x, l(4)
 307  0x00002624:           if_nz r2.y
 308  0x00002630:             mul r2.yz, r2.xxxx, cb0[37].xxyx
 309  0x00002650:             sample_c_lz r2.w, r3.xyxx, t1.xxxx, s2, r3.z
 310  0x0000267C:             mul r4.xy, r1.wwww, -r2.yzyy
 311  0x0000269C:             mov r4.z, l(0)
 312  0x000026B0:             add r4.xyz, r3.xyzx, r4.xyzx
 313  0x000026CC:             sample_c_lz r3.w, r4.xyxx, t1.xxxx, s2, r4.z
 314  0x000026F8:             mul r3.w, r3.w, l(0.062500)
 315  0x00002714:             mad r2.w, r2.w, l(0.500000), r3.w
 316  0x00002738:             mul r4.x, r1.w, r2.y
 317  0x00002754:             mul r4.y, r1.w, -r2.z
 318  0x00002774:             mov r4.z, l(0)
 319  0x00002788:             add r5.xyz, r3.xyzx, r4.xyzx
 320  0x000027A4:             sample_c_lz r3.w, r5.xyxx, t1.xxxx, s2, r5.z
 321  0x000027D0:             mad r2.w, r3.w, l(0.062500), r2.w
 322  0x000027F4:             mul r5.x, r1.w, -r2.y
 323  0x00002814:             mul r5.y, r1.w, r2.z
 324  0x00002830:             mov r5.z, l(0)
 325  0x00002844:             add r6.xyz, r3.xyzx, r5.xyzx
 326  0x00002860:             sample_c_lz r3.w, r6.xyxx, t1.xxxx, s2, r6.z
 327  0x0000288C:             mad r2.w, r3.w, l(0.062500), r2.w
 328  0x000028B0:             mul r6.xy, r1.wwww, r2.yzyy
 329  0x000028CC:             mov r6.z, l(0)
 330  0x000028E0:             add r7.xyz, r3.xyzx, r6.xyzx
 331  0x000028FC:             sample_c_lz r2.y, r7.xyxx, t1.xxxx, s2, r7.z
 332  0x00002928:             mad r2.y, r2.y, l(0.062500), r2.w
 333  0x0000294C:             add r4.xyz, r3.xyzx, r4.zyzz
 334  0x00002968:             sample_c_lz r2.z, r4.xyxx, t1.xxxx, s2, r4.z
 335  0x00002994:             mad r2.y, r2.z, l(0.062500), r2.y
 336  0x000029B8:             add r4.xyz, r3.xyzx, r5.xzzx
 337  0x000029D4:             sample_c_lz r2.z, r4.xyxx, t1.xxxx, s2, r4.z
 338  0x00002A00:             mad r2.y, r2.z, l(0.062500), r2.y
 339  0x00002A24:             add r4.xyz, r3.xyzx, r6.xzzx
 340  0x00002A40:             sample_c_lz r2.z, r4.xyxx, t1.xxxx, s2, r4.z
 341  0x00002A6C:             mad r2.y, r2.z, l(0.062500), r2.y
 342  0x00002A90:             add r4.xyz, r3.xyzx, r6.zyzz
 343  0x00002AAC:             sample_c_lz r2.z, r4.xyxx, t1.xxxx, s2, r4.z
 344  0x00002AD8:             mad r0.w, r2.z, l(0.062500), r2.y
 345  0x00002AFC:           else 
 346  0x00002B00:             mul r2.xy, r2.xxxx, cb0[37].xyxx
 347  0x00002B20:             sample_c_lz r2.z, r3.xyxx, t1.xxxx, s2, r3.z
 348  0x00002B4C:             mul r4.xy, r1.wwww, -r2.xyxx
 349  0x00002B6C:             mov r4.z, l(0)
 350  0x00002B80:             add r4.xyz, r3.xyzx, r4.xyzx
 351  0x00002B9C:             sample_c_lz r2.w, r4.xyxx, t1.xxxx, s2, r4.z
 352  0x00002BC8:             mul r2.w, r2.w, cb0[38].y
 353  0x00002BE8:             mad r2.z, r2.z, cb0[38].x, r2.w
 354  0x00002C10:             mul r4.x, r1.w, r2.x
 355  0x00002C2C:             mul r4.y, r1.w, -r2.y
 356  0x00002C4C:             mov r4.z, l(0)
 357  0x00002C60:             add r4.xyz, r3.xyzx, r4.xyzx
 358  0x00002C7C:             sample_c_lz r2.w, r4.xyxx, t1.xxxx, s2, r4.z
 359  0x00002CA8:             mad r2.z, r2.w, cb0[38].y, r2.z
 360  0x00002CD0:             mul r4.x, r1.w, -r2.x
 361  0x00002CF0:             mul r4.y, r1.w, r2.y
 362  0x00002D0C:             mov r4.z, l(0)
 363  0x00002D20:             add r4.xyz, r3.xyzx, r4.xyzx
 364  0x00002D3C:             sample_c_lz r2.w, r4.xyxx, t1.xxxx, s2, r4.z
 365  0x00002D68:             mad r2.z, r2.w, cb0[38].y, r2.z
 366  0x00002D90:             mul r4.xy, r1.wwww, r2.xyxx
 367  0x00002DAC:             mov r4.z, l(0)
 368  0x00002DC0:             add r2.xyw, r3.xyxz, r4.xyxz
 369  0x00002DDC:             sample_c_lz r1.w, r2.xyxx, t1.xxxx, s2, r2.w
 370  0x00002E08:             mad r0.w, r1.w, cb0[38].y, r2.z
 371  0x00002E30:           endif 
 372  0x00002E34:         endif 
 373  0x00002E38:       endif 
 374  0x00002E3C:     endif 
 375  0x00002E40:   endif 
 376  0x00002E44: else 
 377  0x00002E48:   mov r0.w, l(1.000000)
 378  0x00002E5C: endif 
 379  0x00002E60: lt r1.w, v4.w, cb0[63].x
 380  0x00002E80: add r2.x, v4.w, -cb0[63].x
 381  0x00002EA4: add r2.y, -cb0[63].x, cb0[63].y
 382  0x00002ECC: div_sat r2.x, r2.x, r2.y
 383  0x00002EE8: movc r1.w, r1.w, l(0), r2.x
 384  0x00002F0C: mul r2.x, r1.w, r1.w
 385  0x00002F28: mul r1.w, r1.w, r2.x
 386  0x00002F44: movc r0.z, r0.z, r1.w, l(1.000000)
 387  0x00002F68: add r1.w, v4.y, -cb0[30].y
 388  0x00002F8C: mul r1.w, |r1.w|, cb0[30].x
 389  0x00002FB0: min r1.w, r1.w, l(1.000000)
 390  0x00002FCC: mul r2.x, r1.w, r1.w
 391  0x00002FE8: mul r1.w, r1.w, r2.x
 392  0x00003004: ge r2.x, l(0.000000), cb0[30].x
 393  0x00003024: movc r1.w, r2.x, l(0), r1.w
 394  0x00003048: add r0.z, r0.z, r1.w
 395  0x00003064: dp3 r1.w, v5.xyzx, cb0[53].xyzx
 396  0x00003084: mad r1.w, r1.w, l(0.500000), l(0.500000)
 397  0x000030A8: mul r2.x, cb0[37].w, l(0.400000)
 398  0x000030C8: max r2.y, -v5.y, l(0.000000)
 399  0x000030E8: mad r2.x, -r2.x, r2.y, l(0.400000)
 400  0x00003110: lt r2.y, r2.x, r1.w
 401  0x0000312C: add r1.w, r1.w, -r2.x
 402  0x0000314C: add r2.x, -r2.x, l(1.000000)
 403  0x0000316C: div r1.w, r1.w, r2.x
 404  0x00003188: and r1.w, r1.w, r2.y
 405  0x000031A4: add r1.w, -r1.w, l(1.000000)
 406  0x000031C4: mul r2.x, r1.w, r1.w
 407  0x000031E0: mad r0.z, r1.w, r2.x, r0.z
 408  0x00003204: min r0.z, r0.z, l(1.000000)
 409  0x00003220: add r0.z, r0.z, r0.w
 410  0x0000323C: min r0.z, r0.z, l(1.000000)
 411  0x00003258: add r0.w, -r0.z, l(1.000000)
 412  0x00003278: add r1.w, -cb0[30].w, l(1.000000)
 413  0x0000329C: mad r0.z, r0.w, r1.w, r0.z
 414  0x000032C0: add r0.w, -r0.z, l(1.000000)
 415  0x000032E0: add r1.w, -cb0[66].w, l(1.000000)
 416  0x00003304: mad r0.z, r0.w, r1.w, r0.z
 417  0x00003328: sample r0.x, r0.xyxx, t3.xyzw, s4
 418  0x0000334C: add r0.y, r0.x, l(1.000000)
 419  0x00003368: mul r0.y, r0.y, l(0.500000)
 420  0x00003384: mul r2.xyz, r0.yyyy, cb0[54].xyzx
 421  0x000033A4: mul r0.y, r0.z, r0.z
 422  0x000033C0: mul r2.xyz, r0.yyyy, r2.xyzx
 423  0x000033DC: dp3 r0.y, v5.xyzx, v5.xyzx
 424  0x000033F8: rsq r0.y, r0.y
 425  0x0000340C: mul r3.xyz, r0.yyyy, v5.xyzx
 426  0x00003428: add r4.xyz, -v4.xyzx, cb0[1].xyzx
 427  0x0000344C: dp3 r0.y, r4.xyzx, r4.xyzx
 428  0x00003468: rsq r0.y, r0.y
 429  0x0000347C: dp3 r0.w, cb0[53].xyzx, r3.xyzx
 430  0x0000349C: mad r0.w, r0.w, l(0.500000), l(0.500000)
 431  0x000034C0: mad r4.xyz, r4.xyzx, r0.yyyy, cb0[53].xyzx
 432  0x000034E8: dp3 r0.y, r4.xyzx, r4.xyzx
 433  0x00003504: rsq r0.y, r0.y
 434  0x00003518: mul r4.xyz, r0.yyyy, r4.xyzx
 435  0x00003534: dp3_sat r0.y, r3.xyzx, r4.xyzx
 436  0x00003550: log r0.y, r0.y
 437  0x00003564: mul r0.xy, r0.xyxx, cb0[76].xyxx
 438  0x00003584: exp r0.y, r0.y
 439  0x00003598: min r0.y, r0.y, l(1.000000)
 440  0x000035B4: mul r0.xw, r0.xxxw, r0.yyyw
 441  0x000035D0: mad r4.xyz, cb0[54].xyzx, r0.wwww, cb0[25].xyzx
 442  0x000035FC: min r4.xyz, r4.xyzx, l(1.500000, 1.500000, 1.500000, 0.000000)
 443  0x00003624: mad r0.xyw, cb0[54].xyxz, r0.xxxx, r4.xyxz
 444  0x0000364C: add r0.z, -r0.z, l(1.000000)
 445  0x0000366C: mad r4.xyz, r0.xywx, cb0[29].xyzx, -r0.xywx
 446  0x00003698: mad r0.xyz, r0.zzzz, r4.xyzx, r0.xywx
 447  0x000036BC: add r2.xyz, r2.xyzx, r2.xyzx
 448  0x000036D8: max r2.xyz, r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 449  0x00003700: min r4.xyz, r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 450  0x00003728: add r4.xyz, -r4.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 451  0x00003754: mul r4.xyz, r4.xyzx, cb0[75].yzwy
 452  0x00003774: mad r0.xyz, r4.xyzx, r2.xyzx, r0.xyzx
 453  0x00003798: mul r0.xyz, r0.xyzx, v1.xyzx
 454  0x000037B4: mul r0.xyz, r0.xyzx, r1.xyzx
 455  0x000037D0: mad r0.xyz, r0.xyzx, cb0[65].xyzx, cb0[66].xyzx
 456  0x000037FC: add r0.xyz, r0.xyzx, v2.xyzx
 457  0x00003818: add r1.xyz, -r0.xyzx, cb0[27].xyzx
 458  0x0000383C: mad r0.xyz, v2.wwww, r1.xyzx, r0.xyzx
 459  0x00003860: dp3 r0.w, r0.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
 460  0x00003888: mad r1.xyz, r0.wwww, cb0[31].xyzx, cb0[32].xyzx
 461  0x000038B4: add r1.xyz, -r0.xyzx, r1.xyzx
 462  0x000038D4: mad r0.xyz, cb0[67].xxxx, r1.xyzx, r0.xyzx
 463  0x000038FC: mul r1.xyz, r0.xyzx, cb0[77].wwww
 464  0x0000391C: dp3 r0.w, r1.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
 465  0x00003944: add r0.w, r0.w, -cb0[30].z
 466  0x00003968: max r0.w, r0.w, l(0.000000)
 467  0x00003984: mul r0.w, r0.w, l(0.500000)
 468  0x000039A0: min o0.w, r0.w, l(1.000000)
 469  0x000039BC: mad o1.xyz, r3.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
 470  0x000039F8: div r0.w, v7.z, v7.w
 471  0x00003A14: mul r1.x, r0.w, l(256.000000)
 472  0x00003A30: round_z r1.x, r1.x
 473  0x00003A44: mad r0.w, r0.w, l(256.000000), -r1.x
 474  0x00003A6C: mul r1.w, r0.w, l(256.000000)
 475  0x00003A88: round_z r1.y, r1.w
 476  0x00003A9C: mad r1.z, r0.w, l(256.000000), -r1.y
 477  0x00003AC4: mul o2.xyz, r1.xyzx, l(0.003906, 0.003906, 1.000000, 0.000000)
 478  0x00003AEC: mov o0.xyz, r0.xyzx
 479  0x00003B00: mov o1.w, l(0.750000)
 480  0x00003B14: mov o2.w, l(0)
 481  0x00003B28: ret 
// Approximately 482 instruction slots used
