//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   uint4 DuranteSettings;             // Offset:    0 Size:    16
//   
//   struct
//   {
//       
//       float3 EyePosition;            // Offset:   16
//       float4x4 View;                 // Offset:   32
//       float4x4 Projection;           // Offset:   96
//       float4x4 ViewProjection;       // Offset:  160
//       float4x4 ViewInverse;          // Offset:  224
//       float4x4 ProjectionInverse;    // Offset:  288
//       float2 cameraNearFar;          // Offset:  352
//       float cameraNearTimesFar;      // Offset:  360
//       float cameraFarMinusNear;      // Offset:  364
//       float cameraFarMinusNearInv;   // Offset:  368
//       float2 ViewportWidthHeight;    // Offset:  372
//       float2 screenWidthHeightInv;   // Offset:  384
//       float3 GlobalAmbientColor;     // Offset:  400
//       float Time;                    // Offset:  412
//       float3 FakeRimLightDir;        // Offset:  416
//       float3 FogColor;               // Offset:  432
//       float4 FogRangeParameters;     // Offset:  448
//       float3 MiscParameters1;        // Offset:  464
//       float4 MiscParameters2;        // Offset:  480
//       float3 MonotoneMul;            // Offset:  496
//       float3 MonotoneAdd;            // Offset:  512
//       float3 UserClipPlane2;         // Offset:  528
//       float4 UserClipPlane;          // Offset:  544
//       float4 MiscParameters3;        // Offset:  560
//       float AdditionalShadowOffset;  // Offset:  576
//       float AlphaTestDirection;      // Offset:  580
//       float4 MiscParameters4;        // Offset:  592
//       float3 MiscParameters5;        // Offset:  608
//       float4 light1_attenuation;     // Offset:  624
//       float3 light2_position;        // Offset:  640
//       float3 light2_colorIntensity;  // Offset:  656
//       float4 light2_attenuation;     // Offset:  672
//
//   } scene;                           // Offset:   16 Size:   672
//   bool PhyreContextSwitches;         // Offset:  688 Size:     4 [unused]
//   bool PhyreMaterialSwitches;        // Offset:  692 Size:     4 [unused]
//   float4x4 World;                    // Offset:  704 Size:    64 [unused]
//   float4x4 WorldViewProjection;      // Offset:  768 Size:    64 [unused]
//   float GlobalTexcoordFactor;        // Offset:  832 Size:     4 [unused]
//   
//   struct
//   {
//       
//       float3 m_direction;            // Offset:  848
//       float3 m_colorIntensity;       // Offset:  864
//
//   } Light0;                          // Offset:  848 Size:    28
//   
//   struct
//   {
//       
//       float4x4 m_split0Transform;    // Offset:  880
//       float4x4 m_split1Transform;    // Offset:  944
//       float4 m_splitDistances;       // Offset: 1008
//
//   } LightShadow0;                    // Offset:  880 Size:   144
//   float GameMaterialID;              // Offset: 1024 Size:     4 [unused]
//      = 0x00000000 
//   float4 GameMaterialDiffuse;        // Offset: 1040 Size:    16
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000 
//   float4 GameMaterialEmission;       // Offset: 1056 Size:    16
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//   float GameMaterialMonotone;        // Offset: 1072 Size:     4
//      = 0x00000000 
//   float4 GameMaterialTexcoord;       // Offset: 1088 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 GameDitherParams;           // Offset: 1104 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//   float4 UVaMUvColor;                // Offset: 1120 Size:    16 [unused]
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000 
//   float4 UVaProjTexcoord;            // Offset: 1136 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 UVaMUvTexcoord;             // Offset: 1152 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 UVaMUv2Texcoord;            // Offset: 1168 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 UVaDuDvTexcoord;            // Offset: 1184 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float AlphaThreshold;              // Offset: 1200 Size:     4
//      = 0x3f000000 
//   float3 ShadowColorShift;           // Offset: 1204 Size:    12
//      = 0x3dcccccd 0x3ca3d70a 0x3ca3d70a 
//   float Shininess;                   // Offset: 1216 Size:     4
//      = 0x3f000000 
//   float SpecularPower;               // Offset: 1220 Size:     4
//      = 0x42480000 
//   float2 WindyGrassDirection;        // Offset: 1224 Size:     8 [unused]
//      = 0x00000000 0x00000000 
//   float WindyGrassSpeed;             // Offset: 1232 Size:     4 [unused]
//      = 0x3dcccccd 
//   float WindyGrassHomogenity;        // Offset: 1236 Size:     4 [unused]
//      = 0x40000000 
//   float WindyGrassScale;             // Offset: 1240 Size:     4 [unused]
//      = 0x3f800000 
//   float BloomIntensity;              // Offset: 1244 Size:     4
//      = 0x3f800000 
//   float4 PointLightParams;           // Offset: 1248 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//   float4 PointLightColor;            // Offset: 1264 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PointClampSamplerState            sampler      NA          NA             s0      1 
// LinearClampCmpSamplerState      sampler_c      NA          NA             s1      1 
// DiffuseMapSamplerSampler          sampler      NA          NA             s2      1 
// SpecularMapSamplerSampler         sampler      NA          NA             s3      1 
// LightShadowMap0                   texture  float4          2d             t0      1 
// DiffuseMapSampler                 texture  float4          2d             t1      1 
// SpecularMapSampler                texture  float4          2d             t2      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xy  
// COLOR                    0   xyzw        1     NONE   float   xyzw
// COLOR                    1   xyzw        2     NONE   float   xyzw
// TEXCOORD                 0   xy          3     NONE   float   xy  
// TEXCOORD                 1   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyz         5     NONE   float   xyz 
// TEXCOORD                10   xyzw        6     NONE   float     zw
// SV_SampleIndex           0   x           7   SAMPLE    uint   x   
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
// SV_TARGET                1   xyzw        1   TARGET   float   xyzw
// SV_TARGET                2   xyzw        2   TARGET   float   xyzw
//
// Pixel Shader runs at sample frequency
//
      0x00000000: ps_4_1
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_immediateConstantBuffer { { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0.250000, 0.250000, 0, 0},
                              { -0.250000, -0.250000, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { -0.125000, -0.375000, 0, 0},
                              { 0.375000, -0.125000, 0, 0},
                              { -0.375000, 0.125000, 0, 0},
                              { 0.125000, 0.375000, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0, 0, 0, 0},
                              { 0.062500, -0.187500, 0, 0},
                              { -0.062500, 0.187500, 0, 0},
                              { 0.312500, 0.062500, 0, 0},
                              { -0.187500, -0.312500, 0, 0},
                              { -0.312500, 0.312500, 0, 0},
                              { -0.437500, -0.062500, 0, 0},
                              { 0.187500, 0.437500, 0, 0},
                              { 0.437500, -0.437500, 0, 0} }
      0x00000494: dcl_constantbuffer CB0[78], immediateIndexed
      0x000004A4: dcl_sampler s0, mode_default
      0x000004B0: dcl_sampler s1, mode_comparison
      0x000004BC: dcl_sampler s2, mode_default
      0x000004C8: dcl_sampler s3, mode_default
      0x000004D4: dcl_resource_texture2d (float,float,float,float) t0
      0x000004E4: dcl_resource_texture2d (float,float,float,float) t1
      0x000004F4: dcl_resource_texture2d (float,float,float,float) t2
      0x00000504: dcl_input_ps_siv linear noperspective v0.xy, position
      0x00000514: dcl_input_ps linear v1.xyzw
      0x00000520: dcl_input_ps linear v2.xyzw
      0x0000052C: dcl_input_ps linear v3.xy
      0x00000538: dcl_input_ps linear v4.xyzw
      0x00000544: dcl_input_ps linear v5.xyz
      0x00000550: dcl_input_ps linear v6.zw
      0x0000055C: dcl_input_ps_sgv constant v7.x, sampleIndex
      0x0000056C: dcl_output o0.xyzw
      0x00000578: dcl_output o1.xyzw
      0x00000584: dcl_output o2.xyzw
      0x00000590: dcl_temps 8
   0  0x00000598: and r0.x, cb0[0].x, l(1)
   1  0x000005B8: if_nz r0.x
   2  0x000005C4:   deriv_rtx r0.xy, v3.xyxx
   3  0x000005D8:   deriv_rty r0.zw, v3.xxxy
   4  0x000005EC:   ishl r1.x, cb0[0].y, l(3)
   5  0x0000060C:   iadd r1.x, r1.x, v7.x
   6  0x00000628:   mul r0.zw, r0.zzzw, icb[r1.x + 0].yyyy
   7  0x00000648:   mad r0.xy, icb[r1.x + 0].xxxx, r0.xyxx, r0.zwzz
   8  0x00000670:   add r0.xy, r0.xyxx, v3.xyxx
   9  0x0000068C: else 
  10  0x00000690:   mov r0.xy, v3.xyxx
  11  0x000006A4: endif 
  12  0x000006A8: sample r1.xyzw, r0.xyxx, t1.xyzw, s2
  13  0x000006CC: mul r0.z, v1.w, cb0[75].x
  14  0x000006EC: mad r0.z, r1.w, v1.w, -r0.z
  15  0x00000714: lt r0.z, r0.z, l(0.000000)
  16  0x00000730: discard_nz r0.z
  17  0x0000073C: ge r0.z, cb0[63].y, v4.w
  18  0x0000075C: if_nz r0.z
  19  0x00000768:   mad r2.xyz, cb0[53].xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), v4.xyzx
  20  0x0000079C:   mad r2.xyz, v5.xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), r2.xyzx
  21  0x000007CC:   lt r0.w, v4.w, cb0[63].x
  22  0x000007EC:   if_nz r0.w
  23  0x000007F8:     mov r2.w, l(1.000000)
  24  0x0000080C:     dp4 r3.x, r2.xyzw, cb0[55].xyzw
  25  0x0000082C:     dp4 r3.y, r2.xyzw, cb0[56].xyzw
  26  0x0000084C:     dp4 r3.z, r2.xyzw, cb0[57].xyzw
  27  0x0000086C:     and r0.w, cb0[0].x, l(2)
  28  0x0000088C:     if_nz r0.w
  29  0x00000898:       sample_c_lz r0.w, r3.xyxx, t0.xxxx, s1, r3.z
  30  0x000008C4:     else 
  31  0x000008C8:       div r1.w, l(25.000000), cb0[63].y
  32  0x000008E8:       and r3.w, cb0[0].x, l(16)
  33  0x00000908:       if_nz r3.w
  34  0x00000914:         mul r4.xy, r1.wwww, l(0.000937, 0.001875, 0.000000, 0.000000)
  35  0x0000093C:         add r3.w, r3.z, l(-6.000000)
  36  0x00000958:         mul r4.xy, r3.wwww, r4.xyxx
  37  0x00000974:         div r4.xy, r4.xyxx, r3.zzzz
  38  0x00000990:         dp2 r3.w, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
  39  0x000009B8:         frc r3.w, r3.w
  40  0x000009CC:         mul r3.w, r3.w, l(52.982918)
  41  0x000009E8:         frc r3.w, r3.w
  42  0x000009FC:         mul r3.w, r3.w, l(6.283185)
  43  0x00000A18:         mov r4.zw, l(0,0,0,0)
  44  0x00000A38:         mov r5.x, l(0)
  45  0x00000A4C:         loop 
  46  0x00000A50:           ige r5.y, r5.x, l(16)
  47  0x00000A6C:           breakc_nz r5.y
  48  0x00000A78:           itof r5.y, r5.x
  49  0x00000A8C:           add r5.z, r5.y, l(0.500000)
  50  0x00000AA8:           sqrt r5.z, r5.z
  51  0x00000ABC:           mul r5.z, r5.z, l(0.250000)
  52  0x00000AD8:           mad r5.y, r5.y, l(2.400000), r3.w
  53  0x00000AFC:           sincos r6.x, r7.x, r5.y
  54  0x00000B18:           mul r7.x, r5.z, r7.x
  55  0x00000B34:           mul r7.y, r5.z, r6.x
  56  0x00000B50:           mad r5.yz, r7.xxyx, r4.xxyx, r3.xxyx
  57  0x00000B74:           sample_l r5.y, r5.yzyy, t0.yxzw, s0, l(0.000000)
  58  0x00000BA0:           lt r5.z, r5.y, r3.z
  59  0x00000BBC:           add r6.y, r4.w, r5.y
  60  0x00000BD8:           add r6.x, r4.z, l(1.000000)
  61  0x00000BF4:           movc r4.zw, r5.zzzz, r6.xxxy, r4.zzzw
  62  0x00000C18:           iadd r5.x, r5.x, l(1)
  63  0x00000C34:         endloop 
  64  0x00000C38:         ge r4.x, r4.z, l(1.000000)
  65  0x00000C54:         if_nz r4.x
  66  0x00000C60:           mul r4.xy, r1.wwww, l(0.000625, 0.001250, 0.000000, 0.000000)
  67  0x00000C88:           div r4.z, r4.w, r4.z
  68  0x00000CA4:           add r4.z, r3.z, -r4.z
  69  0x00000CC4:           min r4.z, r4.z, l(0.070000)
  70  0x00000CE0:           mul r4.z, r4.z, l(60.000000)
  71  0x00000CFC:           mul r4.xy, r4.xyxx, r4.zzzz
  72  0x00000D18:           resinfo r4.zw, l(0), t0.zwxy
  73  0x00000D34:           div r4.zw, l(0.000000, 0.000000, 0.500000, 0.500000), r4.zzzw
  74  0x00000D5C:           max r4.xy, r4.xyxx, r4.zwzz
  75  0x00000D78:           mov r4.zw, l(0,0,0,0)
  76  0x00000D98:           loop 
  77  0x00000D9C:             ige r5.x, r4.w, l(16)
  78  0x00000DB8:             breakc_nz r5.x
  79  0x00000DC4:             itof r5.x, r4.w
  80  0x00000DD8:             add r5.y, r5.x, l(0.500000)
  81  0x00000DF4:             sqrt r5.y, r5.y
  82  0x00000E08:             mul r5.y, r5.y, l(0.250000)
  83  0x00000E24:             mad r5.x, r5.x, l(2.400000), r3.w
  84  0x00000E48:             sincos r5.x, r6.x, r5.x
  85  0x00000E64:             mul r6.x, r5.y, r6.x
  86  0x00000E80:             mul r6.y, r5.x, r5.y
  87  0x00000E9C:             mul r5.xy, r4.xyxx, r6.xyxx
  88  0x00000EB8:             mad r5.xy, r5.xyxx, l(3.000000, 3.000000, 0.000000, 0.000000), r3.xyxx
  89  0x00000EE8:             sample_c_lz r5.x, r5.xyxx, t0.xxxx, s1, r3.z
  90  0x00000F14:             add r4.z, r4.z, r5.x
  91  0x00000F30:             iadd r4.w, r4.w, l(1)
  92  0x00000F4C:           endloop 
  93  0x00000F50:           mul r0.w, r4.z, l(0.062500)
  94  0x00000F6C:         else 
  95  0x00000F70:           mov r0.w, l(1.000000)
  96  0x00000F84:         endif 
  97  0x00000F88:       else 
  98  0x00000F8C:         and r3.w, cb0[0].x, l(8)
  99  0x00000FAC:         if_nz r3.w
 100  0x00000FB8:           mul r4.xy, r1.wwww, l(0.000375, 0.000750, 0.000000, 0.000000)
 101  0x00000FE0:           dp2 r3.w, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
 102  0x00001008:           frc r3.w, r3.w
 103  0x0000101C:           mul r3.w, r3.w, l(52.982918)
 104  0x00001038:           frc r3.w, r3.w
 105  0x0000104C:           mul r3.w, r3.w, l(6.283185)
 106  0x00001068:           mov r4.zw, l(0,0,0,0)
 107  0x00001088:           loop 
 108  0x0000108C:             ige r5.x, r4.w, l(16)
 109  0x000010A8:             breakc_nz r5.x
 110  0x000010B4:             itof r5.x, r4.w
 111  0x000010C8:             add r5.y, r5.x, l(0.500000)
 112  0x000010E4:             sqrt r5.y, r5.y
 113  0x000010F8:             mul r5.y, r5.y, l(0.250000)
 114  0x00001114:             mad r5.x, r5.x, l(2.400000), r3.w
 115  0x00001138:             sincos r5.x, r6.x, r5.x
 116  0x00001154:             mul r6.x, r5.y, r6.x
 117  0x00001170:             mul r6.y, r5.x, r5.y
 118  0x0000118C:             mul r5.xy, r4.xyxx, r6.xyxx
 119  0x000011A8:             mad r5.xy, r5.xyxx, l(3.000000, 3.000000, 0.000000, 0.000000), r3.xyxx
 120  0x000011D8:             sample_c_lz r5.x, r5.xyxx, t0.xxxx, s1, r3.z
 121  0x00001204:             add r4.z, r4.z, r5.x
 122  0x00001220:             iadd r4.w, r4.w, l(1)
 123  0x0000123C:           endloop 
 124  0x00001240:           mul r0.w, r4.z, l(0.062500)
 125  0x0000125C:         else 
 126  0x00001260:           dp4 r3.w, r2.xyzw, cb0[58].xyzw
 127  0x00001280:           and r4.x, cb0[0].x, l(4)
 128  0x000012A0:           if_nz r4.x
 129  0x000012AC:             mul r4.xy, r3.wwww, cb0[37].xyxx
 130  0x000012CC:             sample_c_lz r4.z, r3.xyxx, t0.xxxx, s1, r3.z
 131  0x000012F8:             mul r5.xy, r1.wwww, -r4.xyxx
 132  0x00001318:             mov r5.z, l(0)
 133  0x0000132C:             add r5.xyz, r3.xyzx, r5.xyzx
 134  0x00001348:             sample_c_lz r4.w, r5.xyxx, t0.xxxx, s1, r5.z
 135  0x00001374:             mul r4.w, r4.w, l(0.062500)
 136  0x00001390:             mad r4.z, r4.z, l(0.500000), r4.w
 137  0x000013B4:             mul r5.x, r1.w, r4.x
 138  0x000013D0:             mul r5.y, r1.w, -r4.y
 139  0x000013F0:             mov r5.z, l(0)
 140  0x00001404:             add r6.xyz, r3.xyzx, r5.xyzx
 141  0x00001420:             sample_c_lz r4.w, r6.xyxx, t0.xxxx, s1, r6.z
 142  0x0000144C:             mad r4.z, r4.w, l(0.062500), r4.z
 143  0x00001470:             mul r6.x, r1.w, -r4.x
 144  0x00001490:             mul r6.y, r1.w, r4.y
 145  0x000014AC:             mov r6.z, l(0)
 146  0x000014C0:             add r7.xyz, r3.xyzx, r6.xyzx
 147  0x000014DC:             sample_c_lz r4.w, r7.xyxx, t0.xxxx, s1, r7.z
 148  0x00001508:             mad r4.z, r4.w, l(0.062500), r4.z
 149  0x0000152C:             mul r7.xy, r1.wwww, r4.xyxx
 150  0x00001548:             mov r7.z, l(0)
 151  0x0000155C:             add r4.xyw, r3.xyxz, r7.xyxz
 152  0x00001578:             sample_c_lz r4.x, r4.xyxx, t0.xxxx, s1, r4.w
 153  0x000015A4:             mad r4.x, r4.x, l(0.062500), r4.z
 154  0x000015C8:             add r4.yzw, r3.xxyz, r5.zzyz
 155  0x000015E4:             sample_c_lz r4.y, r4.yzyy, t0.xxxx, s1, r4.w
 156  0x00001610:             mad r4.x, r4.y, l(0.062500), r4.x
 157  0x00001634:             add r4.yzw, r3.xxyz, r6.xxzz
 158  0x00001650:             sample_c_lz r4.y, r4.yzyy, t0.xxxx, s1, r4.w
 159  0x0000167C:             mad r4.x, r4.y, l(0.062500), r4.x
 160  0x000016A0:             add r4.yzw, r3.xxyz, r7.xxzz
 161  0x000016BC:             sample_c_lz r4.y, r4.yzyy, t0.xxxx, s1, r4.w
 162  0x000016E8:             mad r4.x, r4.y, l(0.062500), r4.x
 163  0x0000170C:             add r4.yzw, r3.xxyz, r7.zzyz
 164  0x00001728:             sample_c_lz r4.y, r4.yzyy, t0.xxxx, s1, r4.w
 165  0x00001754:             mad r0.w, r4.y, l(0.062500), r4.x
 166  0x00001778:           else 
 167  0x0000177C:             mul r4.xy, r3.wwww, cb0[37].xyxx
 168  0x0000179C:             sample_c_lz r3.w, r3.xyxx, t0.xxxx, s1, r3.z
 169  0x000017C8:             mul r5.xy, r1.wwww, -r4.xyxx
 170  0x000017E8:             mov r5.z, l(0)
 171  0x000017FC:             add r5.xyz, r3.xyzx, r5.xyzx
 172  0x00001818:             sample_c_lz r4.z, r5.xyxx, t0.xxxx, s1, r5.z
 173  0x00001844:             mul r4.z, r4.z, cb0[38].y
 174  0x00001864:             mad r3.w, r3.w, cb0[38].x, r4.z
 175  0x0000188C:             mul r5.x, r1.w, r4.x
 176  0x000018A8:             mul r5.y, r1.w, -r4.y
 177  0x000018C8:             mov r5.z, l(0)
 178  0x000018DC:             add r5.xyz, r3.xyzx, r5.xyzx
 179  0x000018F8:             sample_c_lz r4.z, r5.xyxx, t0.xxxx, s1, r5.z
 180  0x00001924:             mad r3.w, r4.z, cb0[38].y, r3.w
 181  0x0000194C:             mul r5.x, r1.w, -r4.x
 182  0x0000196C:             mul r5.y, r1.w, r4.y
 183  0x00001988:             mov r5.z, l(0)
 184  0x0000199C:             add r5.xyz, r3.xyzx, r5.xyzx
 185  0x000019B8:             sample_c_lz r4.z, r5.xyxx, t0.xxxx, s1, r5.z
 186  0x000019E4:             mad r3.w, r4.z, cb0[38].y, r3.w
 187  0x00001A0C:             mul r4.xy, r1.wwww, r4.xyxx
 188  0x00001A28:             mov r4.z, l(0)
 189  0x00001A3C:             add r3.xyz, r3.xyzx, r4.xyzx
 190  0x00001A58:             sample_c_lz r1.w, r3.xyxx, t0.xxxx, s1, r3.z
 191  0x00001A84:             mad r0.w, r1.w, cb0[38].y, r3.w
 192  0x00001AAC:           endif 
 193  0x00001AB0:         endif 
 194  0x00001AB4:       endif 
 195  0x00001AB8:     endif 
 196  0x00001ABC:   else 
 197  0x00001AC0:     mov r2.w, l(1.000000)
 198  0x00001AD4:     dp4 r3.x, r2.xyzw, cb0[59].xyzw
 199  0x00001AF4:     dp4 r3.y, r2.xyzw, cb0[60].xyzw
 200  0x00001B14:     dp4 r3.z, r2.xyzw, cb0[61].xyzw
 201  0x00001B34:     and r1.w, cb0[0].x, l(2)
 202  0x00001B54:     if_nz r1.w
 203  0x00001B60:       sample_c_lz r0.w, r3.xyxx, t0.xxxx, s1, r3.z
 204  0x00001B8C:     else 
 205  0x00001B90:       div r1.w, l(10.000000), cb0[63].y
 206  0x00001BB0:       and r3.w, cb0[0].x, l(16)
 207  0x00001BD0:       if_nz r3.w
 208  0x00001BDC:         mul r4.xy, r1.wwww, l(0.000937, 0.001875, 0.000000, 0.000000)
 209  0x00001C04:         add r3.w, r3.z, l(-6.000000)
 210  0x00001C20:         mul r4.xy, r3.wwww, r4.xyxx
 211  0x00001C3C:         div r4.xy, r4.xyxx, r3.zzzz
 212  0x00001C58:         dp2 r3.w, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
 213  0x00001C80:         frc r3.w, r3.w
 214  0x00001C94:         mul r3.w, r3.w, l(52.982918)
 215  0x00001CB0:         frc r3.w, r3.w
 216  0x00001CC4:         mul r3.w, r3.w, l(6.283185)
 217  0x00001CE0:         mov r4.zw, l(0,0,0,0)
 218  0x00001D00:         mov r5.x, l(0)
 219  0x00001D14:         loop 
 220  0x00001D18:           ige r5.y, r5.x, l(16)
 221  0x00001D34:           breakc_nz r5.y
 222  0x00001D40:           itof r5.y, r5.x
 223  0x00001D54:           add r5.z, r5.y, l(0.500000)
 224  0x00001D70:           sqrt r5.z, r5.z
 225  0x00001D84:           mul r5.z, r5.z, l(0.250000)
 226  0x00001DA0:           mad r5.y, r5.y, l(2.400000), r3.w
 227  0x00001DC4:           sincos r6.x, r7.x, r5.y
 228  0x00001DE0:           mul r7.x, r5.z, r7.x
 229  0x00001DFC:           mul r7.y, r5.z, r6.x
 230  0x00001E18:           mad r5.yz, r7.xxyx, r4.xxyx, r3.xxyx
 231  0x00001E3C:           sample_l r5.y, r5.yzyy, t0.yxzw, s0, l(0.000000)
 232  0x00001E68:           lt r5.z, r5.y, r3.z
 233  0x00001E84:           add r6.y, r4.w, r5.y
 234  0x00001EA0:           add r6.x, r4.z, l(1.000000)
 235  0x00001EBC:           movc r4.zw, r5.zzzz, r6.xxxy, r4.zzzw
 236  0x00001EE0:           iadd r5.x, r5.x, l(1)
 237  0x00001EFC:         endloop 
 238  0x00001F00:         ge r4.x, r4.z, l(1.000000)
 239  0x00001F1C:         if_nz r4.x
 240  0x00001F28:           mul r4.xy, r1.wwww, l(0.000625, 0.001250, 0.000000, 0.000000)
 241  0x00001F50:           div r4.z, r4.w, r4.z
 242  0x00001F6C:           add r4.z, r3.z, -r4.z
 243  0x00001F8C:           min r4.z, r4.z, l(0.070000)
 244  0x00001FA8:           mul r4.z, r4.z, l(60.000000)
 245  0x00001FC4:           mul r4.xy, r4.xyxx, r4.zzzz
 246  0x00001FE0:           resinfo r4.zw, l(0), t0.zwxy
 247  0x00001FFC:           div r4.zw, l(0.000000, 0.000000, 0.500000, 0.500000), r4.zzzw
 248  0x00002024:           max r4.xy, r4.xyxx, r4.zwzz
 249  0x00002040:           mov r4.zw, l(0,0,0,0)
 250  0x00002060:           loop 
 251  0x00002064:             ige r5.x, r4.w, l(16)
 252  0x00002080:             breakc_nz r5.x
 253  0x0000208C:             itof r5.x, r4.w
 254  0x000020A0:             add r5.y, r5.x, l(0.500000)
 255  0x000020BC:             sqrt r5.y, r5.y
 256  0x000020D0:             mul r5.y, r5.y, l(0.250000)
 257  0x000020EC:             mad r5.x, r5.x, l(2.400000), r3.w
 258  0x00002110:             sincos r5.x, r6.x, r5.x
 259  0x0000212C:             mul r6.x, r5.y, r6.x
 260  0x00002148:             mul r6.y, r5.x, r5.y
 261  0x00002164:             mul r5.xy, r4.xyxx, r6.xyxx
 262  0x00002180:             mad r5.xy, r5.xyxx, l(3.000000, 3.000000, 0.000000, 0.000000), r3.xyxx
 263  0x000021B0:             sample_c_lz r5.x, r5.xyxx, t0.xxxx, s1, r3.z
 264  0x000021DC:             add r4.z, r4.z, r5.x
 265  0x000021F8:             iadd r4.w, r4.w, l(1)
 266  0x00002214:           endloop 
 267  0x00002218:           mul r0.w, r4.z, l(0.062500)
 268  0x00002234:         else 
 269  0x00002238:           mov r0.w, l(1.000000)
 270  0x0000224C:         endif 
 271  0x00002250:       else 
 272  0x00002254:         and r3.w, cb0[0].x, l(8)
 273  0x00002274:         if_nz r3.w
 274  0x00002280:           mul r4.xy, r1.wwww, l(0.000375, 0.000750, 0.000000, 0.000000)
 275  0x000022A8:           dp2 r3.w, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
 276  0x000022D0:           frc r3.w, r3.w
 277  0x000022E4:           mul r3.w, r3.w, l(52.982918)
 278  0x00002300:           frc r3.w, r3.w
 279  0x00002314:           mul r3.w, r3.w, l(6.283185)
 280  0x00002330:           mov r4.zw, l(0,0,0,0)
 281  0x00002350:           loop 
 282  0x00002354:             ige r5.x, r4.w, l(16)
 283  0x00002370:             breakc_nz r5.x
 284  0x0000237C:             itof r5.x, r4.w
 285  0x00002390:             add r5.y, r5.x, l(0.500000)
 286  0x000023AC:             sqrt r5.y, r5.y
 287  0x000023C0:             mul r5.y, r5.y, l(0.250000)
 288  0x000023DC:             mad r5.x, r5.x, l(2.400000), r3.w
 289  0x00002400:             sincos r5.x, r6.x, r5.x
 290  0x0000241C:             mul r6.x, r5.y, r6.x
 291  0x00002438:             mul r6.y, r5.x, r5.y
 292  0x00002454:             mul r5.xy, r4.xyxx, r6.xyxx
 293  0x00002470:             mad r5.xy, r5.xyxx, l(3.000000, 3.000000, 0.000000, 0.000000), r3.xyxx
 294  0x000024A0:             sample_c_lz r5.x, r5.xyxx, t0.xxxx, s1, r3.z
 295  0x000024CC:             add r4.z, r4.z, r5.x
 296  0x000024E8:             iadd r4.w, r4.w, l(1)
 297  0x00002504:           endloop 
 298  0x00002508:           mul r0.w, r4.z, l(0.062500)
 299  0x00002524:         else 
 300  0x00002528:           dp4 r2.x, r2.xyzw, cb0[62].xyzw
 301  0x00002548:           and r2.y, cb0[0].x, l(4)
 302  0x00002568:           if_nz r2.y
 303  0x00002574:             mul r2.yz, r2.xxxx, cb0[37].xxyx
 304  0x00002594:             sample_c_lz r2.w, r3.xyxx, t0.xxxx, s1, r3.z
 305  0x000025C0:             mul r4.xy, r1.wwww, -r2.yzyy
 306  0x000025E0:             mov r4.z, l(0)
 307  0x000025F4:             add r4.xyz, r3.xyzx, r4.xyzx
 308  0x00002610:             sample_c_lz r3.w, r4.xyxx, t0.xxxx, s1, r4.z
 309  0x0000263C:             mul r3.w, r3.w, l(0.062500)
 310  0x00002658:             mad r2.w, r2.w, l(0.500000), r3.w
 311  0x0000267C:             mul r4.x, r1.w, r2.y
 312  0x00002698:             mul r4.y, r1.w, -r2.z
 313  0x000026B8:             mov r4.z, l(0)
 314  0x000026CC:             add r5.xyz, r3.xyzx, r4.xyzx
 315  0x000026E8:             sample_c_lz r3.w, r5.xyxx, t0.xxxx, s1, r5.z
 316  0x00002714:             mad r2.w, r3.w, l(0.062500), r2.w
 317  0x00002738:             mul r5.x, r1.w, -r2.y
 318  0x00002758:             mul r5.y, r1.w, r2.z
 319  0x00002774:             mov r5.z, l(0)
 320  0x00002788:             add r6.xyz, r3.xyzx, r5.xyzx
 321  0x000027A4:             sample_c_lz r3.w, r6.xyxx, t0.xxxx, s1, r6.z
 322  0x000027D0:             mad r2.w, r3.w, l(0.062500), r2.w
 323  0x000027F4:             mul r6.xy, r1.wwww, r2.yzyy
 324  0x00002810:             mov r6.z, l(0)
 325  0x00002824:             add r7.xyz, r3.xyzx, r6.xyzx
 326  0x00002840:             sample_c_lz r2.y, r7.xyxx, t0.xxxx, s1, r7.z
 327  0x0000286C:             mad r2.y, r2.y, l(0.062500), r2.w
 328  0x00002890:             add r7.xyz, r3.xyzx, r4.zyzz
 329  0x000028AC:             sample_c_lz r2.z, r7.xyxx, t0.xxxx, s1, r7.z
 330  0x000028D8:             mad r2.y, r2.z, l(0.062500), r2.y
 331  0x000028FC:             add r5.xyz, r3.xyzx, r5.xzzx
 332  0x00002918:             sample_c_lz r2.z, r5.xyxx, t0.xxxx, s1, r5.z
 333  0x00002944:             mad r2.y, r2.z, l(0.062500), r2.y
 334  0x00002968:             add r4.xyz, r3.xyzx, r4.xzzx
 335  0x00002984:             sample_c_lz r2.z, r4.xyxx, t0.xxxx, s1, r4.z
 336  0x000029B0:             mad r2.y, r2.z, l(0.062500), r2.y
 337  0x000029D4:             add r4.xyz, r3.xyzx, r6.zyzz
 338  0x000029F0:             sample_c_lz r2.z, r4.xyxx, t0.xxxx, s1, r4.z
 339  0x00002A1C:             mad r0.w, r2.z, l(0.062500), r2.y
 340  0x00002A40:           else 
 341  0x00002A44:             mul r2.xy, r2.xxxx, cb0[37].xyxx
 342  0x00002A64:             sample_c_lz r2.z, r3.xyxx, t0.xxxx, s1, r3.z
 343  0x00002A90:             mul r4.xy, r1.wwww, -r2.xyxx
 344  0x00002AB0:             mov r4.z, l(0)
 345  0x00002AC4:             add r4.xyz, r3.xyzx, r4.xyzx
 346  0x00002AE0:             sample_c_lz r2.w, r4.xyxx, t0.xxxx, s1, r4.z
 347  0x00002B0C:             mul r2.w, r2.w, cb0[38].y
 348  0x00002B2C:             mad r2.z, r2.z, cb0[38].x, r2.w
 349  0x00002B54:             mul r4.x, r1.w, r2.x
 350  0x00002B70:             mul r4.y, r1.w, -r2.y
 351  0x00002B90:             mov r4.z, l(0)
 352  0x00002BA4:             add r4.xyz, r3.xyzx, r4.xyzx
 353  0x00002BC0:             sample_c_lz r2.w, r4.xyxx, t0.xxxx, s1, r4.z
 354  0x00002BEC:             mad r2.z, r2.w, cb0[38].y, r2.z
 355  0x00002C14:             mul r4.x, r1.w, -r2.x
 356  0x00002C34:             mul r4.y, r1.w, r2.y
 357  0x00002C50:             mov r4.z, l(0)
 358  0x00002C64:             add r4.xyz, r3.xyzx, r4.xyzx
 359  0x00002C80:             sample_c_lz r2.w, r4.xyxx, t0.xxxx, s1, r4.z
 360  0x00002CAC:             mad r2.z, r2.w, cb0[38].y, r2.z
 361  0x00002CD4:             mul r4.xy, r1.wwww, r2.xyxx
 362  0x00002CF0:             mov r4.z, l(0)
 363  0x00002D04:             add r2.xyw, r3.xyxz, r4.xyxz
 364  0x00002D20:             sample_c_lz r1.w, r2.xyxx, t0.xxxx, s1, r2.w
 365  0x00002D4C:             mad r0.w, r1.w, cb0[38].y, r2.z
 366  0x00002D74:           endif 
 367  0x00002D78:         endif 
 368  0x00002D7C:       endif 
 369  0x00002D80:     endif 
 370  0x00002D84:   endif 
 371  0x00002D88: else 
 372  0x00002D8C:   mov r0.w, l(1.000000)
 373  0x00002DA0: endif 
 374  0x00002DA4: lt r1.w, v4.w, cb0[63].x
 375  0x00002DC4: add r2.x, v4.w, -cb0[63].x
 376  0x00002DE8: add r2.y, -cb0[63].x, cb0[63].y
 377  0x00002E10: div_sat r2.x, r2.x, r2.y
 378  0x00002E2C: movc r1.w, r1.w, l(0), r2.x
 379  0x00002E50: mul r2.x, r1.w, r1.w
 380  0x00002E6C: mul r1.w, r1.w, r2.x
 381  0x00002E88: movc r0.z, r0.z, r1.w, l(1.000000)
 382  0x00002EAC: add r1.w, v4.y, -cb0[30].y
 383  0x00002ED0: mul r1.w, |r1.w|, cb0[30].x
 384  0x00002EF4: min r1.w, r1.w, l(1.000000)
 385  0x00002F10: mul r2.x, r1.w, r1.w
 386  0x00002F2C: mul r1.w, r1.w, r2.x
 387  0x00002F48: ge r2.x, l(0.000000), cb0[30].x
 388  0x00002F68: movc r1.w, r2.x, l(0), r1.w
 389  0x00002F8C: add r0.z, r0.z, r1.w
 390  0x00002FA8: dp3 r1.w, v5.xyzx, cb0[53].xyzx
 391  0x00002FC8: mad r1.w, r1.w, l(0.500000), l(0.500000)
 392  0x00002FEC: mul r2.x, cb0[37].w, l(0.400000)
 393  0x0000300C: max r2.y, -v5.y, l(0.000000)
 394  0x0000302C: mad r2.x, -r2.x, r2.y, l(0.400000)
 395  0x00003054: lt r2.y, r2.x, r1.w
 396  0x00003070: add r1.w, r1.w, -r2.x
 397  0x00003090: add r2.x, -r2.x, l(1.000000)
 398  0x000030B0: div r1.w, r1.w, r2.x
 399  0x000030CC: and r1.w, r1.w, r2.y
 400  0x000030E8: add r1.w, -r1.w, l(1.000000)
 401  0x00003108: mul r2.x, r1.w, r1.w
 402  0x00003124: mad r0.z, r1.w, r2.x, r0.z
 403  0x00003148: min r0.z, r0.z, l(1.000000)
 404  0x00003164: add r0.z, r0.z, r0.w
 405  0x00003180: min r0.z, r0.z, l(1.000000)
 406  0x0000319C: add r0.w, -r0.z, l(1.000000)
 407  0x000031BC: add r1.w, -cb0[30].w, l(1.000000)
 408  0x000031E0: mad r0.z, r0.w, r1.w, r0.z
 409  0x00003204: add r0.w, -r0.z, l(1.000000)
 410  0x00003224: add r1.w, -cb0[66].w, l(1.000000)
 411  0x00003248: mad r0.z, r0.w, r1.w, r0.z
 412  0x0000326C: sample r0.x, r0.xyxx, t2.xyzw, s3
 413  0x00003290: add r0.y, r0.x, l(1.000000)
 414  0x000032AC: mul r0.y, r0.y, l(0.500000)
 415  0x000032C8: mul r2.xyz, r0.yyyy, cb0[54].xyzx
 416  0x000032E8: mul r0.y, r0.z, r0.z
 417  0x00003304: mul r2.xyz, r0.yyyy, r2.xyzx
 418  0x00003320: dp3 r0.y, v5.xyzx, v5.xyzx
 419  0x0000333C: rsq r0.y, r0.y
 420  0x00003350: mul r3.xyz, r0.yyyy, v5.xyzx
 421  0x0000336C: add r4.xyz, -v4.xyzx, cb0[1].xyzx
 422  0x00003390: dp3 r0.y, r4.xyzx, r4.xyzx
 423  0x000033AC: rsq r0.y, r0.y
 424  0x000033C0: dp3 r0.w, cb0[53].xyzx, r3.xyzx
 425  0x000033E0: mad r0.w, r0.w, l(0.500000), l(0.500000)
 426  0x00003404: mad r4.xyz, r4.xyzx, r0.yyyy, cb0[53].xyzx
 427  0x0000342C: dp3 r0.y, r4.xyzx, r4.xyzx
 428  0x00003448: rsq r0.y, r0.y
 429  0x0000345C: mul r4.xyz, r0.yyyy, r4.xyzx
 430  0x00003478: dp3_sat r0.y, r3.xyzx, r4.xyzx
 431  0x00003494: log r0.y, r0.y
 432  0x000034A8: mul r0.xy, r0.xyxx, cb0[76].xyxx
 433  0x000034C8: exp r0.y, r0.y
 434  0x000034DC: min r0.y, r0.y, l(1.000000)
 435  0x000034F8: mul r0.xw, r0.xxxw, r0.yyyw
 436  0x00003514: mad r4.xyz, cb0[54].xyzx, r0.wwww, cb0[25].xyzx
 437  0x00003540: min r4.xyz, r4.xyzx, l(1.500000, 1.500000, 1.500000, 0.000000)
 438  0x00003568: mad r0.xyw, cb0[54].xyxz, r0.xxxx, r4.xyxz
 439  0x00003590: add r0.z, -r0.z, l(1.000000)
 440  0x000035B0: mad r4.xyz, r0.xywx, cb0[29].xyzx, -r0.xywx
 441  0x000035DC: mad r0.xyz, r0.zzzz, r4.xyzx, r0.xywx
 442  0x00003600: add r2.xyz, r2.xyzx, r2.xyzx
 443  0x0000361C: max r2.xyz, r2.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 444  0x00003644: min r4.xyz, r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 445  0x0000366C: add r4.xyz, -r4.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 446  0x00003698: mul r4.xyz, r4.xyzx, cb0[75].yzwy
 447  0x000036B8: mad r0.xyz, r4.xyzx, r2.xyzx, r0.xyzx
 448  0x000036DC: mul r0.xyz, r0.xyzx, v1.xyzx
 449  0x000036F8: mul r0.xyz, r0.xyzx, r1.xyzx
 450  0x00003714: mad r0.xyz, r0.xyzx, cb0[65].xyzx, cb0[66].xyzx
 451  0x00003740: add r0.xyz, r0.xyzx, v2.xyzx
 452  0x0000375C: add r1.xyz, -r0.xyzx, cb0[27].xyzx
 453  0x00003780: mad r0.xyz, v2.wwww, r1.xyzx, r0.xyzx
 454  0x000037A4: dp3 r0.w, r0.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
 455  0x000037CC: mad r1.xyz, r0.wwww, cb0[31].xyzx, cb0[32].xyzx
 456  0x000037F8: add r1.xyz, -r0.xyzx, r1.xyzx
 457  0x00003818: mad r0.xyz, cb0[67].xxxx, r1.xyzx, r0.xyzx
 458  0x00003840: mul r1.xyz, r0.xyzx, cb0[77].wwww
 459  0x00003860: dp3 r0.w, r1.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
 460  0x00003888: add r0.w, r0.w, -cb0[30].z
 461  0x000038AC: max r0.w, r0.w, l(0.000000)
 462  0x000038C8: mul r0.w, r0.w, l(0.500000)
 463  0x000038E4: min o0.w, r0.w, l(1.000000)
 464  0x00003900: mad o1.xyz, r3.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
 465  0x0000393C: div r0.w, v6.z, v6.w
 466  0x00003958: mul r1.x, r0.w, l(256.000000)
 467  0x00003974: round_z r1.x, r1.x
 468  0x00003988: mad r0.w, r0.w, l(256.000000), -r1.x
 469  0x000039B0: mul r1.w, r0.w, l(256.000000)
 470  0x000039CC: round_z r1.y, r1.w
 471  0x000039E0: mad r1.z, r0.w, l(256.000000), -r1.y
 472  0x00003A08: mul o2.xyz, r1.xyzx, l(0.003906, 0.003906, 1.000000, 0.000000)
 473  0x00003A30: mov o0.xyz, r0.xyzx
 474  0x00003A44: mov o1.w, l(0.750000)
 475  0x00003A58: mov o2.w, l(0)
 476  0x00003A6C: ret 
// Approximately 477 instruction slots used
