//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   uint4 DuranteSettings;             // Offset:    0 Size:    16 [unused]
//   
//   struct
//   {
//       
//       float3 EyePosition;            // Offset:   16
//       float4x4 View;                 // Offset:   32
//       float4x4 Projection;           // Offset:   96
//       float4x4 ViewProjection;       // Offset:  160
//       float4x4 ViewInverse;          // Offset:  224
//       float4x4 ProjectionInverse;    // Offset:  288
//       float2 cameraNearFar;          // Offset:  352
//       float cameraNearTimesFar;      // Offset:  360
//       float cameraFarMinusNear;      // Offset:  364
//       float cameraFarMinusNearInv;   // Offset:  368
//       float2 ViewportWidthHeight;    // Offset:  372
//       float2 screenWidthHeightInv;   // Offset:  384
//       float3 GlobalAmbientColor;     // Offset:  400
//       float Time;                    // Offset:  412
//       float3 FakeRimLightDir;        // Offset:  416
//       float3 FogColor;               // Offset:  432
//       float4 FogRangeParameters;     // Offset:  448
//       float3 MiscParameters1;        // Offset:  464
//       float4 MiscParameters2;        // Offset:  480
//       float3 MonotoneMul;            // Offset:  496
//       float3 MonotoneAdd;            // Offset:  512
//       float3 UserClipPlane2;         // Offset:  528
//       float4 UserClipPlane;          // Offset:  544
//       float4 MiscParameters3;        // Offset:  560
//       float AdditionalShadowOffset;  // Offset:  576
//       float AlphaTestDirection;      // Offset:  580
//       float4 MiscParameters4;        // Offset:  592
//       float3 MiscParameters5;        // Offset:  608
//       float4 light1_attenuation;     // Offset:  624
//       float3 light2_position;        // Offset:  640
//       float3 light2_colorIntensity;  // Offset:  656
//       float4 light2_attenuation;     // Offset:  672
//
//   } scene;                           // Offset:   16 Size:   672
//   bool PhyreContextSwitches;         // Offset:  688 Size:     4 [unused]
//   bool PhyreMaterialSwitches;        // Offset:  692 Size:     4 [unused]
//   float4x4 World;                    // Offset:  704 Size:    64
//   float GlobalTexcoordFactor;        // Offset:  768 Size:     4 [unused]
//   float GameMaterialID;              // Offset:  772 Size:     4 [unused]
//      = 0x00000000 
//   float4 GameMaterialDiffuse;        // Offset:  784 Size:    16 [unused]
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000 
//   float4 GameMaterialEmission;       // Offset:  800 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//   float GameMaterialMonotone;        // Offset:  816 Size:     4 [unused]
//      = 0x00000000 
//   float4 GameMaterialTexcoord;       // Offset:  832 Size:    16
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 GameDitherParams;           // Offset:  848 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//   float4 UVaMUvColor;                // Offset:  864 Size:    16 [unused]
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000 
//   float4 UVaProjTexcoord;            // Offset:  880 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 UVaMUvTexcoord;             // Offset:  896 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 UVaMUv2Texcoord;            // Offset:  912 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 UVaDuDvTexcoord;            // Offset:  928 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float Shininess;                   // Offset:  944 Size:     4 [unused]
//      = 0x3f000000 
//   float SpecularPower;               // Offset:  948 Size:     4 [unused]
//      = 0x42480000 
//   float3 SpecularColor;              // Offset:  960 Size:    12 [unused]
//      = 0x3f800000 0x3f800000 0x3f800000 
//   float3 RimLitColor;                // Offset:  976 Size:    12 [unused]
//      = 0x3f800000 0x3f800000 0x3f800000 
//   float RimLitIntensity;             // Offset:  988 Size:     4 [unused]
//      = 0x40800000 
//   float RimLitPower;                 // Offset:  992 Size:     4 [unused]
//      = 0x40000000 
//   float RimLightClampFactor;         // Offset:  996 Size:     4 [unused]
//      = 0x40000000 
//   float CubeMapIntensity;            // Offset: 1000 Size:     4 [unused]
//      = 0x3f800000 
//   float CubeMapFresnel;              // Offset: 1004 Size:     4 [unused]
//      = 0x00000000 
//   float BloomIntensity;              // Offset: 1008 Size:     4 [unused]
//      = 0x3f800000 
//   float4 PointLightParams;           // Offset: 1024 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//   float4 PointLightColor;            // Offset: 1040 Size:    16
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// NORMAL                   0   xyz         1     NONE   float   xyz 
// TEXCOORD                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// COLOR                    0   xyzw        1     NONE   float   xyzw
// COLOR                    1   xyzw        2     NONE   float   xyzw
// TEXCOORD                 0   xy          3     NONE   float   xy  
// TEXCOORD                 1   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyz         5     NONE   float   xyz 
// TEXCOORD                10   xyzw        6     NONE   float   xyzw
//
      0x00000000: vs_4_1
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[66], immediateIndexed
      0x0000001C: dcl_input v0.xyz
      0x00000028: dcl_input v1.xyz
      0x00000034: dcl_input v2.xy
      0x00000040: dcl_output_siv o0.xyzw, position
      0x00000050: dcl_output o1.xyzw
      0x0000005C: dcl_output o2.xyzw
      0x00000068: dcl_output o3.xy
      0x00000074: dcl_output o4.xyzw
      0x00000080: dcl_output o5.xyz
      0x0000008C: dcl_output o6.xyzw
      0x00000098: dcl_temps 3
   0  0x000000A0: mov r0.w, l(1.000000)
   1  0x000000B4: mov r1.xyz, v0.xyzx
   2  0x000000C8: mov r1.w, l(1.000000)
   3  0x000000DC: dp4 r0.x, r1.xyzw, cb0[44].xyzw
   4  0x000000FC: dp4 r0.z, r1.xyzw, cb0[46].xyzw
   5  0x0000011C: dp4 r0.y, r1.xyzw, cb0[45].xyzw
   6  0x0000013C: dp4 r1.x, r0.xyzw, cb0[10].xyzw
   7  0x0000015C: dp4 r1.y, r0.xyzw, cb0[11].xyzw
   8  0x0000017C: dp4 r1.z, r0.xyzw, cb0[12].xyzw
   9  0x0000019C: dp4 r1.w, r0.xyzw, cb0[13].xyzw
  10  0x000001BC: dp4 r0.w, r0.xyzw, cb0[4].xyzw
  11  0x000001DC: mov o0.xyzw, r1.xyzw
  12  0x000001F0: mov o6.xyzw, r1.xyzw
  13  0x00000204: mov o1.xyzw, l(1.000000,1.000000,1.000000,1.000000)
  14  0x00000224: add r1.xyz, -r0.xyzx, cb0[1].xyzx
  15  0x00000248: mov o4.xyz, r0.xyzx
  16  0x0000025C: add r0.x, r0.y, -cb0[35].x
  17  0x00000280: mul_sat r0.x, r0.x, cb0[35].y
  18  0x000002A0: dp3 r0.y, r1.xyzx, r1.xyzx
  19  0x000002BC: rsq r0.y, r0.y
  20  0x000002D0: mul r1.xyz, r0.yyyy, r1.xyzx
  21  0x000002EC: dp3 r2.x, v1.xyzx, cb0[44].xyzx
  22  0x0000030C: dp3 r2.y, v1.xyzx, cb0[45].xyzx
  23  0x0000032C: dp3 r2.z, v1.xyzx, cb0[46].xyzx
  24  0x0000034C: dp3 r0.y, r2.xyzx, r2.xyzx
  25  0x00000368: rsq r0.y, r0.y
  26  0x0000037C: mul r2.xyz, r0.yyyy, r2.xyzx
  27  0x00000398: dp3 r0.y, r2.xyzx, r1.xyzx
  28  0x000003B4: mov o5.xyz, r2.xyzx
  29  0x000003C8: max r0.y, r0.y, l(0.000000)
  30  0x000003E4: add r0.y, -r0.y, l(1.000000)
  31  0x00000404: max r0.y, r0.y, l(0.000000)
  32  0x00000420: log r0.y, r0.y
  33  0x00000434: max r0.z, cb0[65].w, l(1.000000)
  34  0x00000454: mul r0.y, r0.y, r0.z
  35  0x00000470: exp r0.y, r0.y
  36  0x00000484: mul o2.xyz, r0.yyyy, cb0[65].xyzx
  37  0x000004A4: add r0.y, -r0.w, -cb0[28].x
  38  0x000004CC: mov o4.w, -r0.w
  39  0x000004E4: mul_sat r0.y, r0.y, cb0[28].z
  40  0x00000504: add r0.z, r0.y, cb0[35].z
  41  0x00000524: min r0.z, r0.z, l(1.000000)
  42  0x00000540: mad r0.x, r0.x, r0.z, r0.y
  43  0x00000564: min r0.x, r0.x, l(1.000000)
  44  0x00000580: mul o2.w, r0.x, cb0[28].w
  45  0x000005A0: mad o3.xy, v2.xyxx, cb0[52].zwzz, cb0[52].xyxx
  46  0x000005CC: ret 
// Approximately 47 instruction slots used
