//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.3.16 on Thu Feb 26 19:24:56 2026
//
//
// Buffer Definitions:
//
// cbuffer LPVCascadeRelightingParams
// {
//
//   float3 g_LPVCorner1;               // Offset:    0 Size:    12
//   float g_LPVSize1;                  // Offset:   12 Size:     4
//   float3 g_LPVCorner2;               // Offset:   16 Size:    12
//   float g_LPVSize2;                  // Offset:   28 Size:     4
//   float3 g_LPVCorner3;               // Offset:   32 Size:    12
//   float g_LPVSize3;                  // Offset:   44 Size:     4
//   float2 g_StartEndFade1;            // Offset:   48 Size:     8
//   float2 g_StartEndFade2;            // Offset:   56 Size:     8
//   float3 g_CamPos;                   // Offset:   64 Size:    12
//   float g_showDebug;                 // Offset:   76 Size:     4
//   float3 g_ColorScale;               // Offset:   80 Size:    12
//   float g_showCascades;              // Offset:   92 Size:     4
//
// }
//
// cbuffer LPVCascadeProjParams
// {
//
//   float4x4 g_InvViewProj;            // Offset:    0 Size:    64
//   float4x4 g_InvView;                // Offset:   64 Size:    64 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// g_SamplePoint                     sampler      NA          NA    0        1
// g_SampleLinear                    sampler      NA          NA    1        1
// g_NormalTex                       texture  float4          2d    0        1
// g_DiffuseTex                      texture  float4          2d    1        1
// g_SpecularTex                     texture  float4          2d    2        1
// g_AoTex                           texture   float          2d    3        1
// g_DepthTex                        texture   float          2d    4        1
// g_LPVSource1AccumR                texture  float4          3d    5        1
// g_LPVSource1AccumG                texture  float4          3d    6        1
// g_LPVSource1AccumB                texture  float4          3d    7        1
// g_LPVSource2AccumR                texture  float4          3d    8        1
// g_LPVSource2AccumG                texture  float4          3d    9        1
// g_LPVSource2AccumB                texture  float4          3d   10        1
// g_LPVSource3AccumR                texture  float4          3d   11        1
// g_LPVSource3AccumG                texture  float4          3d   12        1
// g_LPVSource3AccumB                texture  float4          3d   13        1
// LPVCascadeRelightingParams        cbuffer      NA          NA    0        1
// LPVCascadeProjParams              cbuffer      NA          NA    1        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float
// TEXCOORD                 0   xy          1     NONE   float   xy
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[6], immediateIndexed
dcl_constantbuffer cb1[4], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture3d (float,float,float,float) t5
dcl_resource_texture3d (float,float,float,float) t6
dcl_resource_texture3d (float,float,float,float) t7
dcl_resource_texture3d (float,float,float,float) t8
dcl_resource_texture3d (float,float,float,float) t9
dcl_resource_texture3d (float,float,float,float) t10
dcl_resource_texture3d (float,float,float,float) t11
dcl_resource_texture3d (float,float,float,float) t12
dcl_resource_texture3d (float,float,float,float) t13
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 9
sample_l_indexable(texture2d)(float,float,float,float) r0.x, v1.xyxx, t4.xyzw, s0, l(0.000000)
eq r0.y, r0.x, l(1.000000)
if_nz r0.y
  mov o0.xyzw, l(0,0,0,0)
  ret
endif
ne r0.y, cb0[5].w, l(0.000000)
mad r0.zw, v1.xxxy, l(0.000000, 0.000000, 1.000000, -1.000000), l(0.000000, 0.000000, 0.000000, 1.000000)
mad r0.zw, r0.zzzw, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
mul r1.xyzw, r0.wwww, cb1[1].xyzw
mad r1.xyzw, cb1[0].xyzw, r0.zzzz, r1.xyzw
mad r1.xyzw, cb1[2].xyzw, r0.xxxx, r1.xyzw
add r1.xyzw, r1.xyzw, cb1[3].xyzw
div r0.xzw, r1.xxyz, r1.wwww
sample_l_indexable(texture2d)(float,float,float,float) r1.xyz, v1.xyxx, t0.xyzw, s1, l(0.000000)
mul r1.xyz, r1.yxzy, l(15.937500, 1.992674, 0.124542125, 0.000000)
round_ni r1.w, r1.x
mad r1.y, r1.w, l(0.000488400517), r1.y
add r1.w, r1.y, l(-1.000000)
frc r1.x, r1.x
mad r1.x, r1.x, l(2.00048852), r1.z
add r1.y, r1.x, l(-1.000000)
add r1.x, -|r1.w|, l(1.000000)
add r2.z, -|r1.y|, r1.x
lt r1.x, r2.z, l(0.000000)
add r3.xy, -|r1.wyww|, l(1.000000, 1.000000, 0.000000, 0.000000)
ge r3.zw, r1.wwwy, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r3.zw, r3.zzzw, l(0,0,1,1), l(0,0,-1,-1)
itof r3.zw, r3.wwwz
mul r3.xy, r3.zwzz, r3.xyxx
movc r2.yw, r1.xxxx, r3.xxxy, r1.yyyw
dp3 r1.x, r2.yzwy, r2.yzwy
rsq r1.x, r1.x
mul r1.xyz, r1.xxxx, r2.yzwy
add r2.xyz, r0.xzwx, -cb0[1].xyzx
div r2.xyz, r2.xyzx, cb0[1].wwww
mul r3.xz, r1.zzyz, l(0.00781250000, 0.000000, 0.00781250000, 0.000000)
add r2.w, -r2.y, l(1.000000)
mad r4.xyz, r1.zxyz, l(0.00781250000, -0.00781250000, 0.00781250000, 0.000000), r2.xwzx
sample_l_indexable(texture3d)(float,float,float,float) r5.xyzw, r4.xyzx, t8.xyzw, s1, l(0.000000)
sample_l_indexable(texture3d)(float,float,float,float) r6.xyzw, r4.xyzx, t9.xyzw, s1, l(0.000000)
sample_l_indexable(texture3d)(float,float,float,float) r4.xyzw, r4.xyzx, t10.xyzw, s1, l(0.000000)
mov r7.x, l(0.886226952)
mul r7.yzw, r1.xxyz, l(0.000000, 1.02332675, -1.02332675, 1.02332675)
dp4 r5.x, r7.xyzw, r5.xyzw
dp4 r5.y, r7.xyzw, r6.xyzw
dp4 r5.z, r7.xyzw, r4.xyzw
mul r1.yzw, r5.xxyz, l(0.000000, 0.318309873, 0.318309873, 0.318309873)
add r4.xyz, r0.xzwx, -cb0[4].xyzx
dp3 r2.w, r4.xyzx, r4.xyzx
sqrt r2.w, r2.w
add r3.w, r2.w, -cb0[3].x
add r4.x, -cb0[3].x, cb0[3].y
div_sat r3.w, r3.w, r4.x
add_sat r2.xyz, r2.xyzx, l(0.000100, 0.000100, 0.000100, 0.000000)
mul r2.xyz, r2.xyzx, l(32.000000, 32.000000, 32.000000, 0.000000)
ftou r2.xyz, r2.xyzx
iadd r2.x, r2.y, r2.x
iadd r2.x, r2.z, r2.x
and r2.x, r2.x, l(1)
movc r2.xyz, r2.xxxx, l(0,0.850000,0,0), l(0,1.000000,0,0)
movc r1.yzw, r0.yyyy, r2.xxyz, r1.yyzw
lt r2.x, r3.w, l(1.000000)
if_nz r2.x
  add r2.xyz, r0.xzwx, -cb0[0].xyzx
  div r4.xyz, r2.xyzx, cb0[0].wwww
  mad r4.w, r1.x, l(-0.00781250000), -r4.y
  mov r3.y, l(1.000000)
  add r2.xyz, r3.xyzx, r4.xwzx
  sample_l_indexable(texture3d)(float,float,float,float) r5.xyzw, r2.xyzx, t5.xyzw, s1, l(0.000000)
  sample_l_indexable(texture3d)(float,float,float,float) r6.xyzw, r2.xyzx, t6.xyzw, s1, l(0.000000)
  sample_l_indexable(texture3d)(float,float,float,float) r8.xyzw, r2.xyzx, t7.xyzw, s1, l(0.000000)
  dp4 r2.x, r7.xyzw, r5.xyzw
  dp4 r2.y, r7.xyzw, r6.xyzw
  dp4 r2.z, r7.xyzw, r8.xyzw
  mul r2.xyz, r2.xyzx, l(0.318309873, 0.318309873, 0.318309873, 0.000000)
  add_sat r4.xyz, r4.xyzx, l(0.000100, 0.000100, 0.000100, 0.000000)
  mul r4.xyz, r4.xyzx, l(32.000000, 32.000000, 32.000000, 0.000000)
  ftou r4.xyz, r4.xyzx
  iadd r4.x, r4.y, r4.x
  iadd r4.x, r4.z, r4.x
  and r4.x, r4.x, l(1)
  movc r4.xyz, r4.xxxx, l(0.850000,0,0,0), l(1.000000,0,0,0)
  movc r2.xyz, r0.yyyy, r4.xyzx, r2.xyzx
  add r4.xyz, r1.yzwy, -r2.xyzx
  mad r2.xyz, r3.wwww, r4.xyzx, r2.xyzx
else
  add r2.w, r2.w, -cb0[3].z
  add r3.w, -cb0[3].z, cb0[3].w
  div_sat r2.w, r2.w, r3.w
  add r0.xzw, r0.xxzw, -cb0[2].xxyz
  div r4.xyz, r0.xzwx, cb0[2].wwww
  mad r4.w, r1.x, l(-0.00781250000), -r4.y
  mov r3.y, l(1.000000)
  add r0.xzw, r3.xxyz, r4.xxwz
  sample_l_indexable(texture3d)(float,float,float,float) r3.xyzw, r0.xzwx, t11.xyzw, s1, l(0.000000)
  sample_l_indexable(texture3d)(float,float,float,float) r5.xyzw, r0.xzwx, t12.xyzw, s1, l(0.000000)
  sample_l_indexable(texture3d)(float,float,float,float) r6.xyzw, r0.xzwx, t13.xyzw, s1, l(0.000000)
  dp4 r3.x, r7.xyzw, r3.xyzw
  dp4 r3.y, r7.xyzw, r5.xyzw
  dp4 r3.z, r7.xyzw, r6.xyzw
  mul r0.xzw, r3.xxyz, l(0.318309873, 0.000000, 0.318309873, 0.318309873)
  add_sat r3.xyz, r4.xyzx, l(0.000100, 0.000100, 0.000100, 0.000000)
  mul r3.xyz, r3.xyzx, l(32.000000, 32.000000, 32.000000, 0.000000)
  ftou r3.xyz, r3.xyzx
  iadd r1.x, r3.y, r3.x
  iadd r1.x, r3.z, r1.x
  and r1.x, r1.x, l(1)
  movc r3.xyz, r1.xxxx, l(0,0,0.850000,0), l(0,0,1.000000,0)
  movc r0.xyz, r0.yyyy, r3.xyzx, r0.xzwx
  add r0.xyz, -r1.yzwy, r0.xyzx
  mad r2.xyz, r2.wwww, r0.xyzx, r1.yzwy
endif
eq r0.x, cb0[4].w, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r1.xyzw, v1.xyxx, t1.xyzw, s1, l(0.000000)
movc r0.xyzw, r0.xxxx, r1.xyzw, l(1.000000,1.000000,1.000000,1.000000)
sample_l_indexable(texture2d)(float,float,float,float) r1.x, v1.xyxx, t2.xyzw, s1, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r1.y, v1.xyxx, t3.yxzw, s1, l(0.000000)
add r1.x, -r1.x, l(1.000000)
mul r0.xyzw, r0.xyzw, r1.xxxy
mul r0.xyz, r0.wwww, r0.xyzx
mul r0.xyz, r0.xyzx, r2.xyzx
mul r0.xyz, r0.xyzx, cb0[5].xyzx
max o0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
mov o0.w, l(0)
ret
// Approximately 126 instruction slots used
