//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.3.16 on Thu Feb 26 19:24:46 2026
//
//
// Buffer Definitions:
//
// cbuffer LightAmbientDiffuseParam
// {
//
//   float4x4 c_InvView;                // Offset:    0 Size:    64
//   float4x4 c_InvProj;                // Offset:   64 Size:    64
//   float3 c_Color;                    // Offset:  128 Size:    12
//   float dummy_;                      // Offset:  140 Size:     4 [unused]
//   float c_SkinMatAOAmount;           // Offset:  144 Size:     4 [unused]
//   float c_EyeMatAOAmount;            // Offset:  148 Size:     4 [unused]
//   float c_BackscatterMatAOAmount;    // Offset:  152 Size:     4
//   uint c_debugMode;                  // Offset:  156 Size:     4 [unused]
//
// }
//
// cbuffer LightProbeCB
// {
//
//   struct LightProbeListDatas
//   {
//
//       uint2 textureSize;             // Offset:    0
//       uint count;                    // Offset:    8
//       uint paddingD_;                // Offset:   12
//       uint4 paddingE_[3];            // Offset:   16
//
//       struct LightProbeData
//       {
//
//           float3 position;           // Offset:   64
//           float radius;              // Offset:   76
//           float3 axisX;              // Offset:   80
//           uint textureIndex;         // Offset:   92
//           float3 axisY;              // Offset:   96
//           uint weightScaling;        // Offset:  108
//           float3 axisZ;              // Offset:  112
//           float sphereScalingAndIntensity;// Offset:  124
//
//       } datas[510];                  // Offset:   64
//
//   } lightProbe;                      // Offset:    0 Size: 32704
//
// }
//
// cbuffer skySHCB
// {
//
//   struct SH3rgbCB
//   {
//
//       float r_f0;                    // Offset:    0
//       float r_f1;                    // Offset:    4
//       float r_f2;                    // Offset:    8
//       float r_f3;                    // Offset:   12
//       float r_f4;                    // Offset:   16
//       float r_f5;                    // Offset:   20
//       float r_f6;                    // Offset:   24
//       float r_f7;                    // Offset:   28
//       float r_f8;                    // Offset:   32
//       float g_f0;                    // Offset:   36
//       float g_f1;                    // Offset:   40
//       float g_f2;                    // Offset:   44
//       float g_f3;                    // Offset:   48
//       float g_f4;                    // Offset:   52
//       float g_f5;                    // Offset:   56
//       float g_f6;                    // Offset:   60
//       float g_f7;                    // Offset:   64
//       float g_f8;                    // Offset:   68
//       float b_f0;                    // Offset:   72
//       float b_f1;                    // Offset:   76
//       float b_f2;                    // Offset:   80
//       float b_f3;                    // Offset:   84
//       float b_f4;                    // Offset:   88
//       float b_f5;                    // Offset:   92
//       float b_f6;                    // Offset:   96
//       float b_f7;                    // Offset:  100
//       float b_f8;                    // Offset:  104
//       float padding00;               // Offset:  108
//
//   } c_skySH;                         // Offset:    0 Size:   112
//
// }
//
// Resource bind info for ExposureBuffer
// {
//
//   struct ExposureValues
//   {
//
//       float exposure_;               // Offset:    0
//       float exposureScale_;          // Offset:    4
//       float maxExposure_;            // Offset:    8
//
//   } $Element;                        // Offset:    0 Size:    12
//
// }
//
// Resource bind info for gridLightingParams
// {
//
//   struct LightProbeLightingParams
//   {
//
//       row_major float3x4 c_WorldSpaceToGridSpace;// Offset:    0
//       float2 c_InvNumCells;          // Offset:   48
//       float c_FadeYpos;              // Offset:   56
//       float c_FadeYneg;              // Offset:   60
//       float4 c_FadeStart;            // Offset:   64
//       float4 c_FadeEnd;              // Offset:   80
//
//   } $Element;                        // Offset:    0 Size:    96
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// linearClampSampler                sampler      NA          NA    0        1
// pointClampSampler                 sampler      NA          NA    1        1
// ExposureBuffer                    texture  struct         r/o    0        1
// albedoSampler                     texture  float4          2d    1        1
// specularSampler                   texture  float4          2d    2        1
// normalSampler                     texture  float4          2d    3        1
// depthSampler                      texture   float          2d    4        1
// aoSampler                         texture   float          2d    5        1
// shadowSampler                     texture   float          2d    6        1
// lightProbeWeightData              texture   uint4          2d    7        1
// gridLightingParams                texture  struct         r/o    8        1
// lightProbeSHDataRGB0              texture  float4     2darray    9        1
// lightProbeSHDataR14               texture  float4     2darray   10        1
// lightProbeSHDataR58               texture  float4     2darray   11        1
// lightProbeSHDataG14               texture  float4     2darray   12        1
// lightProbeSHDataG58               texture  float4     2darray   13        1
// lightProbeSHDataB14               texture  float4     2darray   14        1
// lightProbeSHDataB58               texture  float4     2darray   15        1
// LightAmbientDiffuseParam          cbuffer      NA          NA    0        1
// LightProbeCB                      cbuffer      NA          NA    1        1
// skySHCB                           cbuffer      NA          NA    2        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float      w
// TEXCOORD                 0   xy          1     NONE   float   xy
// TEXCOORD                 1   xyz         2     NONE   float   xyz
// TEXCOORD                 2   xyzw        3     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
// Pixel Shader runs at sample frequency
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[10], immediateIndexed
dcl_constantbuffer cb1[2043], dynamicIndexed
dcl_constantbuffer cb2[7], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_default
dcl_resource_structured t0, 12
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texture2d (float,float,float,float) t6
dcl_resource_texture2d (uint,uint,uint,uint) t7
dcl_resource_structured t8, 96
dcl_resource_texture2darray (float,float,float,float) t9
dcl_resource_texture2darray (float,float,float,float) t10
dcl_resource_texture2darray (float,float,float,float) t11
dcl_resource_texture2darray (float,float,float,float) t12
dcl_resource_texture2darray (float,float,float,float) t13
dcl_resource_texture2darray (float,float,float,float) t14
dcl_resource_texture2darray (float,float,float,float) t15
dcl_input_ps_siv linear noperspective sample v0.w, position
dcl_input_ps linear sample v1.xy
dcl_input_ps linear sample v2.xyz
dcl_input_ps linear sample v3.xyzw
dcl_output o0.xyzw
dcl_temps 21
sample_l_indexable(texture2d)(float,float,float,float) r0.xyzw, v1.xyxx, t3.xyzw, s1, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r1.xyzw, v1.xyxx, t1.xyzw, s1, l(0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r2.xyz, v1.xyxx, t2.xyzw, s1, l(0.000000)
mul r0.xyz, r0.yxzy, l(15.937500, 1.992674, 0.124542125, 0.000000)
round_ni r2.w, r0.x
mad r0.y, r2.w, l(0.000488400517), r0.y
frc r0.x, r0.x
mad r0.x, r0.x, l(2.00048852), r0.z
add r3.xyw, r0.yxyy, l(-1.000000, -1.000000, 0.000000, -1.000000)
add r0.x, -|r3.w|, l(1.000000)
add r4.z, -|r3.y|, r0.x
lt r0.x, r4.z, l(0.000000)
add r5.xyz, -|r3.ywyy|, l(1.000000, 1.000000, 1.000000, 0.000000)
ge r0.yz, r3.wwyw, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r0.yz, r0.yyzy, l(0,1,1,0), l(0,-1,-1,0)
itof r6.xyz, r0.yzyy
mul r5.xyz, r5.xyzx, r6.xyzx
movc r4.xyw, r0.xxxx, r5.xyxz, r3.xyxw
dp3 r0.x, r4.yzwy, r4.yzwy
rsq r0.x, r0.x
mul r3.xyzw, r0.xxxx, r4.xyzw
eq r4.xyzw, r2.xyzy, l(0.000000, 0.00392156886, 0.000000, 0.000000)
and r0.x, r4.y, r4.x
and r0.y, r4.z, r0.x
not r5.z, r4.z
ge r6.y, l(0.500000), r2.z
not r6.w, r6.y
movc r6.yw, r0.yyyy, l(0,0,0,0), r6.yyyw
mov r5.x, r4.z
mov r5.yw, l(0,0,0,0)
mov r6.xz, l(0,0,0,0)
movc r4.xyzw, r4.wwww, r5.xyzw, r6.xyzw
and r0.z, r2.x, r4.x
add r0.z, -r0.z, l(1.000000)
mul r5.xyz, r0.zzzz, r1.xyzx
movc r5.xyz, r4.zzzz, l(1.000000,1.000000,1.000000,0), r5.xyzx
movc r1.xyz, r4.wwww, r1.xyzx, r5.xyzx
lt r0.z, l(0.000000), r2.y
and r2.xyz, r2.xyzx, r0.zzzz
lt r0.z, l(0.500000), r2.z
movc r0.z, r0.z, l(-1.007874), l(-0.000000)
mad r2.w, r2.z, l(2.007874), r0.z
dp3 r0.z, v2.xyzx, v2.xyzx
rsq r0.z, r0.z
mul r5.xyzw, r0.zzzz, v2.xyzx
sample_l_indexable(texture2d)(float,float,float,float) r0.z, v1.xyxx, t5.yzxw, s1, l(0.000000)
and r2.z, r4.y, l(0x3f800000)
mov r0.x, r4.z
or r0.xy, r0.xyxx, r4.ywyy
or r0.x, r0.y, r0.x
movc r0.x, r0.x, l(0), l(1.000000)
mad r0.x, r2.z, cb0[9].z, r0.x
add r0.y, r0.z, l(-1.000000)
mad r0.x, r0.x, r0.y, l(1.000000)
utof r0.yz, cb1[0].xxyx
mul r0.yz, r0.yyzy, v1.xxyx
ftoi r6.xy, r0.yzyy
mov r6.zw, l(0,0,0,0)
ld_indexable(texture2d)(uint,uint,uint,uint) r6.xyz, r6.xyzw, t7.xyzw
ushr r7.xyz, r6.xyzx, l(8, 8, 8, 0)
and r6.xyz, r6.xyzx, l(255, 255, 255, 0)
utof r6.xyz, r6.xyzx
mul r6.xyz, r6.xyzx, l(0.00392156886, 0.00392156886, 0.00392156886, 0.000000)
ult r0.y, r7.x, l(255)
if_nz r0.y
  sample_l_indexable(texture2d)(float,float,float,float) r0.y, v1.xyxx, t4.yxzw, s1, l(0.000000)
  sample_l_indexable(texture2d)(float,float,float,float) r0.z, v1.xyxx, t6.yzxw, s1, l(0.000000)
  add r0.z, -r0.z, l(1.000000)
  div r8.xy, v3.xyxx, v0.wwww
  mov r8.zw, v3.zzzw
  mad r8.xyzw, cb0[6].xyzw, r0.yyyy, r8.xyzw
  div r8.xyz, r8.xyzx, r8.wwww
  mul r9.xyz, r8.yyyy, cb0[1].xyzx
  mad r8.xyw, cb0[0].xyxz, r8.xxxx, r9.xyxz
  mad r8.xyz, cb0[2].xyzx, r8.zzzz, r8.xywx
  add r8.xyz, r8.xyzx, cb0[3].xyzx
  ishl r0.y, r7.x, l(2)
  and r4.xz, l(0x0000ffff, 0, 0x40000000, 0), cb1[r0.y + 5].wwww
  if_nz r4.z
    dp3 r2.z, cb1[r0.y + 5].xyzx, cb1[r0.y + 5].xyzx
    rsq r2.z, r2.z
    mul r9.xy, r2.zzzz, cb1[r0.y + 5].xzxx
    dp2 r10.x, r3.wzww, r9.xyxx
    mov r9.z, -r9.y
    dp2 r10.y, r3.zwzz, r9.xzxx
  else
    mov r10.xy, r3.wzww
  endif
  ld_structured_indexable(structured_buffer, stride=96)(mixed,mixed,mixed,mixed) r9.xyzw, r7.x, l(0), t8.xyzw
  ld_structured_indexable(structured_buffer, stride=96)(mixed,mixed,mixed,mixed) r11.xyzw, r7.x, l(32), t8.xyzw
  mov r8.w, l(1.000000)
  dp4 r9.x, r9.xyzw, r8.xyzw
  dp4 r9.y, r11.xyzw, r8.xyzw
  round_ni r11.xyzw, r9.xyxy
  add r11.xyzw, r11.xyzw, l(0.010000, 0.010000, 0.990000, 0.990000)
  max r7.xw, r9.xxxy, r11.xxxy
  min r7.xw, r11.zzzw, r7.xxxw
  add r7.xw, r7.xxxw, l(0.500000, 0.000000, 0.000000, 0.500000)
  mul r9.xy, r7.xwxx, l(0.062500, 0.062500, 0.000000, 0.000000)
  utof r9.z, r4.x
  sample_l_indexable(texture2darray)(float,float,float,float) r11.xyzw, r9.xyzx, t9.xyzw, s0, l(0.000000)
  sample_l_indexable(texture2darray)(float,float,float,float) r12.xyzw, r9.xyzx, t10.xyzw, s0, l(0.000000)
  sample_l_indexable(texture2darray)(float,float,float,float) r13.xyzw, r9.xyzx, t11.xyzw, s0, l(0.000000)
  sample_l_indexable(texture2darray)(float,float,float,float) r14.xyzw, r9.xyzx, t12.xyzw, s0, l(0.000000)
  sample_l_indexable(texture2darray)(float,float,float,float) r15.xyzw, r9.xyzx, t13.xyzw, s0, l(0.000000)
  sample_l_indexable(texture2darray)(float,float,float,float) r16.xyzw, r9.xyzx, t14.xyzw, s0, l(0.000000)
  sample_l_indexable(texture2darray)(float,float,float,float) r9.xyzw, r9.xyzx, t15.xyzw, s0, l(0.000000)
  max r2.z, r11.w, l(9.999999717E-010)
  div r2.z, l(1.000000, 1.000000, 1.000000, 1.000000), r2.z
  mul r11.xyz, r2.zzzz, r11.xyzx
  mul r12.xyzw, r2.zzzz, r12.xyzw
  mul r13.xyzw, r2.zzzz, r13.xyzw
  mul r14.xyzw, r2.zzzz, r14.xyzw
  mul r15.xyzw, r2.zzzz, r15.xyzw
  mul r16.xyzw, r2.zzzz, r16.xyzw
  mul r9.xyzw, r2.zzzz, r9.xyzw
  mul r4.xz, r10.xxyx, l(-0.325735, 0.000000, 0.325735, 0.000000)
  mul r2.z, r3.y, r10.x
  mul r2.z, r2.z, l(0.273137122)
  mul r7.xw, r3.yyyy, l(-0.325735, 0.000000, 0.000000, -0.273137122)
  mul r6.w, r10.y, r7.w
  mul r17.xy, r10.yxyy, r10.yyyy
  mul r10.w, r17.y, l(-0.273137122)
  mad r11.w, r17.x, l(0.236543670), l(-0.0788478926)
  mul r17.x, r3.y, r3.y
  mad r17.y, r10.x, r10.x, -r17.x
  mul r17.y, r17.y, l(0.136568561)
  mul r17.z, r10.w, r13.z
  mad r17.z, r13.w, r17.y, r17.z
  mad r17.z, r13.y, r11.w, r17.z
  mad r17.z, r13.x, r6.w, r17.z
  mad r17.z, r12.w, r2.z, r17.z
  mad r17.z, r12.z, r4.x, r17.z
  mad r17.z, r12.y, r4.z, r17.z
  mad r17.z, r12.x, r7.x, r17.z
  mad r18.x, r11.x, l(0.282094806), r17.z
  mul r17.z, r10.w, r15.z
  mad r17.z, r15.w, r17.y, r17.z
  mad r17.z, r15.y, r11.w, r17.z
  mad r17.z, r15.x, r6.w, r17.z
  mad r17.z, r14.w, r2.z, r17.z
  mad r17.z, r14.z, r4.x, r17.z
  mad r17.z, r14.y, r4.z, r17.z
  mad r17.z, r14.x, r7.x, r17.z
  mad r18.y, r11.y, l(0.282094806), r17.z
  mul r10.w, r9.z, r10.w
  mad r10.w, r9.w, r17.y, r10.w
  mad r10.w, r9.y, r11.w, r10.w
  mad r6.w, r9.x, r6.w, r10.w
  mad r2.z, r16.w, r2.z, r6.w
  mad r2.z, r16.z, r4.x, r2.z
  mad r2.z, r16.y, r4.z, r2.z
  mad r2.z, r16.x, r7.x, r2.z
  mad r18.z, r11.z, l(0.282094806), r2.z
  max r17.yzw, r18.xxyz, l(0.000000, 0.000000, 0.000000, 0.000000)
  if_nz r4.y
    mov r10.z, r3.y
    dp3 r2.z, r10.zyxz, r5.yzwy
    mov_sat r2.z, -r2.z
    mul r10.xyz, r2.xywx, r2.zzzz
    mul r18.xyz, r5.wzyw, l(-0.325735, 0.325735, -0.325735, 0.000000)
    mul r19.xyzw, r5.wyzw, r5.yzzz
    mul r19.xyw, r19.xyxw, l(0.273137122, -0.273137122, 0.000000, -0.273137122)
    mad r2.z, r19.z, l(0.236543670), l(-0.0788478926)
    mul r4.x, r5.y, r5.y
    mad r4.x, r5.w, r5.w, -r4.x
    mul r4.x, r4.x, l(0.136568561)
    mul r4.z, r13.z, r19.w
    mad r4.z, r13.w, r4.x, r4.z
    mad r4.z, r13.y, r2.z, r4.z
    mad r4.z, r13.x, r19.y, r4.z
    mad r4.z, r12.w, r19.x, r4.z
    mad r4.z, r12.z, r18.x, r4.z
    mad r4.z, r12.y, r18.y, r4.z
    mad r4.z, r12.x, r18.z, r4.z
    mad r12.x, r11.x, l(0.282094806), r4.z
    mul r4.z, r15.z, r19.w
    mad r4.z, r15.w, r4.x, r4.z
    mad r4.z, r15.y, r2.z, r4.z
    mad r4.z, r15.x, r19.y, r4.z
    mad r4.z, r14.w, r19.x, r4.z
    mad r4.z, r14.z, r18.x, r4.z
    mad r4.z, r14.y, r18.y, r4.z
    mad r4.z, r14.x, r18.z, r4.z
    mad r12.y, r11.y, l(0.282094806), r4.z
    mul r4.z, r9.z, r19.w
    mad r4.x, r9.w, r4.x, r4.z
    mad r2.z, r9.y, r2.z, r4.x
    mad r2.z, r9.x, r19.y, r2.z
    mad r2.z, r16.w, r19.x, r2.z
    mad r2.z, r16.z, r18.x, r2.z
    mad r2.z, r16.y, r18.y, r2.z
    mad r2.z, r16.x, r18.z, r2.z
    mad r12.z, r11.z, l(0.282094806), r2.z
    max r9.xyz, r12.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
    mad r17.yzw, r10.xxyz, r9.xxyz, r17.yyzw
  endif
  and r0.y, l(255), cb1[r0.y + 6].w
  utof r0.y, r0.y
  mul r0.y, r0.z, r0.y
  mad r0.y, -r0.y, l(0.00392156886), l(1.000000)
  mul r6.x, r0.y, r6.x
  mul r9.xyz, r6.xxxx, r17.yzwy
  ult r0.y, r7.y, l(255)
  if_nz r0.y
    ishl r0.y, r7.y, l(2)
    and r4.xz, l(0x0000ffff, 0, 0x40000000, 0), cb1[r0.y + 5].wwww
    if_nz r4.z
      dp3 r2.z, cb1[r0.y + 5].xyzx, cb1[r0.y + 5].xyzx
      rsq r2.z, r2.z
      mul r10.xy, r2.zzzz, cb1[r0.y + 5].xzxx
      dp2 r11.x, r3.wzww, r10.xyxx
      mov r10.z, -r10.y
      dp2 r11.y, r3.zwzz, r10.xzxx
    else
      mov r11.xy, r3.wzww
    endif
    ld_structured_indexable(structured_buffer, stride=96)(mixed,mixed,mixed,mixed) r10.xyzw, r7.y, l(0), t8.xyzw
    ld_structured_indexable(structured_buffer, stride=96)(mixed,mixed,mixed,mixed) r12.xyzw, r7.y, l(32), t8.xyzw
    dp4 r10.x, r10.xyzw, r8.xyzw
    dp4 r10.y, r12.xyzw, r8.xyzw
    round_ni r12.xyzw, r10.xyxy
    add r12.xyzw, r12.xyzw, l(0.010000, 0.010000, 0.990000, 0.990000)
    max r10.xy, r10.xyxx, r12.xyxx
    min r10.xy, r12.zwzz, r10.xyxx
    add r10.xy, r10.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
    mul r10.xy, r10.xyxx, l(0.062500, 0.062500, 0.000000, 0.000000)
    utof r10.z, r4.x
    sample_l_indexable(texture2darray)(float,float,float,float) r12.xyzw, r10.xyzx, t9.xyzw, s0, l(0.000000)
    sample_l_indexable(texture2darray)(float,float,float,float) r13.xyzw, r10.xyzx, t10.xyzw, s0, l(0.000000)
    sample_l_indexable(texture2darray)(float,float,float,float) r14.xyzw, r10.xyzx, t11.xyzw, s0, l(0.000000)
    sample_l_indexable(texture2darray)(float,float,float,float) r15.xyzw, r10.xyzx, t12.xyzw, s0, l(0.000000)
    sample_l_indexable(texture2darray)(float,float,float,float) r16.xyzw, r10.xyzx, t13.xyzw, s0, l(0.000000)
    sample_l_indexable(texture2darray)(float,float,float,float) r18.xyzw, r10.xyzx, t14.xyzw, s0, l(0.000000)
    sample_l_indexable(texture2darray)(float,float,float,float) r10.xyzw, r10.xyzx, t15.xyzw, s0, l(0.000000)
    max r2.z, r12.w, l(9.999999717E-010)
    div r2.z, l(1.000000, 1.000000, 1.000000, 1.000000), r2.z
    mul r12.xyz, r2.zzzz, r12.xyzx
    mul r13.xyzw, r2.zzzz, r13.xyzw
    mul r14.xyzw, r2.zzzz, r14.xyzw
    mul r15.xyzw, r2.zzzz, r15.xyzw
    mul r16.xyzw, r2.zzzz, r16.xyzw
    mul r18.xyzw, r2.zzzz, r18.xyzw
    mul r10.xyzw, r2.zzzz, r10.xyzw
    mul r4.xz, r11.xxyx, l(-0.325735, 0.000000, 0.325735, 0.000000)
    mul r2.z, r3.y, r11.x
    mul r2.z, r2.z, l(0.273137122)
    mul r6.w, r7.w, r11.y
    mul r17.yz, r11.yyxy, r11.yyyy
    mul r7.y, r17.z, l(-0.273137122)
    mad r9.w, r17.y, l(0.236543670), l(-0.0788478926)
    mad r11.w, r11.x, r11.x, -r17.x
    mul r11.w, r11.w, l(0.136568561)
    mul r12.w, r7.y, r14.z
    mad r12.w, r14.w, r11.w, r12.w
    mad r12.w, r14.y, r9.w, r12.w
    mad r12.w, r14.x, r6.w, r12.w
    mad r12.w, r13.w, r2.z, r12.w
    mad r12.w, r13.z, r4.x, r12.w
    mad r12.w, r13.y, r4.z, r12.w
    mad r12.w, r13.x, r7.x, r12.w
    mad r19.x, r12.x, l(0.282094806), r12.w
    mul r12.w, r7.y, r16.z
    mad r12.w, r16.w, r11.w, r12.w
    mad r12.w, r16.y, r9.w, r12.w
    mad r12.w, r16.x, r6.w, r12.w
    mad r12.w, r15.w, r2.z, r12.w
    mad r12.w, r15.z, r4.x, r12.w
    mad r12.w, r15.y, r4.z, r12.w
    mad r12.w, r15.x, r7.x, r12.w
    mad r19.y, r12.y, l(0.282094806), r12.w
    mul r7.y, r7.y, r10.z
    mad r7.y, r10.w, r11.w, r7.y
    mad r7.y, r10.y, r9.w, r7.y
    mad r6.w, r10.x, r6.w, r7.y
    mad r2.z, r18.w, r2.z, r6.w
    mad r2.z, r18.z, r4.x, r2.z
    mad r2.z, r18.y, r4.z, r2.z
    mad r2.z, r18.x, r7.x, r2.z
    mad r19.z, r12.z, l(0.282094806), r2.z
    max r17.yzw, r19.xxyz, l(0.000000, 0.000000, 0.000000, 0.000000)
    if_nz r4.y
      mov r11.z, r3.y
      dp3 r2.z, r11.zyxz, r5.yzwy
      mov_sat r2.z, -r2.z
      mul r11.xyz, r2.xywx, r2.zzzz
      mul r19.xyz, r5.wzyw, l(-0.325735, 0.325735, -0.325735, 0.000000)
      mul r20.xyzw, r5.wyzw, r5.yzzz
      mul r20.xyw, r20.xyxw, l(0.273137122, -0.273137122, 0.000000, -0.273137122)
      mad r2.z, r20.z, l(0.236543670), l(-0.0788478926)
      mul r4.x, r5.y, r5.y
      mad r4.x, r5.w, r5.w, -r4.x
      mul r4.x, r4.x, l(0.136568561)
      mul r4.z, r14.z, r20.w
      mad r4.z, r14.w, r4.x, r4.z
      mad r4.z, r14.y, r2.z, r4.z
      mad r4.z, r14.x, r20.y, r4.z
      mad r4.z, r13.w, r20.x, r4.z
      mad r4.z, r13.z, r19.x, r4.z
      mad r4.z, r13.y, r19.y, r4.z
      mad r4.z, r13.x, r19.z, r4.z
      mad r13.x, r12.x, l(0.282094806), r4.z
      mul r4.z, r16.z, r20.w
      mad r4.z, r16.w, r4.x, r4.z
      mad r4.z, r16.y, r2.z, r4.z
      mad r4.z, r16.x, r20.y, r4.z
      mad r4.z, r15.w, r20.x, r4.z
      mad r4.z, r15.z, r19.x, r4.z
      mad r4.z, r15.y, r19.y, r4.z
      mad r4.z, r15.x, r19.z, r4.z
      mad r13.y, r12.y, l(0.282094806), r4.z
      mul r4.z, r10.z, r20.w
      mad r4.x, r10.w, r4.x, r4.z
      mad r2.z, r10.y, r2.z, r4.x
      mad r2.z, r10.x, r20.y, r2.z
      mad r2.z, r18.w, r20.x, r2.z
      mad r2.z, r18.z, r19.x, r2.z
      mad r2.z, r18.y, r19.y, r2.z
      mad r2.z, r18.x, r19.z, r2.z
      mad r13.z, r12.z, l(0.282094806), r2.z
      max r10.xyz, r13.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
      mad r17.yzw, r11.xxyz, r10.xxyz, r17.yyzw
    endif
    and r0.y, l(255), cb1[r0.y + 6].w
    utof r0.y, r0.y
    mul r0.y, r0.z, r0.y
    mad r0.y, -r0.y, l(0.00392156886), l(1.000000)
    mul r6.y, r0.y, r6.y
    mad r9.xyz, r17.yzwy, r6.yyyy, r9.xyzx
    ult r0.y, r7.z, l(255)
    if_nz r0.y
      ishl r0.y, r7.z, l(2)
      and r4.xz, l(0x0000ffff, 0, 0x40000000, 0), cb1[r0.y + 5].wwww
      if_nz r4.z
        dp3 r2.z, cb1[r0.y + 5].xyzx, cb1[r0.y + 5].xyzx
        rsq r2.z, r2.z
        mul r10.xy, r2.zzzz, cb1[r0.y + 5].xzxx
        dp2 r11.x, r3.wzww, r10.xyxx
        mov r10.z, -r10.y
        dp2 r11.y, r3.zwzz, r10.xzxx
      else
        mov r11.xy, r3.wzww
      endif
      ld_structured_indexable(structured_buffer, stride=96)(mixed,mixed,mixed,mixed) r10.xyzw, r7.z, l(0), t8.xyzw
      ld_structured_indexable(structured_buffer, stride=96)(mixed,mixed,mixed,mixed) r12.xyzw, r7.z, l(32), t8.xyzw
      dp4 r10.x, r10.xyzw, r8.xyzw
      dp4 r10.y, r12.xyzw, r8.xyzw
      round_ni r8.xyzw, r10.xyxy
      add r8.xyzw, r8.xyzw, l(0.010000, 0.010000, 0.990000, 0.990000)
      max r7.yz, r8.xxyx, r10.xxyx
      min r7.yz, r8.zzwz, r7.yyzy
      add r7.yz, r7.yyzy, l(0.000000, 0.500000, 0.500000, 0.000000)
      mul r8.xy, r7.yzyy, l(0.062500, 0.062500, 0.000000, 0.000000)
      utof r8.z, r4.x
      sample_l_indexable(texture2darray)(float,float,float,float) r10.xyzw, r8.xyzx, t9.xyzw, s0, l(0.000000)
      sample_l_indexable(texture2darray)(float,float,float,float) r12.xyzw, r8.xyzx, t10.xyzw, s0, l(0.000000)
      sample_l_indexable(texture2darray)(float,float,float,float) r13.xyzw, r8.xyzx, t11.xyzw, s0, l(0.000000)
      sample_l_indexable(texture2darray)(float,float,float,float) r14.xyzw, r8.xyzx, t12.xyzw, s0, l(0.000000)
      sample_l_indexable(texture2darray)(float,float,float,float) r15.xyzw, r8.xyzx, t13.xyzw, s0, l(0.000000)
      sample_l_indexable(texture2darray)(float,float,float,float) r16.xyzw, r8.xyzx, t14.xyzw, s0, l(0.000000)
      sample_l_indexable(texture2darray)(float,float,float,float) r8.xyzw, r8.xyzx, t15.xyzw, s0, l(0.000000)
      max r2.z, r10.w, l(9.999999717E-010)
      div r2.z, l(1.000000, 1.000000, 1.000000, 1.000000), r2.z
      mul r10.xyz, r2.zzzz, r10.xyzx
      mul r12.xyzw, r2.zzzz, r12.xyzw
      mul r13.xyzw, r2.zzzz, r13.xyzw
      mul r14.xyzw, r2.zzzz, r14.xyzw
      mul r15.xyzw, r2.zzzz, r15.xyzw
      mul r16.xyzw, r2.zzzz, r16.xyzw
      mul r8.xyzw, r2.zzzz, r8.xyzw
      mul r4.xz, r11.xxyx, l(-0.325735, 0.000000, 0.325735, 0.000000)
      mul r2.z, r3.y, r11.x
      mul r2.z, r2.z, l(0.273137122)
      mul r6.w, r7.w, r11.y
      mul r7.yz, r11.yyxy, r11.yyyy
      mad r7.y, r7.y, l(0.236543670), l(-0.0788478926)
      mad r7.w, r11.x, r11.x, -r17.x
      mul r7.zw, r7.zzzw, l(0.000000, 0.000000, -0.273137122, 0.136568561)
      mul r9.w, r7.z, r13.z
      mad r9.w, r13.w, r7.w, r9.w
      mad r9.w, r13.y, r7.y, r9.w
      mad r9.w, r13.x, r6.w, r9.w
      mad r9.w, r12.w, r2.z, r9.w
      mad r9.w, r12.z, r4.x, r9.w
      mad r9.w, r12.y, r4.z, r9.w
      mad r9.w, r12.x, r7.x, r9.w
      mad r17.x, r10.x, l(0.282094806), r9.w
      mul r9.w, r7.z, r15.z
      mad r9.w, r15.w, r7.w, r9.w
      mad r9.w, r15.y, r7.y, r9.w
      mad r9.w, r15.x, r6.w, r9.w
      mad r9.w, r14.w, r2.z, r9.w
      mad r9.w, r14.z, r4.x, r9.w
      mad r9.w, r14.y, r4.z, r9.w
      mad r9.w, r14.x, r7.x, r9.w
      mad r17.y, r10.y, l(0.282094806), r9.w
      mul r7.z, r7.z, r8.z
      mad r7.z, r8.w, r7.w, r7.z
      mad r7.y, r8.y, r7.y, r7.z
      mad r6.w, r8.x, r6.w, r7.y
      mad r2.z, r16.w, r2.z, r6.w
      mad r2.z, r16.z, r4.x, r2.z
      mad r2.z, r16.y, r4.z, r2.z
      mad r2.z, r16.x, r7.x, r2.z
      mad r17.z, r10.z, l(0.282094806), r2.z
      max r7.xyz, r17.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
      if_nz r4.y
        mov r11.z, r3.y
        dp3 r2.z, r11.zyxz, r5.yzwy
        mov_sat r2.z, -r2.z
        mul r11.xyz, r2.xywx, r2.zzzz
        mul r17.xyz, r5.wzyw, l(-0.325735, 0.325735, -0.325735, 0.000000)
        mul r18.xyzw, r5.wyzw, r5.yzzz
        mul r18.xyw, r18.xyxw, l(0.273137122, -0.273137122, 0.000000, -0.273137122)
        mad r2.z, r18.z, l(0.236543670), l(-0.0788478926)
        mul r4.x, r5.y, r5.y
        mad r4.x, r5.w, r5.w, -r4.x
        mul r4.x, r4.x, l(0.136568561)
        mul r4.z, r13.z, r18.w
        mad r4.z, r13.w, r4.x, r4.z
        mad r4.z, r13.y, r2.z, r4.z
        mad r4.z, r13.x, r18.y, r4.z
        mad r4.z, r12.w, r18.x, r4.z
        mad r4.z, r12.z, r17.x, r4.z
        mad r4.z, r12.y, r17.y, r4.z
        mad r4.z, r12.x, r17.z, r4.z
        mad r12.x, r10.x, l(0.282094806), r4.z
        mul r4.z, r15.z, r18.w
        mad r4.z, r15.w, r4.x, r4.z
        mad r4.z, r15.y, r2.z, r4.z
        mad r4.z, r15.x, r18.y, r4.z
        mad r4.z, r14.w, r18.x, r4.z
        mad r4.z, r14.z, r17.x, r4.z
        mad r4.z, r14.y, r17.y, r4.z
        mad r4.z, r14.x, r17.z, r4.z
        mad r12.y, r10.y, l(0.282094806), r4.z
        mul r4.z, r8.z, r18.w
        mad r4.x, r8.w, r4.x, r4.z
        mad r2.z, r8.y, r2.z, r4.x
        mad r2.z, r8.x, r18.y, r2.z
        mad r2.z, r16.w, r18.x, r2.z
        mad r2.z, r16.z, r17.x, r2.z
        mad r2.z, r16.y, r17.y, r2.z
        mad r2.z, r16.x, r17.z, r2.z
        mad r12.z, r10.z, l(0.282094806), r2.z
        max r8.xyz, r12.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
        mad r7.xyz, r11.xyzx, r8.xyzx, r7.xyzx
      endif
      and r0.y, l(255), cb1[r0.y + 6].w
      utof r0.y, r0.y
      mul r0.y, r0.z, r0.y
      mad r0.y, -r0.y, l(0.00392156886), l(1.000000)
      mul r6.z, r0.y, r6.z
      mad r9.xyz, r7.xyzx, r6.zzzz, r9.xyzx
    endif
  endif
else
  mov r9.xyz, l(0,0,0,0)
endif
mul r7.xyz, r1.wwww, r9.xyzx
dp3 r0.y, l(1.000000, 1.000000, 1.000000, 0.000000), r6.xyzx
add r0.y, -r0.y, l(1.000000)
lt r0.z, l(0.000000), r0.y
if_nz r0.z
  mul r6.xyz, r3.wzyw, l(-0.325735, 0.325735, -0.325735, 0.000000)
  mul r8.xyzw, r3.xyzw, r3.yzzz
  mul r8.xyw, r8.xyxw, l(0.273137122, -0.273137122, 0.000000, -0.273137122)
  mad r0.z, r8.z, l(0.236543670), l(-0.0788478926)
  mul r2.z, r3.y, r3.y
  mad r2.z, r3.w, r3.w, -r2.z
  mul r2.z, r2.z, l(0.136568561)
  mul r3.x, r8.w, cb2[1].w
  mad r3.x, cb2[2].x, r2.z, r3.x
  mad r3.x, cb2[1].z, r0.z, r3.x
  mad r3.x, cb2[1].y, r8.y, r3.x
  mad r3.x, cb2[1].x, r8.x, r3.x
  mad r3.x, cb2[0].w, r6.x, r3.x
  mad r3.x, cb2[0].z, r6.y, r3.x
  mad r3.x, cb2[0].y, r6.z, r3.x
  mad r3.x, cb2[0].x, l(0.282094806), r3.x
  mul r3.w, r8.w, cb2[4].x
  mad r3.w, cb2[4].y, r2.z, r3.w
  mad r3.w, cb2[3].w, r0.z, r3.w
  mad r3.w, cb2[3].z, r8.y, r3.w
  mad r3.w, cb2[3].y, r8.x, r3.w
  mad r3.w, cb2[3].x, r6.x, r3.w
  mad r3.w, cb2[2].w, r6.y, r3.w
  mad r3.w, cb2[2].z, r6.z, r3.w
  mad r3.y, cb2[2].y, l(0.282094806), r3.w
  mul r3.w, r8.w, cb2[6].y
  mad r2.z, cb2[6].z, r2.z, r3.w
  mad r0.z, cb2[6].x, r0.z, r2.z
  mad r0.z, cb2[5].w, r8.y, r0.z
  mad r0.z, cb2[5].z, r8.x, r0.z
  mad r0.z, cb2[5].y, r6.x, r0.z
  mad r0.z, cb2[5].x, r6.y, r0.z
  mad r0.z, cb2[4].w, r6.z, r0.z
  mad r3.z, cb2[4].z, l(0.282094806), r0.z
  max r3.xyz, r3.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  if_nz r4.y
    mul r4.xyz, r5.wzyw, l(-0.325735, 0.325735, -0.325735, 0.000000)
    mul r6.xyzw, r5.xyzw, r5.yzzz
    mul r6.xyw, r6.xyxw, l(0.273137122, -0.273137122, 0.000000, -0.273137122)
    mad r0.z, r6.z, l(0.236543670), l(-0.0788478926)
    mul r2.z, r5.y, r5.y
    mad r2.z, r5.w, r5.w, -r2.z
    mul r2.z, r2.z, l(0.136568561)
    mul r3.w, r6.w, cb2[1].w
    mad r3.w, cb2[2].x, r2.z, r3.w
    mad r3.w, cb2[1].z, r0.z, r3.w
    mad r3.w, cb2[1].y, r6.y, r3.w
    mad r3.w, cb2[1].x, r6.x, r3.w
    mad r3.w, cb2[0].w, r4.x, r3.w
    mad r3.w, cb2[0].z, r4.y, r3.w
    mad r3.w, cb2[0].y, r4.z, r3.w
    mad r5.x, cb2[0].x, l(0.282094806), r3.w
    mul r3.w, r6.w, cb2[4].x
    mad r3.w, cb2[4].y, r2.z, r3.w
    mad r3.w, cb2[3].w, r0.z, r3.w
    mad r3.w, cb2[3].z, r6.y, r3.w
    mad r3.w, cb2[3].y, r6.x, r3.w
    mad r3.w, cb2[3].x, r4.x, r3.w
    mad r3.w, cb2[2].w, r4.y, r3.w
    mad r3.w, cb2[2].z, r4.z, r3.w
    mad r5.y, cb2[2].y, l(0.282094806), r3.w
    mul r3.w, r6.w, cb2[6].y
    mad r2.z, cb2[6].z, r2.z, r3.w
    mad r0.z, cb2[6].x, r0.z, r2.z
    mad r0.z, cb2[5].w, r6.y, r0.z
    mad r0.z, cb2[5].z, r6.x, r0.z
    mad r0.z, cb2[5].y, r4.x, r0.z
    mad r0.z, cb2[5].x, r4.y, r0.z
    mad r0.z, cb2[4].w, r4.z, r0.z
    mad r5.z, cb2[4].z, l(0.282094806), r0.z
    mad r3.xyz, r2.xywx, r5.xyzx, r3.xyzx
  endif
  mul r2.xyz, r1.wwww, r3.xyzx
  mad r7.xyz, r0.yyyy, r2.xyzx, r7.xyzx
endif
mad r0.y, r0.w, l(0.600000), l(0.400000)
movc r0.y, r4.w, r0.y, l(1.000000)
mul r1.xyz, r1.xyzx, cb0[8].xyzx
ld_structured_indexable(structured_buffer, stride=12)(mixed,mixed,mixed,mixed) r0.z, l(0), l(4), t0.xxxx
mul r0.z, r0.z, r0.x
mul r1.xyz, r0.zzzz, r1.xyzx
mul r0.yzw, r0.yyyy, r1.xxyz
mul o0.xyz, r0.yzwy, r7.xyzx
mov o0.w, r0.x
ret
// Approximately 549 instruction slots used
