//
// Generated by Microsoft (R) HLSL Shader Compiler 10.0.10011.16384
//
//   using 3Dmigoto v1.3.16 on Thu Feb 26 19:25:53 2026
//
//
// Buffer Definitions:
//
// cbuffer AbstractTracingCB
// {
//
//   struct VxgiAbstractTracingConstants
//   {
//
//       float4 rOpacityTextureSize;    // Offset:    0
//       float4 rEmittanceTextureSize;  // Offset:   16
//       float4 ClipmapAnchor;          // Offset:   32
//       float4 SceneBoundaryLower;     // Offset:   48
//       float4 SceneBoundaryUpper;     // Offset:   64
//       float4 ClipmapCenter;          // Offset:   80
//       float4 TracingToroidalOffset;  // Offset:   96
//       float EmittancePackingStride;  // Offset:  112
//       float FinestVoxelSize;         // Offset:  116
//       float StackTextureSize;        // Offset:  120
//       float rNearestLevel0Boundary;  // Offset:  124
//       float MaxMipmapLevel;          // Offset:  128
//       float rEmittanceStorageScale;  // Offset:  132
//       float rClipmapSizeWorld;       // Offset:  136
//       uint Use6DOpacity;             // Offset:  140
//
//   } g_VxgiAbstractTracingCB;         // Offset:    0 Size:   144
//
// }
//
// cbuffer TranslationCB
// {
//
//   float4 g_VxgiTranslationParameters[13];// Offset:    0 Size:   208
//   float4 g_VxgiTranslationParameters2[13];// Offset:  208 Size:   208
//
// }
//
// cbuffer cBuiltinTracingParameters
// {
//
//   struct GBufferParameters
//   {
//
//       row_major float4x4 viewProjMatrix;// Offset:    0
//       row_major float4x4 viewProjMatrixInv;// Offset:   64
//       row_major float4x4 viewMatrix; // Offset:  128
//       float4 viewOffset;             // Offset:  192
//       float4 cameraPosition;         // Offset:  208
//       float4 uvToView;               // Offset:  224
//       float2 gbufferSize;            // Offset:  240
//       float2 gbufferSizeInv;         // Offset:  248
//       float2 viewportOrigin;         // Offset:  256
//       float2 viewportSize;           // Offset:  264
//       float2 viewportSizeInv;        // Offset:  272
//       float2 firstSamplePosition;    // Offset:  280
//       float normalScale;             // Offset:  288
//       float normalBias;              // Offset:  292
//       float projectionA;             // Offset:  296
//       float projectionB;             // Offset:  300
//       float depthScale;              // Offset:  304
//       float depthBias;               // Offset:  308
//       float radiusToScreen;          // Offset:  312
//       float padding0;                // Offset:  316
//
//   } g_GBuffer;                       // Offset:    0 Size:   320
//
//   struct GBufferParameters
//   {
//
//       row_major float4x4 viewProjMatrix;// Offset:  320
//       row_major float4x4 viewProjMatrixInv;// Offset:  384
//       row_major float4x4 viewMatrix; // Offset:  448
//       float4 viewOffset;             // Offset:  512
//       float4 cameraPosition;         // Offset:  528
//       float4 uvToView;               // Offset:  544
//       float2 gbufferSize;            // Offset:  560
//       float2 gbufferSizeInv;         // Offset:  568
//       float2 viewportOrigin;         // Offset:  576
//       float2 viewportSize;           // Offset:  584
//       float2 viewportSizeInv;        // Offset:  592
//       float2 firstSamplePosition;    // Offset:  600
//       float normalScale;             // Offset:  608
//       float normalBias;              // Offset:  612
//       float projectionA;             // Offset:  616
//       float projectionB;             // Offset:  620
//       float depthScale;              // Offset:  624
//       float depthBias;               // Offset:  628
//       float radiusToScreen;          // Offset:  632
//       float padding0;                // Offset:  636
//
//   } g_PreviousGBuffer;               // Offset:  320 Size:   320 [unused]
//   row_major float4x4 g_ReprojectionMatrix;// Offset:  640 Size:    64 [unused]
//   float4 g_AmbientColor;             // Offset:  704 Size:    16 [unused]
//   float4 g_DownsampleScale;          // Offset:  720 Size:    16
//   float4 g_DebugParams;              // Offset:  736 Size:    16 [unused]
//   float4 g_EnvironmentMapTint;       // Offset:  752 Size:    16 [unused]
//   float4 g_RefinementGridResolution; // Offset:  768 Size:    16 [unused]
//   float4 g_BackgroundColor;          // Offset:  784 Size:    16 [unused]
//   int2 g_PixelToSave;                // Offset:  800 Size:     8 [unused]
//   int2 g_RandomOffset;               // Offset:  808 Size:     8
//   float2 g_GridOrigin;               // Offset:  816 Size:     8 [unused]
//   float g_ConeFactor;                // Offset:  824 Size:     4
//   float g_TracingStep;               // Offset:  828 Size:     4
//   float g_OpacityCorrectionFactor;   // Offset:  832 Size:     4
//   int g_MaxSamples;                  // Offset:  836 Size:     4
//   int g_NumCones;                    // Offset:  840 Size:     4 [unused]
//   float g_rNumCones;                 // Offset:  844 Size:     4
//   float g_EmittanceScale;            // Offset:  848 Size:     4 [unused]
//   float g_EnvironmentMapResolution;  // Offset:  852 Size:     4 [unused]
//   float g_MaxEnvironmentMapMipLevel; // Offset:  856 Size:     4 [unused]
//   float g_NormalOffsetFactor;        // Offset:  860 Size:     4
//   float g_AmbientAttenuationFactor;  // Offset:  864 Size:     4
//   uint g_FlipOpacityDirections;      // Offset:  868 Size:     4
//   float g_InitialOffsetBias;         // Offset:  872 Size:     4
//   float g_InitialOffsetDistanceFactor;// Offset:  876 Size:     4
//   uint g_EnableSpecularRandomOffsets;// Offset:  880 Size:     4 [unused]
//   uint g_NumDiscontinuityLevels;     // Offset:  884 Size:     4 [unused]
//   float g_TemporalReprojectionWeight;// Offset:  888 Size:     4 [unused]
//   float g_TangentJitterScale;        // Offset:  892 Size:     4 [unused]
//   float g_DepthDeltaSign;            // Offset:  896 Size:     4
//   float g_ReprojectionDepthWeightScale;// Offset:  900 Size:     4 [unused]
//   float g_ReprojectionNormalWeightExponent;// Offset:  904 Size:     4 [unused]
//   float g_InterpolationWeightThreshold;// Offset:  908 Size:     4 [unused]
//   uint g_EnableRefinement;           // Offset:  912 Size:     4 [unused]
//   float g_AmbientScale;              // Offset:  916 Size:     4
//   float g_AmbientBias;               // Offset:  920 Size:     4
//   float g_AmbientPower;              // Offset:  924 Size:     4
//   float g_AmbientDistanceDarkening;  // Offset:  928 Size:     4
//   int g_AltSettingsStencilMask;      // Offset:  932 Size:     4
//   int g_AltSettingsStencilRefValue;  // Offset:  936 Size:     4
//   float g_AltInitialOffsetBias;      // Offset:  940 Size:     4
//   float g_AltInitialOffsetDistanceFactor;// Offset:  944 Size:     4
//   float g_AltNormalOffsetFactor;     // Offset:  948 Size:     4
//   float g_AltTracingStep;            // Offset:  952 Size:     4
//   float g_SSAO_SurfaceBias;          // Offset:  956 Size:     4 [unused]
//   float g_SSAO_RadiusWorld;          // Offset:  960 Size:     4 [unused]
//   float g_SSAO_rBackgroundViewDepth; // Offset:  964 Size:     4 [unused]
//   float g_SSAO_CoarseAO;             // Offset:  968 Size:     4 [unused]
//   float g_SSAO_PowerExponent;        // Offset:  972 Size:     4 [unused]
//   uint g_EnableSSCorrection;         // Offset:  976 Size:     4
//   float g_SSCStartOffset;            // Offset:  980 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// s_VoxelTextureSampler             sampler      NA          NA    0        1
// g_DepthBuffer                     texture  float4          2d    0        1
// g_TargetNormal                    texture  float4          2d    2        1
// g_TargetFlatNormal                texture  float4          2d    3        1
// g_TargetStencil                   texture   uint2          2d    4        1
// t_OpacityMap_Pos                  texture  float4          3d    6        1
// t_OpacityMap_Neg                  texture  float4          3d    7        1
// t_ConeDirectionMap                texture  float4     2darray   10        1
// AbstractTracingCB                 cbuffer      NA          NA    0        1
// TranslationCB                     cbuffer      NA          NA    1        1
// cBuiltinTracingParameters         cbuffer      NA          NA    2        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float
// INSTANCEID               0     z         0     NONE   float     z
// RAY                      0   xyzw        1     NONE   float
// SV_Position              0   xyzw        2      POS   float   xy
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[9], immediateIndexed
dcl_constantbuffer cb1[26], dynamicIndexed
dcl_constantbuffer cb2[62], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t3
dcl_resource_texture2d (uint,uint,uint,uint) t4
dcl_resource_texture3d (float,float,float,float) t6
dcl_resource_texture3d (float,float,float,float) t7
dcl_resource_texture2darray (float,float,float,float) t10
dcl_input_ps linear v0.z
dcl_input_ps_siv linear noperspective v2.xy, position
dcl_output o0.xyzw
dcl_temps 13
lt r0.xy, l(1.000000, 1.000000, 0.000000, 0.000000), cb2[45].xyxx
and r0.x, r0.y, r0.x
round_ni r0.yz, v2.xxyx
itof r1.xy, cb2[50].zwzz
add r1.xy, r0.yzyy, r1.xyxx
mul r1.xy, r1.xyxx, cb2[45].zwzz
frc r1.xy, r1.xyxx
mul r1.xy, r1.xyxx, cb2[45].xyxx
round_ni r1.xy, r1.xyxx
add r0.w, -r1.x, cb2[45].x
mad r0.w, r0.z, cb2[45].y, r0.w
mad r1.x, r0.y, cb2[45].x, r1.y
add r0.w, r0.w, cb2[17].w
add r1.x, r1.x, cb2[17].z
add r1.y, r0.w, l(-1.000000)
movc r0.xw, r0.xxxx, r1.xxxy, v2.xxxy
ftoi r1.xy, r0.xwxx
mov r1.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r2.x, r1.xyww, t0.xyzw
ld_indexable(texture2d)(float,float,float,float) r2.yzw, r1.xyww, t3.wxyz
mad r2.x, r2.x, cb2[19].x, cb2[19].y
ge r3.x, cb2[18].x, l(-10.000000)
mul r3.yzw, r2.zzyw, l(0.000000, 15.937500, 1.992674, 0.124542125)
round_ni r4.x, r3.y
mad r3.z, r4.x, l(0.000488400517), r3.z
frc r3.y, r3.y
mad r3.y, r3.y, l(2.00048852), r3.w
add r4.xy, r3.zyzz, l(-1.000000, -1.000000, 0.000000, 0.000000)
add r3.yzw, -|r4.xxyx|, l(0.000000, 1.000000, 1.000000, 1.000000)
add r5.z, -|r4.y|, r3.y
lt r3.y, r5.z, l(0.000000)
ge r4.zw, r4.xxxy, l(0.000000, 0.000000, 0.000000, 0.000000)
movc r4.zw, r4.zzzw, l(0,0,1,1), l(0,0,-1,-1)
itof r4.zw, r4.zzzw
mul r3.zw, r3.zzzw, r4.zzzw
movc r5.xy, r3.yyyy, r3.zwzz, r4.xyxx
dp3 r3.y, r5.xyzx, r5.xyzx
rsq r3.y, r3.y
mul r3.yzw, r3.yyyy, r5.xxyz
mad r2.yzw, r2.yyzw, cb2[18].xxxx, cb2[18].yyyy
dp3 r4.x, r2.yzwy, r2.yzwy
sqrt r4.x, r4.x
lt r4.y, l(0.000000), r4.x
div r2.yzw, r2.yyzw, r4.xxxx
and r2.yzw, r2.yyzw, r4.yyyy
movc r2.yzw, r3.xxxx, r2.yyzw, r3.yyzw
add r0.xw, r0.xxxw, -cb2[16].xxxy
mul r0.xw, r0.xxxw, cb2[17].xxxy
mad r0.x, r0.x, l(2.000000), l(-1.000000)
mad r0.w, -r0.w, l(2.000000), l(1.000000)
mul r4.xyzw, r0.wwww, cb2[5].xyzw
mad r4.xyzw, r0.xxxx, cb2[4].xyzw, r4.xyzw
mad r4.xyzw, r2.xxxx, cb2[6].xyzw, r4.xyzw
add r4.xyzw, r4.xyzw, cb2[7].xyzw
div r3.yzw, r4.xxyz, r4.wwww
add r3.yzw, r3.yyzw, cb2[12].xxyz
add r4.xyz, r3.yzwy, -cb0[2].xyzx
max r0.x, |r4.z|, |r4.y|
max r0.x, r0.x, |r4.x|
add r0.w, -r0.x, cb0[2].w
mul r0.w, r0.w, cb0[8].z
mul_sat r0.w, r0.w, l(4.000000)
and r4.xyz, r2.yzwy, l(0x7f800000, 0x7f800000, 0x7f800000, 0)
ieq r5.xyz, r4.xyzx, l(0, 0, 0, 0)
and r2.x, r5.y, r5.x
and r2.x, r5.z, r2.x
ieq r4.xyz, r4.xyzx, l(0x7f800000, 0x7f800000, 0x7f800000, 0)
or r4.x, r4.y, r4.x
or r4.x, r4.z, r4.x
or r2.x, r2.x, r4.x
not r2.x, r2.x
ne r4.x, r0.w, l(0.000000)
and r2.x, r2.x, r4.x
if_nz r2.x
  ftou r4.z, v0.z
  dp3 r2.x, r2.yzwy, r2.yzwy
  rsq r2.x, r2.x
  mul r5.xyz, r2.xxxx, r2.yzwy
  mov r6.xyz, |r5.xyzx|
  max r5.w, r6.z, r6.y
  max r5.w, r5.w, r6.x
  mad r7.xyz, -r2.zyyz, r2.xxxx, -r5.zzyz
  lt r8.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r5.xyzx
  lt r9.xyz, r5.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
  iadd r8.xyz, -r8.xyzx, r9.xyzx
  itof r8.xyz, r8.xyzx
  eq r9.xy, r6.xyxx, r5.wwww
  mul r7.xyz, r7.xyzx, r8.xyzx
  mov r6.w, r7.y
  mov r7.w, r6.z
  movc r6.yzw, r9.yyyy, r6.yywy, r7.wwwz
  mov r7.yz, r6.xxxx
  movc r6.xyz, r9.xxxx, r7.xyzx, r6.yzwy
  dp3 r5.w, r6.xyzx, r6.xyzx
  rsq r5.w, r5.w
  mul r6.xyz, r5.wwww, r6.xyzx
  mul r7.xyz, r5.yzxy, r6.zxyz
  mad r7.xyz, r6.yzxy, r5.zxyz, -r7.xyzx
  ftoi r0.yz, r0.yyzy
  iadd r0.yz, r0.yyzy, cb2[50].zzwz
  and r4.xy, r0.yzyy, l(3, 3, 0, 0)
  mov r4.w, l(0)
  ld_indexable(texture2darray)(float,float,float,float) r4.xyzw, r4.xyzw, t10.xyzw
  mul r5.xyz, r5.xyzx, r4.yyyy
  mad r5.xyz, r4.xxxx, r6.xyzx, r5.xyzx
  mad r4.xyz, r4.zzzz, r7.xyzx, r5.xyzx
  dp3 r0.y, r4.xyzx, r4.xyzx
  rsq r0.y, r0.y
  mul r5.xyz, r0.yyyy, r4.xyzx
  dp2 r0.x, cb0[7].wwww, r0.xxxx
  max r0.x, r0.x, l(1.000000)
  mul r0.z, r4.w, r0.x
  mul r6.y, r0.z, cb2[51].w
  if_nz cb2[58].y
    ld_indexable(texture2d)(uint,uint,uint,uint) r0.z, r1.xyww, t4.xzyw
    and r0.z, r0.z, cb2[58].y
    ieq r0.z, r0.z, cb2[58].z
    mov r7.xy, cb2[54].zwzz
    mov r7.z, cb2[53].w
    mov r7.w, cb2[51].w
    movc r8.y, r0.z, cb2[58].w, r7.x
    movc r8.xzw, r0.zzzz, cb2[59].zzxy, r7.wwyz
    mov r6.xzw, r8.yyzw
  else
    mov r6.xz, cb2[54].zzwz
    mov r6.w, cb2[53].w
    mov r8.x, cb2[51].w
  endif
  if_nz cb2[61].x
    ld_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyzw, t2.xyzw
    mul r7.xyz, r1.yxzy, l(15.937500, 1.992674, 0.124542125, 0.000000)
    round_ni r0.z, r7.x
    mad r0.z, r0.z, l(0.000488400517), r7.y
    add r9.x, r0.z, l(-1.000000)
    frc r0.z, r7.x
    mad r0.z, r0.z, l(2.00048852), r7.z
    add r9.y, r0.z, l(-1.000000)
    add r7.xyz, -|r9.xyxx|, l(1.000000, 1.000000, 1.000000, 0.000000)
    add r10.z, -|r9.y|, r7.x
    lt r0.z, r10.z, l(0.000000)
    ge r7.xw, r9.xxxy, l(0.000000, 0.000000, 0.000000, 0.000000)
    movc r7.xw, r7.xxxw, l(1,0,0,1), l(-1,0,0,-1)
    itof r7.xw, r7.xxxw
    mul r7.xy, r7.xwxx, r7.yzyy
    movc r10.xy, r0.zzzz, r7.xyxx, r9.xyxx
    dp3 r0.z, r10.xyzx, r10.xyzx
    rsq r0.z, r0.z
    mul r7.xyz, r0.zzzz, r10.xyzx
    mad r1.xyz, r1.xyzx, cb2[18].xxxx, cb2[18].yyyy
    dp3 r0.z, r1.xyzx, r1.xyzx
    sqrt r0.z, r0.z
    lt r1.w, l(0.000000), r0.z
    div r1.xyz, r1.xyzx, r0.zzzz
    and r1.xyz, r1.xyzx, r1.wwww
    movc r1.xyz, r3.xxxx, r1.xyzx, r7.xyzx
    mul r0.z, r0.x, cb0[7].y
    add r1.w, r0.z, r0.z
    mul r3.x, r0.z, cb2[61].y
    mad r1.xyz, r4.xyzx, r0.yyyy, r1.xyzx
    mad r1.xyz, r1.xyzx, r3.xxxx, r3.yzwy
    mad r4.xyz, r5.xyzx, r1.wwww, r3.yzwy
    mul r7.xyzw, r1.yyyy, cb2[1].xyzw
    mad r7.xyzw, r1.xxxx, cb2[0].xyzw, r7.xyzw
    mad r7.xyzw, r1.zzzz, cb2[2].xyzw, r7.xyzw
    add r7.xyzw, r7.xyzw, cb2[3].xyzw
    mul r9.xyzw, r4.yyyy, cb2[1].xyzw
    mad r9.xyzw, r4.xxxx, cb2[0].xyzw, r9.xyzw
    mad r9.xyzw, r4.zzzz, cb2[2].xyzw, r9.xyzw
    add r9.xyzw, r9.xyzw, cb2[3].xyzw
    div r7.xyz, r7.xyzx, r7.wwww
    div r8.yzw, r9.xxyz, r9.wwww
    mad r7.xyz, r7.xyzx, l(0.500000, -0.500000, 1.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    mad r8.yzw, r8.yyzw, l(0.000000, 0.500000, -0.500000, 1.000000), l(0.000000, 0.500000, 0.500000, 0.000000)
    add r8.yzw, -r7.xxyz, r8.yyzw
    mul r8.yzw, r8.yyzw, l(0.000000, 0.100000, 0.100000, 0.100000)
    mul r0.y, |r8.w|, l(0.100000)
    mov r9.zw, l(0,0,0,0)
    mov r10.xyz, l(0,0,0,0)
    mov r1.w, l(1.000000)
    mov r3.x, l(0)
    mov r4.w, l(0)
    loop
      ge r5.w, r4.w, l(10.000000)
      breakc_nz r5.w
      mad r10.xyz, r8.yzwy, r4.wwww, r7.xyzx
      mad r11.xy, r10.xyxx, cb2[16].zwzz, cb2[16].xyxx
      ftoi r9.xy, r11.xyxx
      ld_indexable(texture2d)(float,float,float,float) r5.w, r9.xyzw, t0.yzwx
      mad r1.w, r5.w, cb2[19].x, cb2[19].y
      add r5.w, -r1.w, r10.z
      mul r5.w, r5.w, cb2[56].x
      lt r3.x, r0.y, r5.w
      add r5.w, r4.w, l(1.000000)
      movc r4.w, r3.x, l(11.000000), r5.w
    endloop
    mad r7.xy, r10.xyxx, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
    mul r9.xyzw, r7.yyyy, cb2[5].xyzw
    mad r7.xyzw, r7.xxxx, cb2[4].xyzw, r9.xyzw
    mad r9.xyzw, r10.zzzz, cb2[6].xyzw, r7.xyzw
    add r9.xyzw, r9.xyzw, cb2[7].xyzw
    div r8.yzw, r9.xxyz, r9.wwww
    add r9.xyz, r8.yzwy, cb2[12].xyzx
    mad r7.xyzw, r1.wwww, cb2[6].xyzw, r7.xyzw
    add r7.xyzw, r7.xyzw, cb2[7].xyzw
    div r7.xyz, r7.xyzx, r7.wwww
    add r7.xyz, r7.xyzx, cb2[12].xyzx
    add r7.xyz, -r7.xyzx, r9.xyzx
    dp3 r0.y, r7.xyzx, r7.xyzx
    sqrt r0.y, r0.y
    lt r1.w, r0.y, r0.z
    div_sat r0.y, r0.y, r0.z
    log r0.y, r0.y
    mul r0.y, r0.y, l(0.800000)
    exp r0.y, r0.y
    add r7.xyz, r1.xyzx, -r9.xyzx
    dp3 r0.z, r7.xyzx, r7.xyzx
    sqrt r0.z, r0.z
    add r1.xyz, r1.xyzx, -r4.xyzx
    dp3 r1.x, r1.xyzx, r1.xyzx
    sqrt r1.x, r1.x
    div r0.z, r0.z, r1.x
    add r0.yz, -r0.yyzy, l(0.000000, 1.000000, 1.000000, 0.000000)
    mul r0.y, r0.z, r0.y
    max r0.y, r0.y, l(0.000000)
    and r9.w, r0.y, r1.w
    mov r10.w, l(0)
    movc r1.xyzw, r3.xxxx, r9.wxyz, r10.wxyz
    lt r0.y, l(0.000000), r1.x
    add r1.yzw, -r3.yyzw, r1.yyzw
    mad r1.yzw, r1.xxxx, r1.yyzw, r3.yyzw
    add r0.z, -r1.x, l(1.000000)
    mul r4.xyzw, r0.zzzz, r6.xzwy
    movc r6.xyzw, r0.yyyy, r4.xwyz, r6.xyzw
    movc r3.yzw, r0.yyyy, r1.yyzw, r3.yyzw
  else
    mov r1.x, l(0)
  endif
  log r0.x, r0.x
  mul r0.x, r0.x, cb2[58].x
  exp r0.x, r0.x
  mul r0.x, r0.x, cb2[54].x
  itof r0.y, cb2[52].y
  add r1.yzw, r3.yyzw, -cb0[2].xxyz
  max r0.z, |r1.w|, |r1.z|
  max r0.z, r0.z, |r1.y|
  dp2 r0.z, cb0[7].wwww, r0.zzzz
  max r0.z, r0.z, l(1.000000)
  mad r0.z, r0.z, r6.z, r6.x
  add r0.z, r6.y, r0.z
  mad r1.yzw, r2.yyzw, r2.xxxx, -r5.xxyz
  mad r1.yzw, r6.wwww, r1.yyzw, r5.xxyz
  dp3 r2.x, r1.yzwy, r1.yzwy
  rsq r2.x, r2.x
  mul r1.yzw, r1.yyzw, r2.xxxx
  mul r2.x, r0.z, cb0[7].y
  mad r1.yzw, r1.yyzw, r2.xxxx, r3.yyzw
  add r1.x, -r1.x, l(1.000000)
  add r2.x, -cb2[51].z, l(2.000000)
  add r2.y, cb2[51].z, l(2.000000)
  div r2.y, r2.y, r2.x
  add r2.y, r2.y, l(-1.000000)
  add r2.z, cb0[8].x, l(1.000000)
  movc r3.xyz, cb2[54].yyyy, -r5.xyzx, r5.xyzx
  mov r4.xyz, r1.yzwy
  mov r2.w, cb0[8].w
  mov r3.w, r1.x
  mov r4.w, l(0)
  mov r5.w, l(1.000000)
  mov r6.x, r0.z
  mov r6.y, l(0)
  loop
    ge r6.z, r6.y, r0.y
    breakc_nz r6.z
    add r7.xyz, r4.xyzx, -cb0[2].xyzx
    max r6.z, |r7.z|, |r7.y|
    max r6.z, r6.z, |r7.x|
    dp2 r6.w, cb0[7].wwww, r6.zzzz
    max r6.w, r6.w, l(1.000000)
    mul r7.x, r6.x, cb2[51].z
    lt r7.y, r7.x, r6.w
    movc r7.x, r7.y, r6.w, r7.x
    log r7.z, r7.x
    ge r7.w, r7.z, r2.z
    if_nz r7.w
      break
    endif
    add r6.z, -r6.z, cb0[2].w
    mul r7.w, r7.x, cb0[7].y
    mad r6.z, -r7.x, cb0[7].y, r6.z
    lt r8.y, r6.z, l(0.000000)
    if_nz r8.y
      break
    endif
    mad r8.yzw, r7.xxxx, cb0[7].yyyy, r4.xxyz
    lt r8.yzw, r8.yyzw, cb0[3].xxyz
    or r8.y, r8.z, r8.y
    or r8.y, r8.w, r8.y
    mad r9.xyz, -r7.xxxx, cb0[7].yyyy, r4.xyzx
    lt r9.xyz, cb0[4].xyzx, r9.xyzx
    or r8.z, r9.y, r9.x
    or r8.z, r9.z, r8.z
    or r8.y, r8.z, r8.y
    if_nz r8.y
      break
    endif
    mad r8.y, r6.x, l(2.000000), r6.w
    div r8.y, r8.y, r2.x
    add r6.w, r6.w, r6.x
    max r6.w, r6.w, r8.y
    add r6.w, -r6.x, r6.w
    mul r8.y, r2.y, r6.x
    movc r6.w, r7.y, r6.w, r8.y
    mul r7.y, r8.x, r6.w
    mul r8.y, r0.x, -r6.x
    mul r8.y, r8.y, l(1.442695)
    exp r8.y, r8.y
    add r8.z, r5.w, -r8.y
    mad r8.z, r8.z, r3.w, r4.w
    div_sat r6.z, r6.z, r7.w
    round_ni r7.w, r7.z
    add r8.w, -r7.w, r7.z
    add r9.x, -r8.w, l(1.000000)
    mul r9.x, r6.z, r9.x
    lt r7.z, cb0[8].x, r7.z
    mul r6.z, r6.z, r8.w
    ftoi r8.w, r7.w
    add r9.yzw, r4.xxyz, -cb0[5].xxyz
    mad r10.xyz, r9.yzwy, cb1[r8.w + 0].xxxx, l(0.500000, 0.500000, 0.500000, 0.000000)
    add r10.xyz, r10.xyzx, cb1[r8.w + 13].xyzx
    frc r10.xyz, r10.xyzx
    mul r11.xy, r10.xyxx, cb1[r8.w + 0].yyyy
    mad r11.z, r10.z, cb1[r8.w + 0].y, cb1[r8.w + 0].z
    mul r10.xyz, r11.xyzx, cb0[0].xyzx
    add r7.w, r7.w, l(1.000000)
    ftoi r7.w, r7.w
    mad r9.yzw, r9.yyzw, cb1[r7.w + 0].xxxx, l(0.000000, 0.500000, 0.500000, 0.500000)
    add r9.yzw, r9.yyzw, cb1[r7.w + 13].xxyz
    frc r9.yzw, r9.yyzw
    mul r11.xy, r9.yzyy, cb1[r7.w + 0].yyyy
    mad r11.z, r9.w, cb1[r7.w + 0].y, cb1[r7.w + 0].z
    mul r9.yzw, r11.xxyz, cb0[0].xxyz
    sample_l_indexable(texture3d)(float,float,float,float) r11.xyz, r10.xyzx, t6.xyzw, s0, l(0.000000)
    if_nz r2.w
      sample_l_indexable(texture3d)(float,float,float,float) r10.xyz, r10.xyzx, t7.xyzw, s0, l(0.000000)
      mul_sat r12.xyz, -r3.xyzx, r11.xyzx
      add r7.w, r12.y, r12.x
      add r7.w, r12.z, r7.w
      min r7.w, r7.w, l(1.000000)
      mul_sat r10.xyz, r3.xyzx, r10.xyzx
      add r8.w, r10.y, r10.x
      add r8.w, r10.z, r8.w
      min r8.w, r8.w, l(1.000000)
      add r7.w, r7.w, r8.w
    else
      mul_sat r10.xyz, |r5.xyzx|, r11.xyzx
      add r8.w, r10.y, r10.x
      add r8.w, r10.z, r8.w
      min r7.w, r8.w, l(1.000000)
    endif
    sample_l_indexable(texture3d)(float,float,float,float) r10.xyz, r9.yzwy, t6.xyzw, s0, l(0.000000)
    if_nz r2.w
      sample_l_indexable(texture3d)(float,float,float,float) r9.yzw, r9.yzwy, t7.wxyz, s0, l(0.000000)
      mul_sat r11.xyz, -r3.xyzx, r10.xyzx
      add r8.w, r11.y, r11.x
      add r8.w, r11.z, r8.w
      min r8.w, r8.w, l(1.000000)
      mul_sat r9.yzw, r3.xxyz, r9.yyzw
      add r9.y, r9.z, r9.y
      add r9.y, r9.w, r9.y
      min r9.y, r9.y, l(1.000000)
      add r8.w, r8.w, r9.y
    else
      mul_sat r9.yzw, |r5.xxyz|, r10.xxyz
      add r9.y, r9.z, r9.y
      add r9.y, r9.w, r9.y
      min r8.w, r9.y, l(1.000000)
    endif
    mul r6.z, r6.z, r8.w
    movc r6.z, r7.z, l(0), r6.z
    mad_sat r6.z, r7.w, r9.x, r6.z
    lt r7.z, l(0.000000), r6.z
    add r6.z, -r6.z, l(1.000000)
    mul r7.w, r7.y, cb2[52].x
    div r7.x, r7.w, r7.x
    log r6.z, r6.z
    mul r6.z, r6.z, r7.x
    exp r6.z, r6.z
    add r6.z, -r6.z, l(1.000000)
    and r6.z, r6.z, r7.z
    add r6.z, -r6.z, l(1.000000)
    mul r3.w, r3.w, r6.z
    lt r6.z, r3.w, l(0.000100)
    if_nz r6.z
      mov r4.w, r8.z
      break
    endif
    mad r6.x, r6.w, r8.x, r6.x
    mul r6.z, r7.y, cb0[7].y
    mad r4.xyz, r6.zzzz, r5.xyzx, r4.xyzx
    add r6.y, r6.y, l(1.000000)
    mov r4.w, r8.z
    mov r5.w, r8.y
  endloop
  mov_sat r4.w, r4.w
  mad_sat r0.x, r4.w, cb2[57].y, cb2[57].z
  log r0.x, r0.x
  mul r0.x, r0.x, cb2[57].w
  exp r0.x, r0.x
  mul r0.x, r0.x, cb2[52].w
  mul r0.xyz, r0.xxxx, r5.xyzx
else
  mov r0.xyz, l(0,0,0,0)
endif
mul r0.w, r0.w, cb2[52].w
and r1.x, r0.x, l(0x7f800000)
ieq r1.x, r1.x, l(0x7f800000)
movc o0.x, r1.x, l(0), r0.x
and r0.x, r0.y, l(0x7f800000)
ieq r0.x, r0.x, l(0x7f800000)
movc o0.y, r0.x, l(0), r0.y
and r0.x, r0.z, l(0x7f800000)
ieq r0.x, r0.x, l(0x7f800000)
movc o0.z, r0.x, l(0), r0.z
and r0.x, r0.w, l(0x7f800000)
ieq r0.x, r0.x, l(0x7f800000)
movc o0.w, r0.x, l(0), r0.w
ret
// Approximately 427 instruction slots used
