//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   uint4 DuranteSettings;             // Offset:    0 Size:    16
//   
//   struct
//   {
//       
//       float3 EyePosition;            // Offset:   16
//       float4x4 View;                 // Offset:   32
//       float4x4 Projection;           // Offset:   96
//       float4x4 ViewProjection;       // Offset:  160
//       float4x4 ViewInverse;          // Offset:  224
//       float4x4 ProjectionInverse;    // Offset:  288
//       float2 cameraNearFar;          // Offset:  352
//       float cameraNearTimesFar;      // Offset:  360
//       float cameraFarMinusNear;      // Offset:  364
//       float cameraFarMinusNearInv;   // Offset:  368
//       float2 ViewportWidthHeight;    // Offset:  372
//       float2 screenWidthHeightInv;   // Offset:  384
//       float3 GlobalAmbientColor;     // Offset:  400
//       float Time;                    // Offset:  412
//       float3 FakeRimLightDir;        // Offset:  416
//       float3 FogColor;               // Offset:  432
//       float4 FogRangeParameters;     // Offset:  448
//       float3 MiscParameters1;        // Offset:  464
//       float4 MiscParameters2;        // Offset:  480
//       float3 MonotoneMul;            // Offset:  496
//       float3 MonotoneAdd;            // Offset:  512
//       float3 UserClipPlane2;         // Offset:  528
//       float4 UserClipPlane;          // Offset:  544
//       float4 MiscParameters3;        // Offset:  560
//       float AdditionalShadowOffset;  // Offset:  576
//       float AlphaTestDirection;      // Offset:  580
//       float4 MiscParameters4;        // Offset:  592
//       float3 MiscParameters5;        // Offset:  608
//       float4 light1_attenuation;     // Offset:  624
//       float3 light2_position;        // Offset:  640
//       float3 light2_colorIntensity;  // Offset:  656
//       float4 light2_attenuation;     // Offset:  672
//
//   } scene;                           // Offset:   16 Size:   672
//   bool PhyreContextSwitches;         // Offset:  688 Size:     4 [unused]
//   bool PhyreMaterialSwitches;        // Offset:  692 Size:     4 [unused]
//   float4x4 World;                    // Offset:  704 Size:    64 [unused]
//   float4x4 WorldViewProjection;      // Offset:  768 Size:    64 [unused]
//   float GlobalTexcoordFactor;        // Offset:  832 Size:     4 [unused]
//   
//   struct
//   {
//       
//       float3 m_direction;            // Offset:  848
//       float3 m_colorIntensity;       // Offset:  864
//
//   } Light0;                          // Offset:  848 Size:    28
//   
//   struct
//   {
//       
//       float4x4 m_split0Transform;    // Offset:  880
//       float4x4 m_split1Transform;    // Offset:  944
//       float4 m_splitDistances;       // Offset: 1008
//
//   } LightShadow0;                    // Offset:  880 Size:   144
//   float GameMaterialID;              // Offset: 1024 Size:     4 [unused]
//      = 0x00000000 
//   float4 GameMaterialDiffuse;        // Offset: 1040 Size:    16
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000 
//   float4 GameMaterialEmission;       // Offset: 1056 Size:    16
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//   float GameMaterialMonotone;        // Offset: 1072 Size:     4
//      = 0x00000000 
//   float4 GameMaterialTexcoord;       // Offset: 1088 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 GameDitherParams;           // Offset: 1104 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//   float4 UVaMUvColor;                // Offset: 1120 Size:    16 [unused]
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000 
//   float4 UVaProjTexcoord;            // Offset: 1136 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 UVaMUvTexcoord;             // Offset: 1152 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 UVaMUv2Texcoord;            // Offset: 1168 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 UVaDuDvTexcoord;            // Offset: 1184 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float Shininess;                   // Offset: 1200 Size:     4
//      = 0x3f000000 
//   float SpecularPower;               // Offset: 1204 Size:     4
//      = 0x42480000 
//   float BloomIntensity;              // Offset: 1208 Size:     4
//      = 0x3f800000 
//   float4 PointLightParams;           // Offset: 1216 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//   float4 PointLightColor;            // Offset: 1232 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PointClampSamplerState            sampler      NA          NA             s0      1 
// LinearClampCmpSamplerState      sampler_c      NA          NA             s1      1 
// DiffuseMapSamplerSampler          sampler      NA          NA             s2      1 
// SpecularMapSamplerSampler         sampler      NA          NA             s3      1 
// LightShadowMap0                   texture  float4          2d             t0      1 
// DiffuseMapSampler                 texture  float4          2d             t1      1 
// SpecularMapSampler                texture  float4          2d             t2      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xy  
// COLOR                    0   xyzw        1     NONE   float   xyz 
// COLOR                    1   xyzw        2     NONE   float   xyzw
// TEXCOORD                 0   xy          3     NONE   float   xy  
// TEXCOORD                 1   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyz         5     NONE   float   xyz 
// TEXCOORD                10   xyzw        6     NONE   float     zw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
// SV_TARGET                1   xyzw        1   TARGET   float   xyzw
// SV_TARGET                2   xyzw        2   TARGET   float   xyzw
//
      0x00000000: ps_4_1
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[76], immediateIndexed
      0x0000001C: dcl_sampler s0, mode_default
      0x00000028: dcl_sampler s1, mode_comparison
      0x00000034: dcl_sampler s2, mode_default
      0x00000040: dcl_sampler s3, mode_default
      0x0000004C: dcl_resource_texture2d (float,float,float,float) t0
      0x0000005C: dcl_resource_texture2d (float,float,float,float) t1
      0x0000006C: dcl_resource_texture2d (float,float,float,float) t2
      0x0000007C: dcl_input_ps_siv linear noperspective v0.xy, position
      0x0000008C: dcl_input_ps linear v1.xyz
      0x00000098: dcl_input_ps linear v2.xyzw
      0x000000A4: dcl_input_ps linear v3.xy
      0x000000B0: dcl_input_ps linear v4.xyzw
      0x000000BC: dcl_input_ps linear v5.xyz
      0x000000C8: dcl_input_ps linear v6.zw
      0x000000D4: dcl_output o0.xyzw
      0x000000E0: dcl_output o1.xyzw
      0x000000EC: dcl_output o2.xyzw
      0x000000F8: dcl_temps 8
   0  0x00000100: sample r0.xyz, v3.xyxx, t1.xyzw, s2
   1  0x00000124: ge r0.w, cb0[63].y, v4.w
   2  0x00000144: if_nz r0.w
   3  0x00000150:   mad r1.xyz, cb0[53].xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), v4.xyzx
   4  0x00000184:   mad r1.xyz, v5.xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), r1.xyzx
   5  0x000001B4:   lt r2.x, v4.w, cb0[63].x
   6  0x000001D4:   if_nz r2.x
   7  0x000001E0:     mov r1.w, l(1.000000)
   8  0x000001F4:     dp4 r2.x, r1.xyzw, cb0[55].xyzw
   9  0x00000214:     dp4 r2.y, r1.xyzw, cb0[56].xyzw
  10  0x00000234:     dp4 r2.z, r1.xyzw, cb0[57].xyzw
  11  0x00000254:     and r2.w, cb0[0].x, l(2)
  12  0x00000274:     if_nz r2.w
  13  0x00000280:       sample_c_lz r2.w, r2.xyxx, t0.xxxx, s1, r2.z
  14  0x000002AC:     else 
  15  0x000002B0:       div r3.x, l(25.000000), cb0[63].y
  16  0x000002D0:       and r3.y, cb0[0].x, l(16)
  17  0x000002F0:       if_nz r3.y
  18  0x000002FC:         mul r3.yz, r3.xxxx, l(0.000000, 0.000937, 0.001875, 0.000000)
  19  0x00000324:         add r3.w, r2.z, l(-6.000000)
  20  0x00000340:         mul r3.yz, r3.wwww, r3.yyzy
  21  0x0000035C:         div r3.yz, r3.yyzy, r2.zzzz
  22  0x00000378:         dp2 r3.w, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
  23  0x000003A0:         frc r3.w, r3.w
  24  0x000003B4:         mul r3.w, r3.w, l(52.982918)
  25  0x000003D0:         frc r3.w, r3.w
  26  0x000003E4:         mul r3.w, r3.w, l(6.283185)
  27  0x00000400:         mov r4.xyz, l(0,0,0,0)
  28  0x00000420:         loop 
  29  0x00000424:           ige r4.w, r4.z, l(16)
  30  0x00000440:           breakc_nz r4.w
  31  0x0000044C:           itof r4.w, r4.z
  32  0x00000460:           add r5.x, r4.w, l(0.500000)
  33  0x0000047C:           sqrt r5.x, r5.x
  34  0x00000490:           mul r5.x, r5.x, l(0.250000)
  35  0x000004AC:           mad r4.w, r4.w, l(2.400000), r3.w
  36  0x000004D0:           sincos r6.x, r7.x, r4.w
  37  0x000004EC:           mul r7.x, r5.x, r7.x
  38  0x00000508:           mul r7.y, r5.x, r6.x
  39  0x00000524:           mad r5.xy, r7.xyxx, r3.yzyy, r2.xyxx
  40  0x00000548:           sample_l r4.w, r5.xyxx, t0.yzwx, s0, l(0.000000)
  41  0x00000574:           lt r5.x, r4.w, r2.z
  42  0x00000590:           add r6.y, r4.w, r4.y
  43  0x000005AC:           add r6.x, r4.x, l(1.000000)
  44  0x000005C8:           movc r4.xy, r5.xxxx, r6.xyxx, r4.xyxx
  45  0x000005EC:           iadd r4.z, r4.z, l(1)
  46  0x00000608:         endloop 
  47  0x0000060C:         ge r3.y, r4.x, l(1.000000)
  48  0x00000628:         if_nz r3.y
  49  0x00000634:           mul r3.yz, r3.xxxx, l(0.000000, 0.000625, 0.001250, 0.000000)
  50  0x0000065C:           div r4.x, r4.y, r4.x
  51  0x00000678:           add r4.x, r2.z, -r4.x
  52  0x00000698:           min r4.x, r4.x, l(0.070000)
  53  0x000006B4:           mul r4.x, r4.x, l(60.000000)
  54  0x000006D0:           mul r3.yz, r3.yyzy, r4.xxxx
  55  0x000006EC:           resinfo r4.xy, l(0), t0.xyzw
  56  0x00000708:           div r4.xy, l(0.500000, 0.500000, 0.000000, 0.000000), r4.xyxx
  57  0x00000730:           max r3.yz, r3.yyzy, r4.xxyx
  58  0x0000074C:           mov r4.xy, l(0,0,0,0)
  59  0x0000076C:           loop 
  60  0x00000770:             ige r4.z, r4.y, l(16)
  61  0x0000078C:             breakc_nz r4.z
  62  0x00000798:             itof r4.z, r4.y
  63  0x000007AC:             add r4.w, r4.z, l(0.500000)
  64  0x000007C8:             sqrt r4.w, r4.w
  65  0x000007DC:             mul r4.w, r4.w, l(0.250000)
  66  0x000007F8:             mad r4.z, r4.z, l(2.400000), r3.w
  67  0x0000081C:             sincos r5.x, r6.x, r4.z
  68  0x00000838:             mul r6.x, r4.w, r6.x
  69  0x00000854:             mul r6.y, r4.w, r5.x
  70  0x00000870:             mul r4.zw, r3.yyyz, r6.xxxy
  71  0x0000088C:             mad r4.zw, r4.zzzw, l(0.000000, 0.000000, 3.000000, 3.000000), r2.xxxy
  72  0x000008BC:             sample_c_lz r4.z, r4.zwzz, t0.xxxx, s1, r2.z
  73  0x000008E8:             add r4.x, r4.z, r4.x
  74  0x00000904:             iadd r4.y, r4.y, l(1)
  75  0x00000920:           endloop 
  76  0x00000924:           mul r2.
