//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   uint4 DuranteSettings;             // Offset:    0 Size:    16
//   
//   struct
//   {
//       
//       float3 EyePosition;            // Offset:   16
//       float4x4 View;                 // Offset:   32
//       float4x4 Projection;           // Offset:   96
//       float4x4 ViewProjection;       // Offset:  160
//       float4x4 ViewInverse;          // Offset:  224
//       float4x4 ProjectionInverse;    // Offset:  288
//       float2 cameraNearFar;          // Offset:  352
//       float cameraNearTimesFar;      // Offset:  360
//       float cameraFarMinusNear;      // Offset:  364
//       float cameraFarMinusNearInv;   // Offset:  368
//       float2 ViewportWidthHeight;    // Offset:  372
//       float2 screenWidthHeightInv;   // Offset:  384
//       float3 GlobalAmbientColor;     // Offset:  400
//       float Time;                    // Offset:  412
//       float3 FakeRimLightDir;        // Offset:  416
//       float3 FogColor;               // Offset:  432
//       float4 FogRangeParameters;     // Offset:  448
//       float3 MiscParameters1;        // Offset:  464
//       float4 MiscParameters2;        // Offset:  480
//       float3 MonotoneMul;            // Offset:  496
//       float3 MonotoneAdd;            // Offset:  512
//       float3 UserClipPlane2;         // Offset:  528
//       float4 UserClipPlane;          // Offset:  544
//       float4 MiscParameters3;        // Offset:  560
//       float AdditionalShadowOffset;  // Offset:  576
//       float AlphaTestDirection;      // Offset:  580
//       float4 MiscParameters4;        // Offset:  592
//       float3 MiscParameters5;        // Offset:  608
//       float4 light1_attenuation;     // Offset:  624
//       float3 light2_position;        // Offset:  640
//       float3 light2_colorIntensity;  // Offset:  656
//       float4 light2_attenuation;     // Offset:  672
//
//   } scene;                           // Offset:   16 Size:   672
//   bool PhyreContextSwitches;         // Offset:  688 Size:     4 [unused]
//   bool PhyreMaterialSwitches;        // Offset:  692 Size:     4 [unused]
//   float4x4 World;                    // Offset:  704 Size:    64 [unused]
//   float4x4 WorldViewProjection;      // Offset:  768 Size:    64 [unused]
//   float GlobalTexcoordFactor;        // Offset:  832 Size:     4 [unused]
//   
//   struct
//   {
//       
//       float3 m_direction;            // Offset:  848
//       float3 m_colorIntensity;       // Offset:  864
//
//   } Light0;                          // Offset:  848 Size:    28
//   
//   struct
//   {
//       
//       float4x4 m_split0Transform;    // Offset:  880
//       float4x4 m_split1Transform;    // Offset:  944
//       float4 m_splitDistances;       // Offset: 1008
//
//   } LightShadow0;                    // Offset:  880 Size:   144
//   float GameMaterialID;              // Offset: 1024 Size:     4 [unused]
//      = 0x00000000 
//   float4 GameMaterialDiffuse;        // Offset: 1040 Size:    16
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000 
//   float4 GameMaterialEmission;       // Offset: 1056 Size:    16
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//   float GameMaterialMonotone;        // Offset: 1072 Size:     4
//      = 0x00000000 
//   float4 GameMaterialTexcoord;       // Offset: 1088 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 GameDitherParams;           // Offset: 1104 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//   float4 UVaMUvColor;                // Offset: 1120 Size:    16 [unused]
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000 
//   float4 UVaProjTexcoord;            // Offset: 1136 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 UVaMUvTexcoord;             // Offset: 1152 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 UVaMUv2Texcoord;            // Offset: 1168 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float4 UVaDuDvTexcoord;            // Offset: 1184 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000 
//   float Shininess;                   // Offset: 1200 Size:     4
//      = 0x3f000000 
//   float SpecularPower;               // Offset: 1204 Size:     4
//      = 0x42480000 
//   float CubeMapIntensity;            // Offset: 1208 Size:     4
//      = 0x3f800000 
//   float CubeMapFresnel;              // Offset: 1212 Size:     4
//      = 0x00000000 
//   float BloomIntensity;              // Offset: 1216 Size:     4 [unused]
//      = 0x3f800000 
//   float GlareIntensity;              // Offset: 1220 Size:     4
//      = 0x3f800000 
//   float4 PointLightParams;           // Offset: 1232 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//   float4 PointLightColor;            // Offset: 1248 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000 
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// LinearClampSamplerState           sampler      NA          NA             s0      1 
// PointClampSamplerState            sampler      NA          NA             s1      1 
// LinearClampCmpSamplerState      sampler_c      NA          NA             s2      1 
// DiffuseMapSamplerSampler          sampler      NA          NA             s3      1 
// LightShadowMap0                   texture  float4          2d             t0      1 
// DiffuseMapSampler                 texture  float4          2d             t1      1 
// CubeMapSampler                    texture  float4        cube             t2      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xy  
// COLOR                    0   xyzw        1     NONE   float   xyz 
// COLOR                    1   xyzw        2     NONE   float   xyzw
// TEXCOORD                 0   xy          3     NONE   float   xy  
// TEXCOORD                 1   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyz         5     NONE   float   xyz 
// TEXCOORD                10   xyzw        6     NONE   float     zw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
// SV_TARGET                1   xyzw        1   TARGET   float   xyzw
// SV_TARGET                2   xyzw        2   TARGET   float   xyzw
//
      0x00000000: ps_4_1
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[77], immediateIndexed
      0x0000001C: dcl_sampler s0, mode_default
      0x00000028: dcl_sampler s1, mode_default
      0x00000034: dcl_sampler s2, mode_comparison
      0x00000040: dcl_sampler s3, mode_default
      0x0000004C: dcl_resource_texture2d (float,float,float,float) t0
      0x0000005C: dcl_resource_texture2d (float,float,float,float) t1
      0x0000006C: dcl_resource_texturecube (float,float,float,float) t2
      0x0000007C: dcl_input_ps_siv linear noperspective v0.xy, position
      0x0000008C: dcl_input_ps linear v1.xyz
      0x00000098: dcl_input_ps linear v2.xyzw
      0x000000A4: dcl_input_ps linear v3.xy
      0x000000B0: dcl_input_ps linear v4.xyzw
      0x000000BC: dcl_input_ps linear v5.xyz
      0x000000C8: dcl_input_ps linear v6.zw
      0x000000D4: dcl_output o0.xyzw
      0x000000E0: dcl_output o1.xyzw
      0x000000EC: dcl_output o2.xyzw
      0x000000F8: dcl_temps 8
   0  0x00000100: sample r0.xyz, v3.xyxx, t1.xyzw, s3
   1  0x00000124: ge r0.w, cb0[63].y, v4.w
   2  0x00000144: if_nz r0.w
   3  0x00000150:   mad r1.xyz, cb0[53].xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), v4.xyzx
   4  0x00000184:   mad r1.xyz, v5.xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), r1.xyzx
   5  0x000001B4:   lt r2.x, v4.w, cb0[63].x
   6  0x000001D4:   if_nz r2.x
   7  0x000001E0:     mov r1.w, l(1.000000)
   8  0x000001F4:     dp4 r2.x, r1.xyzw, cb0[55].xyzw
   9  0x00000214:     dp4 r2.y, r1.xyzw, cb0[56].xyzw
  10  0x00000234:     dp4 r2.z, r1.xyzw, cb0[57].xyzw
  11  0x00000254:     and r2.w, cb0[0].x, l(2)
  12  0x00000274:     if_nz r2.w
  13  0x00000280:       sample_c_lz r2.w, r2.xyxx, t0.xxxx, s2, r2.z
  14  0x000002AC:     else 
  15  0x000002B0:       div r3.x, l(25.000000), cb0[63].y
  16  0x000002D0:       and r3.y, cb0[0].x, l(16)
  17  0x000002F0:       if_nz r3.y
  18  0x000002FC:         mul r3.yz, r3.xxxx, l(0.000000, 0.000937, 0.001875, 0.000000)
  19  0x00000324:         add r3.w, r2.z, l(-6.000000)
  20  0x00000340:         mul r3.yz, r3.wwww, r3.yyzy
  21  0x0000035C:         div r3.yz, r3.yyzy, r2.zzzz
  22  0x00000378:         dp2 r3.w, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
  23  0x000003A0:         frc r3.w, r3.w
  24  0x000003B4:         mul r3.w, r3.w, l(52.982918)
  25  0x000003D0:         frc r3.w, r3.w
  26  0x000003E4:         mul r3.w, r3.w, l(6.283185)
  27  0x00000400:         mov r4.xyz, l(0,0,0,0)
  28  0x00000420:         loop 
  29  0x00000424:           ige r4.w, r4.z, l(16)
  30  0x00000440:           breakc_nz r4.w
  31  0x0000044C:           itof r4.w, r4.z
  32  0x00000460:           add r5.x, r4.w, l(0.500000)
  33  0x0000047C:           sqrt r5.x, r5.x
  34  0x00000490:           mul r5.x, r5.x, l(0.250000)
  35  0x000004AC:           mad r4.w, r4.w, l(2.400000), r3.w
  36  0x000004D0:           sincos r6.x, r7.x, r4.w
  37  0x000004EC:           mul r7.x, r5.x, r7.x
  38  0x00000508:           mul r7.y, r5.x, r6.x
  39  0x00000524:           mad r5.xy, r7.xyxx, r3.yzyy, r2.xyxx
  40  0x00000548:           sample_l r4.w, r5.xyxx, t0.yzwx, s1, l(0.000000)
  41  0x00000574:           lt r5.x, r4.w, r2.z
  42  0x00000590:           add r6.y, r4.w, r4.y
  43  0x000005AC:           add r6.x, r4.x, l(1.000000)
  44  0x000005C8:           movc r4.xy, r5.xxxx, r6.xyxx, r4.xyxx
  45  0x000005EC:           iadd r4.z, r4.z, l(1)
  46  0x00000608:         endloop 
  47  0x0000060C:         ge r3.y, r4.x, l(1.000000)
  48  0x00000628:         if_nz r3.y
  49  0x00000634:           mul r3.yz, r3.xxxx, l(0.000000, 0.000625, 0.001250, 0.000000)
  50  0x0000065C:           div r4.x, r4.y, r4.x
  51  0x00000678:           add r4.x, r2.z, -r4.x
  52  0x00000698:           min r4.x, r4.x, l(0.070000)
  53  0x000006B4:           mul r4.x, r4.x, l(60.000000)
  54  0x000006D0:           mul r3.yz, r3.yyzy, r4.xxxx
  55  0x000006EC:           resinfo r4.xy, l(0), t0.xyzw
  56  0x00000708:           div r4.xy, l(0.500000, 0.500000, 0.000000, 0.000000), r4.xyxx
  57  0x00000730:           max r3.yz, r3.yyzy, r4.xxyx
  58  0x0000074C:           mov r4.xy, l(0,0,0,0)
  59  0x0000076C:           loop 
  60  0x00000770:             ige r4.z, r4.y, l(16)
  61  0x0000078C:             breakc_nz r4.z
  62  0x00000798:             itof r4.z, r4.y
  63  0x000007AC:             add r4.w, r4.z, l(0.500000)
  64  0x000007C8:             sqrt r4.w, r4.w
  65  0x000007DC:             mul r4.w, r4.w, l(0.250000)
  66  0x000007F8:             mad r4.z, r4.z, l(2.400000), r3.w
  67  0x0000081C:             sincos r5.x, r6.x, r4.z
  68  0x00000838:             mul r6.x, r4.w, r6.x
  69  0x00000854:             mul r6.y, r4.w, r5.x
  70  0x00000870:             mul r4.zw, r3.yyyz, r6.xxxy
  71  0x0000088C:             mad r4.zw, r4.zzzw, l(0.000000, 0.000000, 3.000000, 3.000000), r2.xxxy
  72  0x000008BC:             sample_c_lz r4.z, r4.zwzz, t0.xxxx, s2, r2.z
  73  0x000008E8:             add r4.x, r4.z, r4.x
  74  0x00000904:             iadd r4.y, r4.y, l(1)
  75  0x00000920:           endloop 
  76  0x00000924:           mul r2.w, r4.x, l(0.062500)
  77  0x00000940:         else 
  78  0x00000944:           mov r2.w, l(1.000000)
  79  0x00000958:         endif 
  80  0x0000095C:       else 
  81  0x00000960:         and r3.y, cb0[0].x, l(8)
  82  0x00000980:         if_nz r3.y
  83  0x0000098C:           mul r3.yz, r3.xxxx, l(0.000000, 0.000375, 0.000750, 0.000000)
  84  0x000009B4:           dp2 r3.w, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
  85  0x000009DC:           frc r3.w, r3.w
  86  0x000009F0:           mul r3.w, r3.w, l(52.982918)
  87  0x00000A0C:           frc r3.w, r3.w
  88  0x00000A20:           mul r3.w, r3.w, l(6.283185)
  89  0x00000A3C:           mov r4.xy, l(0,0,0,0)
  90  0x00000A5C:           loop 
  91  0x00000A60:             ige r4.z, r4.y, l(16)
  92  0x00000A7C:             breakc_nz r4.z
  93  0x00000A88:             itof r4.z, r4.y
  94  0x00000A9C:             add r4.w, r4.z, l(0.500000)
  95  0x00000AB8:             sqrt r4.w, r4.w
  96  0x00000ACC:             mul r4.w, r4.w, l(0.250000)
  97  0x00000AE8:             mad r4.z, r4.z, l(2.400000), r3.w
  98  0x00000B0C:             sincos r5.x, r6.x, r4.z
  99  0x00000B28:             mul r6.x, r4.w, r6.x
 100  0x00000B44:             mul r6.y, r4.w, r5.x
 101  0x00000B60:             mul r4.zw, r3.yyyz, r6.xxxy
 102  0x00000B7C:             mad r4.zw, r4.zzzw, l(0.000000, 0.000000, 3.000000, 3.000000), r2.xxxy
 103  0x00000BAC:             sample_c_lz r4.z, r4.zwzz, t0.xxxx, s2, r2.z
 104  0x00000BD8:             add r4.x, r4.z, r4.x
 105  0x00000BF4:             iadd r4.y, r4.y, l(1)
 106  0x00000C10:           endloop 
 107  0x00000C14:           mul r2.w, r4.x, l(0.062500)
 108  0x00000C30:         else 
 109  0x00000C34:           dp4 r3.y, r1.xyzw, cb0[58].xyzw
 110  0x00000C54:           and r3.z, cb0[0].x, l(4)
 111  0x00000C74:           if_nz r3.z
 112  0x00000C80:             mul r3.zw, r3.yyyy, cb0[37].xxxy
 113  0x00000CA0:             sample_c_lz r4.x, r2.xyxx, t0.xxxx, s2, r2.z
 114  0x00000CCC:             mul r5.xy, r3.xxxx, -r3.zwzz
 115  0x00000CEC:             mov r5.z, l(0)
 116  0x00000D00:             add r4.yzw, r2.xxyz, r5.xxyz
 117  0x00000D1C:             sample_c_lz r4.y, r4.yzyy, t0.xxxx, s2, r4.w
 118  0x00000D48:             mul r4.y, r4.y, l(0.062500)
 119  0x00000D64:             mad r4.x, r4.x, l(0.500000), r4.y
 120  0x00000D88:             mul r6.x, r3.x, r3.z
 121  0x00000DA4:             mul r6.y, r3.x, -r3.w
 122  0x00000DC4:             mov r6.z, l(0)
 123  0x00000DD8:             add r4.yzw, r2.xxyz, r6.xxyz
 124  0x00000DF4:             sample_c_lz r4.y, r4.yzyy, t0.xxxx, s2, r4.w
 125  0x00000E20:             mad r4.x, r4.y, l(0.062500), r4.x
 126  0x00000E44:             mul r7.x, r3.x, -r3.z
 127  0x00000E64:             mul r7.y, r3.x, r3.w
 128  0x00000E80:             mov r7.z, l(0)
 129  0x00000E94:             add r4.yzw, r2.xxyz, r7.xxyz
 130  0x00000EB0:             sample_c_lz r4.y, r4.yzyy, t0.xxxx, s2, r4.w
 131  0x00000EDC:             mad r4.x, r4.y, l(0.062500), r4.x
 132  0x00000F00:             mul r7.xy, r3.xxxx, r3.zwzz
 133  0x00000F1C:             mov r7.z, l(0)
 134  0x00000F30:             add r4.yzw, r2.xxyz, r7.xxyz
 135  0x00000F4C:             sample_c_lz r3.z, r4.yzyy, t0.xxxx, s2, r4.w
 136  0x00000F78:             mad r3.z, r3.z, l(0.062500), r4.x
 137  0x00000F9C:             add r4.xyz, r2.xyzx, r6.zyzz
 138  0x00000FB8:             sample_c_lz r3.w, r4.xyxx, t0.xxxx, s2, r4.z
 139  0x00000FE4:             mad r3.z, r3.w, l(0.062500), r3.z
 140  0x00001008:             add r4.xyz, r2.xyzx, r5.xzzx
 141  0x00001024:             sample_c_lz r3.w, r4.xyxx, t0.xxxx, s2, r4.z
 142  0x00001050:             mad r3.z, r3.w, l(0.062500), r3.z
 143  0x00001074:             add r4.xyz, r2.xyzx, r7.xzzx
 144  0x00001090:             sample_c_lz r3.w, r4.xyxx, t0.xxxx, s2, r4.z
 145  0x000010BC:             mad r3.z, r3.w, l(0.062500), r3.z
 146  0x000010E0:             add r4.xyz, r2.xyzx, r7.zyzz
 147  0x000010FC:             sample_c_lz r3.w, r4.xyxx, t0.xxxx, s2, r4.z
 148  0x00001128:             mad r2.w, r3.w, l(0.062500), r3.z
 149  0x0000114C:           else 
 150  0x00001150:             mul r3.yz, r3.yyyy, cb0[37].xxyx
 151  0x00001170:             sample_c_lz r3.w, r2.xyxx, t0.xxxx, s2, r2.z
 152  0x0000119C:             mul r4.xy, r3.xxxx, -r3.yzyy
 153  0x000011BC:             mov r4.z, l(0)
 154  0x000011D0:             add r4.xyz, r2.xyzx, r4.xyzx
 155  0x000011EC:             sample_c_lz r4.x, r4.xyxx, t0.xxxx, s2, r4.z
 156  0x00001218:             mul r4.x, r4.x, cb0[38].y
 157  0x00001238:             mad r3.w, r3.w, cb0[38].x, r4.x
 158  0x00001260:             mul r4.x, r3.x, r3.y
 159  0x0000127C:             mul r4.y, r3.x, -r3.z
 160  0x0000129C:             mov r4.z, l(0)
 161  0x000012B0:             add r4.xyz, r2.xyzx, r4.xyzx
 162  0x000012CC:             sample_c_lz r4.x, r4.xyxx, t0.xxxx, s2, r4.z
 163  0x000012F8:             mad r3.w, r4.x, cb0[38].y, r3.w
 164  0x00001320:             mul r4.x, r3.x, -r3.y
 165  0x00001340:             mul r4.y, r3.x, r3.z
 166  0x0000135C:             mov r4.z, l(0)
 167  0x00001370:             add r4.xyz, r2.xyzx, r4.xyzx
 168  0x0000138C:             sample_c_lz r4.x, r4.xyxx, t0.xxxx, s2, r4.z
 169  0x000013B8:             mad r3.w, r4.x, cb0[38].y, r3.w
 170  0x000013E0:             mul r3.xy, r3.xxxx, r3.yzyy
 171  0x000013FC:             mov r3.z, l(0)
 172  0x00001410:             add r2.xyz, r2.xyzx, r3.xyzx
 173  0x0000142C:             sample_c_lz r2.x, r2.xyxx, t0.xxxx, s2, r2.z
 174  0x00001458:             mad r2.w, r2.x, cb0[38].y, r3.w
 175  0x00001480:           endif 
 176  0x00001484:         endif 
 177  0x00001488:       endif 
 178  0x0000148C:     endif 
 179  0x00001490:   else 
 180  0x00001494:     mov r1.w, l(1.000000)
 181  0x000014A8:     dp4 r2.x, r1.xyzw, cb0[59].xyzw
 182  0x000014C8:     dp4 r2.y, r1.xyzw, cb0[60].xyzw
 183  0x000014E8:     dp4 r2.z, r1.xyzw, cb0[61].xyzw
 184  0x00001508:     and r3.x, cb0[0].x, l(2)
 185  0x00001528:     if_nz r3.x
 186  0x00001534:       sample_c_lz r2.w, r2.xyxx, t0.xxxx, s2, r2.z
 187  0x00001560:     else 
 188  0x00001564:       div r3.x, l(10.000000), cb0[63].y
 189  0x00001584:       and r3.y, cb0[0].x, l(16)
 190  0x000015A4:       if_nz r3.y
 191  0x000015B0:         mul r3.yz, r3.xxxx, l(0.000000, 0.000937, 0.001875, 0.000000)
 192  0x000015D8:         add r3.w, r2.z, l(-6.000000)
 193  0x000015F4:         mul r3.yz, r3.wwww, r3.yyzy
 194  0x00001610:         div r3.yz, r3.yyzy, r2.zzzz
 195  0x0000162C:         dp2 r3.w, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
 196  0x00001654:         frc r3.w, r3.w
 197  0x00001668:         mul r3.w, r3.w, l(52.982918)
 198  0x00001684:         frc r3.w, r3.w
 199  0x00001698:         mul r3.w, r3.w, l(6.283185)
 200  0x000016B4:         mov r4.xyz, l(0,0,0,0)
 201  0x000016D4:         loop 
 202  0x000016D8:           ige r4.w, r4.z, l(16)
 203  0x000016F4:           breakc_nz r4.w
 204  0x00001700:           itof r4.w, r4.z
 205  0x00001714:           add r5.x, r4.w, l(0.500000)
 206  0x00001730:           sqrt r5.x, r5.x
 207  0x00001744:           mul r5.x, r5.x, l(0.250000)
 208  0x00001760:           mad r4.w, r4.w, l(2.400000), r3.w
 209  0x00001784:           sincos r6.x, r7.x, r4.w
 210  0x000017A0:           mul r7.x, r5.x, r7.x
 211  0x000017BC:           mul r7.y, r5.x, r6.x
 212  0x000017D8:           mad r5.xy, r7.xyxx, r3.yzyy, r2.xyxx
 213  0x000017FC:           sample_l r4.w, r5.xyxx, t0.yzwx, s1, l(0.000000)
 214  0x00001828:           lt r5.x, r4.w, r2.z
 215  0x00001844:           add r6.y, r4.w, r4.y
 216  0x00001860:           add r6.x, r4.x, l(1.000000)
 217  0x0000187C:           movc r4.xy, r5.xxxx, r6.xyxx, r4.xyxx
 218  0x000018A0:           iadd r4.z, r4.z, l(1)
 219  0x000018BC:         endloop 
 220  0x000018C0:         ge r3.y, r4.x, l(1.000000)
 221  0x000018DC:         if_nz r3.y
 222  0x000018E8:           mul r3.yz, r3.xxxx, l(0.000000, 0.000625, 0.001250, 0.000000)
 223  0x00001910:           div r4.x, r4.y, r4.x
 224  0x0000192C:           add r4.x, r2.z, -r4.x
 225  0x0000194C:           min r4.x, r4.x, l(0.070000)
 226  0x00001968:           mul r4.x, r4.x, l(60.000000)
 227  0x00001984:           mul r3.yz, r3.yyzy, r4.xxxx
 228  0x000019A0:           resinfo r4.xy, l(0), t0.xyzw
 229  0x000019BC:           div r4.xy, l(0.500000, 0.500000, 0.000000, 0.000000), r4.xyxx
 230  0x000019E4:           max r3.yz, r3.yyzy, r4.xxyx
 231  0x00001A00:           mov r4.xy, l(0,0,0,0)
 232  0x00001A20:           loop 
 233  0x00001A24:             ige r4.z, r4.y, l(16)
 234  0x00001A40:             breakc_nz r4.z
 235  0x00001A4C:             itof r4.z, r4.y
 236  0x00001A60:             add r4.w, r4.z, l(0.500000)
 237  0x00001A7C:             sqrt r4.w, r4.w
 238  0x00001A90:             mul r4.w, r4.w, l(0.250000)
 239  0x00001AAC:             mad r4.z, r4.z, l(2.400000), r3.w
 240  0x00001AD0:             sincos r5.x, r6.x, r4.z
 241  0x00001AEC:             mul r6.x, r4.w, r6.x
 242  0x00001B08:             mul r6.y, r4.w, r5.x
 243  0x00001B24:             mul r4.zw, r3.yyyz, r6.xxxy
 244  0x00001B40:             mad r4.zw, r4.zzzw, l(0.000000, 0.000000, 3.000000, 3.000000), r2.xxxy
 245  0x00001B70:             sample_c_lz r4.z, r4.zwzz, t0.xxxx, s2, r2.z
 246  0x00001B9C:             add r4.x, r4.z, r4.x
 247  0x00001BB8:             iadd r4.y, r4.y, l(1)
 248  0x00001BD4:           endloop 
 249  0x00001BD8:           mul r2.w, r4.x, l(0.062500)
 250  0x00001BF4:         else 
 251  0x00001BF8:           mov r2.w, l(1.000000)
 252  0x00001C0C:         endif 
 253  0x00001C10:       else 
 254  0x00001C14:         and r3.y, cb0[0].x, l(8)
 255  0x00001C34:         if_nz r3.y
 256  0x00001C40:           mul r3.yz, r3.xxxx, l(0.000000, 0.000375, 0.000750, 0.000000)
 257  0x00001C68:           dp2 r3.w, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
 258  0x00001C90:           frc r3.w, r3.w
 259  0x00001CA4:           mul r3.w, r3.w, l(52.982918)
 260  0x00001CC0:           frc r3.w, r3.w
 261  0x00001CD4:           mul r3.w, r3.w, l(6.283185)
 262  0x00001CF0:           mov r4.xy, l(0,0,0,0)
 263  0x00001D10:           loop 
 264  0x00001D14:             ige r4.z, r4.y, l(16)
 265  0x00001D30:             breakc_nz r4.z
 266  0x00001D3C:             itof r4.z, r4.y
 267  0x00001D50:             add r4.w, r4.z, l(0.500000)
 268  0x00001D6C:             sqrt r4.w, r4.w
 269  0x00001D80:             mul r4.w, r4.w, l(0.250000)
 270  0x00001D9C:             mad r4.z, r4.z, l(2.400000), r3.w
 271  0x00001DC0:             sincos r5.x, r6.x, r4.z
 272  0x00001DDC:             mul r6.x, r4.w, r6.x
 273  0x00001DF8:             mul r6.y, r4.w, r5.x
 274  0x00001E14:             mul r4.zw, r3.yyyz, r6.xxxy
 275  0x00001E30:             mad r4.zw, r4.zzzw, l(0.000000, 0.000000, 3.000000, 3.000000), r2.xxxy
 276  0x00001E60:             sample_c_lz r4.z, r4.zwzz, t0.xxxx, s2, r2.z
 277  0x00001E8C:             add r4.x, r4.z, r4.x
 278  0x00001EA8:             iadd r4.y, r4.y, l(1)
 279  0x00001EC4:           endloop 
 280  0x00001EC8:           mul r2.w, r4.x, l(0.062500)
 281  0x00001EE4:         else 
 282  0x00001EE8:           dp4 r1.x, r1.xyzw, cb0[62].xyzw
 283  0x00001F08:           and r1.y, cb0[0].x, l(4)
 284  0x00001F28:           if_nz r1.y
 285  0x00001F34:             mul r1.yz, r1.xxxx, cb0[37].xxyx
 286  0x00001F54:             sample_c_lz r1.w, r2.xyxx, t0.xxxx, s2, r2.z
 287  0x00001F80:             mul r4.xy, r3.xxxx, -r1.yzyy
 288  0x00001FA0:             mov r4.z, l(0)
 289  0x00001FB4:             add r3.yzw, r2.xxyz, r4.xxyz
 290  0x00001FD0:             sample_c_lz r3.y, r3.yzyy, t0.xxxx, s2, r3.w
 291  0x00001FFC:             mul r3.y, r3.y, l(0.062500)
 292  0x00002018:             mad r1.w, r1.w, l(0.500000), r3.y
 293  0x0000203C:             mul r5.x, r3.x, r1.y
 294  0x00002058:             mul r5.y, r3.x, -r1.z
 295  0x00002078:             mov r5.z, l(0)
 296  0x0000208C:             add r3.yzw, r2.xxyz, r5.xxyz
 297  0x000020A8:             sample_c_lz r3.y, r3.yzyy, t0.xxxx, s2, r3.w
 298  0x000020D4:             mad r1.w, r3.y, l(0.062500), r1.w
 299  0x000020F8:             mul r6.x, r3.x, -r1.y
 300  0x00002118:             mul r6.y, r3.x, r1.z
 301  0x00002134:             mov r6.z, l(0)
 302  0x00002148:             add r3.yzw, r2.xxyz, r6.xxyz
 303  0x00002164:             sample_c_lz r3.y, r3.yzyy, t0.xxxx, s2, r3.w
 304  0x00002190:             mad r1.w, r3.y, l(0.062500), r1.w
 305  0x000021B4:             mul r6.xy, r3.xxxx, r1.yzyy
 306  0x000021D0:             mov r6.z, l(0)
 307  0x000021E4:             add r3.yzw, r2.xxyz, r6.xxyz
 308  0x00002200:             sample_c_lz r1.y, r3.yzyy, t0.xxxx, s2, r3.w
 309  0x0000222C:             mad r1.y, r1.y, l(0.062500), r1.w
 310  0x00002250:             add r3.yzw, r2.xxyz, r5.zzyz
 311  0x0000226C:             sample_c_lz r1.z, r3.yzyy, t0.xxxx, s2, r3.w
 312  0x00002298:             mad r1.y, r1.z, l(0.062500), r1.y
 313  0x000022BC:             add r3.yzw, r2.xxyz, r4.xxzz
 314  0x000022D8:             sample_c_lz r1.z, r3.yzyy, t0.xxxx, s2, r3.w
 315  0x00002304:             mad r1.y, r1.z, l(0.062500), r1.y
 316  0x00002328:             add r3.yzw, r2.xxyz, r6.xxzz
 317  0x00002344:             sample_c_lz r1.z, r3.yzyy, t0.xxxx, s2, r3.w
 318  0x00002370:             mad r1.y, r1.z, l(0.062500), r1.y
 319  0x00002394:             add r3.yzw, r2.xxyz, r6.zzyz
 320  0x000023B0:             sample_c_lz r1.z, r3.yzyy, t0.xxxx, s2, r3.w
 321  0x000023DC:             mad r2.w, r1.z, l(0.062500), r1.y
 322  0x00002400:           else 
 323  0x00002404:             mul r1.xy, r1.xxxx, cb0[37].xyxx
 324  0x00002424:             sample_c_lz r1.z, r2.xyxx, t0.xxxx, s2, r2.z
 325  0x00002450:             mul r4.xy, r3.xxxx, -r1.xyxx
 326  0x00002470:             mov r4.z, l(0)
 327  0x00002484:             add r3.yzw, r2.xxyz, r4.xxyz
 328  0x000024A0:             sample_c_lz r1.w, r3.yzyy, t0.xxxx, s2, r3.w
 329  0x000024CC:             mul r1.w, r1.w, cb0[38].y
 330  0x000024EC:             mad r1.z, r1.z, cb0[38].x, r1.w
 331  0x00002514:             mul r4.x, r3.x, r1.x
 332  0x00002530:             mul r4.y, r3.x, -r1.y
 333  0x00002550:             mov r4.z, l(0)
 334  0x00002564:             add r3.yzw, r2.xxyz, r4.xxyz
 335  0x00002580:             sample_c_lz r1.w, r3.yzyy, t0.xxxx, s2, r3.w
 336  0x000025AC:             mad r1.z, r1.w, cb0[38].y, r1.z
 337  0x000025D4:             mul r4.x, r3.x, -r1.x
 338  0x000025F4:             mul r4.y, r3.x, r1.y
 339  0x00002610:             mov r4.z, l(0)
 340  0x00002624:             add r3.yzw, r2.xxyz, r4.xxyz
 341  0x00002640:             sample_c_lz r1.w, r3.yzyy, t0.xxxx, s2, r3.w
 342  0x0000266C:             mad r1.z, r1.w, cb0[38].y, r1.z
 343  0x00002694:             mul r3.xy, r3.xxxx, r1.xyxx
 344  0x000026B0:             mov r3.z, l(0)
 345  0x000026C4:             add r1.xyw, r2.xyxz, r3.xyxz
 346  0x000026E0:             sample_c_lz r1.x, r1.xyxx, t0.xxxx, s2, r1.w
 347  0x0000270C:             mad r2.w, r1.x, cb0[38].y, r1.z
 348  0x00002734:           endif 
 349  0x00002738:         endif 
 350  0x0000273C:       endif 
 351  0x00002740:     endif 
 352  0x00002744:   endif 
 353  0x00002748: else 
 354  0x0000274C:   mov r2.w, l(1.000000)
 355  0x00002760: endif 
 356  0x00002764: lt r1.x, v4.w, cb0[63].x
 357  0x00002784: add r1.y, v4.w, -cb0[63].x
 358  0x000027A8: add r1.z, -cb0[63].x, cb0[63].y
 359  0x000027D0: div_sat r1.y, r1.y, r1.z
 360  0x000027EC: movc r1.x, r1.x, l(0), r1.y
 361  0x00002810: mul r1.y, r1.x, r1.x
 362  0x0000282C: mul r1.x, r1.y, r1.x
 363  0x00002848: movc r0.w, r0.w, r1.x, l(1.000000)
 364  0x0000286C: add r1.x, v4.y, -cb0[30].y
 365  0x00002890: mul r1.x, |r1.x|, cb0[30].x
 366  0x000028B4: min r1.x, r1.x, l(1.000000)
 367  0x000028D0: mul r1.y, r1.x, r1.x
 368  0x000028EC: mul r1.x, r1.y, r1.x
 369  0x00002908: ge r1.y, l(0.000000), cb0[30].x
 370  0x00002928: movc r1.x, r1.y, l(0), r1.x
 371  0x0000294C: add r0.w, r0.w, r1.x
 372  0x00002968: dp3 r1.x, v5.xyzx, cb0[53].xyzx
 373  0x00002988: mad r1.x, r1.x, l(0.500000), l(0.500000)
 374  0x000029AC: mul r1.y, cb0[37].w, l(0.400000)
 375  0x000029CC: max r1.z, -v5.y, l(0.000000)
 376  0x000029EC: mad r1.y, -r1.y, r1.z, l(0.400000)
 377  0x00002A14: lt r1.z, r1.y, r1.x
 378  0x00002A30: add r1.x, -r1.y, r1.x
 379  0x00002A50: add r1.y, -r1.y, l(1.000000)
 380  0x00002A70: div r1.x, r1.x, r1.y
 381  0x00002A8C: and r1.x, r1.x, r1.z
 382  0x00002AA8: add r1.x, -r1.x, l(1.000000)
 383  0x00002AC8: mul r1.y, r1.x, r1.x
 384  0x00002AE4: mad r0.w, r1.x, r1.y, r0.w
 385  0x00002B08: min r0.w, r0.w, l(1.000000)
 386  0x00002B24: add r0.w, r0.w, r2.w
 387  0x00002B40: min r0.w, r0.w, l(1.000000)
 388  0x00002B5C: add r1.x, -r0.w, l(1.000000)
 389  0x00002B7C: add r1.y, -cb0[30].w, l(1.000000)
 390  0x00002BA0: mad r0.w, r1.x, r1.y, r0.w
 391  0x00002BC4: add r1.x, -r0.w, l(1.000000)
 392  0x00002BE4: add r1.y, -cb0[66].w, l(1.000000)
 393  0x00002C08: mad r0.w, r1.x, r1.y, r0.w
 394  0x00002C2C: dp3 r1.x, v5.xyzx, v5.xyzx
 395  0x00002C48: rsq r1.x, r1.x
 396  0x00002C5C: mul r1.xyz, r1.xxxx, v5.xyzx
 397  0x00002C78: add r2.xyz, -v4.xyzx, cb0[1].xyzx
 398  0x00002C9C: dp3 r1.w, r2.xyzx, r2.xyzx
 399  0x00002CB8: rsq r1.w, r1.w
 400  0x00002CCC: mul r3.xyz, r1.wwww, r2.xyzx
 401  0x00002CE8: dp3 r2.w, -r3.xyzx, r1.xyzx
 402  0x00002D08: add r2.w, r2.w, r2.w
 403  0x00002D24: mad r4.xyz, r1.xyzx, -r2.wwww, -r3.xyzx
 404  0x00002D50: dp3 r2.w, r4.xyzx, r4.xyzx
 405  0x00002D6C: rsq r2.w, r2.w
 406  0x00002D80: mul r4.xyz, r2.wwww, r4.xyzx
 407  0x00002D9C: sample r4.xyz, r4.xyzx, t2.xyzw, s0
 408  0x00002DC0: dp3 r2.w, r1.xyzx, r3.xyzx
 409  0x00002DDC: max r2.w, r2.w, l(0.000000)
 410  0x00002DF8: mad r2.w, -r2.w, cb0[75].w, l(1.000000)
 411  0x00002E24: mul r2.w, r2.w, cb0[75].z
 412  0x00002E44: add r3.xyz, -r0.xyzx, r4.xyzx
 413  0x00002E64: mad r0.xyz, r2.wwww, r3.xyzx, r0.xyzx
 414  0x00002E88: dp3 r2.w, cb0[53].xyzx, r1.xyzx
 415  0x00002EA8: mad r2.w, r2.w, l(0.500000), l(0.500000)
 416  0x00002ECC: mul r2.w, r2.w, r2.w
 417  0x00002EE8: mad r2.xyz, r2.xyzx, r1.wwww, cb0[53].xyzx
 418  0x00002F10: dp3 r1.w, r2.xyzx, r2.xyzx
 419  0x00002F2C: rsq r1.w, r1.w
 420  0x00002F40: mul r2.xyz, r1.wwww, r2.xyzx
 421  0x00002F5C: dp3_sat r1.w, r1.xyzx, r2.xyzx
 422  0x00002F78: log r1.w, r1.w
 423  0x00002F8C: mul r1.w, r1.w, cb0[75].y
 424  0x00002FAC: exp r1.w, r1.w
 425  0x00002FC0: min r1.w, r1.w, l(1.000000)
 426  0x00002FDC: mul r1.w, r1.w, cb0[75].x
 427  0x00002FFC: mad r2.xyz, cb0[54].xyzx, r2.wwww, cb0[25].xyzx
 428  0x00003028: min r2.xyz, r2.xyzx, l(1.500000, 1.500000, 1.500000, 0.000000)
 429  0x00003050: mad r2.xyz, cb0[54].xyzx, r1.wwww, r2.xyzx
 430  0x00003078: add r0.w, -r0.w, l(1.000000)
 431  0x00003098: mad r3.xyz, r2.xyzx, cb0[29].xyzx, -r2.xyzx
 432  0x000030C4: mad r2.xyz, r0.wwww, r3.xyzx, r2.xyzx
 433  0x000030E8: mul r2.xyz, r2.xyzx, v1.xyzx
 434  0x00003104: mul r0.xyz, r0.xyzx, r2.xyzx
 435  0x00003120: mad r0.xyz, r0.xyzx, cb0[65].xyzx, cb0[66].xyzx
 436  0x0000314C: add r0.xyz, r0.xyzx, v2.xyzx
 437  0x00003168: add r2.xyz, -r0.xyzx, cb0[27].xyzx
 438  0x0000318C: mad r0.xyz, v2.wwww, r2.xyzx, r0.xyzx
 439  0x000031B0: dp3 r0.w, r0.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
 440  0x000031D8: mad r2.xyz, r0.wwww, cb0[31].xyzx, cb0[32].xyzx
 441  0x00003204: add r2.xyz, -r0.xyzx, r2.xyzx
 442  0x00003224: mad o0.xyz, cb0[67].xxxx, r2.xyzx, r0.xyzx
 443  0x0000324C: min o0.w, cb0[76].y, l(1.000000)
 444  0x0000326C: mad o1.xyz, r1.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
 445  0x000032A8: div r0.x, v6.z, v6.w
 446  0x000032C4: mul r0.y, r0.x, l(256.000000)
 447  0x000032E0: round_z r1.x, r0.y
 448  0x000032F4: mad r0.x, r0.x, l(256.000000), -r1.x
 449  0x0000331C: mul r0.y, r0.x, l(256.000000)
 450  0x00003338: round_z r1.y, r0.y
 451  0x0000334C: mad r1.z, r0.x, l(256.000000), -r1.y
 452  0x00003374: mul o2.xyz, r1.xyzx, l(0.003906, 0.003906, 1.000000, 0.000000)
 453  0x0000339C: mov o1.w, l(0.750000)
 454  0x000033B0: mov o2.w, l(0)
 455  0x000033C4: ret 
// Approximately 456 instruction slots used
 
