//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.4.1 on Tue Aug 11 01:57:17 2026
//
//
// Buffer Definitions:
//
// cbuffer $Globals
// {
//
//   uint4 DuranteSettings;             // Offset:    0 Size:    16
//
//   struct
//   {
//
//       float3 EyePosition;            // Offset:   16
//       float4x4 View;                 // Offset:   32
//       float4x4 Projection;           // Offset:   96
//       float4x4 ViewProjection;       // Offset:  160
//       float4x4 ViewInverse;          // Offset:  224
//       float4x4 ProjectionInverse;    // Offset:  288
//       float2 cameraNearFar;          // Offset:  352
//       float cameraNearTimesFar;      // Offset:  360
//       float cameraFarMinusNear;      // Offset:  364
//       float cameraFarMinusNearInv;   // Offset:  368
//       float2 ViewportWidthHeight;    // Offset:  372
//       float2 screenWidthHeightInv;   // Offset:  384
//       float3 GlobalAmbientColor;     // Offset:  400
//       float Time;                    // Offset:  412
//       float3 FakeRimLightDir;        // Offset:  416
//       float3 FogColor;               // Offset:  432
//       float4 FogRangeParameters;     // Offset:  448
//       float3 MiscParameters1;        // Offset:  464
//       float4 MiscParameters2;        // Offset:  480
//       float3 MonotoneMul;            // Offset:  496
//       float3 MonotoneAdd;            // Offset:  512
//       float3 UserClipPlane2;         // Offset:  528
//       float4 UserClipPlane;          // Offset:  544
//       float4 MiscParameters3;        // Offset:  560
//       float AdditionalShadowOffset;  // Offset:  576
//       float AlphaTestDirection;      // Offset:  580
//       float4 MiscParameters4;        // Offset:  592
//       float3 MiscParameters5;        // Offset:  608
//       float4 light1_attenuation;     // Offset:  624
//       float3 light2_position;        // Offset:  640
//       float3 light2_colorIntensity;  // Offset:  656
//       float4 light2_attenuation;     // Offset:  672
//
//   } scene;                           // Offset:   16 Size:   672
//   bool PhyreContextSwitches;         // Offset:  688 Size:     4 [unused]
//   bool PhyreMaterialSwitches;        // Offset:  692 Size:     4 [unused]
//   float4x4 World;                    // Offset:  704 Size:    64 [unused]
//   float4x4 WorldViewProjection;      // Offset:  768 Size:    64 [unused]
//   float GlobalTexcoordFactor;        // Offset:  832 Size:     4 [unused]
//
//   struct
//   {
//
//       float3 m_direction;            // Offset:  848
//       float3 m_colorIntensity;       // Offset:  864
//
//   } Light0;                          // Offset:  848 Size:    28
//
//   struct
//   {
//
//       float4x4 m_split0Transform;    // Offset:  880
//       float4x4 m_split1Transform;    // Offset:  944
//       float4 m_splitDistances;       // Offset: 1008
//
//   } LightShadow0;                    // Offset:  880 Size:   144
//   float GameMaterialID;              // Offset: 1024 Size:     4 [unused]
//      = 0x00000000
//   float4 GameMaterialDiffuse;        // Offset: 1040 Size:    16
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000
//   float4 GameMaterialEmission;       // Offset: 1056 Size:    16
//      = 0x00000000 0x00000000 0x00000000 0x00000000
//   float GameMaterialMonotone;        // Offset: 1072 Size:     4
//      = 0x00000000
//   float4 GameMaterialTexcoord;       // Offset: 1088 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000
//   float4 GameDitherParams;           // Offset: 1104 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000
//   float4 UVaMUvColor;                // Offset: 1120 Size:    16 [unused]
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000
//   float4 UVaProjTexcoord;            // Offset: 1136 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000
//   float4 UVaMUvTexcoord;             // Offset: 1152 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000
//   float4 UVaMUv2Texcoord;            // Offset: 1168 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000
//   float4 UVaDuDvTexcoord;            // Offset: 1184 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000
//   float3 ShadowColorShift;           // Offset: 1200 Size:    12
//      = 0x3dcccccd 0x3ca3d70a 0x3ca3d70a
//   float Shininess;                   // Offset: 1212 Size:     4
//      = 0x3f000000
//   float SpecularPower;               // Offset: 1216 Size:     4
//      = 0x42480000
//   float3 RimLitColor;                // Offset: 1220 Size:    12
//      = 0x3f800000 0x3f800000 0x3f800000
//   float RimLitIntensity;             // Offset: 1232 Size:     4
//      = 0x40800000
//   float RimLitPower;                 // Offset: 1236 Size:     4
//      = 0x40000000
//   float RimLightClampFactor;         // Offset: 1240 Size:     4
//      = 0x40000000
//   float BloomIntensity;              // Offset: 1244 Size:     4
//      = 0x3f800000
//   float4 PointLightParams;           // Offset: 1248 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000
//   float4 PointLightColor;            // Offset: 1264 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PointClampSamplerState            sampler      NA          NA             s0      1
// LinearClampCmpSamplerState      sampler_c      NA          NA             s1      1
// DiffuseMapSamplerSampler          sampler      NA          NA             s2      1
// NormalMapSamplerSampler           sampler      NA          NA             s3      1
// LightShadowMap0                   texture  float4          2d             t0      1
// DiffuseMapSampler                 texture  float4          2d             t1      1
// NormalMapSampler                  texture  float4          2d             t2      1
// $Globals                          cbuffer      NA          NA            cb0      1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xy
// COLOR                    0   xyzw        1     NONE   float   xyz
// COLOR                    1   xyzw        2     NONE   float   xyzw
// TEXCOORD                 0   xy          3     NONE   float   xy
// TEXCOORD                 1   xyzw        4     NONE   float   xyzw
// TEXCOORD                 4   xyz         5     NONE   float   xyz
// TEXCOORD                 6   xyz         6     NONE   float   xyz
// TEXCOORD                10   xyzw        7     NONE   float     zw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
// SV_TARGET                1   xyzw        1   TARGET   float   xyzw
// SV_TARGET                2   xyzw        2   TARGET   float   xyzw
//
ps_4_1
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[78], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_comparison
dcl_sampler s2, mode_default
dcl_sampler s3, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyzw
dcl_input_ps linear v3.xy
dcl_input_ps linear v4.xyzw
dcl_input_ps linear v5.xyz
dcl_input_ps linear v6.xyz
dcl_input_ps linear v7.zw
dcl_output o0.xyzw
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_temps 9
sample r0.xyz, v3.xyxx, t1.xyzw, s2
ge r0.w, cb0[63].y, v4.w
if_nz r0.w
  mad r1.xyz, cb0[53].xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), v4.xyzx
  mad r1.xyz, v5.xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), r1.xyzx
  lt r2.x, v4.w, cb0[63].x
  if_nz r2.x
    mov r1.w, l(1.000000)
    dp4 r2.x, r1.xyzw, cb0[55].xyzw
    dp4 r2.y, r1.xyzw, cb0[56].xyzw
    dp4 r2.z, r1.xyzw, cb0[57].xyzw
    and r2.w, cb0[0].x, l(2)
    if_nz r2.w
      sample_c_lz r2.w, r2.xyxx, t0.xxxx, s1, r2.z
    else
      div r3.x, l(25.000000), cb0[63].y
      and r3.y, cb0[0].x, l(16)
      if_nz r3.y
        mul r3.yz, r3.xxxx, l(0.000000, 0.000937499979, 0.001875, 0.000000)
        add r3.w, r2.z, l(-6.000000)
        mul r3.yz, r3.wwww, r3.yyzy
        div r3.yz, r3.yyzy, r2.zzzz
        dp2 r3.w, v0.xyxx, l(0.0671105608, 0.00583714992, 0.000000, 0.000000)
        frc r3.w, r3.w
        mul r3.w, r3.w, l(52.982918)
        frc r3.w, r3.w
        mul r3.w, r3.w, l(6.28318548)
        mov r4.xyz, l(0,0,0,0)
        loop
          ige r4.w, r4.z, l(16)
          breakc_nz r4.w
          itof r4.w, r4.z
          add r5.x, r4.w, l(0.500000)
          sqrt r5.x, r5.x
          mul r5.x, r5.x, l(0.250000)
          mad r4.w, r4.w, l(2.400000), r3.w
          sincos r6.x, r7.x, r4.w
          mul r7.x, r5.x, r7.x
          mul r7.y, r5.x, r6.x
          mad r5.xy, r7.xyxx, r3.yzyy, r2.xyxx
          sample_l r4.w, r5.xyxx, t0.yzwx, s0, l(0.000000)
          lt r5.x, r4.w, r2.z
          add r6.y, r4.w, r4.y
          add r6.x, r4.x, l(1.000000)
          movc r4.xy, r5.xxxx, r6.xyxx, r4.xyxx
          iadd r4.z, r4.z, l(1)
        endloop
        ge r3.y, r4.x, l(1.000000)
        if_nz r3.y
          mul r3.yz, r3.xxxx, l(0.000000, 0.000625, 0.001250, 0.000000)
          div r4.x, r4.y, r4.x
          add r4.x, r2.z, -r4.x
          min r4.x, r4.x, l(0.070000)
          mul r4.x, r4.x, l(60.000000)
          mul r3.yz, r3.yyzy, r4.xxxx
          resinfo r4.xy, l(0), t0.xyzw
          div r4.xy, l(0.500000, 0.500000, 0.000000, 0.000000), r4.xyxx
          max r3.yz, r3.yyzy, r4.xxyx
          mov r4.xy, l(0,0,0,0)
          loop
            ige r4.z, r4.y, l(16)
            breakc_nz r4.z
            itof r4.z, r4.y
            add r4.w, r4.z, l(0.500000)
            sqrt r4.w, r4.w
            mul r4.w, r4.w, l(0.250000)
            mad r4.z, r4.z, l(2.400000), r3.w
            sincos r5.x, r6.x, r4.z
            mul r6.x, r4.w, r6.x
            mul r6.y, r4.w, r5.x
            mul r4.zw, r3.yyyz, r6.xxxy
            mad r4.zw, r4.zzzw, l(0.000000, 0.000000, 3.000000, 3.000000), r2.xxxy
            sample_c_lz r4.z, r4.zwzz, t0.xxxx, s1, r2.z
            add r4.x, r4.z, r4.x
            iadd r4.y, r4.y, l(1)
          endloop
          mul r2.w, r4.x, l(0.062500)
        else
          mov r2.w, l(1.000000)
        endif
      else
        and r3.y, cb0[0].x, l(8)
        if_nz r3.y
          mul r3.yz, r3.xxxx, l(0.000000, 0.000375, 0.000750, 0.000000)
          dp2 r3.w, v0.xyxx, l(0.0671105608, 0.00583714992, 0.000000, 0.000000)
          frc r3.w, r3.w
          mul r3.w, r3.w, l(52.982918)
          frc r3.w, r3.w
          mul r3.w, r3.w, l(6.28318548)
          mov r4.xy, l(0,0,0,0)
          loop
            ige r4.z, r4.y, l(16)
            breakc_nz r4.z
            itof r4.z, r4.y
            add r4.w, r4.z, l(0.500000)
            sqrt r4.w, r4.w
            mul r4.w, r4.w, l(0.250000)
            mad r4.z, r4.z, l(2.400000), r3.w
            sincos r5.x, r6.x, r4.z
            mul r6.x, r4.w, r6.x
            mul r6.y, r4.w, r5.x
            mul r4.zw, r3.yyyz, r6.xxxy
            mad r4.zw, r4.zzzw, l(0.000000, 0.000000, 3.000000, 3.000000), r2.xxxy
            sample_c_lz r4.z, r4.zwzz, t0.xxxx, s1, r2.z
            add r4.x, r4.z, r4.x
            iadd r4.y, r4.y, l(1)
          endloop
          mul r2.w, r4.x, l(0.062500)
        else
          dp4 r3.y, r1.xyzw, cb0[58].xyzw
          and r3.z, cb0[0].x, l(4)
          if_nz r3.z
            mul r3.zw, r3.yyyy, cb0[37].xxxy
            sample_c_lz r4.x, r2.xyxx, t0.xxxx, s1, r2.z
            mul r5.xy, r3.xxxx, -r3.zwzz
            mov r5.z, l(0)
            add r4.yzw, r2.xxyz, r5.xxyz
            sample_c_lz r4.y, r4.yzyy, t0.xxxx, s1, r4.w
            mul r4.y, r4.y, l(0.062500)
            mad r4.x, r4.x, l(0.500000), r4.y
            mul r6.x, r3.x, r3.z
            mul r6.y, r3.x, -r3.w
            mov r6.z, l(0)
            add r4.yzw, r2.xxyz, r6.xxyz
            sample_c_lz r4.y, r4.yzyy, t0.xxxx, s1, r4.w
            mad r4.x, r4.y, l(0.062500), r4.x
            mul r7.x, r3.x, -r3.z
            mul r7.y, r3.x, r3.w
            mov r7.z, l(0)
            add r4.yzw, r2.xxyz, r7.xxyz
            sample_c_lz r4.y, r4.yzyy, t0.xxxx, s1, r4.w
            mad r4.x, r4.y, l(0.062500), r4.x
            mul r8.xy, r3.xxxx, r3.zwzz
            mov r8.z, l(0)
            add r4.yzw, r2.xxyz, r8.xxyz
            sample_c_lz r3.z, r4.yzyy, t0.xxxx, s1, r4.w
            mad r3.z, r3.z, l(0.062500), r4.x
            add r4.xyz, r2.xyzx, r5.zyzz
            sample_c_lz r3.w, r4.xyxx, t0.xxxx, s1, r4.z
            mad r3.z, r3.w, l(0.062500), r3.z
            add r4.xyz, r2.xyzx, r7.xzzx
            sample_c_lz r3.w, r4.xyxx, t0.xxxx, s1, r4.z
            mad r3.z, r3.w, l(0.062500), r3.z
            add r4.xyz, r2.xyzx, r6.xzzx
            sample_c_lz r3.w, r4.xyxx, t0.xxxx, s1, r4.z
            mad r3.z, r3.w, l(0.062500), r3.z
            add r4.xyz, r2.xyzx, r8.zyzz
            sample_c_lz r3.w, r4.xyxx, t0.xxxx, s1, r4.z
            mad r2.w, r3.w, l(0.062500), r3.z
          else
            mul r3.yz, r3.yyyy, cb0[37].xxyx
            sample_c_lz r3.w, r2.xyxx, t0.xxxx, s1, r2.z
            mul r4.xy, r3.xxxx, -r3.yzyy
            mov r4.z, l(0)
            add r4.xyz, r2.xyzx, r4.xyzx
            sample_c_lz r4.x, r4.xyxx, t0.xxxx, s1, r4.z
            mul r4.x, r4.x, cb0[38].y
            mad r3.w, r3.w, cb0[38].x, r4.x
            mul r4.x, r3.x, r3.y
            mul r4.y, r3.x, -r3.z
            mov r4.z, l(0)
            add r4.xyz, r2.xyzx, r4.xyzx
            sample_c_lz r4.x, r4.xyxx, t0.xxxx, s1, r4.z
            mad r3.w, r4.x, cb0[38].y, r3.w
            mul r4.x, r3.x, -r3.y
            mul r4.y, r3.x, r3.z
            mov r4.z, l(0)
            add r4.xyz, r2.xyzx, r4.xyzx
            sample_c_lz r4.x, r4.xyxx, t0.xxxx, s1, r4.z
            mad r3.w, r4.x, cb0[38].y, r3.w
            mul r3.xy, r3.xxxx, r3.yzyy
            mov r3.z, l(0)
            add r2.xyz, r2.xyzx, r3.xyzx
            sample_c_lz r2.x, r2.xyxx, t0.xxxx, s1, r2.z
            mad r2.w, r2.x, cb0[38].y, r3.w
          endif
        endif
      endif
    endif
  else
    mov r1.w, l(1.000000)
    dp4 r2.x, r1.xyzw, cb0[59].xyzw
    dp4 r2.y, r1.xyzw, cb0[60].xyzw
    dp4 r2.z, r1.xyzw, cb0[61].xyzw
    and r3.x, cb0[0].x, l(2)
    if_nz r3.x
      sample_c_lz r2.w, r2.xyxx, t0.xxxx, s1, r2.z
    else
      div r3.x, l(10.000000), cb0[63].y
      and r3.y, cb0[0].x, l(16)
      if_nz r3.y
        mul r3.yz, r3.xxxx, l(0.000000, 0.000937499979, 0.001875, 0.000000)
        add r3.w, r2.z, l(-6.000000)
        mul r3.yz, r3.wwww, r3.yyzy
        div r3.yz, r3.yyzy, r2.zzzz
        dp2 r3.w, v0.xyxx, l(0.0671105608, 0.00583714992, 0.000000, 0.000000)
        frc r3.w, r3.w
        mul r3.w, r3.w, l(52.982918)
        frc r3.w, r3.w
        mul r3.w, r3.w, l(6.28318548)
        mov r4.xyz, l(0,0,0,0)
        loop
          ige r4.w, r4.z, l(16)
          breakc_nz r4.w
          itof r4.w, r4.z
          add r5.x, r4.w, l(0.500000)
          sqrt r5.x, r5.x
          mul r5.x, r5.x, l(0.250000)
          mad r4.w, r4.w, l(2.400000), r3.w
          sincos r6.x, r7.x, r4.w
          mul r7.x, r5.x, r7.x
          mul r7.y, r5.x, r6.x
          mad r5.xy, r7.xyxx, r3.yzyy, r2.xyxx
          sample_l r4.w, r5.xyxx, t0.yzwx, s0, l(0.000000)
          lt r5.x, r4.w, r2.z
          add r6.y, r4.w, r4.y
          add r6.x, r4.x, l(1.000000)
          movc r4.xy, r5.xxxx, r6.xyxx, r4.xyxx
          iadd r4.z, r4.z, l(1)
        endloop
        ge r3.y, r4.x, l(1.000000)
        if_nz r3.y
          mul r3.yz, r3.xxxx, l(0.000000, 0.000625, 0.001250, 0.000000)
          div r4.x, r4.y, r4.x
          add r4.x, r2.z, -r4.x
          min r4.x, r4.x, l(0.070000)
          mul r4.x, r4.x, l(60.000000)
          mul r3.yz, r3.yyzy, r4.xxxx
          resinfo r4.xy, l(0), t0.xyzw
          div r4.xy, l(0.500000, 0.500000, 0.000000, 0.000000), r4.xyxx
          max r3.yz, r3.yyzy, r4.xxyx
          mov r4.xy, l(0,0,0,0)
          loop
            ige r4.z, r4.y, l(16)
            breakc_nz r4.z
            itof r4.z, r4.y
            add r4.w, r4.z, l(0.500000)
            sqrt r4.w, r4.w
            mul r4.w, r4.w, l(0.250000)
            mad r4.z, r4.z, l(2.400000), r3.w
            sincos r5.x, r6.x, r4.z
            mul r6.x, r4.w, r6.x
            mul r6.y, r4.w, r5.x
            mul r4.zw, r3.yyyz, r6.xxxy
            mad r4.zw, r4.zzzw, l(0.000000, 0.000000, 3.000000, 3.000000), r2.xxxy
            sample_c_lz r4.z, r4.zwzz, t0.xxxx, s1, r2.z
            add r4.x, r4.z, r4.x
            iadd r4.y, r4.y, l(1)
          endloop
          mul r2.w, r4.x, l(0.062500)
        else
          mov r2.w, l(1.000000)
        endif
      else
        and r3.y, cb0[0].x, l(8)
        if_nz r3.y
          mul r3.yz, r3.xxxx, l(0.000000, 0.000375, 0.000750, 0.000000)
          dp2 r3.w, v0.xyxx, l(0.0671105608, 0.00583714992, 0.000000, 0.000000)
          frc r3.w, r3.w
          mul r3.w, r3.w, l(52.982918)
          frc r3.w, r3.w
          mul r3.w, r3.w, l(6.28318548)
          mov r4.xy, l(0,0,0,0)
          loop
            ige r4.z, r4.y, l(16)
            breakc_nz r4.z
            itof r4.z, r4.y
            add r4.w, r4.z, l(0.500000)
            sqrt r4.w, r4.w
            mul r4.w, r4.w, l(0.250000)
            mad r4.z, r4.z, l(2.400000), r3.w
            sincos r5.x, r6.x, r4.z
            mul r6.x, r4.w, r6.x
            mul r6.y, r4.w, r5.x
            mul r4.zw, r3.yyyz, r6.xxxy
            mad r4.zw, r4.zzzw, l(0.000000, 0.000000, 3.000000, 3.000000), r2.xxxy
            sample_c_lz r4.z, r4.zwzz, t0.xxxx, s1, r2.z
            add r4.x, r4.z, r4.x
            iadd r4.y, r4.y, l(1)
          endloop
          mul r2.w, r4.x, l(0.062500)
        else
          dp4 r1.x, r1.xyzw, cb0[62].xyzw
          and r1.y, cb0[0].x, l(4)
          if_nz r1.y
            mul r1.yz, r1.xxxx, cb0[37].xxyx
            sample_c_lz r1.w, r2.xyxx, t0.xxxx, s1, r2.z
            mul r4.xy, r3.xxxx, -r1.yzyy
            mov r4.z, l(0)
            add r3.yzw, r2.xxyz, r4.xxyz
            sample_c_lz r3.y, r3.yzyy, t0.xxxx, s1, r3.w
            mul r3.y, r3.y, l(0.062500)
            mad r1.w, r1.w, l(0.500000), r3.y
            mul r4.x, r3.x, r1.y
            mul r4.y, r3.x, -r1.z
            mov r4.z, l(0)
            add r3.yzw, r2.xxyz, r4.xxyz
            sample_c_lz r3.y, r3.yzyy, t0.xxxx, s1, r3.w
            mad r1.w, r3.y, l(0.062500), r1.w
            mul r5.x, r3.x, -r1.y
            mul r5.y, r3.x, r1.z
            mov r5.z, l(0)
            add r3.yzw, r2.xxyz, r5.xxyz
            sample_c_lz r3.y, r3.yzyy, t0.xxxx, s1, r3.w
            mad r1.w, r3.y, l(0.062500), r1.w
            mul r6.xy, r3.xxxx, r1.yzyy
            mov r6.z, l(0)
            add r3.yzw, r2.xxyz, r6.xxyz
            sample_c_lz r1.y, r3.yzyy, t0.xxxx, s1, r3.w
            mad r1.y, r1.y, l(0.062500), r1.w
            add r3.yzw, r2.xxyz, r4.zzyz
            sample_c_lz r1.z, r3.yzyy, t0.xxxx, s1, r3.w
            mad r1.y, r1.z, l(0.062500), r1.y
            add r3.yzw, r2.xxyz, r5.xxzz
            sample_c_lz r1.z, r3.yzyy, t0.xxxx, s1, r3.w
            mad r1.y, r1.z, l(0.062500), r1.y
            add r3.yzw, r2.xxyz, r4.xxzz
            sample_c_lz r1.z, r3.yzyy, t0.xxxx, s1, r3.w
            mad r1.y, r1.z, l(0.062500), r1.y
            add r3.yzw, r2.xxyz, r6.zzyz
            sample_c_lz r1.z, r3.yzyy, t0.xxxx, s1, r3.w
            mad r2.w, r1.z, l(0.062500), r1.y
          else
            mul r1.xy, r1.xxxx, cb0[37].xyxx
            sample_c_lz r1.z, r2.xyxx, t0.xxxx, s1, r2.z
            mul r4.xy, r3.xxxx, -r1.xyxx
            mov r4.z, l(0)
            add r3.yzw, r2.xxyz, r4.xxyz
            sample_c_lz r1.w, r3.yzyy, t0.xxxx, s1, r3.w
            mul r1.w, r1.w, cb0[38].y
            mad r1.z, r1.z, cb0[38].x, r1.w
            mul r4.x, r3.x, r1.x
            mul r4.y, r3.x, -r1.y
            mov r4.z, l(0)
            add r3.yzw, r2.xxyz, r4.xxyz
            sample_c_lz r1.w, r3.yzyy, t0.xxxx, s1, r3.w
            mad r1.z, r1.w, cb0[38].y, r1.z
            mul r4.x, r3.x, -r1.x
            mul r4.y, r3.x, r1.y
            mov r4.z, l(0)
            add r3.yzw, r2.xxyz, r4.xxyz
            sample_c_lz r1.w, r3.yzyy, t0.xxxx, s1, r3.w
            mad r1.z, r1.w, cb0[38].y, r1.z
            mul r3.xy, r3.xxxx, r1.xyxx
            mov r3.z, l(0)
            add r1.xyw, r2.xyxz, r3.xyxz
            sample_c_lz r1.x, r1.xyxx, t0.xxxx, s1, r1.w
            mad r2.w, r1.x, cb0[38].y, r1.z
          endif
        endif
      endif
    endif
  endif
else
  mov r2.w, l(1.000000)
endif
lt r1.x, v4.w, cb0[63].x
add r1.y, v4.w, -cb0[63].x
add r1.z, -cb0[63].x, cb0[63].y
div_sat r1.y, r1.y, r1.z
movc r1.x, r1.x, l(0), r1.y
mul r1.y, r1.x, r1.x
mul r1.x, r1.y, r1.x
movc r0.w, r0.w, r1.x, l(1.000000)
add r1.x, v4.y, -cb0[30].y
mul r1.x, |r1.x|, cb0[30].x
min r1.x, r1.x, l(1.000000)
mul r1.y, r1.x, r1.x
mul r1.x, r1.y, r1.x
ge r1.y, l(0.000000), cb0[30].x
movc r1.x, r1.y, l(0), r1.x
add r0.w, r0.w, r1.x
dp3 r1.x, v5.xyzx, cb0[53].xyzx
mad r1.x, r1.x, l(0.500000), l(0.500000)
mul r1.y, cb0[37].w, l(0.400000)
max r1.z, -v5.y, l(0.000000)
mad r1.y, -r1.y, r1.z, l(0.400000)
lt r1.z, r1.y, r1.x
add r1.x, -r1.y, r1.x
add r1.y, -r1.y, l(1.000000)
div r1.x, r1.x, r1.y
and r1.x, r1.x, r1.z
add r1.x, -r1.x, l(1.000000)
mul r1.y, r1.x, r1.x
mad r0.w, r1.x, r1.y, r0.w
min r0.w, r0.w, l(1.000000)
add r0.w, r0.w, r2.w
min r0.w, r0.w, l(1.000000)
add r1.x, -r0.w, l(1.000000)
add r1.y, -cb0[30].w, l(1.000000)
mad r0.w, r1.x, r1.y, r0.w
add r1.x, -r0.w, l(1.000000)
add r1.y, -cb0[66].w, l(1.000000)
mad r0.w, r1.x, r1.y, r0.w
mul r1.x, r0.w, r0.w
mul r1.xyz, r1.xxxx, cb0[54].xyzx
sample r2.xyz, v3.xyxx, t2.xyzw, s3
mad r2.xyz, r2.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
dp3 r1.w, v6.xyzx, v6.xyzx
rsq r1.w, r1.w
mul r3.xyz, r1.wwww, v6.xyzx
dp3 r1.w, v5.xyzx, v5.xyzx
rsq r1.w, r1.w
mul r4.xyz, r1.wwww, v5.xyzx
mul r5.xyz, r3.yzxy, r4.zxyz
mad r5.xyz, r4.yzxy, r3.zxyz, -r5.xyzx
lt r1.w, v3.x, l(0.000000)
movc r1.w, r1.w, -r2.x, r2.x
mul r2.xyw, r2.yyyy, r5.xyxz
mad r2.xyw, r1.wwww, r3.xyxz, r2.xyxw
mad r2.xyz, r2.zzzz, r4.xyzx, r2.xywx
dp3 r1.w, r2.xyzx, r2.xyzx
rsq r1.w, r1.w
mul r2.xyz, r1.wwww, r2.xyzx
add r3.xyz, -v4.xyzx, cb0[1].xyzx
dp3 r1.w, r3.xyzx, r3.xyzx
rsq r1.w, r1.w
mul r4.xyz, r1.wwww, r3.xyzx
dp3 r2.w, r2.xyzx, r4.xyzx
lt r3.w, r2.w, l(0.000000)
movc r2.xyzw, r3.wwww, -r2.xyzw, r2.xyzw
dp3 r3.w, cb0[53].xyzx, r2.xyzx
mad r3.w, r3.w, l(0.500000), l(0.500000)
mul r3.w, r3.w, r3.w
mad r3.xyz, r3.xyzx, r1.wwww, cb0[53].xyzx
dp3 r1.w, r3.xyzx, r3.xyzx
rsq r1.w, r1.w
mul r3.xyz, r1.wwww, r3.xyzx
dp3_sat r1.w, r2.xyzx, r3.xyzx
log r1.w, r1.w
mul r1.w, r1.w, cb0[76].x
exp r1.w, r1.w
min r1.w, r1.w, l(1.000000)
mul r1.w, r1.w, cb0[75].w
mad r3.xyz, cb0[54].xyzx, r3.wwww, cb0[25].xyzx
min r3.xyz, r3.xyzx, l(1.500000, 1.500000, 1.500000, 0.000000)
mad r3.xyz, cb0[54].xyzx, r1.wwww, r3.xyzx
add r0.w, -r0.w, l(1.000000)
mad r4.xyz, r3.xyzx, cb0[29].xyzx, -r3.xyzx
mad r3.xyz, r0.wwww, r4.xyzx, r3.xyzx
add r0.w, -|r2.w|, l(1.000000)
max r0.w, r0.w, l(0.000000)
log r0.w, r0.w
mul r0.w, r0.w, cb0[77].y
exp r0.w, r0.w
mul r0.w, r0.w, cb0[77].x
mul r4.xyz, r0.wwww, cb0[76].yzwy
mad r3.xyz, r4.xyzx, r1.xyzx, r3.xyzx
min r3.xyz, r3.xyzx, cb0[77].zzzz
add r1.xyz, r1.xyzx, r1.xyzx
max r1.xyz, r1.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
min r4.xyz, r3.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
add r4.xyz, -r4.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mul r4.xyz, r4.xyzx, cb0[75].xyzx
mad r1.xyz, r4.xyzx, r1.xyzx, r3.xyzx
mul r1.xyz, r1.xyzx, v1.xyzx
mul r0.xyz, r0.xyzx, r1.xyzx
mad r0.xyz, r0.xyzx, cb0[65].xyzx, cb0[66].xyzx
add r0.xyz, r0.xyzx, v2.xyzx
add r1.xyz, -r0.xyzx, cb0[27].xyzx
mad r0.xyz, v2.wwww, r1.xyzx, r0.xyzx
dp3 r0.w, r0.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
mad r1.xyz, r0.wwww, cb0[31].xyzx, cb0[32].xyzx
add r1.xyz, -r0.xyzx, r1.xyzx
mad r0.xyz, cb0[67].xxxx, r1.xyzx, r0.xyzx
mul r1.xyz, r0.xyzx, cb0[77].wwww
dp3 r0.w, r1.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
add r0.w, r0.w, -cb0[30].z
max r0.w, r0.w, l(0.000000)
mul r0.w, r0.w, l(0.500000)
min o0.w, r0.w, l(1.000000)
mad o1.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
div r0.w, v7.z, v7.w
mul r1.x, r0.w, l(256.000000)
round_z r1.x, r1.x
mad r0.w, r0.w, l(256.000000), -r1.x
mul r1.w, r0.w, l(256.000000)
round_z r1.y, r1.w
mad r1.z, r0.w, l(256.000000), -r1.y
mul o2.xyz, r1.xyzx, l(0.00390625000, 0.00390625000, 1.000000, 0.000000)
mov o0.xyz, r0.xyzx
mov o1.w, l(0.750000)
mov o2.w, l(0)
ret
// Approximately 484 instruction slots used
