//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
//   using 3Dmigoto v1.4.1 on Tue Aug 11 02:10:11 2026
//
//
// Buffer Definitions:
//
// cbuffer $Globals
// {
//
//   uint4 DuranteSettings;             // Offset:    0 Size:    16 [unused]
//
//   struct
//   {
//
//       float3 EyePosition;            // Offset:   16
//       float4x4 View;                 // Offset:   32
//       float4x4 Projection;           // Offset:   96
//       float4x4 ViewProjection;       // Offset:  160
//       float4x4 ViewInverse;          // Offset:  224
//       float4x4 ProjectionInverse;    // Offset:  288
//       float2 cameraNearFar;          // Offset:  352
//       float cameraNearTimesFar;      // Offset:  360
//       float cameraFarMinusNear;      // Offset:  364
//       float cameraFarMinusNearInv;   // Offset:  368
//       float2 ViewportWidthHeight;    // Offset:  372
//       float2 screenWidthHeightInv;   // Offset:  384
//       float3 GlobalAmbientColor;     // Offset:  400
//       float Time;                    // Offset:  412
//       float3 FakeRimLightDir;        // Offset:  416
//       float3 FogColor;               // Offset:  432
//       float4 FogRangeParameters;     // Offset:  448
//       float3 MiscParameters1;        // Offset:  464
//       float4 MiscParameters2;        // Offset:  480
//       float3 MonotoneMul;            // Offset:  496
//       float3 MonotoneAdd;            // Offset:  512
//       float3 UserClipPlane2;         // Offset:  528
//       float4 UserClipPlane;          // Offset:  544
//       float4 MiscParameters3;        // Offset:  560
//       float AdditionalShadowOffset;  // Offset:  576
//       float AlphaTestDirection;      // Offset:  580
//       float4 MiscParameters4;        // Offset:  592
//       float3 MiscParameters5;        // Offset:  608
//       float4 light1_attenuation;     // Offset:  624
//       float3 light2_position;        // Offset:  640
//       float3 light2_colorIntensity;  // Offset:  656
//       float4 light2_attenuation;     // Offset:  672
//
//   } scene;                           // Offset:   16 Size:   672
//   bool PhyreContextSwitches;         // Offset:  688 Size:     4 [unused]
//   bool PhyreMaterialSwitches;        // Offset:  692 Size:     4 [unused]
//   float4x4 World;                    // Offset:  704 Size:    64 [unused]
//   float GlobalTexcoordFactor;        // Offset:  768 Size:     4 [unused]
//   float PerMaterialMainLightClampFactor;// Offset:  772 Size:     4 [unused]
//      = 0x3fc00000
//   float3 LightDirForChar;            // Offset:  784 Size:    12 [unused]
//   float GameMaterialID;              // Offset:  796 Size:     4 [unused]
//      = 0x00000000
//   float4 GameMaterialDiffuse;        // Offset:  800 Size:    16 [unused]
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000
//   float4 GameMaterialEmission;       // Offset:  816 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000
//   float GameMaterialMonotone;        // Offset:  832 Size:     4 [unused]
//      = 0x00000000
//   float4 GameMaterialTexcoord;       // Offset:  848 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000
//   float4 UVaMUvColor;                // Offset:  864 Size:    16 [unused]
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000
//   float4 UVaProjTexcoord;            // Offset:  880 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000
//   float4 UVaMUvTexcoord;             // Offset:  896 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000
//   float4 UVaMUv2Texcoord;            // Offset:  912 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000
//   float4 UVaDuDvTexcoord;            // Offset:  928 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x3f800000 0x3f800000
//   float3 ShadowColorShift;           // Offset:  944 Size:    12 [unused]
//      = 0x3dcccccd 0x3ca3d70a 0x3ca3d70a
//   float3 RimLitColor;                // Offset:  960 Size:    12 [unused]
//      = 0x3f800000 0x3f800000 0x3f800000
//   float RimLitIntensity;             // Offset:  972 Size:     4 [unused]
//      = 0x40800000
//   float RimLitPower;                 // Offset:  976 Size:     4 [unused]
//      = 0x40000000
//   float RimLightClampFactor;         // Offset:  980 Size:     4 [unused]
//      = 0x40000000
//   float ShadowReceiveOffset;         // Offset:  984 Size:     4 [unused]
//      = 0x3f19999a
//   float BloomIntensity;              // Offset:  988 Size:     4 [unused]
//      = 0x3f333333
//   float4 GameEdgeParameters;         // Offset:  992 Size:    16
//      = 0x3f800000 0x3f800000 0x3f800000 0x3b449ba6
//   float4 OutlineColorFactor;         // Offset: 1008 Size:    16
//      = 0x3f800000 0x3f800000 0x3f800000 0x3f800000
//   float4 PointLightParams;           // Offset: 1024 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000
//   float4 PointLightColor;            // Offset: 1040 Size:    16 [unused]
//      = 0x00000000 0x00000000 0x00000000 0x00000000
//
// }
//
// Resource bind info for BoneTransformConstantBuffer
// {
//
//   float4x4 $Element;                 // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// BoneTransformConstantBuffer       texture  struct         r/o             t0      1
// $Globals                          cbuffer      NA          NA            cb0      1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz
// NORMAL                   0   xyz         1     NONE   float   xyz
// TEXCOORD                 0   xy          2     NONE   float   xy
// BLENDINDICES             0   xyzw        3     NONE    uint   xyzw
// BLENDWEIGHTS             0   xyzw        4     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// COLOR                    0   xyzw        1     NONE   float   xyzw
// COLOR                    1   xyzw        2     NONE   float   xyzw
// TEXCOORD                 0   xy          3     NONE   float   xy
// TEXCOORD                 1   xyzw        4     NONE   float   xyzw
// TEXCOORD                 9   xyz         5     NONE   float   xyz
// TEXCOORD                10   xyzw        6     NONE   float   xyzw
// TEXCOORD                 5   xyzw        7     NONE   float   xyzw
//
vs_4_1
dcl_globalFlags refactoringAllowed | enableRawAndStructuredBuffers
dcl_constantbuffer CB0[64], immediateIndexed
dcl_resource_structured t0, 64
dcl_input v0.xyz
dcl_input v1.xyz
dcl_input v2.xy
dcl_input v3.xyzw
dcl_input v4.xyzw
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_output o2.xyzw
dcl_output o3.xy
dcl_output o4.xyzw
dcl_output o5.xyz
dcl_output o6.xyzw
dcl_temps 18
dcl_constantbuffer CB1[4], immediateIndexed
dcl_resource_structured t1, 64
dcl_output o7.xyzw
ld_structured r0.xyzw, v3.y, l(0), t0.xyzw
mov r1.xyz, v0.xyzx
mov r1.w, l(1.000000)
dp4 r0.x, r1.xyzw, r0.xyzw
ld_structured r2.xyzw, v3.y, l(16), t0.xyzw
dp4 r0.y, r1.xyzw, r2.xyzw
ld_structured r2.xyzw, v3.y, l(32), t0.xyzw
dp4 r0.z, r1.xyzw, r2.xyzw
mul r0.xyz, r0.xyzx, v4.yyyy
ld_structured r2.xyzw, v3.x, l(0), t0.xyzw
dp4 r2.x, r1.xyzw, r2.xyzw
ld_structured r3.xyzw, v3.x, l(16), t0.xyzw
dp4 r2.y, r1.xyzw, r3.xyzw
ld_structured r3.xyzw, v3.x, l(32), t0.xyzw
dp4 r2.z, r1.xyzw, r3.xyzw
mad r0.xyz, r2.xyzx, v4.xxxx, r0.xyzx
ld_structured r2.xyzw, v3.z, l(0), t0.xyzw
dp4 r2.x, r1.xyzw, r2.xyzw
ld_structured r3.xyzw, v3.z, l(16), t0.xyzw
dp4 r2.y, r1.xyzw, r3.xyzw
ld_structured r3.xyzw, v3.z, l(32), t0.xyzw
dp4 r2.z, r1.xyzw, r3.xyzw
mad r0.xyz, r2.xyzx, v4.zzzz, r0.xyzx
ld_structured r2.xyzw, v3.w, l(0), t0.xyzw
dp4 r2.x, r1.xyzw, r2.xyzw
ld_structured r3.xyzw, v3.w, l(16), t0.xyzw
dp4 r2.y, r1.xyzw, r3.xyzw
ld_structured r3.xyzw, v3.w, l(32), t0.xyzw
dp4 r2.z, r1.xyzw, r3.xyzw
mad r0.xyz, r2.xyzx, v4.wwww, r0.xyzx
mov r0.w, l(1.000000)
dp4 r0.w, r0.xyzw, cb0[13].xyzw
max r0.w, r0.w, l(0.300000)
min r0.w, r0.w, l(1.000000)
ld_structured r1.xyz, v3.y, l(0), t0.xyzx
dp3 r1.x, v1.xyzx, r1.xyzx
ld_structured r2.xyz, v3.y, l(16), t0.xyzx
dp3 r1.y, v1.xyzx, r2.xyzx
ld_structured r2.xyz, v3.y, l(32), t0.xyzx
dp3 r1.z, v1.xyzx, r2.xyzx
mul r1.xyz, r1.xyzx, v4.yyyy
ld_structured r2.xyz, v3.x, l(0), t0.xyzx
dp3 r2.x, v1.xyzx, r2.xyzx
ld_structured r3.xyz, v3.x, l(16), t0.xyzx
dp3 r2.y, v1.xyzx, r3.xyzx
ld_structured r3.xyz, v3.x, l(32), t0.xyzx
dp3 r2.z, v1.xyzx, r3.xyzx
mad r1.xyz, r2.xyzx, v4.xxxx, r1.xyzx
ld_structured r2.xyz, v3.z, l(0), t0.xyzx
dp3 r2.x, v1.xyzx, r2.xyzx
ld_structured r3.xyz, v3.z, l(16), t0.xyzx
dp3 r2.y, v1.xyzx, r3.xyzx
ld_structured r3.xyz, v3.z, l(32), t0.xyzx
dp3 r2.z, v1.xyzx, r3.xyzx
mad r1.xyz, r2.xyzx, v4.zzzz, r1.xyzx
ld_structured r2.xyz, v3.w, l(0), t0.xyzx
dp3 r2.x, v1.xyzx, r2.xyzx
ld_structured r3.xyz, v3.w, l(16), t0.xyzx
dp3 r2.y, v1.xyzx, r3.xyzx
ld_structured r3.xyz, v3.w, l(32), t0.xyzx
dp3 r2.z, v1.xyzx, r3.xyzx
mad r1.xyz, r2.xyzx, v4.wwww, r1.xyzx
dp3 r1.w, r1.xyzx, r1.xyzx
rsq r1.w, r1.w
mul r1.xyz, r1.wwww, r1.xyzx
mul r2.xyz, r1.xyzx, cb0[62].wwww
mov o5.xyz, r1.xyzx
mad r0.xyz, r2.xyzx, r0.wwww, r0.xyzx
add r1.xyz, r0.xyzx, -cb0[1].xyzx
dp3 r0.w, r1.xyzx, r1.xyzx
rsq r0.w, r0.w
mul r1.xyz, r0.wwww, r1.xyzx
add r0.w, cb0[62].w, l(0.001000)
mad r0.xyz, r1.xyzx, r0.wwww, r0.xyzx
mov r0.w, l(1.000000)
dp4 r1.x, r0.xyzw, cb0[10].xyzw
dp4 r1.y, r0.xyzw, cb0[11].xyzw
dp4 r1.z, r0.xyzw, cb0[12].xyzw
dp4 r1.w, r0.xyzw, cb0[13].xyzw
dp4 r0.w, r0.xyzw, cb0[4].xyzw
add r0.w, -r0.w, -cb0[28].x
mul_sat r0.w, r0.w, cb0[28].z
mov o0.xyzw, r1.xyzw
mov o6.xyzw, r1.xyzw
mul o1.xyz, cb0[62].xyzx, cb0[63].xyzx
mov o1.w, l(1.000000)
add r1.x, r0.y, -cb0[35].x
mov o4.xyz, r0.xyzx
mul_sat r0.x, r1.x, cb0[35].y
add r0.y, r0.w, cb0[35].z
min r0.y, r0.y, l(1.000000)
mad r0.x, r0.x, r0.y, r0.w
min r0.x, r0.x, l(1.000000)
mul o2.w, r0.x, cb0[28].w
mov o2.xyz, l(0,0,0,0)
mov o3.xy, v2.xyxx
mov o4.w, l(0)
mov r4.xyz, v0.xyz
mov r4.w, l(1.000000)
ld_structured r5.xyzw, v3.y, l(0), t1.xyzw
dp4 r6.x, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.y, l(16), t1.xyzw
dp4 r6.y, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.y, l(32), t1.xyzw
dp4 r6.z, r5.xyzw, r4.xyzw
mul r7.xyz, v4.yyyy, r6.xyzw
ld_structured r5.xyzw, v3.x, l(0), t1.xyzw
dp4 r6.x, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.x, l(16), t1.xyzw
dp4 r6.y, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.x, l(32), t1.xyzw
dp4 r6.z, r5.xyzw, r4.xyzw
mad r7.xyz, v4.xxxx, r6.xyzw, r7.xyzw
ld_structured r5.xyzw, v3.z, l(0), t1.xyzw
dp4 r6.x, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.z, l(16), t1.xyzw
dp4 r6.y, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.z, l(32), t1.xyzw
dp4 r6.z, r5.xyzw, r4.xyzw
mad r7.xyz, v4.zzzz, r6.xyzw, r7.xyzw
ld_structured r5.xyzw, v3.w, l(0), t1.xyzw
dp4 r6.x, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.w, l(16), t1.xyzw
dp4 r6.y, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.w, l(32), t1.xyzw
dp4 r6.z, r5.xyzw, r4.xyzw
mad r7.xyz, v4.wwww, r6.xyzw, r7.xyzw
mov r7.w, l(1.000000)
ld_structured r5.xyz, v3.y, l(0), t1.xyzw
dp3 r6.x, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.y, l(16), t1.xyzw
dp3 r6.y, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.y, l(32), t1.xyzw
dp3 r6.z, v1.xyz, r5.xyzw
mul r8.xyz, v4.yyyy, r6.xyzw
ld_structured r5.xyz, v3.x, l(0), t1.xyzw
dp3 r6.x, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.x, l(16), t1.xyzw
dp3 r6.y, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.x, l(32), t1.xyzw
dp3 r6.z, v1.xyz, r5.xyzw
mad r8.xyz, v4.xxxx, r6.xyzw, r8.xyzw
ld_structured r5.xyz, v3.z, l(0), t1.xyzw
dp3 r6.x, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.z, l(16), t1.xyzw
dp3 r6.y, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.z, l(32), t1.xyzw
dp3 r6.z, v1.xyz, r5.xyzw
mad r8.xyz, v4.zzzz, r6.xyzw, r8.xyzw
ld_structured r5.xyz, v3.w, l(0), t1.xyzw
dp3 r6.x, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.w, l(16), t1.xyzw
dp3 r6.y, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.w, l(32), t1.xyzw
dp3 r6.z, v1.xyz, r5.xyzw
mad r8.xyz, v4.wwww, r6.xyzw, r8.xyzw
dp3 r8.w, r8.xyzw, r8.xyzw
rsq r8.w, r8.wwww
mul r8.xyz, r8.xyzw, r8.wwww
mov r9.xyzw, cb0[13].xyzw
dp4 r9.x, r9.xyzw, r7.xyzw
max r9.x, r9.xxxx, l(0.300000)
min r9.x, r9.xxxx, l(1.000000)
mov r10.xyzw, cb0[62].xyzw
mul r11.xyz, r10.wwww, r8.xyzw
mul r11.xyz, r11.xyzw, r9.xxxx
add r7.xyz, r7.xyzw, r11.xyzw
mov r12.xyzw, cb0[1].xyzw
mul r12.xyz, r12.xyzw, l(-1.000000, -1.000000, -1.000000, -1.000000)
add r12.xyz, r7.xyzw, r12.xyzw
dp3 r12.w, r12.xyzw, r12.xyzw
rsq r12.w, r12.wwww
mul r12.xyz, r12.xyzw, r12.wwww
add r10.w, r10.wwww, l(0.001000)
mul r12.xyz, r12.xyzw, r10.wwww
add r7.xyz, r7.xyzw, r12.xyzw
mov r13.xyz, v0.xyz
mov r13.w, l(1.000000)
ld_structured r5.xyzw, v3.y, l(0), t0.xyzw
dp4 r6.x, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.y, l(16), t0.xyzw
dp4 r6.y, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.y, l(32), t0.xyzw
dp4 r6.z, r5.xyzw, r4.xyzw
mul r13.xyz, v4.yyyy, r6.xyzw
ld_structured r5.xyzw, v3.x, l(0), t0.xyzw
dp4 r6.x, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.x, l(16), t0.xyzw
dp4 r6.y, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.x, l(32), t0.xyzw
dp4 r6.z, r5.xyzw, r4.xyzw
mad r13.xyz, v4.xxxx, r6.xyzw, r13.xyzw
ld_structured r5.xyzw, v3.z, l(0), t0.xyzw
dp4 r6.x, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.z, l(16), t0.xyzw
dp4 r6.y, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.z, l(32), t0.xyzw
dp4 r6.z, r5.xyzw, r4.xyzw
mad r13.xyz, v4.zzzz, r6.xyzw, r13.xyzw
ld_structured r5.xyzw, v3.w, l(0), t0.xyzw
dp4 r6.x, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.w, l(16), t0.xyzw
dp4 r6.y, r5.xyzw, r4.xyzw
ld_structured r5.xyzw, v3.w, l(32), t0.xyzw
dp4 r6.z, r5.xyzw, r4.xyzw
mad r13.xyz, v4.wwww, r6.xyzw, r13.xyzw
mov r13.w, l(1.000000)
ld_structured r5.xyz, v3.y, l(0), t0.xyzw
dp3 r6.x, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.y, l(16), t0.xyzw
dp3 r6.y, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.y, l(32), t0.xyzw
dp3 r6.z, v1.xyz, r5.xyzw
mul r8.xyz, v4.yyyy, r6.xyzw
ld_structured r5.xyz, v3.x, l(0), t0.xyzw
dp3 r6.x, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.x, l(16), t0.xyzw
dp3 r6.y, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.x, l(32), t0.xyzw
dp3 r6.z, v1.xyz, r5.xyzw
mad r8.xyz, v4.xxxx, r6.xyzw, r8.xyzw
ld_structured r5.xyz, v3.z, l(0), t0.xyzw
dp3 r6.x, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.z, l(16), t0.xyzw
dp3 r6.y, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.z, l(32), t0.xyzw
dp3 r6.z, v1.xyz, r5.xyzw
mad r8.xyz, v4.zzzz, r6.xyzw, r8.xyzw
ld_structured r5.xyz, v3.w, l(0), t0.xyzw
dp3 r6.x, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.w, l(16), t0.xyzw
dp3 r6.y, v1.xyz, r5.xyzw
ld_structured r5.xyz, v3.w, l(32), t0.xyzw
dp3 r6.z, v1.xyz, r5.xyzw
mad r8.xyz, v4.wwww, r6.xyzw, r8.xyzw
dp3 r8.w, r8.xyzw, r8.xyzw
rsq r8.w, r8.wwww
mul r8.xyz, r8.xyzw, r8.wwww
mov r9.xyzw, cb0[13].xyzw
dp4 r9.x, r9.xyzw, r13.xyzw
max r9.x, r9.xxxx, l(0.300000)
min r9.x, r9.xxxx, l(1.000000)
mov r10.xyzw, cb0[62].xyzw
mul r11.xyz, r10.wwww, r8.xyzw
mul r11.xyz, r11.xyzw, r9.xxxx
add r13.xyz, r13.xyzw, r11.xyzw
mov r12.xyzw, cb0[1].xyzw
mul r12.xyz, r12.xyzw, l(-1.000000, -1.000000, -1.000000, -1.000000)
add r12.xyz, r13.xyzw, r12.xyzw
dp3 r12.w, r12.xyzw, r12.xyzw
rsq r12.w, r12.wwww
mul r12.xyz, r12.xyzw, r12.wwww
add r10.w, r10.wwww, l(0.001000)
mul r12.xyz, r12.xyzw, r10.wwww
add r13.xyz, r13.xyzw, r12.xyzw
dp4 r14.x, cb0[10].xyzw, r13.xyzw
dp4 r14.y, cb0[11].xyzw, r13.xyzw
dp4 r14.z, cb0[12].xyzw, r13.xyzw
dp4 r14.w, cb0[13].xyzw, r13.xyzw
dp4 r6.x, cb1[0].xyzw, r7.xyzw
dp4 r6.y, cb1[1].xyzw, r7.xyzw
dp4 r6.z, cb1[2].xyzw, r7.xyzw
dp4 r6.w, cb1[3].xyzw, r7.xyzw
mov o7.xyzw, r6.xyzw
div r15.x, r6.xxxx, r6.wwww
div r15.y, r6.yyyy, r6.wwww
div r15.z, r14.xxxx, r14.wwww
div r15.w, r14.yyyy, r14.wwww
mad r15.x, r15.zzzz, l(-1.000000, 0.000000, 0.000000, 0.000000), r15.xxxx
mad r15.y, r15.wwww, l(-1.000000, 0.000000, 0.000000, 0.000000), r15.yyyy
mul r15.x, r15.xxxx, l(2.000000, 0.000000, 0.000000, 0.000000)
add r15.x, r15.xxxx, l(0.500000)
max r15.x, r15.xxxx, l(0.000000)
min r15.x, r15.xxxx, l(1.000000)
mul r15.y, r15.yyyy, l(2.000000, 0.000000, 0.000000, 0.000000)
add r15.y, r15.yyyy, l(0.500000)
max r15.y, r15.yyyy, l(0.000000)
min r15.y, r15.yyyy, l(1.000000)
mul r15.x, r15.xxxx, l(4096.000000, 0.000000, 0.000000, 0.000000)
mul r15.y, r15.yyyy, l(4096.000000, 0.000000, 0.000000, 0.000000)
round_z r15.x, r15.xxxx
round_z r15.y, r15.yyyy
max r15.x, r15.xxxx, l(0.000000)
min r15.x, r15.xxxx, l(4095.000000)
max r15.y, r15.yyyy, l(0.000000)
min r15.y, r15.yyyy, l(4095.000000)
mul r15.z, r15.xxxx, l(4096.000000, 0.000000, 0.000000, 0.000000)
add r15.z, r15.zzzz, r15.yyyy
mul r15.z, r15.zzzz, l(5.960464478E-08, 0.000000, 0.000000, 0.000000)
mov r15.w, l(1.000000)
mov o6.zw, r15.zzzw
ret
// Approximately 292 instruction slots used
