//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cb_scene
// {
//
//   float4x4 view_g;                   // Offset:    0 Size:    64
//   float4x4 viewInv_g;                // Offset:   64 Size:    64
//   float4x4 proj_g;                   // Offset:  128 Size:    64 [unused]
//   float4x4 projInv_g;                // Offset:  192 Size:    64 [unused]
//   float4x4 viewProj_g;               // Offset:  256 Size:    64 [unused]
//   float4x4 viewProjInv_g;            // Offset:  320 Size:    64 [unused]
//   float2 vpSize_g;                   // Offset:  384 Size:     8
//   float2 invVPSize_g;                // Offset:  392 Size:     8
//   float3 lightColor_g;               // Offset:  400 Size:    12
//   float ldotvXZ_g;                   // Offset:  412 Size:     4 [unused]
//   float3 lightDirection_g;           // Offset:  416 Size:    12
//   float shadowSplitDistance_g;       // Offset:  428 Size:     4
//   float4x4 shadowMtx_g[2];           // Offset:  432 Size:   128
//   float2 invShadowSize_g;            // Offset:  560 Size:     8
//   float shadowFadeNear_g;            // Offset:  568 Size:     4
//   float shadowFadeRangeInv_g;        // Offset:  572 Size:     4
//   float3 sceneShadowColor_g;         // Offset:  576 Size:    12
//   float gameTime_g;                  // Offset:  588 Size:     4 [unused]
//   float3 windDirection_g;            // Offset:  592 Size:    12 [unused]
//   uint collisionCount_g;             // Offset:  604 Size:     4 [unused]
//   float lightTileWidthInv_g;         // Offset:  608 Size:     4
//   float lightTileHeightInv_g;        // Offset:  612 Size:     4
//   float fogNearDistance_g;           // Offset:  616 Size:     4 [unused]
//   float fogFadeRangeInv_g;           // Offset:  620 Size:     4 [unused]
//   float3 fogColor_g;                 // Offset:  624 Size:    12
//   float fogIntensity_g;              // Offset:  636 Size:     4 [unused]
//   float fogHeight_g;                 // Offset:  640 Size:     4 [unused]
//   float fogHeightRangeInv_g;         // Offset:  644 Size:     4 [unused]
//   float windWaveTime_g;              // Offset:  648 Size:     4 [unused]
//   float windWaveFrequency_g;         // Offset:  652 Size:     4 [unused]
//   uint localLightProbeCount_g;       // Offset:  656 Size:     4 [unused]
//   float lightSpecularGlossiness_g;   // Offset:  660 Size:     4
//   float lightSpecularIntensity_g;    // Offset:  664 Size:     4
//   float lightTileDepthInv_g;         // Offset:  668 Size:     4
//   float4x4 ditherMtx_g;              // Offset:  672 Size:    64 [unused]
//   float4 lightProbe_g[9];            // Offset:  736 Size:   144
//   float4x4 farShadowMtx_g;           // Offset:  880 Size:    64 [unused]
//   float3 chrLightDir_g;              // Offset:  944 Size:    12 [unused]
//   float shadowDistance_g;            // Offset:  956 Size:     4
//   float resolutionScaling_g;         // Offset:  960 Size:     4 [unused]
//   float sceneTime_g;                 // Offset:  964 Size:     4 [unused]
//   float windForce_g;                 // Offset:  968 Size:     4 [unused]
//   float disableMapObjNearFade_g;     // Offset:  972 Size:     4
//   float4 mapColor_g;                 // Offset:  976 Size:    16
//   float4 clipPlane_g;                // Offset:  992 Size:    16 [unused]
//   float shadowZeroCascadeUVMult_g;   // Offset: 1008 Size:     4 [unused]
//   float prevSceneTime_g;             // Offset: 1012 Size:     4 [unused]
//   float prevWindWaveTime_g;          // Offset: 1016 Size:     4 [unused]
//   uint enableMotionVectors_g;        // Offset: 1020 Size:     4 [unused]
//   float4x4 prevView_g;               // Offset: 1024 Size:    64 [unused]
//   float4x4 prevViewInv_g;            // Offset: 1088 Size:    64 [unused]
//   float4x4 prevProj_g;               // Offset: 1152 Size:    64 [unused]
//   float4x4 prevProjInv_g;            // Offset: 1216 Size:    64 [unused]
//   float4x4 prevViewProj_g;           // Offset: 1280 Size:    64 [unused]
//   float4x4 prevViewProjInv_g;        // Offset: 1344 Size:    64 [unused]
//   float2 motionJitterOffset_g;       // Offset: 1408 Size:     8
//
// }
//
// cbuffer ConstantBuffer
// {
//
//   float3 incomingLight_g;            // Offset:    0 Size:    12 [unused]
//   float3 scatteringR_g;              // Offset:   16 Size:    12 [unused]
//   float3 scatteringM_g;              // Offset:   32 Size:    12 [unused]
//   float3 extinctionR_g;              // Offset:   48 Size:    12 [unused]
//   float3 extinctionM_g;              // Offset:   64 Size:    12 [unused]
//   float3 densityScaleHeight_g;       // Offset:   80 Size:    12 [unused]
//   float3 sunDirection_g;             // Offset:   96 Size:    12 [unused]
//   float mieG_g;                      // Offset:  112 Size:     4 [unused]
//   float distanceScale_g;             // Offset:  116 Size:     4 [unused]
//   float planetRadius_g;              // Offset:  120 Size:     4 [unused]
//   float atmosphereHeight_g;          // Offset:  124 Size:     4 [unused]
//   float sunIntensity_g;              // Offset:  128 Size:     4 [unused]
//   float volumeNearOverFarClip_g;     // Offset:  132 Size:     4
//   float volumeCameraFarClip_g;       // Offset:  136 Size:     4
//   float cloudCoverage_g;             // Offset:  144 Size:     4 [unused]
//   float cloudThickness_g;            // Offset:  148 Size:     4 [unused]
//   uint cloudRaySteps_g;              // Offset:  152 Size:     4 [unused]
//   float cloudLightIntensity_g;       // Offset:  156 Size:     4 [unused]
//   float cloudDistance_g;             // Offset:  160 Size:     4 [unused]
//   float cloudFadeRangeInv_g;         // Offset:  164 Size:     4 [unused]
//   float cloudHeight_g;               // Offset:  168 Size:     4 [unused]
//   float3 cloudColor_g;               // Offset:  176 Size:    12 [unused]
//
// }
//
// cbuffer cb_local
// {
//
//   float2 uvScroll0_g;                // Offset:    0 Size:     8 [unused]
//   float2 uvScroll1_g;                // Offset:    8 Size:     8 [unused]
//   float2 uvScroll2_g;                // Offset:   16 Size:     8 [unused]
//   float emissive_g;                  // Offset:   24 Size:     4
//   float materialFogIntensity_g;      // Offset:   28 Size:     4
//   float opacity_g;                   // Offset:   32 Size:     4 [unused]
//   float translucency_g;              // Offset:   36 Size:     4
//   float ssaoIntensity_g;             // Offset:   40 Size:     4
//   float3 shadowColor_g;              // Offset:   48 Size:    12
//   float glowShadowFadeRatio_g;       // Offset:   60 Size:     4 [unused]
//   float3 rimLightColor_g;            // Offset:   64 Size:    12
//   float rimLightPower_g;             // Offset:   76 Size:     4
//   float3 specularColor_g;            // Offset:   80 Size:    12
//   float specularShadowFadeRatio_g;   // Offset:   92 Size:     4
//   float rimIntensity_g;              // Offset:   96 Size:     4
//   float dynamicLightIntensity_g;     // Offset:  100 Size:     4
//   float fresnel0_g;                  // Offset:  104 Size:     4
//   float specularGlossiness0_g;       // Offset:  108 Size:     4
//   float metalness_g;                 // Offset:  112 Size:     4
//   float roughness_g;                 // Offset:  116 Size:     4
//   uint materialID_g;                 // Offset:  120 Size:     4 [unused]
//
// }
//
// Resource bind info for dynamicLights_g
// {
//
//   struct LightParam
//   {
//       
//       float3 pos;                    // Offset:    0
//       float radius;                  // Offset:   12
//       float3 color;                  // Offset:   16
//       float radiusInv;               // Offset:   28
//       float3 charaColor;             // Offset:   32
//       float attenuation;             // Offset:   44
//       float3 vec;                    // Offset:   48
//       float spotAngleInv;            // Offset:   60
//       float attenuationAngle;        // Offset:   64
//       float specularIntensity;       // Offset:   68
//       float specularGlossiness;      // Offset:   72
//       float scatterAnisotropy;       // Offset:   76
//       float3 scatterColor;           // Offset:   80
//       float scatterDensity;          // Offset:   92
//       float translucency;            // Offset:   96
//       int shadowmapIndex;            // Offset:  100
//       float userParams[2];           // Offset:  104
//
//   } $Element;                        // Offset:    0 Size:   112
//
// }
//
// Resource bind info for lightIndices_g
// {
//
//   struct LightIndexData
//   {
//       
//       int pointLightIndices[63];     // Offset:    0
//       uint pointLightCount;          // Offset:  252
//       int spotLightIndices[63];      // Offset:  256
//       uint spotLightCount;           // Offset:  508
//       int lightProbeIndices[15];     // Offset:  512
//       uint lightProbeCount;          // Offset:  572
//
//   } $Element;                        // Offset:    0 Size:   576
//
// }
//
// Resource bind info for spotShadowMatrices_g
// {
//
//   float4x4 $Element;                 // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Smpl0                             sampler      NA          NA             s0      1 
// Smpl6                             sampler      NA          NA             s6      1 
// SmplShadow                      sampler_c      NA          NA            s13      1 
// SmplCube                          sampler      NA          NA            s14      1 
// SmplLinearClamp                   sampler      NA          NA            s15      1 
// Tex0                              texture  float4          2d             t0      1 
// Tex6                              texture  float4          2d             t6      1 
// shadowMap                         texture  float4          2d            t16      1 
// texEnvMap_g                       texture  float4        cube            t17      1 
// dynamicLights_g                   texture  struct         r/o            t18      1 
// lightIndices_g                    texture  struct         r/o            t19      1 
// atmosphereInscatterLUT            texture  float4          3d            t22      1 
// atmosphereExtinctionLUT           texture  float4          3d            t23      1 
// spotShadowMaps                    texture  float4     2darray            t24      1 
// spotShadowMatrices_g              texture  struct         r/o            t25      1 
// cb_scene                          cbuffer      NA          NA            cb0      1 
// cb_local                          cbuffer      NA          NA            cb5      1 
// ConstantBuffer                    cbuffer      NA          NA            cb6      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// NORMAL                   0   xyzw        1     NONE   float   xyzw
// TANGENT                  0   xyzw        2     NONE   float      w
// BINORMAL                 0   xyzw        3     NONE   float       
// TEXCOORD                 0   xyzw        4     NONE   float   xy  
// TEXCOORD                 1   xyzw        5     NONE   float     zw
// TEXCOORD                 2   xyzw        6     NONE   float       
// TEXCOORD                 3   xyzw        7     NONE   float   xyzw
// TEXCOORD                 4   xyzw        8     NONE   float   xyzw
// TEXCOORD                 5   xyzw        9     NONE   float   xy w
// SV_IsFrontFace           0   x          10    FFACE    uint       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xy          2   TARGET   float   xy  
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_immediateConstantBuffer { { -0.840520, -0.073954, 0, 0},
                              { -0.326235, -0.405830, 0, 0},
                              { -0.698464, 0.457259, 0, 0},
                              { -0.203356, 0.620585, 0, 0},
                              { 0.963450, -0.194353, 0, 0},
                              { 0.473434, -0.480026, 0, 0},
                              { 0.519454, 0.767034, 0, 0},
                              { 0.185461, -0.894523, 0, 0},
                              { 0.507351, 0.064963, 0, 0},
                              { -0.321932, 0.595435, 0, 0} }
      0x000000B4: dcl_constantbuffer CB0[89], immediateIndexed
      0x000000C4: dcl_constantbuffer CB6[9], immediateIndexed
      0x000000D4: dcl_constantbuffer CB5[8], immediateIndexed
      0x000000E4: dcl_sampler s0, mode_default
      0x000000F0: dcl_sampler s6, mode_default
      0x000000FC: dcl_sampler s13, mode_comparison
      0x00000108: dcl_sampler s14, mode_default
      0x00000114: dcl_sampler s15, mode_default
      0x00000120: dcl_resource_texture2d (float,float,float,float) t0
      0x00000130: dcl_resource_texture2d (float,float,float,float) t6
      0x00000140: dcl_resource_texture2d (float,float,float,float) t16
      0x00000150: dcl_resource_texturecube (float,float,float,float) t17
      0x00000160: dcl_resource_structured t18, 112
      0x00000170: dcl_resource_structured t19, 576
      0x00000180: dcl_resource_texture3d (float,float,float,float) t22
      0x00000190: dcl_resource_texture3d (float,float,float,float) t23
      0x000001A0: dcl_resource_texture2darray (float,float,float,float) t24
      0x000001B0: dcl_resource_structured t25, 64
      0x000001C0: dcl_input_ps_siv linear noperspective v0.xy, position
      0x000001D0: dcl_input_ps linear v1.xyzw
      0x000001DC: dcl_input_ps linear v2.w
      0x000001E8: dcl_input_ps linear v4.xy
      0x000001F4: dcl_input_ps linear v5.zw
      0x00000200: dcl_input_ps linear centroid v7.xyzw
      0x0000020C: dcl_input_ps linear v8.xyzw
      0x00000218: dcl_input_ps linear v9.xyw
      0x00000224: dcl_output o0.xyzw
      0x00000230: dcl_output o1.xyzw
      0x0000023C: dcl_output o2.xy
      0x00000248: dcl_temps 15
   0  0x00000250: div r0.xy, v9.xyxx, v9.wwww
   1  0x0000026C: mad r0.xy, r0.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
   2  0x000002A8: mad r0.xy, r0.xyxx, cb0[24].xyxx, -v0.xyxx
   3  0x000002D4: add o2.xy, r0.xyxx, -cb0[88].xyxx
   4  0x000002F8: add r0.x, -v8.x, cb0[4].w
   5  0x0000031C: add r0.y, -v8.y, cb0[5].w
   6  0x00000340: add r0.z, -v8.z, cb0[6].w
   7  0x00000364: dp3 r0.w, r0.xyzx, r0.xyzx
   8  0x00000380: sqrt r1.x, r0.w
   9  0x00000394: rsq r0.w, r0.w
  10  0x000003A8: mul r1.yzw, r0.wwww, r0.xxyz
  11  0x000003C4: add r1.x, r1.x, -v1.w
  12  0x000003E4: mul r1.x, r1.x, v2.w
  13  0x00000400: min r1.x, r1.x, l(1.000000)
  14  0x0000041C: max r1.x, r1.x, cb0[60].w
  15  0x0000043C: dp3 r2.x, v1.xyzx, v1.xyzx
  16  0x00000458: rsq r2.x, r2.x
  17  0x0000046C: mul r2.xyz, r2.xxxx, v1.xyzx
  18  0x00000488: mad r3.xy, v4.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.000000, 1.000000, 0.000000, 0.000000)
  19  0x000004C4: sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r3.xyxx, t0.xyzw, s0
  20  0x000004F0: sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r3.xyxx, t6.xyzw, s6
  21  0x0000051C: mul r4.xyzw, r4.xyzw, v7.xyzw
  22  0x00000538: mul r2.w, r3.w, cb5[1].z
  23  0x00000558: dp4 r3.w, cb0[2].xyzw, v8.xyzw
  24  0x00000578: mad r5.xyz, cb0[47].xyzx, r2.xxxx, cb0[46].xyzx
  25  0x000005A4: mad r5.xyz, cb0[48].xyzx, r2.yyyy, r5.xyzx
  26  0x000005CC: mad r5.xyz, cb0[49].xyzx, r2.zzzz, r5.xyzx
  27  0x000005F4: mul r6.xyz, r2.zzzz, cb0[50].xyzx
  28  0x00000614: mad r5.xyz, r6.xyzx, r2.xxxx, r5.xyzx
  29  0x00000638: mul r6.xyz, r2.yyyy, cb0[51].xyzx
  30  0x00000658: mad r5.xyz, r6.xyzx, r2.zzzz, r5.xyzx
  31  0x0000067C: mul r6.xyz, r2.yyyy, cb0[52].xyzx
  32  0x0000069C: mad r5.xyz, r6.xyzx, r2.xxxx, r5.xyzx
  33  0x000006C0: mul r6.xy, r2.zyzz, r2.zyzz
  34  0x000006DC: mad r5.w, r6.x, l(3.000000), l(-1.000000)
  35  0x00000700: mad r5.xyz, cb0[53].xyzx, r5.wwww, r5.xyzx
  36  0x00000728: mad r5.w, r2.x, r2.x, -r6.y
  37  0x00000750: mad r5.xyz, cb0[54].xyzx, r5.wwww, r5.xyzx
  38  0x00000778: add r6.xyz, cb5[3].xyzx, cb0[36].xyzx
  39  0x0000079C: min r6.xyz, r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  40  0x000007C4: dp3 r5.w, r2.xyzx, -cb0[26].xyzx
  41  0x000007E8: dp3 r6.w, r2.xyzx, r1.yzwy
  42  0x00000804: ge r7.x, cb0[59].w, -r3.w
  43  0x00000828: if_nz r7.x
  44  0x00000834:   lt r7.x, -r3.w, cb0[26].w
  45  0x00000858:   movc r8.xyzw, r7.xxxx, cb0[27].xyzw, cb0[31].xyzw
  46  0x00000884:   movc r9.xyzw, r7.xxxx, cb0[28].xyzw, cb0[32].xyzw
  47  0x000008B0:   movc r10.xyzw, r7.xxxx, cb0[29].xyzw, cb0[33].xyzw
  48  0x000008DC:   movc r7.xyzw, r7.xxxx, cb0[30].xyzw, cb0[34].xyzw
  49  0x00000908:   dp4 r8.x, v8.xyzw, r8.xyzw
  50  0x00000924:   dp4 r8.y, v8.xyzw, r9.xyzw
  51  0x00000940:   dp4 r8.z, v8.xyzw, r10.xyzw
  52  0x0000095C:   dp4 r7.x, v8.xyzw, r7.xyzw
  53  0x00000978:   div r7.xyz, r8.xyzx, r7.xxxx
  54  0x00000994:   mov r7.w, l(0)
  55  0x000009A8:   mov r8.x, l(0)
  56  0x000009BC:   loop 
  57  0x000009C0:     ige r8.y, r8.x, l(10)
  58  0x000009DC:     breakc_nz r8.y
  59  0x000009E8:     mul r8.yz, cb0[35].xxyx, icb[r8.x + 0].xxyx
  60  0x00000A0C:     mad_sat r8.yz, r8.yyzy, l(0.000000, 1.500000, 1.500000, 0.000000), r7.xxyx
  61  0x00000A3C:     sample_c_lz_indexable(texture2d)(float,float,float,float) r8.y, r8.yzyy, t16.xxxx, s13, r7.z
  62  0x00000A70:     mad r7.w, r8.y, l(0.100000), r7.w
  63  0x00000A94:     iadd r8.x, r8.x, l(1)
  64  0x00000AB0:   endloop 
  65  0x00000AB4:   add r7.x, -r3.w, -cb0[35].z
  66  0x00000ADC:   mul_sat r7.x, r7.x, cb0[35].w
  67  0x00000AFC:   add r7.y, -r7.w, l(1.000000)
  68  0x00000B1C:   mad r7.x, r7.x, r7.y, r7.w
  69  0x00000B40: else 
  70  0x00000B44:   mov r7.x, l(1.000000)
  71  0x00000B58: endif 
  72  0x00000B5C: add r7.y, r7.x, l(-1.000000)
  73  0x00000B78: mad r7.y, cb5[5].w, r7.y, l(1.000000)
  74  0x00000BA0: add r7.z, -r5.w, l(1.000000)
  75  0x00000BC0: mad r7.z, cb5[2].y, r7.z, r5.w
  76  0x00000BE8: mad r7.z, r7.z, l(0.500000), l(0.500000)
  77  0x00000C0C: mul r7.w, r7.z, r7.z
  78  0x00000C28: mad r7.z, -r7.z, r7.w, l(1.000000)
  79  0x00000C50: mad r7.x, r7.z, r7.z, r7.x
  80  0x00000C74: min r7.x, r7.x, l(1.000000)
  81  0x00000C90: mad r8.xyz, r0.xyzx, r0.wwww, -cb0[26].xyzx
  82  0x00000CBC: dp3 r7.z, r8.xyzx, r8.xyzx
  83  0x00000CD8: rsq r7.z, r7.z
  84  0x00000CEC: mul r8.xyz, r7.zzzz, r8.xyzx
  85  0x00000D08: mul r7.z, cb5[6].w, cb0[41].y
  86  0x00000D2C: dp3_sat r7.w, r8.xyzx, r2.xyzx
  87  0x00000D48: max r7.z, r7.z, l(0.001000)
  88  0x00000D64: log r7.w, r7.w
  89  0x00000D78: mul r7.z, r7.w, r7.z
  90  0x00000D94: exp r7.z, r7.z
  91  0x00000DA8: mul r7.y, r7.y, r7.z
  92  0x00000DC4: mul r7.y, r7.y, cb0[41].z
  93  0x00000DE4: mul r7.yzw, r7.yyyy, cb5[5].xxyz
  94  0x00000E04: mad r8.xy, r5.wwww, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
  95  0x00000E40: max r5.w, r8.y, r8.x
  96  0x00000E5C: add r5.w, -r8.x, r5.w
  97  0x00000E7C: mad r5.w, cb5[2].y, r5.w, r8.x
  98  0x00000EA4: mul r8.xy, r3.xyxx, cb5[7].xyxx
  99  0x00000EC4: add r3.x, r6.w, r6.w
 100  0x00000EE0: mad r1.yzw, r2.xxyz, -r3.xxxx, r1.yyzw
 101  0x00000F08: resinfo_indexable(texturecube)(float,float,float,float)_uint r3.x, l(0), t17.wxyz
 102  0x00000F2C: mul r1.yzw, r1.yyzw, l(0.000000, 1.000000, -1.000000, -1.000000)
 103  0x00000F54: iadd r3.x, r3.x, l(-1)
 104  0x00000F70: utof r3.x, r3.x
 105  0x00000F84: mul r3.x, r3.x, r8.y
 106  0x00000FA0: sample_l_indexable(texturecube)(float,float,float,float) r1.yzw, r1.yzwy, t17.wxyz, s14, r3.x
 107  0x00000FD4: lt r3.x, l(0.000000), cb5[6].z
 108  0x00000FF4: add r6.w, -|r6.w|, l(1.000000)
 109  0x00001014: max r6.w, r6.w, l(0.000000)
 110  0x00001030: log r8.z, r6.w
 111  0x00001044: mul r8.z, r8.z, cb5[6].z
 112  0x00001064: exp r8.z, r8.z
 113  0x00001078: movc r3.x, r3.x, r8.z, l(1.000000)
 114  0x0000109C: mul r8.z, r3.x, r8.x
 115  0x000010B8: mad r9.xyz, r4.xyzx, r1.yzwy, -r4.xyzx
 116  0x000010E0: mad r4.xyz, r8.zzzz, r9.xyzx, r4.xyzx
 117  0x00001104: dp3 r8.z, r1.yzwy, l(0.299000, 0.587000, 0.114000, 0.000000)
 118  0x0000112C: mad r8.y, r8.y, l(-9.000000), l(10.000000)
 119  0x00001150: log r8.z, r8.z
 120  0x00001164: mul r8.y, r8.z, r8.y
 121  0x00001180: exp r8.y, r8.y
 122  0x00001194: add r8.z, -r8.y, l(1.000000)
 123  0x000011B4: mad r8.x, r8.x, r8.z, r8.y
 124  0x000011D8: mul r1.yzw, r1.yyzw, r5.wwww
 125  0x000011F4: mul r1.yzw, r8.xxxx, r1.yyzw
 126  0x00001210: mul r1.yzw, r3.xxxx, r1.yyzw
 127  0x0000122C: mad r3.y, -r3.y, cb5[7].y, l(1.000000)
 128  0x00001258: mul r1.yzw, r1.yyzw, r3.yyyy
 129  0x00001274: mad r1.yzw, r7.yyzw, cb0[25].xxyz, r1.yyzw
 130  0x0000129C: mul r3.y, r7.x, r5.w
 131  0x000012B8: add r7.xyz, -r6.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 132  0x000012E4: mad r6.xyz, r3.yyyy, r7.xyzx, r6.xyzx
 133  0x00001308: mad r5.xyz, r6.xyzx, cb0[25].xyzx, r5.xyzx
 134  0x00001330: min r3.y, r2.w, l(1.000000)
 135  0x0000134C: add r6.xyz, -r5.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 136  0x00001378: mad r5.xyz, r3.yyyy, r6.xyzx, r5.xyzx
 137  0x0000139C: mul r3.y, r6.w, cb5[6].x
 138  0x000013BC: log r3.y, r3.y
 139  0x000013D0: mul r3.y, r3.y, cb5[4].w
 140  0x000013F0: exp r3.y, r3.y
 141  0x00001404: min r3.y, r3.y, l(1.000000)
 142  0x00001420: mad r1.yzw, cb5[4].xxyz, r3.yyyy, r1.yyzw
 143  0x00001448: mul r6.xy, v0.xyxx, cb0[38].xyxx
 144  0x00001468: mul r3.y, -r3.w, cb0[41].w
 145  0x0000148C: min r3.y, r3.y, l(7.000000)
 146  0x000014A8: max r3.y, r3.y, l(0.000000)
 147  0x000014C4: ftou r6.xy, r6.xyxx
 148  0x000014D8: ftou r3.y, r3.y
 149  0x000014EC: ishl r5.w, r6.y, l(5)
 150  0x00001508: imad r3.y, r3.y, l(576), r5.w
 151  0x0000152C: iadd r3.y, r6.x, r3.y
 152  0x00001548: umin r3.y, r3.y, l(4607)
 153  0x00001564: ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r5.w, r3.y, l(252), t19.xxxx
 154  0x00001590: umin r5.w, r5.w, l(63)
 155  0x000015AC: mov r7.xyz, l(0,0,0,0)
 156  0x000015CC: mov r6.xyzw, l(0,0,0,0)
 157  0x000015EC: loop 
 158  0x000015F0:   uge r7.w, r6.w, r5.w
 159  0x0000160C:   breakc_nz r7.w
 160  0x00001618:   ishl r7.w, r6.w, l(2)
 161  0x00001634:   ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r7.w, r3.y, r7.w, t19.xxxx
 162  0x00001660:   ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r8.xyz, r7.w, l(0), t18.xyzx
 163  0x0000168C:   add r8.xyz, r8.xyzx, -v8.xyzx
 164  0x000016AC:   dp3 r8.w, r8.xyzx, r8.xyzx
 165  0x000016C8:   sqrt r9.x, r8.w
 166  0x000016DC:   ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r9.y, r7.w, l(28), t18.xxxx
 167  0x00001708:   mul r9.x, r9.y, r9.x
 168  0x00001724:   ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r9.y, r7.w, l(44), t18.xxxx
 169  0x00001750:   log r9.x, |r9.x|
 170  0x00001768:   mul r9.x, r9.x, r9.y
 171  0x00001784:   exp r9.x, r9.x
 172  0x00001798:   add r9.x, -r9.x, l(1.000000)
 173  0x000017B8:   max r9.x, r9.x, l(0.000000)
 174  0x000017D4:   lt r9.y, l(0.000000), r9.x
 175  0x000017F0:   if_nz r9.y
 176  0x000017FC:     rsq r8.w, r8.w
 177  0x00001810:     mul r8.xyz, r8.wwww, r8.xyzx
 178  0x0000182C:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r8.w, r7.w, l(96), t18.xxxx
 179  0x00001858:     dp3 r9.y, r8.xyzx, r2.xyzx
 180  0x00001874:     max r8.w, r8.w, r9.y
 181  0x00001890:     mul r8.w, r8.w, r9.x
 182  0x000018AC:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r9.xyz, r7.w, l(16), t18.xyzx
 183  0x000018D8:     mad r7.xyz, r9.xyzx, r8.wwww, r7.xyzx
 184  0x000018FC:     mad r8.xyz, r0.xyzx, r0.wwww, r8.xyzx
 185  0x00001920:     dp3 r9.w, r8.xyzx, r8.xyzx
 186  0x0000193C:     rsq r9.w, r9.w
 187  0x00001950:     mul r8.xyz, r8.xyzx, r9.wwww
 188  0x0000196C:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r10.xy, r7.w, l(68), t18.xyxx
 189  0x00001998:     mul r7.w, r10.y, cb5[6].w
 190  0x000019B8:     dp3_sat r8.x, r8.xyzx, r2.xyzx
 191  0x000019D4:     max r7.w, r7.w, l(0.001000)
 192  0x000019F0:     log r8.x, r8.x
 193  0x00001A04:     mul r7.w, r7.w, r8.x
 194  0x00001A20:     exp r7.w, r7.w
 195  0x00001A34:     mul r8.xyz, r7.wwww, r9.xyzx
 196  0x00001A50:     mul r8.xyz, r8.wwww, r8.xyzx
 197  0x00001A6C:     mad r6.xyz, r8.xyzx, r10.xxxx, r6.xyzx
 198  0x00001A90:   endif 
 199  0x00001A94:   iadd r6.w, r6.w, l(1)
 200  0x00001AB0: endloop 
 201  0x00001AB4: mad r5.xyz, r7.xyzx, cb5[6].yyyy, r5.xyzx
 202  0x00001ADC: ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r5.w, r3.y, l(508), t19.xxxx
 203  0x00001B08: umin r5.w, r5.w, l(63)
 204  0x00001B24: mov r7.xyz, r6.xyzx
 205  0x00001B38: mov r8.xyz, l(0,0,0,0)
 206  0x00001B58: mov r6.w, l(0)
 207  0x00001B6C: loop 
 208  0x00001B70:   uge r7.w, r6.w, r5.w
 209  0x00001B8C:   breakc_nz r7.w
 210  0x00001B98:   ishl r7.w, r6.w, l(2)
 211  0x00001BB4:   iadd r7.w, r7.w, l(256)
 212  0x00001BD0:   ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r7.w, r3.y, r7.w, t19.xxxx
 213  0x00001BFC:   ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r9.xyz, r7.w, l(0), t18.xyzx
 214  0x00001C28:   add r9.xyz, r9.xyzx, -v8.xyzx
 215  0x00001C48:   dp3 r8.w, r9.xyzx, r9.xyzx
 216  0x00001C64:   rsq r9.w, r8.w
 217  0x00001C78:   mul r9.xyz, r9.wwww, r9.xyzx
 218  0x00001C94:   ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r10.xyzw, r7.w, l(48), t18.xyzw
 219  0x00001CC0:   dp3 r9.w, r9.xyzx, r10.xyzx
 220  0x00001CDC:   max r9.w, r9.w, l(0.000000)
 221  0x00001CF8:   add r9.w, -r9.w, l(1.000000)
 222  0x00001D18:   mul r9.w, r10.w, r9.w
 223  0x00001D34:   ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r10.x, r7.w, l(64), t18.xxxx
 224  0x00001D60:   log r9.w, r9.w
 225  0x00001D74:   mul r9.w, r9.w, r10.x
 226  0x00001D90:   exp r9.w, r9.w
 227  0x00001DA4:   add r9.w, -r9.w, l(1.000000)
 228  0x00001DC4:   max r9.w, r9.w, l(0.000000)
 229  0x00001DE0:   lt r10.x, l(0.000000), r9.w
 230  0x00001DFC:   if_nz r10.x
 231  0x00001E08:     sqrt r8.w, r8.w
 232  0x00001E1C:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r10.x, r7.w, l(28), t18.xxxx
 233  0x00001E48:     mul r8.w, r8.w, r10.x
 234  0x00001E64:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r10.x, r7.w, l(44), t18.xxxx
 235  0x00001E90:     log r8.w, |r8.w|
 236  0x00001EA8:     mul r8.w, r8.w, r10.x
 237  0x00001EC4:     exp r8.w, r8.w
 238  0x00001ED8:     add r8.w, -r8.w, l(1.000000)
 239  0x00001EF8:     max r8.w, r8.w, l(0.000000)
 240  0x00001F14:     mul r8.w, r8.w, r9.w
 241  0x00001F30:     lt r9.w, l(0.000000), r8.w
 242  0x00001F4C:     if_nz r9.w
 243  0x00001F58:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r10.xy, r7.w, l(96), t18.xyxx
 244  0x00001F84:       ine r9.w, r10.y, l(-1)
 245  0x00001FA0:       if_nz r9.w
 246  0x00001FAC:         ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r11.xyzw, r10.y, l(0), t25.xyzw
 247  0x00001FD8:         ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r12.xyzw, r10.y, l(16), t25.xyzw
 248  0x00002004:         ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r13.xyzw, r10.y, l(32), t25.xyzw
 249  0x00002030:         ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r14.xyzw, r10.y, l(48), t25.xyzw
 250  0x0000205C:         dp4 r11.x, v8.xyzw, r11.xyzw
 251  0x00002078:         dp4 r11.y, v8.xyzw, r12.xyzw
 252  0x00002094:         dp4 r11.z, v8.xyzw, r13.xyzw
 253  0x000020B0:         dp4 r9.w, v8.xyzw, r14.xyzw
 254  0x000020CC:         div r11.xyz, r11.xyzx, r9.wwww
 255  0x000020E8:         itof r11.w, r10.y
 256  0x000020FC:         sample_c_lz_indexable(texture2darray)(float,float,float,float) r9.w, r11.xywx, t24.xxxx, s13, r11.z
 257  0x00002130:         mul r8.w, r8.w, r9.w
 258  0x0000214C:       endif 
 259  0x00002150:       dp3 r9.w, r9.xyzx, r2.xyzx
 260  0x0000216C:       max r9.w, r9.w, r10.x
 261  0x00002188:       mul r8.w, r8.w, r9.w
 262  0x000021A4:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r10.xyz, r7.w, l(16), t18.xyzx
 263  0x000021D0:       mad r8.xyz, r10.xyzx, r8.wwww, r8.xyzx
 264  0x000021F4:       mad r9.xyz, r0.xyzx, r0.wwww, r9.xyzx
 265  0x00002218:       dp3 r9.w, r9.xyzx, r9.xyzx
 266  0x00002234:       rsq r9.w, r9.w
 267  0x00002248:       mul r9.xyz, r9.wwww, r9.xyzx
 268  0x00002264:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r11.xy, r7.w, l(68), t18.xyxx
 269  0x00002290:       mul r7.w, r11.y, cb5[6].w
 270  0x000022B0:       dp3_sat r9.x, r9.xyzx, r2.xyzx
 271  0x000022CC:       max r7.w, r7.w, l(0.001000)
 272  0x000022E8:       log r9.x, r9.x
 273  0x000022FC:       mul r7.w, r7.w, r9.x
 274  0x00002318:       exp r7.w, r7.w
 275  0x0000232C:       mul r9.xyz, r7.wwww, r10.xyzx
 276  0x00002348:       mul r9.xyz, r8.wwww, r9.xyzx
 277  0x00002364:       mad r7.xyz, r9.xyzx, r11.xxxx, r7.xyzx
 278  0x00002388:     endif 
 279  0x0000238C:   endif 
 280  0x00002390:   iadd r6.w, r6.w, l(1)
 281  0x000023AC: endloop 
 282  0x000023B0: mad r0.xyz, r8.xyzx, cb5[6].yyyy, r5.xyzx
 283  0x000023D8: mad r1.yzw, r7.xxyz, cb5[6].yyyy, r1.yyzw
 284  0x00002400: mul r5.xyz, r3.zzzz, r1.yzwy
 285  0x0000241C: mad r0.xyz, r4.xyzx, r0.xyzx, r5.xyzx
 286  0x00002440: dp3 r0.w, r1.yzwy, l(0.299000, 0.587000, 0.114000, 0.000000)
 287  0x00002468: min r0.w, r0.w, l(1.000000)
 288  0x00002484: mul r1.y, r3.x, r4.w
 289  0x000024A0: mad r1.z, -r4.w, r3.x, v5.w
 290  0x000024C8: mad r0.w, r0.w, r1.z, r1.y
 291  0x000024EC: max r1.y, r2.w, l(1.000000)
 292  0x00002508: mul r3.xyz, r0.xyzx, r1.yyyy
 293  0x00002524: mul r0.w, r1.x, r0.w
 294  0x00002540: mul r1.x, v5.z, cb5[1].w
 295  0x00002560: mad r0.xyz, -r0.xyzx, r1.yyyy, cb0[39].xyzx
 296  0x0000258C: mad r0.xyz, r1.xxxx, r0.xyzx, r3.xyzx
 297  0x000025B0: div r1.x, -r3.w, cb6[8].z
 298  0x000025D4: mul r3.xy, v0.xyxx, cb0[24].zwzz
 299  0x000025F4: add r1.x, r1.x, -cb6[8].y
 300  0x00002618: add r1.y, l(1.000000), -cb6[8].y
 301  0x0000263C: div r3.z, r1.x, r1.y
 302  0x00002658: sample_l_indexable(texture3d)(float,float,float,float) r1.xyz, r3.xyzx, t22.xyzw, s15, l(0.000000)
 303  0x0000268C: sample_l_indexable(texture3d)(float,float,float,float) r3.xyz, r3.xyzx, t23.xyzw, s15, l(0.000000)
 304  0x000026C0: add r1.xyz, r1.xyzx, r3.xyzx
 305  0x000026DC: mul r0.xyz, r0.xyzx, r1.xyzx
 306  0x000026F8: mul o0.xyz, r0.xyzx, cb0[61].xyzx
 307  0x00002718: add r0.x, -v5.z, l(1.000000)
 308  0x00002738: mul r0.x, r0.x, cb5[2].z
 309  0x00002758: mul r0.x, r0.w, r0.x
 310  0x00002774: mad r1.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
 311  0x000027B0: mov_sat r1.xy, r1.xyxx
 312  0x000027C4: mul r0.yz, r1.xxyx, l(0.000000, 65535.000000, 65535.000000, 0.000000)
 313  0x000027EC: ftou r0.yz, r0.yyzy
 314  0x00002800: imad o1.x, r0.z, l(0x00010000), r0.y
 315  0x00002824: mul r0.y, r1.z, l(65535.000000)
 316  0x00002840: ftou o1.y, r0.y
 317  0x00002854: mul r0.x, r0.x, l(255.000000)
 318  0x00002870: ftou r0.x, r0.x
 319  0x00002884: ishl r0.yz, r0.xxxx, l(0, 8, 16, 0)
 320  0x000028AC: or r0.x, r0.y, r0.x
 321  0x000028C8: or o1.z, r0.z, r0.x
 322  0x000028E4: mov o0.w, r0.w
 323  0x000028F8: mov o1.w, l(0)
 324  0x0000290C: ret 
// Approximately 325 instruction slots used
