//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cb_scene
// {
//
//   float4x4 view_g;                   // Offset:    0 Size:    64
//   float4x4 viewInv_g;                // Offset:   64 Size:    64
//   float4x4 proj_g;                   // Offset:  128 Size:    64 [unused]
//   float4x4 projInv_g;                // Offset:  192 Size:    64 [unused]
//   float4x4 viewProj_g;               // Offset:  256 Size:    64 [unused]
//   float4x4 viewProjInv_g;            // Offset:  320 Size:    64 [unused]
//   float2 vpSize_g;                   // Offset:  384 Size:     8
//   float2 invVPSize_g;                // Offset:  392 Size:     8
//   float3 lightColor_g;               // Offset:  400 Size:    12
//   float ldotvXZ_g;                   // Offset:  412 Size:     4 [unused]
//   float3 lightDirection_g;           // Offset:  416 Size:    12
//   float shadowSplitDistance_g;       // Offset:  428 Size:     4
//   float4x4 shadowMtx_g[2];           // Offset:  432 Size:   128
//   float2 invShadowSize_g;            // Offset:  560 Size:     8
//   float shadowFadeNear_g;            // Offset:  568 Size:     4
//   float shadowFadeRangeInv_g;        // Offset:  572 Size:     4
//   float3 sceneShadowColor_g;         // Offset:  576 Size:    12
//   float gameTime_g;                  // Offset:  588 Size:     4 [unused]
//   float3 windDirection_g;            // Offset:  592 Size:    12 [unused]
//   uint collisionCount_g;             // Offset:  604 Size:     4 [unused]
//   float lightTileWidthInv_g;         // Offset:  608 Size:     4
//   float lightTileHeightInv_g;        // Offset:  612 Size:     4
//   float fogNearDistance_g;           // Offset:  616 Size:     4 [unused]
//   float fogFadeRangeInv_g;           // Offset:  620 Size:     4 [unused]
//   float3 fogColor_g;                 // Offset:  624 Size:    12
//   float fogIntensity_g;              // Offset:  636 Size:     4 [unused]
//   float fogHeight_g;                 // Offset:  640 Size:     4 [unused]
//   float fogHeightRangeInv_g;         // Offset:  644 Size:     4 [unused]
//   float windWaveTime_g;              // Offset:  648 Size:     4 [unused]
//   float windWaveFrequency_g;         // Offset:  652 Size:     4 [unused]
//   uint localLightProbeCount_g;       // Offset:  656 Size:     4 [unused]
//   float lightSpecularGlossiness_g;   // Offset:  660 Size:     4
//   float lightSpecularIntensity_g;    // Offset:  664 Size:     4
//   float lightTileDepthInv_g;         // Offset:  668 Size:     4
//   float4x4 ditherMtx_g;              // Offset:  672 Size:    64 [unused]
//   float4 lightProbe_g[9];            // Offset:  736 Size:   144
//   float4x4 farShadowMtx_g;           // Offset:  880 Size:    64 [unused]
//   float3 chrLightDir_g;              // Offset:  944 Size:    12 [unused]
//   float shadowDistance_g;            // Offset:  956 Size:     4
//   float resolutionScaling_g;         // Offset:  960 Size:     4 [unused]
//   float sceneTime_g;                 // Offset:  964 Size:     4 [unused]
//   float windForce_g;                 // Offset:  968 Size:     4 [unused]
//   float disableMapObjNearFade_g;     // Offset:  972 Size:     4
//   float4 mapColor_g;                 // Offset:  976 Size:    16
//   float4 clipPlane_g;                // Offset:  992 Size:    16
//   float shadowZeroCascadeUVMult_g;   // Offset: 1008 Size:     4 [unused]
//   float prevSceneTime_g;             // Offset: 1012 Size:     4 [unused]
//   float prevWindWaveTime_g;          // Offset: 1016 Size:     4 [unused]
//   uint enableMotionVectors_g;        // Offset: 1020 Size:     4 [unused]
//   float4x4 prevView_g;               // Offset: 1024 Size:    64 [unused]
//   float4x4 prevViewInv_g;            // Offset: 1088 Size:    64 [unused]
//   float4x4 prevProj_g;               // Offset: 1152 Size:    64 [unused]
//   float4x4 prevProjInv_g;            // Offset: 1216 Size:    64 [unused]
//   float4x4 prevViewProj_g;           // Offset: 1280 Size:    64 [unused]
//   float4x4 prevViewProjInv_g;        // Offset: 1344 Size:    64 [unused]
//   float2 motionJitterOffset_g;       // Offset: 1408 Size:     8
//
// }
//
// cbuffer ConstantBuffer
// {
//
//   float3 incomingLight_g;            // Offset:    0 Size:    12 [unused]
//   float3 scatteringR_g;              // Offset:   16 Size:    12 [unused]
//   float3 scatteringM_g;              // Offset:   32 Size:    12 [unused]
//   float3 extinctionR_g;              // Offset:   48 Size:    12 [unused]
//   float3 extinctionM_g;              // Offset:   64 Size:    12 [unused]
//   float3 densityScaleHeight_g;       // Offset:   80 Size:    12 [unused]
//   float3 sunDirection_g;             // Offset:   96 Size:    12 [unused]
//   float mieG_g;                      // Offset:  112 Size:     4 [unused]
//   float distanceScale_g;             // Offset:  116 Size:     4 [unused]
//   float planetRadius_g;              // Offset:  120 Size:     4 [unused]
//   float atmosphereHeight_g;          // Offset:  124 Size:     4 [unused]
//   float sunIntensity_g;              // Offset:  128 Size:     4 [unused]
//   float volumeNearOverFarClip_g;     // Offset:  132 Size:     4
//   float volumeCameraFarClip_g;       // Offset:  136 Size:     4
//   float cloudCoverage_g;             // Offset:  144 Size:     4 [unused]
//   float cloudThickness_g;            // Offset:  148 Size:     4 [unused]
//   uint cloudRaySteps_g;              // Offset:  152 Size:     4 [unused]
//   float cloudLightIntensity_g;       // Offset:  156 Size:     4 [unused]
//   float cloudDistance_g;             // Offset:  160 Size:     4 [unused]
//   float cloudFadeRangeInv_g;         // Offset:  164 Size:     4 [unused]
//   float cloudHeight_g;               // Offset:  168 Size:     4 [unused]
//   float3 cloudColor_g;               // Offset:  176 Size:    12 [unused]
//
// }
//
// cbuffer cb_local
// {
//
//   float2 uvScroll0_g;                // Offset:    0 Size:     8 [unused]
//   float2 uvScroll1_g;                // Offset:    8 Size:     8 [unused]
//   float2 uvScroll2_g;                // Offset:   16 Size:     8 [unused]
//   float emissive_g;                  // Offset:   24 Size:     4
//   float materialFogIntensity_g;      // Offset:   28 Size:     4
//   float opacity_g;                   // Offset:   32 Size:     4 [unused]
//   float translucency_g;              // Offset:   36 Size:     4
//   float ssaoIntensity_g;             // Offset:   40 Size:     4
//   float3 shadowColor_g;              // Offset:   48 Size:    12
//   float glowShadowFadeRatio_g;       // Offset:   60 Size:     4 [unused]
//   float3 rimLightColor_g;            // Offset:   64 Size:    12
//   float rimLightPower_g;             // Offset:   76 Size:     4
//   float3 specularColor_g;            // Offset:   80 Size:    12
//   float specularShadowFadeRatio_g;   // Offset:   92 Size:     4
//   float rimIntensity_g;              // Offset:   96 Size:     4
//   float dynamicLightIntensity_g;     // Offset:  100 Size:     4
//   float fresnel0_g;                  // Offset:  104 Size:     4
//   float specularGlossiness0_g;       // Offset:  108 Size:     4
//   float metalness_g;                 // Offset:  112 Size:     4
//   float roughness_g;                 // Offset:  116 Size:     4
//   uint materialID_g;                 // Offset:  120 Size:     4 [unused]
//
// }
//
// Resource bind info for dynamicLights_g
// {
//
//   struct LightParam
//   {
//       
//       float3 pos;                    // Offset:    0
//       float radius;                  // Offset:   12
//       float3 color;                  // Offset:   16
//       float radiusInv;               // Offset:   28
//       float3 charaColor;             // Offset:   32
//       float attenuation;             // Offset:   44
//       float3 vec;                    // Offset:   48
//       float spotAngleInv;            // Offset:   60
//       float attenuationAngle;        // Offset:   64
//       float specularIntensity;       // Offset:   68
//       float specularGlossiness;      // Offset:   72
//       float scatterAnisotropy;       // Offset:   76
//       float3 scatterColor;           // Offset:   80
//       float scatterDensity;          // Offset:   92
//       float translucency;            // Offset:   96
//       int shadowmapIndex;            // Offset:  100
//       float userParams[2];           // Offset:  104
//
//   } $Element;                        // Offset:    0 Size:   112
//
// }
//
// Resource bind info for lightIndices_g
// {
//
//   struct LightIndexData
//   {
//       
//       int pointLightIndices[63];     // Offset:    0
//       uint pointLightCount;          // Offset:  252
//       int spotLightIndices[63];      // Offset:  256
//       uint spotLightCount;           // Offset:  508
//       int lightProbeIndices[15];     // Offset:  512
//       uint lightProbeCount;          // Offset:  572
//
//   } $Element;                        // Offset:    0 Size:   576
//
// }
//
// Resource bind info for spotShadowMatrices_g
// {
//
//   float4x4 $Element;                 // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Smpl0                             sampler      NA          NA             s0      1 
// SmplShadow                      sampler_c      NA          NA            s13      1 
// SmplCube                          sampler      NA          NA            s14      1 
// SmplLinearClamp                   sampler      NA          NA            s15      1 
// Tex0                              texture  float4          2d             t0      1 
// shadowMap                         texture  float4          2d            t16      1 
// texEnvMap_g                       texture  float4        cube            t17      1 
// dynamicLights_g                   texture  struct         r/o            t18      1 
// lightIndices_g                    texture  struct         r/o            t19      1 
// atmosphereInscatterLUT            texture  float4          3d            t22      1 
// atmosphereExtinctionLUT           texture  float4          3d            t23      1 
// spotShadowMaps                    texture  float4     2darray            t24      1 
// spotShadowMatrices_g              texture  struct         r/o            t25      1 
// cb_scene                          cbuffer      NA          NA            cb0      1 
// cb_local                          cbuffer      NA          NA            cb5      1 
// ConstantBuffer                    cbuffer      NA          NA            cb6      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// NORMAL                   0   xyzw        1     NONE   float   xyzw
// TANGENT                  0   xyzw        2     NONE   float      w
// BINORMAL                 0   xyzw        3     NONE   float       
// TEXCOORD                 0   xyzw        4     NONE   float   xy  
// TEXCOORD                 1   xyzw        5     NONE   float     zw
// TEXCOORD                 2   xyzw        6     NONE   float       
// TEXCOORD                 3   xyzw        7     NONE   float   xyzw
// TEXCOORD                 4   xyzw        8     NONE   float   xyzw
// TEXCOORD                 5   xyzw        9     NONE   float   xy w
// SV_IsFrontFace           0   x          10    FFACE    uint       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET   float   xyzw
// SV_Target                2   xy          2   TARGET   float   xy  
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_immediateConstantBuffer { { -0.840520, -0.073954, 0, 0},
                              { -0.326235, -0.405830, 0, 0},
                              { -0.698464, 0.457259, 0, 0},
                              { -0.203356, 0.620585, 0, 0},
                              { 0.963450, -0.194353, 0, 0},
                              { 0.473434, -0.480026, 0, 0},
                              { 0.519454, 0.767034, 0, 0},
                              { 0.185461, -0.894523, 0, 0},
                              { 0.507351, 0.064963, 0, 0},
                              { -0.321932, 0.595435, 0, 0} }
      0x000000B4: dcl_constantbuffer CB0[89], immediateIndexed
      0x000000C4: dcl_constantbuffer CB6[9], immediateIndexed
      0x000000D4: dcl_constantbuffer CB5[8], immediateIndexed
      0x000000E4: dcl_sampler s0, mode_default
      0x000000F0: dcl_sampler s13, mode_comparison
      0x000000FC: dcl_sampler s14, mode_default
      0x00000108: dcl_sampler s15, mode_default
      0x00000114: dcl_resource_texture2d (float,float,float,float) t0
      0x00000124: dcl_resource_texture2d (float,float,float,float) t16
      0x00000134: dcl_resource_texturecube (float,float,float,float) t17
      0x00000144: dcl_resource_structured t18, 112
      0x00000154: dcl_resource_structured t19, 576
      0x00000164: dcl_resource_texture3d (float,float,float,float) t22
      0x00000174: dcl_resource_texture3d (float,float,float,float) t23
      0x00000184: dcl_resource_texture2darray (float,float,float,float) t24
      0x00000194: dcl_resource_structured t25, 64
      0x000001A4: dcl_input_ps_siv linear noperspective v0.xy, position
      0x000001B4: dcl_input_ps linear v1.xyzw
      0x000001C0: dcl_input_ps linear v2.w
      0x000001CC: dcl_input_ps linear v4.xy
      0x000001D8: dcl_input_ps linear v5.zw
      0x000001E4: dcl_input_ps linear centroid v7.xyzw
      0x000001F0: dcl_input_ps linear v8.xyzw
      0x000001FC: dcl_input_ps linear v9.xyw
      0x00000208: dcl_output o0.xyzw
      0x00000214: dcl_output o1.xyzw
      0x00000220: dcl_output o2.xy
      0x0000022C: dcl_temps 14
   0  0x00000234: dp3 r0.x, v8.xyzx, cb0[62].xyzx
   1  0x00000254: add r0.x, r0.x, -cb0[62].w
   2  0x00000278: lt r0.x, r0.x, l(0.000000)
   3  0x00000294: discard_nz r0.x
   4  0x000002A0: div r0.xy, v9.xyxx, v9.wwww
   5  0x000002BC: mad r0.xy, r0.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
   6  0x000002F8: mad r0.xy, r0.xyxx, cb0[24].xyxx, -v0.xyxx
   7  0x00000324: add o2.xy, r0.xyxx, -cb0[88].xyxx
   8  0x00000348: add r0.x, -v8.x, cb0[4].w
   9  0x0000036C: add r0.y, -v8.y, cb0[5].w
  10  0x00000390: add r0.z, -v8.z, cb0[6].w
  11  0x000003B4: dp3 r0.w, r0.xyzx, r0.xyzx
  12  0x000003D0: sqrt r1.x, r0.w
  13  0x000003E4: rsq r0.w, r0.w
  14  0x000003F8: mul r1.yzw, r0.wwww, r0.xxyz
  15  0x00000414: add r1.x, r1.x, -v1.w
  16  0x00000434: mul r1.x, r1.x, v2.w
  17  0x00000450: min r1.x, r1.x, l(1.000000)
  18  0x0000046C: max r1.x, r1.x, cb0[60].w
  19  0x0000048C: dp3 r2.x, v1.xyzx, v1.xyzx
  20  0x000004A8: rsq r2.x, r2.x
  21  0x000004BC: mul r2.xyz, r2.xxxx, v1.xyzx
  22  0x000004D8: mad r3.xy, v4.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.000000, 1.000000, 0.000000, 0.000000)
  23  0x00000514: sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r3.xyxx, t0.xyzw, s0
  24  0x00000540: mul r3.xyzw, r3.xyzw, v7.xyzw
  25  0x0000055C: dp4 r2.w, cb0[2].xyzw, v8.xyzw
  26  0x0000057C: mad r4.xyz, cb0[47].xyzx, r2.xxxx, cb0[46].xyzx
  27  0x000005A8: mad r4.xyz, cb0[48].xyzx, r2.yyyy, r4.xyzx
  28  0x000005D0: mad r4.xyz, cb0[49].xyzx, r2.zzzz, r4.xyzx
  29  0x000005F8: mul r5.xyz, r2.zzzz, cb0[50].xyzx
  30  0x00000618: mad r4.xyz, r5.xyzx, r2.xxxx, r4.xyzx
  31  0x0000063C: mul r5.xyz, r2.yyyy, cb0[51].xyzx
  32  0x0000065C: mad r4.xyz, r5.xyzx, r2.zzzz, r4.xyzx
  33  0x00000680: mul r5.xyz, r2.yyyy, cb0[52].xyzx
  34  0x000006A0: mad r4.xyz, r5.xyzx, r2.xxxx, r4.xyzx
  35  0x000006C4: mul r5.xy, r2.zyzz, r2.zyzz
  36  0x000006E0: mad r4.w, r5.x, l(3.000000), l(-1.000000)
  37  0x00000704: mad r4.xyz, cb0[53].xyzx, r4.wwww, r4.xyzx
  38  0x0000072C: mad r4.w, r2.x, r2.x, -r5.y
  39  0x00000754: mad r4.xyz, cb0[54].xyzx, r4.wwww, r4.xyzx
  40  0x0000077C: add r5.xyz, cb5[3].xyzx, cb0[36].xyzx
  41  0x000007A0: min r5.xyz, r5.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
  42  0x000007C8: dp3 r4.w, r2.xyzx, -cb0[26].xyzx
  43  0x000007EC: dp3 r5.w, r2.xyzx, r1.yzwy
  44  0x00000808: ge r6.x, cb0[59].w, -r2.w
  45  0x0000082C: if_nz r6.x
  46  0x00000838:   lt r6.x, -r2.w, cb0[26].w
  47  0x0000085C:   movc r7.xyzw, r6.xxxx, cb0[27].xyzw, cb0[31].xyzw
  48  0x00000888:   movc r8.xyzw, r6.xxxx, cb0[28].xyzw, cb0[32].xyzw
  49  0x000008B4:   movc r9.xyzw, r6.xxxx, cb0[29].xyzw, cb0[33].xyzw
  50  0x000008E0:   movc r6.xyzw, r6.xxxx, cb0[30].xyzw, cb0[34].xyzw
  51  0x0000090C:   dp4 r7.x, v8.xyzw, r7.xyzw
  52  0x00000928:   dp4 r7.y, v8.xyzw, r8.xyzw
  53  0x00000944:   dp4 r7.z, v8.xyzw, r9.xyzw
  54  0x00000960:   dp4 r6.x, v8.xyzw, r6.xyzw
  55  0x0000097C:   div r6.xyz, r7.xyzx, r6.xxxx
  56  0x00000998:   mov r6.w, l(0)
  57  0x000009AC:   mov r7.x, l(0)
  58  0x000009C0:   loop 
  59  0x000009C4:     ige r7.y, r7.x, l(10)
  60  0x000009E0:     breakc_nz r7.y
  61  0x000009EC:     mul r7.yz, cb0[35].xxyx, icb[r7.x + 0].xxyx
  62  0x00000A10:     mad_sat r7.yz, r7.yyzy, l(0.000000, 1.500000, 1.500000, 0.000000), r6.xxyx
  63  0x00000A40:     sample_c_lz_indexable(texture2d)(float,float,float,float) r7.y, r7.yzyy, t16.xxxx, s13, r6.z
  64  0x00000A74:     mad r6.w, r7.y, l(0.100000), r6.w
  65  0x00000A98:     iadd r7.x, r7.x, l(1)
  66  0x00000AB4:   endloop 
  67  0x00000AB8:   add r6.x, -r2.w, -cb0[35].z
  68  0x00000AE0:   mul_sat r6.x, r6.x, cb0[35].w
  69  0x00000B00:   add r6.y, -r6.w, l(1.000000)
  70  0x00000B20:   mad r6.x, r6.x, r6.y, r6.w
  71  0x00000B44: else 
  72  0x00000B48:   mov r6.x, l(1.000000)
  73  0x00000B5C: endif 
  74  0x00000B60: add r6.y, r6.x, l(-1.000000)
  75  0x00000B7C: mad r6.y, cb5[5].w, r6.y, l(1.000000)
  76  0x00000BA4: add r6.z, -r4.w, l(1.000000)
  77  0x00000BC4: mad r6.z, cb5[2].y, r6.z, r4.w
  78  0x00000BEC: mad r6.z, r6.z, l(0.500000), l(0.500000)
  79  0x00000C10: mul r6.w, r6.z, r6.z
  80  0x00000C2C: mad r6.z, -r6.z, r6.w, l(1.000000)
  81  0x00000C54: mad r6.x, r6.z, r6.z, r6.x
  82  0x00000C78: min r6.x, r6.x, l(1.000000)
  83  0x00000C94: mad r7.xyz, r0.xyzx, r0.wwww, -cb0[26].xyzx
  84  0x00000CC0: dp3 r6.z, r7.xyzx, r7.xyzx
  85  0x00000CDC: rsq r6.z, r6.z
  86  0x00000CF0: mul r7.xyz, r6.zzzz, r7.xyzx
  87  0x00000D0C: mul r6.z, cb5[6].w, cb0[41].y
  88  0x00000D30: dp3_sat r6.w, r7.xyzx, r2.xyzx
  89  0x00000D4C: max r6.z, r6.z, l(0.001000)
  90  0x00000D68: log r6.w, r6.w
  91  0x00000D7C: mul r6.z, r6.w, r6.z
  92  0x00000D98: exp r6.z, r6.z
  93  0x00000DAC: mul r6.y, r6.y, r6.z
  94  0x00000DC8: mul r6.y, r6.y, cb0[41].z
  95  0x00000DE8: mul r6.yzw, r6.yyyy, cb5[5].xxyz
  96  0x00000E08: mad r7.xy, r4.wwww, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
  97  0x00000E44: max r4.w, r7.y, r7.x
  98  0x00000E60: add r4.w, -r7.x, r4.w
  99  0x00000E80: mad r4.w, cb5[2].y, r4.w, r7.x
 100  0x00000EA8: add r7.x, r5.w, r5.w
 101  0x00000EC4: mad r1.yzw, r2.xxyz, -r7.xxxx, r1.yyzw
 102  0x00000EEC: resinfo_indexable(texturecube)(float,float,float,float)_uint r7.x, l(0), t17.wxyz
 103  0x00000F10: mul r1.yzw, r1.yyzw, l(0.000000, 1.000000, -1.000000, -1.000000)
 104  0x00000F38: iadd r7.x, r7.x, l(-1)
 105  0x00000F54: utof r7.x, r7.x
 106  0x00000F68: mul r7.x, r7.x, cb5[7].y
 107  0x00000F88: sample_l_indexable(texturecube)(float,float,float,float) r1.yzw, r1.yzwy, t17.wxyz, s14, r7.x
 108  0x00000FBC: lt r7.x, l(0.000000), cb5[6].z
 109  0x00000FDC: add r5.w, -|r5.w|, l(1.000000)
 110  0x00000FFC: max r5.w, r5.w, l(0.000000)
 111  0x00001018: log r7.y, r5.w
 112  0x0000102C: mul r7.y, r7.y, cb5[6].z
 113  0x0000104C: exp r7.y, r7.y
 114  0x00001060: movc r7.x, r7.x, r7.y, l(1.000000)
 115  0x00001084: mul r7.y, r7.x, cb5[7].x
 116  0x000010A4: mad r8.xyz, r3.xyzx, r1.yzwy, -r3.xyzx
 117  0x000010CC: mad r3.xyz, r7.yyyy, r8.xyzx, r3.xyzx
 118  0x000010F0: dp3 r7.y, r1.yzwy, l(0.299000, 0.587000, 0.114000, 0.000000)
 119  0x00001118: mad r7.z, cb5[7].y, l(-9.000000), l(10.000000)
 120  0x00001140: log r7.y, r7.y
 121  0x00001154: mul r7.y, r7.y, r7.z
 122  0x00001170: exp r7.y, r7.y
 123  0x00001184: add r7.z, -r7.y, l(1.000000)
 124  0x000011A4: mad r7.y, cb5[7].x, r7.z, r7.y
 125  0x000011CC: mul r1.yzw, r1.yyzw, r4.wwww
 126  0x000011E8: mul r1.yzw, r7.yyyy, r1.yyzw
 127  0x00001204: mul r1.yzw, r7.xxxx, r1.yyzw
 128  0x00001220: add r7.y, -cb5[7].y, l(1.000000)
 129  0x00001244: mul r1.yzw, r1.yyzw, r7.yyyy
 130  0x00001260: mad r1.yzw, r6.yyzw, cb0[25].xxyz, r1.yyzw
 131  0x00001288: mul r4.w, r6.x, r4.w
 132  0x000012A4: add r6.xyz, -r5.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 133  0x000012D0: mad r5.xyz, r4.wwww, r6.xyzx, r5.xyzx
 134  0x000012F4: mad r4.xyz, r5.xyzx, cb0[25].xyzx, r4.xyzx
 135  0x0000131C: min r4.w, cb5[1].z, l(1.000000)
 136  0x0000133C: add r5.xyz, -r4.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 137  0x00001368: mad r4.xyz, r4.wwww, r5.xyzx, r4.xyzx
 138  0x0000138C: mul r4.w, r5.w, cb5[6].x
 139  0x000013AC: log r4.w, r4.w
 140  0x000013C0: mul r4.w, r4.w, cb5[4].w
 141  0x000013E0: exp r4.w, r4.w
 142  0x000013F4: min r4.w, r4.w, l(1.000000)
 143  0x00001410: mad r1.yzw, cb5[4].xxyz, r4.wwww, r1.yyzw
 144  0x00001438: mul r5.xy, v0.xyxx, cb0[38].xyxx
 145  0x00001458: mul r4.w, -r2.w, cb0[41].w
 146  0x0000147C: min r4.w, r4.w, l(7.000000)
 147  0x00001498: max r4.w, r4.w, l(0.000000)
 148  0x000014B4: ftou r5.xy, r5.xyxx
 149  0x000014C8: ftou r4.w, r4.w
 150  0x000014DC: ishl r5.y, r5.y, l(5)
 151  0x000014F8: imad r4.w, r4.w, l(576), r5.y
 152  0x0000151C: iadd r4.w, r5.x, r4.w
 153  0x00001538: umin r4.w, r4.w, l(4607)
 154  0x00001554: ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r5.x, r4.w, l(252), t19.xxxx
 155  0x00001580: umin r5.x, r5.x, l(63)
 156  0x0000159C: mov r5.yzw, l(0,0,0,0)
 157  0x000015BC: mov r6.xyzw, l(0,0,0,0)
 158  0x000015DC: loop 
 159  0x000015E0:   uge r7.y, r6.w, r5.x
 160  0x000015FC:   breakc_nz r7.y
 161  0x00001608:   ishl r7.y, r6.w, l(2)
 162  0x00001624:   ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r7.y, r4.w, r7.y, t19.xxxx
 163  0x00001650:   ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r8.xyz, r7.y, l(0), t18.xyzx
 164  0x0000167C:   add r8.xyz, r8.xyzx, -v8.xyzx
 165  0x0000169C:   dp3 r7.z, r8.xyzx, r8.xyzx
 166  0x000016B8:   sqrt r7.w, r7.z
 167  0x000016CC:   ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r8.w, r7.y, l(28), t18.xxxx
 168  0x000016F8:   mul r7.w, r7.w, r8.w
 169  0x00001714:   ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r8.w, r7.y, l(44), t18.xxxx
 170  0x00001740:   log r7.w, |r7.w|
 171  0x00001758:   mul r7.w, r7.w, r8.w
 172  0x00001774:   exp r7.w, r7.w
 173  0x00001788:   add r7.w, -r7.w, l(1.000000)
 174  0x000017A8:   max r7.w, r7.w, l(0.000000)
 175  0x000017C4:   lt r8.w, l(0.000000), r7.w
 176  0x000017E0:   if_nz r8.w
 177  0x000017EC:     rsq r7.z, r7.z
 178  0x00001800:     mul r8.xyz, r7.zzzz, r8.xyzx
 179  0x0000181C:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r7.z, r7.y, l(96), t18.xxxx
 180  0x00001848:     dp3 r8.w, r8.xyzx, r2.xyzx
 181  0x00001864:     max r7.z, r7.z, r8.w
 182  0x00001880:     mul r7.z, r7.z, r7.w
 183  0x0000189C:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r9.xyz, r7.y, l(16), t18.xyzx
 184  0x000018C8:     mad r6.xyz, r9.xyzx, r7.zzzz, r6.xyzx
 185  0x000018EC:     mad r8.xyz, r0.xyzx, r0.wwww, r8.xyzx
 186  0x00001910:     dp3 r7.w, r8.xyzx, r8.xyzx
 187  0x0000192C:     rsq r7.w, r7.w
 188  0x00001940:     mul r8.xyz, r7.wwww, r8.xyzx
 189  0x0000195C:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r7.yw, r7.y, l(68), t18.xxxy
 190  0x00001988:     mul r7.w, r7.w, cb5[6].w
 191  0x000019A8:     dp3_sat r8.x, r8.xyzx, r2.xyzx
 192  0x000019C4:     max r7.w, r7.w, l(0.001000)
 193  0x000019E0:     log r8.x, r8.x
 194  0x000019F4:     mul r7.w, r7.w, r8.x
 195  0x00001A10:     exp r7.w, r7.w
 196  0x00001A24:     mul r8.xyz, r7.wwww, r9.xyzx
 197  0x00001A40:     mul r8.xyz, r7.zzzz, r8.xyzx
 198  0x00001A5C:     mad r5.yzw, r8.xxyz, r7.yyyy, r5.yyzw
 199  0x00001A80:   endif 
 200  0x00001A84:   iadd r6.w, r6.w, l(1)
 201  0x00001AA0: endloop 
 202  0x00001AA4: mad r4.xyz, r6.xyzx, cb5[6].yyyy, r4.xyzx
 203  0x00001ACC: ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r5.x, r4.w, l(508), t19.xxxx
 204  0x00001AF8: umin r5.x, r5.x, l(63)
 205  0x00001B14: mov r6.xyz, r5.yzwy
 206  0x00001B28: mov r7.yzw, l(0,0,0,0)
 207  0x00001B48: mov r6.w, l(0)
 208  0x00001B5C: loop 
 209  0x00001B60:   uge r8.x, r6.w, r5.x
 210  0x00001B7C:   breakc_nz r8.x
 211  0x00001B88:   ishl r8.x, r6.w, l(2)
 212  0x00001BA4:   iadd r8.x, r8.x, l(256)
 213  0x00001BC0:   ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r8.x, r4.w, r8.x, t19.xxxx
 214  0x00001BEC:   ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r8.yzw, r8.x, l(0), t18.xxyz
 215  0x00001C18:   add r8.yzw, r8.yyzw, -v8.xxyz
 216  0x00001C38:   dp3 r9.x, r8.yzwy, r8.yzwy
 217  0x00001C54:   rsq r9.y, r9.x
 218  0x00001C68:   mul r8.yzw, r8.yyzw, r9.yyyy
 219  0x00001C84:   ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r10.xyzw, r8.x, l(48), t18.xyzw
 220  0x00001CB0:   dp3 r9.y, r8.yzwy, r10.xyzx
 221  0x00001CCC:   max r9.y, r9.y, l(0.000000)
 222  0x00001CE8:   add r9.y, -r9.y, l(1.000000)
 223  0x00001D08:   mul r9.y, r10.w, r9.y
 224  0x00001D24:   ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r9.z, r8.x, l(64), t18.xxxx
 225  0x00001D50:   log r9.y, r9.y
 226  0x00001D64:   mul r9.y, r9.y, r9.z
 227  0x00001D80:   exp r9.y, r9.y
 228  0x00001D94:   add r9.y, -r9.y, l(1.000000)
 229  0x00001DB4:   max r9.y, r9.y, l(0.000000)
 230  0x00001DD0:   lt r9.z, l(0.000000), r9.y
 231  0x00001DEC:   if_nz r9.z
 232  0x00001DF8:     sqrt r9.x, r9.x
 233  0x00001E0C:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r9.z, r8.x, l(28), t18.xxxx
 234  0x00001E38:     mul r9.x, r9.z, r9.x
 235  0x00001E54:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r9.z, r8.x, l(44), t18.xxxx
 236  0x00001E80:     log r9.x, |r9.x|
 237  0x00001E98:     mul r9.x, r9.x, r9.z
 238  0x00001EB4:     exp r9.x, r9.x
 239  0x00001EC8:     add r9.x, -r9.x, l(1.000000)
 240  0x00001EE8:     max r9.x, r9.x, l(0.000000)
 241  0x00001F04:     mul r9.x, r9.x, r9.y
 242  0x00001F20:     lt r9.y, l(0.000000), r9.x
 243  0x00001F3C:     if_nz r9.y
 244  0x00001F48:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r9.yz, r8.x, l(96), t18.xxyx
 245  0x00001F74:       ine r9.w, r9.z, l(-1)
 246  0x00001F90:       if_nz r9.w
 247  0x00001F9C:         ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r10.xyzw, r9.z, l(0), t25.xyzw
 248  0x00001FC8:         ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r11.xyzw, r9.z, l(16), t25.xyzw
 249  0x00001FF4:         ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r12.xyzw, r9.z, l(32), t25.xyzw
 250  0x00002020:         ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r13.xyzw, r9.z, l(48), t25.xyzw
 251  0x0000204C:         dp4 r10.x, v8.xyzw, r10.xyzw
 252  0x00002068:         dp4 r10.y, v8.xyzw, r11.xyzw
 253  0x00002084:         dp4 r10.z, v8.xyzw, r12.xyzw
 254  0x000020A0:         dp4 r9.w, v8.xyzw, r13.xyzw
 255  0x000020BC:         div r10.xyz, r10.xyzx, r9.wwww
 256  0x000020D8:         itof r10.w, r9.z
 257  0x000020EC:         sample_c_lz_indexable(texture2darray)(float,float,float,float) r9.z, r10.xywx, t24.xxxx, s13, r10.z
 258  0x00002120:         mul r9.x, r9.z, r9.x
 259  0x0000213C:       endif 
 260  0x00002140:       dp3 r9.z, r8.yzwy, r2.xyzx
 261  0x0000215C:       max r9.y, r9.z, r9.y
 262  0x00002178:       mul r9.x, r9.y, r9.x
 263  0x00002194:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r9.yzw, r8.x, l(16), t18.xxyz
 264  0x000021C0:       mad r7.yzw, r9.yyzw, r9.xxxx, r7.yyzw
 265  0x000021E4:       mad r8.yzw, r0.xxyz, r0.wwww, r8.yyzw
 266  0x00002208:       dp3 r10.x, r8.yzwy, r8.yzwy
 267  0x00002224:       rsq r10.x, r10.x
 268  0x00002238:       mul r8.yzw, r8.yyzw, r10.xxxx
 269  0x00002254:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r10.xy, r8.x, l(68), t18.xyxx
 270  0x00002280:       mul r8.x, r10.y, cb5[6].w
 271  0x000022A0:       dp3_sat r8.y, r8.yzwy, r2.xyzx
 272  0x000022BC:       max r8.x, r8.x, l(0.001000)
 273  0x000022D8:       log r8.y, r8.y
 274  0x000022EC:       mul r8.x, r8.y, r8.x
 275  0x00002308:       exp r8.x, r8.x
 276  0x0000231C:       mul r8.xyz, r8.xxxx, r9.yzwy
 277  0x00002338:       mul r8.xyz, r9.xxxx, r8.xyzx
 278  0x00002354:       mad r6.xyz, r8.xyzx, r10.xxxx, r6.xyzx
 279  0x00002378:     endif 
 280  0x0000237C:   endif 
 281  0x00002380:   iadd r6.w, r6.w, l(1)
 282  0x0000239C: endloop 
 283  0x000023A0: mad r0.xyz, r7.yzwy, cb5[6].yyyy, r4.xyzx
 284  0x000023C8: mad r1.yzw, r6.xxyz, cb5[6].yyyy, r1.yyzw
 285  0x000023F0: mad r0.xyz, r3.xyzx, r0.xyzx, r1.yzwy
 286  0x00002414: dp3 r0.w, r1.yzwy, l(0.299000, 0.587000, 0.114000, 0.000000)
 287  0x0000243C: min r0.w, r0.w, l(1.000000)
 288  0x00002458: mul r1.y, r3.w, r7.x
 289  0x00002474: mad r1.z, -r3.w, r7.x, v5.w
 290  0x0000249C: mad r0.w, r0.w, r1.z, r1.y
 291  0x000024C0: max r1.y, cb5[1].z, l(1.000000)
 292  0x000024E0: mul r3.xyz, r0.xyzx, r1.yyyy
 293  0x000024FC: mul r0.w, r1.x, r0.w
 294  0x00002518: mul r1.x, v5.z, cb5[1].w
 295  0x00002538: mad r0.xyz, -r0.xyzx, r1.yyyy, cb0[39].xyzx
 296  0x00002564: mad r0.xyz, r1.xxxx, r0.xyzx, r3.xyzx
 297  0x00002588: div r1.x, -r2.w, cb6[8].z
 298  0x000025AC: mul r3.xy, v0.xyxx, cb0[24].zwzz
 299  0x000025CC: add r1.x, r1.x, -cb6[8].y
 300  0x000025F0: add r1.y, l(1.000000), -cb6[8].y
 301  0x00002614: div r3.z, r1.x, r1.y
 302  0x00002630: sample_l_indexable(texture3d)(float,float,float,float) r1.xyz, r3.xyzx, t22.xyzw, s15, l(0.000000)
 303  0x00002664: sample_l_indexable(texture3d)(float,float,float,float) r3.xyz, r3.xyzx, t23.xyzw, s15, l(0.000000)
 304  0x00002698: add r1.xyz, r1.xyzx, r3.xyzx
 305  0x000026B4: mul r0.xyz, r0.xyzx, r1.xyzx
 306  0x000026D0: mul o0.xyz, r0.xyzx, cb0[61].xyzx
 307  0x000026F0: add r0.x, -v5.z, l(1.000000)
 308  0x00002710: mul r0.x, r0.x, cb5[2].z
 309  0x00002730: mul r0.x, r0.w, r0.x
 310  0x0000274C: mad r1.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
 311  0x00002788: mov_sat r1.xy, r1.xyxx
 312  0x0000279C: mul r0.yz, r1.xxyx, l(0.000000, 65535.000000, 65535.000000, 0.000000)
 313  0x000027C4: ftou r0.yz, r0.yyzy
 314  0x000027D8: imad o1.x, r0.z, l(0x00010000), r0.y
 315  0x000027FC: mul r0.y, r1.z, l(65535.000000)
 316  0x00002818: ftou o1.y, r0.y
 317  0x0000282C: mul r0.x, r0.x, l(255.000000)
 318  0x00002848: ftou r0.x, r0.x
 319  0x0000285C: ishl r0.yz, r0.xxxx, l(0, 8, 16, 0)
 320  0x00002884: or r0.x, r0.y, r0.x
 321  0x000028A0: or o1.z, r0.z, r0.x
 322  0x000028BC: mov o0.w, r0.w
 323  0x000028D0: mov o1.w, l(0)
 324  0x000028E4: ret 
// Approximately 325 instruction slots used
