//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cb_scene
// {
//
//   float4x4 view_g;                   // Offset:    0 Size:    64
//   float4x4 viewInv_g;                // Offset:   64 Size:    64
//   float4x4 proj_g;                   // Offset:  128 Size:    64 [unused]
//   float4x4 projInv_g;                // Offset:  192 Size:    64
//   float4x4 viewProj_g;               // Offset:  256 Size:    64 [unused]
//   float4x4 viewProjInv_g;            // Offset:  320 Size:    64
//   float2 vpSize_g;                   // Offset:  384 Size:     8 [unused]
//   float2 invVPSize_g;                // Offset:  392 Size:     8 [unused]
//   float3 lightColor_g;               // Offset:  400 Size:    12
//   float ldotvXZ_g;                   // Offset:  412 Size:     4 [unused]
//   float3 lightDirection_g;           // Offset:  416 Size:    12
//   float shadowSplitDistance_g;       // Offset:  428 Size:     4
//   float4x4 shadowMtx_g[2];           // Offset:  432 Size:   128
//   float2 invShadowSize_g;            // Offset:  560 Size:     8
//   float shadowFadeNear_g;            // Offset:  568 Size:     4 [unused]
//   float shadowFadeRangeInv_g;        // Offset:  572 Size:     4 [unused]
//   float3 sceneShadowColor_g;         // Offset:  576 Size:    12
//   float gameTime_g;                  // Offset:  588 Size:     4 [unused]
//   float3 windDirection_g;            // Offset:  592 Size:    12 [unused]
//   uint collisionCount_g;             // Offset:  604 Size:     4 [unused]
//   float lightTileWidthInv_g;         // Offset:  608 Size:     4
//   float lightTileHeightInv_g;        // Offset:  612 Size:     4
//   float fogNearDistance_g;           // Offset:  616 Size:     4
//   float fogFadeRangeInv_g;           // Offset:  620 Size:     4
//   float3 fogColor_g;                 // Offset:  624 Size:    12
//   float fogIntensity_g;              // Offset:  636 Size:     4
//   float fogHeight_g;                 // Offset:  640 Size:     4
//   float fogHeightRangeInv_g;         // Offset:  644 Size:     4
//   float windWaveTime_g;              // Offset:  648 Size:     4 [unused]
//   float windWaveFrequency_g;         // Offset:  652 Size:     4 [unused]
//   uint localLightProbeCount_g;       // Offset:  656 Size:     4 [unused]
//   float lightSpecularGlossiness_g;   // Offset:  660 Size:     4
//   float lightSpecularIntensity_g;    // Offset:  664 Size:     4
//   float lightTileDepthInv_g;         // Offset:  668 Size:     4
//   float4x4 ditherMtx_g;              // Offset:  672 Size:    64 [unused]
//   float4 lightProbe_g[9];            // Offset:  736 Size:   144
//   float4x4 farShadowMtx_g;           // Offset:  880 Size:    64
//   float3 chrLightDir_g;              // Offset:  944 Size:    12 [unused]
//   float shadowDistance_g;            // Offset:  956 Size:     4
//   float resolutionScaling_g;         // Offset:  960 Size:     4 [unused]
//   float sceneTime_g;                 // Offset:  964 Size:     4 [unused]
//   float windForce_g;                 // Offset:  968 Size:     4 [unused]
//   float disableMapObjNearFade_g;     // Offset:  972 Size:     4 [unused]
//   float4 mapColor_g;                 // Offset:  976 Size:    16 [unused]
//   float4 clipPlane_g;                // Offset:  992 Size:    16 [unused]
//   float shadowZeroCascadeUVMult_g;   // Offset: 1008 Size:     4
//   float prevSceneTime_g;             // Offset: 1012 Size:     4 [unused]
//   float prevWindWaveTime_g;          // Offset: 1016 Size:     4 [unused]
//   uint enableMotionVectors_g;        // Offset: 1020 Size:     4 [unused]
//   float4x4 prevView_g;               // Offset: 1024 Size:    64 [unused]
//   float4x4 prevViewInv_g;            // Offset: 1088 Size:    64 [unused]
//   float4x4 prevProj_g;               // Offset: 1152 Size:    64 [unused]
//   float4x4 prevProjInv_g;            // Offset: 1216 Size:    64 [unused]
//   float4x4 prevViewProj_g;           // Offset: 1280 Size:    64 [unused]
//   float4x4 prevViewProjInv_g;        // Offset: 1344 Size:    64 [unused]
//   float2 motionJitterOffset_g;       // Offset: 1408 Size:     8 [unused]
//   float2 curJitterOffset_g;          // Offset: 1416 Size:     8 [unused]
//
// }
//
// cbuffer cb_local
// {
//
//   float fadeRangeInv_g;              // Offset:    0 Size:     4
//   float density_g;                   // Offset:    4 Size:     4
//   float4 offsetsAndWeights[8];       // Offset:   16 Size:   128
//
// }
//
// cbuffer cb_deferred
// {
//
//   uint outlineShapeCount_g;          // Offset:    0 Size:     4
//   uint evaluateAllShadowSamples_g;   // Offset:    4 Size:     4 [unused]
//   float4 outlineShapeMaskUVParam_g;  // Offset:   16 Size:    16
//
// }
//
// Resource bind info for deferredParams_g
// {
//
//   struct DeferredParam
//   {
//       
//       float3 shadowColor;            // Offset:    0
//       float emissive;                // Offset:   12
//       float3 specularColor;          // Offset:   16
//       float rimLightPower;           // Offset:   28
//       float3 rimLightColor;          // Offset:   32
//       float rimIntensity;            // Offset:   44
//       float3 fresnels;               // Offset:   48
//       float specularShadowFadeRatio; // Offset:   60
//       float3 specularGlossinesses;   // Offset:   64
//       float dynamicLightIntensity;   // Offset:   76
//       float materialFogIntensity;    // Offset:   80
//       float metalness;               // Offset:   84
//       float roughness;               // Offset:   88
//       float cryRefractionIndex;      // Offset:   92
//       float cryFresnel;              // Offset:   96
//       float cryBrightness;           // Offset:  100
//       float cryBrightnessPower;      // Offset:  104
//       float glowIntensity;           // Offset:  108
//       float glowLumThreshold;        // Offset:  112
//       float glowShadowFadeRatio;     // Offset:  116
//       float ssaoIntensity;           // Offset:  120
//       float translucency;            // Offset:  124
//       float ssrDistance;             // Offset:  128
//       float ssrThickness;            // Offset:  132
//       float reserve;                 // Offset:  136
//       uint flag;                     // Offset:  140
//
//   } $Element;                        // Offset:    0 Size:   144
//
// }
//
// Resource bind info for outlineShapes_g
// {
//
//   struct OutlineShapeParam
//   {
//       
//       float4x4 mtx;                  // Offset:    0
//       float4 color;                  // Offset:   64
//       uint type;                     // Offset:   80
//       float radius;                  // Offset:   84
//       float2 gradation_size;         // Offset:   88
//       float gradation_sharpness;     // Offset:   96
//       float height_base;             // Offset:  100
//       float height_width;            // Offset:  104
//       float height_gradation_width;  // Offset:  108
//       float fan_angle;               // Offset:  112
//       float pad[3];                  // Offset:  116
//
//   } $Element;                        // Offset:    0 Size:   128
//
// }
//
// Resource bind info for dynamicLights_g
// {
//
//   struct LightParam
//   {
//       
//       float3 pos;                    // Offset:    0
//       float radius;                  // Offset:   12
//       float3 color;                  // Offset:   16
//       float radiusInv;               // Offset:   28
//       float3 charaColor;             // Offset:   32
//       float attenuation;             // Offset:   44
//       float3 vec;                    // Offset:   48
//       float spotAngleInv;            // Offset:   60
//       float attenuationAngle;        // Offset:   64
//       float specularIntensity;       // Offset:   68
//       float specularGlossiness;      // Offset:   72
//       float scatterAnisotropy;       // Offset:   76
//       float3 scatterColor;           // Offset:   80
//       float scatterDensity;          // Offset:   92
//       float translucency;            // Offset:   96
//       int shadowmapIndex;            // Offset:  100
//       float userParams[2];           // Offset:  104
//
//   } $Element;                        // Offset:    0 Size:   112
//
// }
//
// Resource bind info for lightIndices_g
// {
//
//   struct LightIndexData
//   {
//       
//       int pointLightIndices[63];     // Offset:    0
//       uint pointLightCount;          // Offset:  252
//       int spotLightIndices[63];      // Offset:  256
//       uint spotLightCount;           // Offset:  508
//       int lightProbeIndices[15];     // Offset:  512
//       uint lightProbeCount;          // Offset:  572
//
//   } $Element;                        // Offset:    0 Size:   576
//
// }
//
// Resource bind info for spotShadowMatrices_g
// {
//
//   float4x4 $Element;                 // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// samPoint                          sampler      NA          NA             s0      1 
// samLinear                         sampler      NA          NA             s1      1 
// SmplShadow                      sampler_c      NA          NA            s13      1 
// SmplCube                          sampler      NA          NA            s14      1 
// SmplLinearClamp                   sampler      NA          NA            s15      1 
// colorTexture                      texture  float4          2d             t0      1 
// mrtTexture                        texture   uint4          2d             t1      1 
// depthTexture                      texture   float          2d             t2      1 
// deferredParams_g                  texture  struct         r/o             t3      1 
// outlineShapes_g                   texture  struct         r/o             t4      1 
// outlineShapeMask                  texture  float4          2d             t5      1 
// texSSRMap_g                       texture  float4          2d            t14      1 
// texMirror_g                       texture  float4          2d            t15      1 
// shadowMap                         texture  float4          2d            t16      1 
// texEnvMap_g                       texture  float4        cube            t17      1 
// dynamicLights_g                   texture  struct         r/o            t18      1 
// lightIndices_g                    texture  struct         r/o            t19      1 
// farShadowMap                      texture  float4          2d            t21      1 
// spotShadowMaps                    texture  float4     2darray            t24      1 
// spotShadowMatrices_g              texture  struct         r/o            t25      1 
// cb_scene                          cbuffer      NA          NA            cb0      1 
// cb_local                          cbuffer      NA          NA            cb2      1 
// cb_deferred                       cbuffer      NA          NA            cb3      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET    uint   xyzw
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[64], immediateIndexed
      0x0000001C: dcl_constantbuffer CB2[9], immediateIndexed
      0x0000002C: dcl_constantbuffer CB3[2], immediateIndexed
      0x0000003C: dcl_sampler s0, mode_default
      0x00000048: dcl_sampler s1, mode_default
      0x00000054: dcl_sampler s13, mode_comparison
      0x00000060: dcl_sampler s14, mode_default
      0x0000006C: dcl_sampler s15, mode_default
      0x00000078: dcl_resource_texture2d (float,float,float,float) t0
      0x00000088: dcl_resource_texture2d (uint,uint,uint,uint) t1
      0x00000098: dcl_resource_texture2d (float,float,float,float) t2
      0x000000A8: dcl_resource_structured t3, 144
      0x000000B8: dcl_resource_structured t4, 128
      0x000000C8: dcl_resource_texture2d (float,float,float,float) t5
      0x000000D8: dcl_resource_texture2d (float,float,float,float) t14
      0x000000E8: dcl_resource_texture2d (float,float,float,float) t15
      0x000000F8: dcl_resource_texture2d (float,float,float,float) t16
      0x00000108: dcl_resource_texturecube (float,float,float,float) t17
      0x00000118: dcl_resource_structured t18, 112
      0x00000128: dcl_resource_structured t19, 576
      0x00000138: dcl_resource_texture2d (float,float,float,float) t21
      0x00000148: dcl_resource_texture2darray (float,float,float,float) t24
      0x00000158: dcl_resource_structured t25, 64
      0x00000168: dcl_input_ps_siv linear noperspective v0.xy, position
      0x00000178: dcl_input_ps linear v1.xyzw
      0x00000184: dcl_output o0.xyzw
      0x00000190: dcl_output o1.xyzw
      0x0000019C: dcl_temps 23
   0  0x000001A4: sample_l_indexable(texture2d)(float,float,float,float) r0.xyzw, v1.xyxx, t0.xyzw, s0, l(0.000000)
   1  0x000001D8: resinfo_indexable(texture2d)(uint,uint,uint,uint) r1.xy, l(0), t1.xyzw
   2  0x000001FC: mul r1.zw, r1.xxxy, v1.xxxy
   3  0x00000218: ftoi r2.xy, r1.zwzz
   4  0x0000022C: mov r2.zw, l(0,0,0,0)
   5  0x0000024C: ld_indexable(texture2d)(uint,uint,uint,uint) r2.xyzw, r2.xyzw, t1.wxyz
   6  0x00000270: ushr r3.z, r2.w, l(24)
   7  0x0000028C: ubfe r1.z, l(1), l(24), r2.w
   8  0x000002B0: ine r1.z, r1.z, l(0)
   9  0x000002CC: and r1.w, r3.z, l(4)
  10  0x000002E8: ieq r1.w, r1.w, l(0)
  11  0x00000304: and r1.z, r1.w, r1.z
  12  0x00000320: if_nz r1.z
  13  0x0000032C:   sample_l_indexable(texture2d)(float,float,float,float) r4.z, v1.xyxx, t2.yzxw, s0, l(0.000000)
  14  0x00000360:   ushr r5.y, r2.y, l(16)
  15  0x0000037C:   mov r5.x, r2.y
  16  0x00000390:   and r1.zw, r5.xxxy, l(0, 0, 0x0000ffff, 0x0000ffff)
  17  0x000003B8:   utof r1.zw, r1.zzzw
  18  0x000003CC:   mul r5.xy, r1.zwzz, l(0.000015, 0.000015, 0.000000, 0.000000)
  19  0x000003F4:   and r1.z, r2.z, l(0x0000ffff)
  20  0x00000410:   utof r1.z, r1.z
  21  0x00000424:   mul r5.z, r1.z, l(0.000015)
  22  0x00000440:   add r5.xyz, r5.xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)
  23  0x00000468:   add r5.xyz, r5.xyzx, r5.xyzx
  24  0x00000484:   mad r4.xy, v1.xyxx, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
  25  0x000004C0:   mov r4.w, l(1.000000)
  26  0x000004D4:   dp4 r1.z, r4.xyzw, cb0[14].xyzw
  27  0x000004F4:   dp4 r1.w, r4.xyzw, cb0[15].xyzw
  28  0x00000514:   div r1.z, r1.z, r1.w
  29  0x00000530:   mul_sat r1.w, r1.z, l(-0.500000)
  30  0x0000054C:   mad r1.w, r1.w, l(0.009000), l(0.001000)
  31  0x00000570:   add r4.xy, v1.xyxx, cb2[1].xyxx
  32  0x00000590:   mul r4.zw, r1.xxxy, r4.xxxy
  33  0x000005AC:   ftoi r6.xy, r4.zwzz
  34  0x000005C0:   mov r6.zw, l(0,0,0,0)
  35  0x000005E0:   ld_indexable(texture2d)(uint,uint,uint,uint) r3.w, r6.xyzw, t1.xywz
  36  0x00000604:   ushr r3.w, r3.w, l(24)
  37  0x00000620:   and r3.w, r3.w, l(4)
  38  0x0000063C:   if_z r3.w
  39  0x00000648:     sample_l_indexable(texture2d)(float,float,float,float) r6.z, r4.xyxx, t2.yzxw, s1, l(0.000000)
  40  0x0000067C:     mad r6.xy, r4.xyxx, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
  41  0x000006B8:     mov r6.w, l(1.000000)
  42  0x000006CC:     dp4 r3.w, r6.xyzw, cb0[14].xyzw
  43  0x000006EC:     dp4 r4.x, r6.xyzw, cb0[15].xyzw
  44  0x0000070C:     div r3.w, r3.w, r4.x
  45  0x00000728:     add r3.w, -r1.z, r3.w
  46  0x00000748:     ge r3.w, |r3.w|, r1.w
  47  0x00000768:     and r3.w, r3.w, l(0x3f800000)
  48  0x00000784:     mul r3.w, r3.w, cb2[1].z
  49  0x000007A4:     add r4.xy, v1.xyxx, cb2[2].xyxx
  50  0x000007C4:     mul r4.zw, r1.xxxy, r4.xxxy
  51  0x000007E0:     ftoi r6.xy, r4.zwzz
  52  0x000007F4:     mov r6.zw, l(0,0,0,0)
  53  0x00000814:     ld_indexable(texture2d)(uint,uint,uint,uint) r4.z, r6.xyzw, t1.xyzw
  54  0x00000838:     ushr r4.z, r4.z, l(24)
  55  0x00000854:     and r4.z, r4.z, l(4)
  56  0x00000870:     ine r4.w, r4.z, l(0)
  57  0x0000088C:     if_z r4.w
  58  0x00000898:       sample_l_indexable(texture2d)(float,float,float,float) r6.z, r4.xyxx, t2.yzxw, s1, l(0.000000)
  59  0x000008CC:       mad r6.xy, r4.xyxx, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
  60  0x00000908:       mov r6.w, l(1.000000)
  61  0x0000091C:       dp4 r4.x, r6.xyzw, cb0[14].xyzw
  62  0x0000093C:       dp4 r4.y, r6.xyzw, cb0[15].xyzw
  63  0x0000095C:       div r4.x, r4.x, r4.y
  64  0x00000978:       add r4.x, -r1.z, r4.x
  65  0x00000998:       ge r4.x, |r4.x|, r1.w
  66  0x000009B8:       and r4.x, r4.x, l(0x3f800000)
  67  0x000009D4:       mad r3.w, r4.x, cb2[2].z, r3.w
  68  0x000009FC:     endif 
  69  0x00000A00:     mov r4.z, r4.w
  70  0x00000A14:   else 
  71  0x00000A18:     mov r3.w, l(0)
  72  0x00000A2C:     mov r4.zw, l(0,0,-1,-1)
  73  0x00000A4C:   endif 
  74  0x00000A50:   not r4.xy, r4.wzww
  75  0x00000A64:   and r4.x, r4.y, r4.x
  76  0x00000A80:   if_nz r4.x
  77  0x00000A8C:     add r4.xy, v1.xyxx, cb2[3].xyxx
  78  0x00000AAC:     mul r6.xy, r1.xyxx, r4.xyxx
  79  0x00000AC8:     ftoi r6.xy, r6.xyxx
  80  0x00000ADC:     mov r6.zw, l(0,0,0,0)
  81  0x00000AFC:     ld_indexable(texture2d)(uint,uint,uint,uint) r5.w, r6.xyzw, t1.xywz
  82  0x00000B20:     ushr r5.w, r5.w, l(24)
  83  0x00000B3C:     and r5.w, r5.w, l(4)
  84  0x00000B58:     ine r4.w, r5.w, l(0)
  85  0x00000B74:     if_z r4.w
  86  0x00000B80:       sample_l_indexable(texture2d)(float,float,float,float) r6.z, r4.xyxx, t2.yzxw, s1, l(0.000000)
  87  0x00000BB4:       mad r6.xy, r4.xyxx, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
  88  0x00000BF0:       mov r6.w, l(1.000000)
  89  0x00000C04:       dp4 r4.x, r6.xyzw, cb0[14].xyzw
  90  0x00000C24:       dp4 r4.y, r6.xyzw, cb0[15].xyzw
  91  0x00000C44:       div r4.x, r4.x, r4.y
  92  0x00000C60:       add r4.x, -r1.z, r4.x
  93  0x00000C80:       ge r4.x, |r4.x|, r1.w
  94  0x00000CA0:       and r4.x, r4.x, l(0x3f800000)
  95  0x00000CBC:       mad r3.w, r4.x, cb2[3].z, r3.w
  96  0x00000CE4:     endif 
  97  0x00000CE8:     mov r4.z, r4.w
  98  0x00000CFC:   else 
  99  0x00000D00:     mov r4.w, l(-1)
 100  0x00000D14:   endif 
 101  0x00000D18:   not r4.xy, r4.wzww
 102  0x00000D2C:   and r4.x, r4.y, r4.x
 103  0x00000D48:   if_nz r4.x
 104  0x00000D54:     add r4.xy, v1.xyxx, cb2[4].xyxx
 105  0x00000D74:     mul r6.xy, r1.xyxx, r4.xyxx
 106  0x00000D90:     ftoi r6.xy, r6.xyxx
 107  0x00000DA4:     mov r6.zw, l(0,0,0,0)
 108  0x00000DC4:     ld_indexable(texture2d)(uint,uint,uint,uint) r5.w, r6.xyzw, t1.xywz
 109  0x00000DE8:     ushr r5.w, r5.w, l(24)
 110  0x00000E04:     and r5.w, r5.w, l(4)
 111  0x00000E20:     ine r4.w, r5.w, l(0)
 112  0x00000E3C:     if_z r4.w
 113  0x00000E48:       sample_l_indexable(texture2d)(float,float,float,float) r6.z, r4.xyxx, t2.yzxw, s1, l(0.000000)
 114  0x00000E7C:       mad r6.xy, r4.xyxx, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
 115  0x00000EB8:       mov r6.w, l(1.000000)
 116  0x00000ECC:       dp4 r4.x, r6.xyzw, cb0[14].xyzw
 117  0x00000EEC:       dp4 r4.y, r6.xyzw, cb0[15].xyzw
 118  0x00000F0C:       div r4.x, r4.x, r4.y
 119  0x00000F28:       add r4.x, -r1.z, r4.x
 120  0x00000F48:       ge r4.x, |r4.x|, r1.w
 121  0x00000F68:       and r4.x, r4.x, l(0x3f800000)
 122  0x00000F84:       mad r3.w, r4.x, cb2[4].z, r3.w
 123  0x00000FAC:     endif 
 124  0x00000FB0:     mov r4.z, r4.w
 125  0x00000FC4:   else 
 126  0x00000FC8:     mov r4.w, l(-1)
 127  0x00000FDC:   endif 
 128  0x00000FE0:   not r4.xy, r4.wzww
 129  0x00000FF4:   and r4.x, r4.y, r4.x
 130  0x00001010:   if_nz r4.x
 131  0x0000101C:     add r4.xy, v1.xyxx, cb2[5].xyxx
 132  0x0000103C:     mul r6.xy, r1.xyxx, r4.xyxx
 133  0x00001058:     ftoi r6.xy, r6.xyxx
 134  0x0000106C:     mov r6.zw, l(0,0,0,0)
 135  0x0000108C:     ld_indexable(texture2d)(uint,uint,uint,uint) r5.w, r6.xyzw, t1.xywz
 136  0x000010B0:     ushr r5.w, r5.w, l(24)
 137  0x000010CC:     and r5.w, r5.w, l(4)
 138  0x000010E8:     ine r4.w, r5.w, l(0)
 139  0x00001104:     if_z r4.w
 140  0x00001110:       sample_l_indexable(texture2d)(float,float,float,float) r6.z, r4.xyxx, t2.yzxw, s1, l(0.000000)
 141  0x00001144:       mad r6.xy, r4.xyxx, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
 142  0x00001180:       mov r6.w, l(1.000000)
 143  0x00001194:       dp4 r4.x, r6.xyzw, cb0[14].xyzw
 144  0x000011B4:       dp4 r4.y, r6.xyzw, cb0[15].xyzw
 145  0x000011D4:       div r4.x, r4.x, r4.y
 146  0x000011F0:       add r4.x, -r1.z, r4.x
 147  0x00001210:       ge r4.x, |r4.x|, r1.w
 148  0x00001230:       and r4.x, r4.x, l(0x3f800000)
 149  0x0000124C:       mad r3.w, r4.x, cb2[5].z, r3.w
 150  0x00001274:     endif 
 151  0x00001278:     mov r4.z, r4.w
 152  0x0000128C:   else 
 153  0x00001290:     mov r4.w, l(-1)
 154  0x000012A4:   endif 
 155  0x000012A8:   not r4.xy, r4.wzww
 156  0x000012BC:   and r4.x, r4.y, r4.x
 157  0x000012D8:   if_nz r4.x
 158  0x000012E4:     add r4.xy, v1.xyxx, cb2[6].xyxx
 159  0x00001304:     mul r6.xy, r1.xyxx, r4.xyxx
 160  0x00001320:     ftoi r6.xy, r6.xyxx
 161  0x00001334:     mov r6.zw, l(0,0,0,0)
 162  0x00001354:     ld_indexable(texture2d)(uint,uint,uint,uint) r5.w, r6.xyzw, t1.xywz
 163  0x00001378:     ushr r5.w, r5.w, l(24)
 164  0x00001394:     and r5.w, r5.w, l(4)
 165  0x000013B0:     ine r4.w, r5.w, l(0)
 166  0x000013CC:     if_z r4.w
 167  0x000013D8:       sample_l_indexable(texture2d)(float,float,float,float) r6.z, r4.xyxx, t2.yzxw, s1, l(0.000000)
 168  0x0000140C:       mad r6.xy, r4.xyxx, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
 169  0x00001448:       mov r6.w, l(1.000000)
 170  0x0000145C:       dp4 r4.x, r6.xyzw, cb0[14].xyzw
 171  0x0000147C:       dp4 r4.y, r6.xyzw, cb0[15].xyzw
 172  0x0000149C:       div r4.x, r4.x, r4.y
 173  0x000014B8:       add r4.x, -r1.z, r4.x
 174  0x000014D8:       ge r4.x, |r4.x|, r1.w
 175  0x000014F8:       and r4.x, r4.x, l(0x3f800000)
 176  0x00001514:       mad r3.w, r4.x, cb2[6].z, r3.w
 177  0x0000153C:     endif 
 178  0x00001540:     mov r4.z, r4.w
 179  0x00001554:   else 
 180  0x00001558:     mov r4.w, l(-1)
 181  0x0000156C:   endif 
 182  0x00001570:   not r4.xy, r4.wzww
 183  0x00001584:   and r4.x, r4.y, r4.x
 184  0x000015A0:   if_nz r4.x
 185  0x000015AC:     add r4.xy, v1.xyxx, cb2[7].xyxx
 186  0x000015CC:     mul r6.xy, r1.xyxx, r4.xyxx
 187  0x000015E8:     ftoi r6.xy, r6.xyxx
 188  0x000015FC:     mov r6.zw, l(0,0,0,0)
 189  0x0000161C:     ld_indexable(texture2d)(uint,uint,uint,uint) r5.w, r6.xyzw, t1.xywz
 190  0x00001640:     ushr r5.w, r5.w, l(24)
 191  0x0000165C:     and r5.w, r5.w, l(4)
 192  0x00001678:     ine r4.w, r5.w, l(0)
 193  0x00001694:     if_z r4.w
 194  0x000016A0:       sample_l_indexable(texture2d)(float,float,float,float) r6.z, r4.xyxx, t2.yzxw, s1, l(0.000000)
 195  0x000016D4:       mad r6.xy, r4.xyxx, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
 196  0x00001710:       mov r6.w, l(1.000000)
 197  0x00001724:       dp4 r4.x, r6.xyzw, cb0[14].xyzw
 198  0x00001744:       dp4 r4.y, r6.xyzw, cb0[15].xyzw
 199  0x00001764:       div r4.x, r4.x, r4.y
 200  0x00001780:       add r4.x, -r1.z, r4.x
 201  0x000017A0:       ge r4.x, |r4.x|, r1.w
 202  0x000017C0:       and r4.x, r4.x, l(0x3f800000)
 203  0x000017DC:       mad r3.w, r4.x, cb2[7].z, r3.w
 204  0x00001804:     endif 
 205  0x00001808:     mov r4.z, r4.w
 206  0x0000181C:   else 
 207  0x00001820:     mov r4.w, l(-1)
 208  0x00001834:   endif 
 209  0x00001838:   not r4.xy, r4.wzww
 210  0x0000184C:   and r4.x, r4.y, r4.x
 211  0x00001868:   if_nz r4.x
 212  0x00001874:     add r4.xy, v1.xyxx, cb2[8].xyxx
 213  0x00001894:     mul r1.xy, r1.xyxx, r4.xyxx
 214  0x000018B0:     ftoi r6.xy, r1.xyxx
 215  0x000018C4:     mov r6.zw, l(0,0,0,0)
 216  0x000018E4:     ld_indexable(texture2d)(uint,uint,uint,uint) r1.x, r6.xyzw, t1.zxyw
 217  0x00001908:     ushr r1.x, r1.x, l(24)
 218  0x00001924:     and r1.x, r1.x, l(4)
 219  0x00001940:     ine r4.z, r1.x, l(0)
 220  0x0000195C:     if_z r4.z
 221  0x00001968:       sample_l_indexable(texture2d)(float,float,float,float) r6.z, r4.xyxx, t2.yzxw, s1, l(0.000000)
 222  0x0000199C:       mad r6.xy, r4.xyxx, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
 223  0x000019D8:       mov r6.w, l(1.000000)
 224  0x000019EC:       dp4 r1.x, r6.xyzw, cb0[14].xyzw
 225  0x00001A0C:       dp4 r1.y, r6.xyzw, cb0[15].xyzw
 226  0x00001A2C:       div r1.x, r1.x, r1.y
 227  0x00001A48:       add r1.x, -r1.z, r1.x
 228  0x00001A68:       ge r1.x, |r1.x|, r1.w
 229  0x00001A88:       and r1.x, r1.x, l(0x3f800000)
 230  0x00001AA4:       mad r3.w, r1.x, cb2[8].z, r3.w
 231  0x00001ACC:     endif 
 232  0x00001AD0:   endif 
 233  0x00001AD4:   ubfe r6.xyzw, l(4, 4, 4, 4), l(16, 20, 24, 28), r2.yzwx
 234  0x00001B10:   utof r6.xyzw, r6.xyzw
 235  0x00001B24:   mul r1.x, r6.w, l(0.066667)
 236  0x00001B40:   lt r1.y, l(0.000000), r6.w
 237  0x00001B5C:   mul r1.w, r3.w, r3.w
 238  0x00001B78:   mul r1.x, r1.x, r1.w
 239  0x00001B94:   mul r1.x, r1.x, cb2[0].y
 240  0x00001BB4:   mul r1.z, -r1.z, cb2[0].x
 241  0x00001BD8:   min r1.xz, r1.xxzx, l(1.000000, 0.000000, 1.000000, 0.000000)
 242  0x00001C00:   add r1.z, -r1.z, l(1.000000)
 243  0x00001C20:   mul r1.x, r1.z, r1.x
 244  0x00001C3C:   dp3 r4.x, cb0[26].xyzx, cb0[0].xyzx
 245  0x00001C60:   dp3 r4.y, cb0[26].xyzx, cb0[1].xyzx
 246  0x00001C84:   dp2 r1.z, r4.xyxx, r4.xyxx
 247  0x00001CA0:   rsq r1.z, r1.z
 248  0x00001CB4:   mul r1.zw, r1.zzzz, r4.xxxy
 249  0x00001CD0:   dp3 r7.x, r5.xyzx, cb0[0].xyzx
 250  0x00001CF0:   dp3 r7.y, r5.xyzx, cb0[1].xyzx
 251  0x00001D10:   dp3 r7.z, r5.xyzx, cb0[2].xyzx
 252  0x00001D30:   dp3 r3.w, r7.xyzx, r7.xyzx
 253  0x00001D4C:   rsq r3.w, r3.w
 254  0x00001D60:   mul r4.xy, r3.wwww, r7.xyxx
 255  0x00001D7C:   dp2 r1.z, r4.xyxx, r1.zwzz
 256  0x00001D98:   mad r1.z, r1.z, l(0.500000), l(0.500000)
 257  0x00001DBC:   log r1.z, |r1.z|
 258  0x00001DD4:   mul r1.z, r1.z, l(0.400000)
 259  0x00001DF0:   exp r1.z, r1.z
 260  0x00001E04:   mul r1.x, r1.z, r1.x
 261  0x00001E20:   mad r4.xyw, r6.xyxz, l(0.066667, 0.066667, 0.000000, 0.066667), -r0.xyxz
 262  0x00001E54:   mad r1.xzw, r1.xxxx, r4.xxyw, r0.xxyz
 263  0x00001E78:   movc r1.xyz, r1.yyyy, r1.xzwx, r0.xyzx
 264  0x00001E9C:   movc o0.xyz, r4.zzzz, r0.xyzx, r1.xyzx
 265  0x00001EC0:   mov o0.w, r0.w
 266  0x00001ED4:   mov o1.xyzw, r2.yzwx
 267  0x00001EE8:   ret 
 268  0x00001EEC: else 
 269  0x00001EF0:   and r1.x, r3.z, l(8)
 270  0x00001F0C:   if_z r1.x
 271  0x00001F18:     mov o0.xyzw, r0.xyzw
 272  0x00001F2C:     mov o1.xyzw, r2.yzwx
 273  0x00001F40:     ret 
 274  0x00001F44:   endif 
 275  0x00001F48: endif 
 276  0x00001F4C: sample_l_indexable(texture2d)(float,float,float,float) r1.z, v1.xyxx, t2.yzxw, s0, l(0.000000)
 277  0x00001F80: ushr r4.xyzw, r2.zwwy, l(16, 8, 16, 16)
 278  0x00001FA8: mov r5.x, r2.z
 279  0x00001FBC: mov r5.y, r4.x
 280  0x00001FD0: and r5.xy, r5.xyxx, l(0x0000ffff, 0x0000ffff, 0, 0)
 281  0x00001FF8: mov r6.xz, r2.yyyy
 282  0x0000200C: mov r6.yw, r4.wwww
 283  0x00002020: and r6.xyzw, r6.xyzw, l(0x0000ffff, 0x0000ffff, 0x0000ffff, 0x0000ffff)
 284  0x00002048: utof r6.xyzw, r6.xyzw
 285  0x0000205C: mul r6.xyzw, r6.xyzw, l(0.000015, 0.000015, 1.000000, 1.000000)
 286  0x00002084: utof r0.w, r5.x
 287  0x00002098: mul r7.xy, r0.wwww, l(0.000015, 1.000000, 0.000000, 0.000000)
 288  0x000020C0: mov r7.zw, r6.xxxy
 289  0x000020D4: add r5.xzw, r7.zzwx, l(-0.500000, 0.000000, -0.500000, -0.500000)
 290  0x000020FC: add r7.xzw, r5.xxzw, r5.xxzw
 291  0x00002118: mov r4.x, r2.w
 292  0x0000212C: and r4.xyz, r4.xyzx, l(255, 255, 255, 0)
 293  0x00002154: utof r4.xyz, r4.xyzx
 294  0x00002168: mul r4.xyz, r4.xyzx, l(0.003922, 0.003922, 0.003922, 0.000000)
 295  0x00002190: ushr r2.yzw, r2.xxxx, l(0, 8, 16, 24)
 296  0x000021B8: and r2.xyzw, r2.xyzw, l(255, 255, 255, 255)
 297  0x000021E0: utof r2.xyzw, r2.xyzw
 298  0x000021F4: mul r8.xyzw, r2.wxyz, l(0.003922, 0.003922, 0.003922, 0.003922)
 299  0x0000221C: umin r0.w, r5.y, l(0x00004e1f)
 300  0x00002238: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r9.xyzw, r0.w, l(0), t3.xyzw
 301  0x00002264: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r10.xyzw, r0.w, l(16), t3.xyzw
 302  0x00002290: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r11.xyzw, r0.w, l(32), t3.xyzw
 303  0x000022BC: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r12.xyz, r0.w, l(48), t3.xyzx
 304  0x000022E8: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r13.xyzw, r0.w, l(64), t3.xyzw
 305  0x00002314: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r14.xyzw, r0.w, l(80), t3.xyzw
 306  0x00002340: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r15.xyzw, r0.w, l(96), t3.xyzw
 307  0x0000236C: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r2.xyz, r0.w, l(112), t3.xyzx
 308  0x00002398: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r5.xy, r0.w, l(128), t3.xyxx
 309  0x000023C4: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r0.w, r0.w, l(140), t3.xxxx
 310  0x000023F0: mov r12.w, r13.x
 311  0x00002404: mov r16.xz, r12.yyzy
 312  0x00002418: mov r16.yw, r13.yyyz
 313  0x0000242C: add r6.xy, -r12.xwxx, r16.xyxx
 314  0x0000244C: mad r6.xy, r8.yyyy, r6.xyxx, r12.xwxx
 315  0x00002470: add r12.xy, -r6.xyxx, r16.zwzz
 316  0x00002490: mad r6.xy, r8.zzzz, r12.xyxx, r6.xyxx
 317  0x000024B4: mad r12.xyz, cb0[47].xyzx, r7.xxxx, cb0[46].xyzx
 318  0x000024E0: mad r12.xyz, cb0[48].xyzx, r7.zzzz, r12.xyzx
 319  0x00002508: mad r12.xyz, cb0[49].xyzx, r7.wwww, r12.xyzx
 320  0x00002530: mul r13.xyz, r7.wwww, cb0[50].xyzx
 321  0x00002550: mad r12.xyz, r13.xyzx, r7.xxxx, r12.xyzx
 322  0x00002574: mul r13.xyz, r7.zzzz, cb0[51].xyzx
 323  0x00002594: mad r12.xyz, r13.xyzx, r7.wwww, r12.xyzx
 324  0x000025B8: mul r13.xyz, r7.zzzz, cb0[52].xyzx
 325  0x000025D8: mad r12.xyz, r13.xyzx, r7.xxxx, r12.xyzx
 326  0x000025FC: mul r3.w, r5.w, r7.w
 327  0x00002618: mad r3.w, r3.w, l(6.000000), l(-1.000000)
 328  0x0000263C: mad r12.xyz, cb0[53].xyzx, r3.wwww, r12.xyzx
 329  0x00002664: mul r3.w, r7.z, r7.z
 330  0x00002680: mad r3.w, r7.x, r7.x, -r3.w
 331  0x000026A8: mad r12.xyz, cb0[54].xyzx, r3.wwww, r12.xyzx
 332  0x000026D0: mad r1.xy, v1.zwzz, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
 333  0x0000270C: mov r1.w, l(1.000000)
 334  0x00002720: dp4 r16.x, r1.xyzw, cb0[20].xyzw
 335  0x00002740: dp4 r16.y, r1.xyzw, cb0[21].xyzw
 336  0x00002760: dp4 r16.z, r1.xyzw, cb0[22].xyzw
 337  0x00002780: dp4 r16.w, r1.xyzw, cb0[23].xyzw
 338  0x000027A0: div r1.xyzw, r16.xyzw, r16.wwww
 339  0x000027BC: dp4 r3.w, cb0[2].xyzw, r1.xyzw
 340  0x000027DC: mov r13.x, cb0[4].w
 341  0x000027F4: mov r13.y, cb0[5].w
 342  0x0000280C: mov r13.z, cb0[6].w
 343  0x00002824: add r16.xyz, -r1.xyzx, r13.xyzx
 344  0x00002844: dp3 r4.w, r16.xyzx, r16.xyzx
 345  0x00002860: rsq r4.w, r4.w
 346  0x00002874: mul r17.xyz, r4.wwww, r16.xyzx
 347  0x00002890: add r9.xyz, r9.xyzx, cb0[36].xyzx
 348  0x000028B0: min r9.xyz, r9.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 349  0x000028D8: mul r5.z, r8.w, r9.w
 350  0x000028F4: dp3 r5.w, r7.xzwx, r17.xyzx
 351  0x00002910: and r18.xyzw, r0.wwww, l(1, 2, 4, 16)
 352  0x00002938: if_nz r18.x
 353  0x00002944:   add r13.xyz, r1.xyzx, -r13.xyzx
 354  0x00002964:   dp3 r8.y, r13.xyzx, r13.xyzx
 355  0x00002980:   sqrt r8.y, r8.y
 356  0x00002994:   div r8.z, l(30.000000), cb0[59].w
 357  0x000029B4:   add r9.w, l(-5.000000), cb0[59].w
 358  0x000029D4:   lt r9.w, r9.w, r8.y
 359  0x000029F0:   if_nz r9.w
 360  0x000029FC:     dp4 r13.x, r1.xyzw, cb0[55].xyzw
 361  0x00002A1C:     dp4 r13.y, r1.xyzw, cb0[56].xyzw
 362  0x00002A3C:     dp4 r13.z, r1.xyzw, cb0[57].xyzw
 363  0x00002A5C:     dp4 r9.w, r1.xyzw, cb0[58].xyzw
 364  0x00002A7C:     div r13.xyz, r13.xyzx, r9.wwww
 365  0x00002A98:     lt r19.xy, r13.xyxx, l(0.000000, 0.000000, 0.000000, 0.000000)
 366  0x00002AC0:     lt r19.zw, l(0.000000, 0.000000, 1.000000, 1.000000), r13.xxxy
 367  0x00002AE8:     or r9.w, r19.z, r19.x
 368  0x00002B04:     or r9.w, r19.y, r9.w
 369  0x00002B20:     or r9.w, r19.w, r9.w
 370  0x00002B3C:     if_nz r9.w
 371  0x00002B48:       mov r9.w, l(1.000000)
 372  0x00002B5C:     else 
 373  0x00002B60:       mov_sat r13.xy, r13.xyxx
 374  0x00002B74:       sample_c_lz_indexable(texture2d)(float,float,float,float) r9.w, r13.xyxx, t21.xxxx, s13, r13.z
 375  0x00002BA8:     endif 
 376  0x00002BAC:     lt r12.w, r8.y, cb0[59].w
 377  0x00002BCC:     if_nz r12.w
 378  0x00002BD8:       dp4 r13.x, r1.xyzw, cb0[31].xyzw
 379  0x00002BF8:       dp4 r13.y, r1.xyzw, cb0[32].xyzw
 380  0x00002C18:       dp4 r13.z, r1.xyzw, cb0[33].xyzw
 381  0x00002C38:       dp4 r12.w, r1.xyzw, cb0[34].xyzw
 382  0x00002C58:       div r13.xyz, r13.xyzx, r12.wwww
 383  0x00002C74:       mul r19.xy, r8.zzzz, l(0.000500, 0.000250, 0.000000, 0.000000)
 384  0x00002C9C:       lt r12.w, l(0.500000), r13.y
 385  0x00002CB8:       add r20.x, l(0.500000), cb0[35].x
 386  0x00002CD8:       mov r20.yz, l(0,1.000000,0,0)
 387  0x00002CF8:       add r20.w, l(0.500000), -cb0[35].x
 388  0x00002D1C:       movc r19.zw, r12.wwww, r20.xxxy, r20.zzzw
 389  0x00002D40:       dp2 r12.w, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
 390  0x00002D68:       frc r12.w, r12.w
 391  0x00002D7C:       mul r12.w, r12.w, l(52.982918)
 392  0x00002D98:       frc r12.w, r12.w
 393  0x00002DAC:       mul r12.w, r12.w, l(6.283185)
 394  0x00002DC8:       mov r16.w, l(0)
 395  0x00002DDC:       mov r17.w, l(0)
 396  0x00002DF0:       loop 
 397  0x00002DF4:         ige r18.x, r17.w, l(16)
 398  0x00002E10:         breakc_nz r18.x
 399  0x00002E1C:         itof r18.x, r17.w
 400  0x00002E30:         add r20.x, r18.x, l(0.500000)
 401  0x00002E4C:         sqrt r20.x, r20.x
 402  0x00002E60:         mul r20.x, r20.x, l(0.250000)
 403  0x00002E7C:         mad r18.x, r18.x, l(2.400000), r12.w
 404  0x00002EA0:         sincos r18.x, r21.x, r18.x
 405  0x00002EBC:         mul r21.x, r20.x, r21.x
 406  0x00002ED8:         mul r21.y, r18.x, r20.x
 407  0x00002EF4:         mad r20.xy, r21.xyxx, r19.xyxx, r13.xyxx
 408  0x00002F18:         max r18.x, r19.z, r20.y
 409  0x00002F34:         min r20.z, r19.w, r18.x
 410  0x00002F50:         sample_c_lz_indexable(texture2d)(float,float,float,float) r18.x, r20.xzxx, t16.xxxx, s13, r13.z
 411  0x00002F84:         add r16.w, r16.w, r18.x
 412  0x00002FA0:         iadd r17.w, r17.w, l(1)
 413  0x00002FBC:       endloop 
 414  0x00002FC0:       add r12.w, -r8.y, cb0[59].w
 415  0x00002FE4:       mul r12.w, r12.w, l(0.200000)
 416  0x00003000:       mad r13.x, r16.w, l(0.062500), -r9.w
 417  0x00003028:       mad r9.w, r12.w, r13.x, r9.w
 418  0x0000304C:     endif 
 419  0x00003050:   else 
 420  0x00003054:     lt r12.w, r8.y, cb0[26].w
 421  0x00003074:     movc r19.xyzw, r12.wwww, cb0[27].xyzw, cb0[31].xyzw
 422  0x000030A0:     movc r20.xyzw, r12.wwww, cb0[28].xyzw, cb0[32].xyzw
 423  0x000030CC:     movc r21.xyzw, r12.wwww, cb0[29].xyzw, cb0[33].xyzw
 424  0x000030F8:     movc r22.xyzw, r12.wwww, cb0[30].xyzw, cb0[34].xyzw
 425  0x00003124:     dp4 r13.x, r1.xyzw, r19.xyzw
 426  0x00003140:     dp4 r13.y, r1.xyzw, r20.xyzw
 427  0x0000315C:     dp4 r13.z, r1.xyzw, r21.xyzw
 428  0x00003178:     dp4 r16.w, r1.xyzw, r22.xyzw
 429  0x00003194:     div r13.xyz, r13.xyzx, r16.wwww
 430  0x000031B0:     movc r16.w, r12.w, cb0[63].x, l(1.000000)
 431  0x000031D8:     mul r16.w, r8.z, r16.w
 432  0x000031F4:     mul r19.xy, r16.wwww, l(0.000500, 0.000250, 0.000000, 0.000000)
 433  0x0000321C:     lt r16.w, l(0.500000), r13.y
 434  0x00003238:     add r20.x, l(0.500000), cb0[35].x
 435  0x00003258:     mov r20.yz, l(0,1.000000,0,0)
 436  0x00003278:     add r20.w, l(0.500000), -cb0[35].x
 437  0x0000329C:     movc r19.zw, r16.wwww, r20.xxxy, r20.zzzw
 438  0x000032C0:     dp2 r16.w, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
 439  0x000032E8:     frc r16.w, r16.w
 440  0x000032FC:     mul r16.w, r16.w, l(52.982918)
 441  0x00003318:     frc r16.w, r16.w
 442  0x0000332C:     mul r16.w, r16.w, l(6.283185)
 443  0x00003348:     mov r17.w, l(0)
 444  0x0000335C:     mov r18.x, l(0)
 445  0x00003370:     loop 
 446  0x00003374:       ige r20.x, r18.x, l(16)
 447  0x00003390:       breakc_nz r20.x
 448  0x0000339C:       itof r20.x, r18.x
 449  0x000033B0:       add r20.y, r20.x, l(0.500000)
 450  0x000033CC:       sqrt r20.y, r20.y
 451  0x000033E0:       mul r20.y, r20.y, l(0.250000)
 452  0x000033FC:       mad r20.x, r20.x, l(2.400000), r16.w
 453  0x00003420:       sincos r20.x, r21.x, r20.x
 454  0x0000343C:       mul r21.x, r20.y, r21.x
 455  0x00003458:       mul r21.y, r20.x, r20.y
 456  0x00003474:       mad r20.xy, r21.xyxx, r19.xyxx, r13.xyxx
 457  0x00003498:       max r20.y, r19.z, r20.y
 458  0x000034B4:       min r20.z, r19.w, r20.y
 459  0x000034D0:       sample_c_lz_indexable(texture2d)(float,float,float,float) r20.x, r20.xzxx, t16.xxxx, s13, r13.z
 460  0x00003504:       add r17.w, r17.w, r20.x
 461  0x00003520:       iadd r18.x, r18.x, l(1)
 462  0x0000353C:     endloop 
 463  0x00003540:     mul r9.w, r17.w, l(0.062500)
 464  0x0000355C:     add r13.x, l(-1.000000), cb0[26].w
 465  0x0000357C:     lt r13.x, r13.x, r8.y
 466  0x00003598:     and r12.w, r12.w, r13.x
 467  0x000035B4:     if_nz r12.w
 468  0x000035C0:       dp4 r13.x, r1.xyzw, cb0[31].xyzw
 469  0x000035E0:       dp4 r13.y, r1.xyzw, cb0[32].xyzw
 470  0x00003600:       dp4 r13.z, r1.xyzw, cb0[33].xyzw
 471  0x00003620:       dp4 r12.w, r1.xyzw, cb0[34].xyzw
 472  0x00003640:       div r13.xyz, r13.xyzx, r12.wwww
 473  0x0000365C:       mul r19.xy, r8.zzzz, l(0.000500, 0.000250, 0.000000, 0.000000)
 474  0x00003684:       lt r8.z, l(0.500000), r13.y
 475  0x000036A0:       add r20.x, l(0.500000), cb0[35].x
 476  0x000036C0:       mov r20.yz, l(0,1.000000,0,0)
 477  0x000036E0:       add r20.w, l(0.500000), -cb0[35].x
 478  0x00003704:       movc r19.zw, r8.zzzz, r20.xxxy, r20.zzzw
 479  0x00003728:       dp2 r8.z, v0.xyxx, l(0.067111, 0.005837, 0.000000, 0.000000)
 480  0x00003750:       frc r8.z, r8.z
 481  0x00003764:       mul r8.z, r8.z, l(52.982918)
 482  0x00003780:       frc r8.z, r8.z
 483  0x00003794:       mul r8.z, r8.z, l(6.283185)
 484  0x000037B0:       mov r12.w, l(0)
 485  0x000037C4:       mov r16.w, l(0)
 486  0x000037D8:       loop 
 487  0x000037DC:         ige r18.x, r16.w, l(16)
 488  0x000037F8:         breakc_nz r18.x
 489  0x00003804:         itof r18.x, r16.w
 490  0x00003818:         add r20.x, r18.x, l(0.500000)
 491  0x00003834:         sqrt r20.x, r20.x
 492  0x00003848:         mul r20.x, r20.x, l(0.250000)
 493  0x00003864:         mad r18.x, r18.x, l(2.400000), r8.z
 494  0x00003888:         sincos r18.x, r21.x, r18.x
 495  0x000038A4:         mul r21.x, r20.x, r21.x
 496  0x000038C0:         mul r21.y, r18.x, r20.x
 497  0x000038DC:         mad r20.xy, r21.xyxx, r19.xyxx, r13.xyxx
 498  0x00003900:         max r18.x, r19.z, r20.y
 499  0x0000391C:         min r20.z, r19.w, r18.x
 500  0x00003938:         sample_c_lz_indexable(texture2d)(float,float,float,float) r18.x, r20.xzxx, t16.xxxx, s13, r13.z
 501  0x0000396C:         add r12.w, r12.w, r18.x
 502  0x00003988:         iadd r16.w, r16.w, l(1)
 503  0x000039A4:       endloop 
 504  0x000039A8:       mul r8.z, r12.w, l(0.062500)
 505  0x000039C4:       add r8.y, -r8.y, cb0[26].w
 506  0x000039E8:       mad r12.w, r17.w, l(0.062500), -r8.z
 507  0x00003A10:       mad r9.w, r8.y, r12.w, r8.z
 508  0x00003A34:     endif 
 509  0x00003A38:   endif 
 510  0x00003A3C: else 
 511  0x00003A40:   mov r9.w, l(1.000000)
 512  0x00003A54: endif 
 513  0x00003A58: mad r13.xyz, r16.xyzx, r4.wwww, -cb0[26].xyzx
 514  0x00003A84: dp3 r8.y, r13.xyzx, r13.xyzx
 515  0x00003AA0: rsq r8.y, r8.y
 516  0x00003AB4: mul r13.xyz, r8.yyyy, r13.xyzx
 517  0x00003AD0: mul r8.y, r6.y, cb0[41].y
 518  0x00003AF0: dp3_sat r8.z, r13.xyzx, r7.xzwx
 519  0x00003B0C: max r8.y, r8.y, l(0.001000)
 520  0x00003B28: log r8.z, r8.z
 521  0x00003B3C: mul r8.y, r8.z, r8.y
 522  0x00003B58: exp r8.y, r8.y
 523  0x00003B6C: mul r8.y, r9.w, r8.y
 524  0x00003B88: mul r8.y, r8.y, cb0[41].z
 525  0x00003BA8: movc r8.y, r18.y, r8.y, l(0)
 526  0x00003BCC: mul r10.xyz, r10.xyzx, r8.yyyy
 527  0x00003BE8: mul r10.xyz, r10.xyzx, cb0[25].xyzx
 528  0x00003C08: if_nz r18.z
 529  0x00003C14:   mul r8.yz, r4.xxyx, r14.yyzy
 530  0x00003C30:   and r4.x, r0.w, l(32)
 531  0x00003C4C:   if_nz r4.x
 532  0x00003C58:     mad r13.xy, v1.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000), l(0.000000, 1.000000, 0.000000, 0.000000)
 533  0x00003C94:     sample_l_indexable(texture2d)(float,float,float,float) r13.xyz, r13.xyxx, t15.xyzw, s15, l(0.000000)
 534  0x00003CC8:   else 
 535  0x00003CCC:     add r12.w, r5.w, r5.w
 536  0x00003CE8:     mad r19.xyz, r7.xzwx, -r12.wwww, r17.xyzx
 537  0x00003D10:     resinfo_indexable(texturecube)(float,float,float,float)_uint r12.w, l(0), t17.xyzw
 538  0x00003D34:     mul r19.xyz, r19.xyzx, l(1.000000, -1.000000, -1.000000, 0.000000)
 539  0x00003D5C:     iadd r12.w, r12.w, l(-1)
 540  0x00003D78:     utof r12.w, r12.w
 541  0x00003D8C:     mul r12.w, r8.z, r12.w
 542  0x00003DA8:     sample_l_indexable(texturecube)(float,float,float,float) r13.xyz, r19.xyzx, t17.xyzw, s14, r12.w
 543  0x00003DDC:   endif 
 544  0x00003DE0:   and r12.w, r3.z, l(2)
 545  0x00003DFC:   if_nz r12.w
 546  0x00003E08:     sample_l_indexable(texture2d)(float,float,float,float) r19.xyzw, v1.xyxx, t14.xyzw, s15, l(0.000000)
 547  0x00003E3C:     add r19.xyz, -r13.xyzx, r19.xyzx
 548  0x00003E5C:     mad r13.xyz, r19.wwww, r19.xyzx, r13.xyzx
 549  0x00003E80:   endif 
 550  0x00003E84:   lt r12.w, l(0.000000), r6.x
 551  0x00003EA0:   add r14.y, -|r5.w|, l(1.000000)
 552  0x00003EC0:   max r14.y, r14.y, l(0.000000)
 553  0x00003EDC:   log r14.y, r14.y
 554  0x00003EF0:   mul r6.x, r6.x, r14.y
 555  0x00003F0C:   exp r6.x, r6.x
 556  0x00003F20:   movc r6.x, r12.w, r6.x, l(1.000000)
 557  0x00003F44:   mul r12.w, r6.x, r8.y
 558  0x00003F60:   mad r19.xyz, r0.xyzx, r13.xyzx, -r0.xyzx
 559  0x00003F88:   mad r19.xyz, r12.wwww, r19.xyzx, r0.xyzx
 560  0x00003FAC:   dp3 r12.w, r13.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
 561  0x00003FD4:   mad r8.z, r8.z, l(-9.000000), l(10.000000)
 562  0x00003FF8:   log r12.w, r12.w
 563  0x0000400C:   mul r8.z, r8.z, r12.w
 564  0x00004028:   exp r8.z, r8.z
 565  0x0000403C:   add r12.w, -r8.z, l(1.000000)
 566  0x0000405C:   mad r8.y, r8.y, r12.w, r8.z
 567  0x00004080:   mul r13.xyz, r8.yyyy, r13.xyzx
 568  0x0000409C:   mul r13.xyz, r6.xxxx, r13.xyzx
 569  0x000040B8:   mad r6.x, -r4.y, r14.z, l(1.000000)
 570  0x000040E0:   mad r13.xyz, r13.xyzx, r6.xxxx, r10.xyzx
 571  0x00004104:   movc r10.xyz, r4.xxxx, r10.xyzx, r13.xyzx
 572  0x00004128: else 
 573  0x0000412C:   and r0.w, r0.w, l(8)
 574  0x00004148:   if_nz r0.w
 575  0x00004154:     add r0.w, r5.w, r5.w
 576  0x00004170:     mad r13.xyz, r7.xzwx, -r0.wwww, r17.xyzx
 577  0x00004198:     div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r14.w
 578  0x000041C0:     dp3 r4.x, -r17.xyzx, r7.xzwx
 579  0x000041E0:     mul r6.x, r0.w, r0.w
 580  0x000041FC:     mad r8.y, -r4.x, r4.x, l(1.000000)
 581  0x00004224:     mad r6.x, -r6.x, r8.y, l(1.000000)
 582  0x0000424C:     sqrt r8.y, r6.x
 583  0x00004260:     mad r4.x, r0.w, r4.x, r8.y
 584  0x00004284:     ge r6.x, r6.x, l(0.000000)
 585  0x000042A0:     mul r20.xyz, r7.xzwx, r4.xxxx
 586  0x000042BC:     mad r17.xyz, r0.wwww, -r17.xyzx, -r20.xyzx
 587  0x000042E8:     and r17.xyz, r6.xxxx, r17.xyzx
 588  0x00004304:     mul r0.w, r4.y, r14.z
 589  0x00004320:     resinfo_indexable(texturecube)(float,float,float,float)_uint r4.x, l(0), t17.wxyz
 590  0x00004344:     mul r13.xyz, r13.xyzx, l(1.000000, -1.000000, -1.000000, 0.000000)
 591  0x0000436C:     iadd r4.x, r4.x, l(-1)
 592  0x00004388:     utof r4.x, r4.x
 593  0x0000439C:     mul r0.w, r0.w, r4.x
 594  0x000043B8:     sample_l_indexable(texturecube)(float,float,float,float) r13.xyz, r13.xyzx, t17.xyzw, s14, r0.w
 595  0x000043EC:     and r4.x, r3.z, l(2)
 596  0x00004408:     if_nz r4.x
 597  0x00004414:       sample_l_indexable(texture2d)(float,float,float,float) r20.xyzw, v1.xyxx, t14.xyzw, s15, l(0.000000)
 598  0x00004448:       add r20.xyz, -r13.xyzx, r20.xyzx
 599  0x00004468:       mad r13.xyz, r20.wwww, r20.xyzx, r13.xyzx
 600  0x0000448C:     endif 
 601  0x00004490:     sample_l_indexable(texturecube)(float,float,float,float) r17.xyz, r17.xyzx, t17.xyzw, s14, r0.w
 602  0x000044C4:     lt r0.w, l(0.000000), r15.x
 603  0x000044E0:     add r4.x, -|r5.w|, l(1.000000)
 604  0x00004500:     max r4.x, r4.x, l(0.000000)
 605  0x0000451C:     log r4.x, r4.x
 606  0x00004530:     mul r4.x, r4.x, r15.x
 607  0x0000454C:     exp r4.x, r4.x
 608  0x00004560:     movc r0.w, r0.w, r4.x, l(1.000000)
 609  0x00004584:     mad r20.xyz, r0.xyzx, r13.xyzx, -r0.xyzx
 610  0x000045AC:     mad r20.xyz, r0.wwww, r20.xyzx, r0.xyzx
 611  0x000045D0:     mad r2.w, -r2.w, l(0.003922), l(1.000000)
 612  0x000045F8:     mad r8.x, r0.w, r2.w, r8.x
 613  0x0000461C:     mul r2.w, r15.y, |r5.w|
 614  0x0000463C:     log r2.w, r2.w
 615  0x00004650:     mul r2.w, r2.w, r15.z
 616  0x0000466C:     exp r2.w, r2.w
 617  0x00004680:     mul r13.xyz, r13.xyzx, r8.xxxx
 618  0x0000469C:     mul r13.xyz, r0.wwww, r13.xyzx
 619  0x000046B8:     mad r0.w, -r4.y, r14.z, l(1.000000)
 620  0x000046E0:     mad r10.xyz, r13.xyzx, r0.wwww, r10.xyzx
 621  0x00004704:     mul r13.xyz, r17.xyzx, r2.wwww
 622  0x00004720:     mul r19.xyz, r13.xyzx, r20.xyzx
 623  0x0000473C:   else 
 624  0x00004740:     mov r19.xyz, r0.xyzx
 625  0x00004754:   endif 
 626  0x00004758: endif 
 627  0x0000475C: mul r0.w, r9.w, r8.x
 628  0x00004778: add r8.xyz, -r9.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 629  0x000047A4: mad r8.xyz, r0.wwww, r8.xyzx, r9.xyzx
 630  0x000047C8: mad r8.xyz, r8.xyzx, cb0[25].xyzx, r12.xyzx
 631  0x000047F0: min r0.w, r5.z, l(1.000000)
 632  0x0000480C: add r9.xyz, -r8.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 633  0x00004838: mad r8.xyz, r0.wwww, r9.xyzx, r8.xyzx
 634  0x0000485C: add r0.w, -|r5.w|, l(1.000000)
 635  0x0000487C: max r0.w, r0.w, l(0.000000)
 636  0x00004898: mul r0.w, r11.w, r0.w
 637  0x000048B4: log r0.w, r0.w
 638  0x000048C8: mul r0.w, r0.w, r10.w
 639  0x000048E4: exp r0.w, r0.w
 640  0x000048F8: min r0.w, r0.w, l(1.000000)
 641  0x00004914: mad r9.xyz, r11.xyzx, r0.wwww, r10.xyzx
 642  0x00004938: if_nz r18.y
 643  0x00004944:   mul r4.xy, v0.xyxx, cb0[38].xyxx
 644  0x00004964:   mul r0.w, -r3.w, cb0[41].w
 645  0x00004988:   min r0.w, r0.w, l(7.000000)
 646  0x000049A4:   max r0.w, r0.w, l(0.000000)
 647  0x000049C0:   ftou r4.xy, r4.xyxx
 648  0x000049D4:   ftou r0.w, r0.w
 649  0x000049E8:   ishl r2.w, r4.y, l(5)
 650  0x00004A04:   imad r0.w, r0.w, l(576), r2.w
 651  0x00004A28:   iadd r0.w, r4.x, r0.w
 652  0x00004A44:   umin r0.w, r0.w, l(4607)
 653  0x00004A60:   ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r2.w, r0.w, l(252), t19.xxxx
 654  0x00004A8C:   umin r2.w, r2.w, l(63)
 655  0x00004AA8:   mov r10.xyz, l(0,0,0,0)
 656  0x00004AC8:   mov r11.xyz, l(0,0,0,0)
 657  0x00004AE8:   mov r4.x, l(0)
 658  0x00004AFC:   loop 
 659  0x00004B00:     uge r4.y, r4.x, r2.w
 660  0x00004B1C:     breakc_nz r4.y
 661  0x00004B28:     ishl r4.y, r4.x, l(2)
 662  0x00004B44:     ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r4.y, r0.w, r4.y, t19.xxxx
 663  0x00004B70:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r12.xyz, r4.y, l(0), t18.xyzx
 664  0x00004B9C:     add r12.xyz, -r1.xyzx, r12.xyzx
 665  0x00004BBC:     dp3 r5.z, r12.xyzx, r12.xyzx
 666  0x00004BD8:     sqrt r5.w, r5.z
 667  0x00004BEC:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.x, r4.y, l(28), t18.xxxx
 668  0x00004C18:     mul r5.w, r5.w, r6.x
 669  0x00004C34:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.x, r4.y, l(44), t18.xxxx
 670  0x00004C60:     log r5.w, |r5.w|
 671  0x00004C78:     mul r5.w, r5.w, r6.x
 672  0x00004C94:     exp r5.w, r5.w
 673  0x00004CA8:     add r5.w, -r5.w, l(1.000000)
 674  0x00004CC8:     max r5.w, r5.w, l(0.000000)
 675  0x00004CE4:     lt r6.x, l(0.000000), r5.w
 676  0x00004D00:     if_nz r6.x
 677  0x00004D0C:       rsq r5.z, r5.z
 678  0x00004D20:       mul r12.xyz, r5.zzzz, r12.xyzx
 679  0x00004D3C:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r5.z, r4.y, l(96), t18.xxxx
 680  0x00004D68:       dp3 r6.x, r12.xyzx, r7.xzwx
 681  0x00004D84:       max r5.z, r5.z, r6.x
 682  0x00004DA0:       mul r5.z, r5.z, r5.w
 683  0x00004DBC:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r13.xyz, r4.y, l(16), t18.xyzx
 684  0x00004DE8:       mad r11.xyz, r13.xyzx, r5.zzzz, r11.xyzx
 685  0x00004E0C:       mad r12.xyz, r16.xyzx, r4.wwww, r12.xyzx
 686  0x00004E30:       dp3 r5.w, r12.xyzx, r12.xyzx
 687  0x00004E4C:       rsq r5.w, r5.w
 688  0x00004E60:       mul r12.xyz, r5.wwww, r12.xyzx
 689  0x00004E7C:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r14.yz, r4.y, l(68), t18.xxyx
 690  0x00004EA8:       mul r4.y, r6.y, r14.z
 691  0x00004EC4:       dp3_sat r5.w, r12.xyzx, r7.xzwx
 692  0x00004EE0:       max r4.y, r4.y, l(0.001000)
 693  0x00004EFC:       log r5.w, r5.w
 694  0x00004F10:       mul r4.y, r4.y, r5.w
 695  0x00004F2C:       exp r4.y, r4.y
 696  0x00004F40:       mul r12.xyz, r4.yyyy, r13.xyzx
 697  0x00004F5C:       mul r12.xyz, r5.zzzz, r12.xyzx
 698  0x00004F78:       mad r10.xyz, r12.xyzx, r14.yyyy, r10.xyzx
 699  0x00004F9C:     endif 
 700  0x00004FA0:     iadd r4.x, r4.x, l(1)
 701  0x00004FBC:   endloop 
 702  0x00004FC0:   mad r11.xyz, r11.xyzx, r13.wwww, r8.xyzx
 703  0x00004FE4:   ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r2.w, r0.w, l(508), t19.xxxx
 704  0x00005010:   umin r2.w, r2.w, l(63)
 705  0x0000502C:   mov r12.xyz, r10.xyzx
 706  0x00005040:   mov r13.xyz, l(0,0,0,0)
 707  0x00005060:   mov r4.x, l(0)
 708  0x00005074:   loop 
 709  0x00005078:     uge r4.y, r4.x, r2.w
 710  0x00005094:     breakc_nz r4.y
 711  0x000050A0:     ishl r4.y, r4.x, l(2)
 712  0x000050BC:     iadd r4.y, r4.y, l(256)
 713  0x000050D8:     ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r4.y, r0.w, r4.y, t19.xxxx
 714  0x00005104:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r14.yzw, r4.y, l(0), t18.xxyz
 715  0x00005130:     add r14.yzw, -r1.xxyz, r14.yyzw
 716  0x00005150:     dp3 r5.z, r14.yzwy, r14.yzwy
 717  0x0000516C:     rsq r5.w, r5.z
 718  0x00005180:     mul r14.yzw, r5.wwww, r14.yyzw
 719  0x0000519C:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r17.xyzw, r4.y, l(48), t18.xyzw
 720  0x000051C8:     dp3 r5.w, r14.yzwy, r17.xyzx
 721  0x000051E4:     max r5.w, r5.w, l(0.000000)
 722  0x00005200:     add r5.w, -r5.w, l(1.000000)
 723  0x00005220:     mul r5.w, r17.w, r5.w
 724  0x0000523C:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.x, r4.y, l(64), t18.xxxx
 725  0x00005268:     log r5.w, r5.w
 726  0x0000527C:     mul r5.w, r5.w, r6.x
 727  0x00005298:     exp r5.w, r5.w
 728  0x000052AC:     add r5.w, -r5.w, l(1.000000)
 729  0x000052CC:     max r5.w, r5.w, l(0.000000)
 730  0x000052E8:     lt r6.x, l(0.000000), r5.w
 731  0x00005304:     if_nz r6.x
 732  0x00005310:       sqrt r5.z, r5.z
 733  0x00005324:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.x, r4.y, l(28), t18.xxxx
 734  0x00005350:       mul r5.z, r5.z, r6.x
 735  0x0000536C:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.x, r4.y, l(44), t18.xxxx
 736  0x00005398:       log r5.z, |r5.z|
 737  0x000053B0:       mul r5.z, r5.z, r6.x
 738  0x000053CC:       exp r5.z, r5.z
 739  0x000053E0:       add r5.z, -r5.z, l(1.000000)
 740  0x00005400:       max r5.z, r5.z, l(0.000000)
 741  0x0000541C:       mul r5.z, r5.z, r5.w
 742  0x00005438:       lt r5.w, l(0.000000), r5.z
 743  0x00005454:       if_nz r5.w
 744  0x00005460:         ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r15.xy, r4.y, l(96), t18.xyxx
 745  0x0000548C:         ine r5.w, r15.y, l(-1)
 746  0x000054A8:         if_nz r5.w
 747  0x000054B4:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r17.xyzw, r15.y, l(0), t25.xyzw
 748  0x000054E0:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r20.xyzw, r15.y, l(16), t25.xyzw
 749  0x0000550C:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r21.xyzw, r15.y, l(32), t25.xyzw
 750  0x00005538:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r22.xyzw, r15.y, l(48), t25.xyzw
 751  0x00005564:           dp4 r17.x, r1.xyzw, r17.xyzw
 752  0x00005580:           dp4 r17.y, r1.xyzw, r20.xyzw
 753  0x0000559C:           dp4 r17.z, r1.xyzw, r21.xyzw
 754  0x000055B8:           dp4 r5.w, r1.xyzw, r22.xyzw
 755  0x000055D4:           div r17.xyz, r17.xyzx, r5.wwww
 756  0x000055F0:           itof r17.w, r15.y
 757  0x00005604:           sample_c_lz_indexable(texture2darray)(float,float,float,float) r5.w, r17.xywx, t24.xxxx, s13, r17.z
 758  0x00005638:           mul r5.z, r5.w, r5.z
 759  0x00005654:         endif 
 760  0x00005658:         dp3 r5.w, r14.yzwy, r7.xzwx
 761  0x00005674:         max r5.w, r5.w, r15.x
 762  0x00005690:         mul r5.z, r5.w, r5.z
 763  0x000056AC:         ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r15.xyz, r4.y, l(16), t18.xyzx
 764  0x000056D8:         mad r13.xyz, r15.xyzx, r5.zzzz, r13.xyzx
 765  0x000056FC:         mad r14.yzw, r16.xxyz, r4.wwww, r14.yyzw
 766  0x00005720:         dp3 r5.w, r14.yzwy, r14.yzwy
 767  0x0000573C:         rsq r5.w, r5.w
 768  0x00005750:         mul r14.yzw, r5.wwww, r14.yyzw
 769  0x0000576C:         ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r17.xy, r4.y, l(68), t18.xyxx
 770  0x00005798:         mul r4.y, r6.y, r17.y
 771  0x000057B4:         dp3_sat r5.w, r14.yzwy, r7.xzwx
 772  0x000057D0:         max r4.y, r4.y, l(0.001000)
 773  0x000057EC:         log r5.w, r5.w
 774  0x00005800:         mul r4.y, r4.y, r5.w
 775  0x0000581C:         exp r4.y, r4.y
 776  0x00005830:         mul r14.yzw, r4.yyyy, r15.xxyz
 777  0x0000584C:         mul r14.yzw, r5.zzzz, r14.yyzw
 778  0x00005868:         mad r12.xyz, r14.yzwy, r17.xxxx, r12.xyzx
 779  0x0000588C:       endif 
 780  0x00005890:     endif 
 781  0x00005894:     iadd r4.x, r4.x, l(1)
 782  0x000058B0:   endloop 
 783  0x000058B4:   mad r4.xyw, r13.xyxz, r13.wwww, r11.xyxz
 784  0x000058D8:   mad r9.xyz, r12.xyzx, r13.wwww, r9.xyzx
 785  0x000058FC: else 
 786  0x00005900:   mul r5.zw, v0.xxxy, cb0[38].xxxy
 787  0x00005920:   mul r0.w, -r3.w, cb0[41].w
 788  0x00005944:   min r0.w, r0.w, l(7.000000)
 789  0x00005960:   max r0.w, r0.w, l(0.000000)
 790  0x0000597C:   ftou r5.zw, r5.zzzw
 791  0x00005990:   ftou r0.w, r0.w
 792  0x000059A4:   ishl r2.w, r5.w, l(5)
 793  0x000059C0:   imad r0.w, r0.w, l(576), r2.w
 794  0x000059E4:   iadd r0.w, r5.z, r0.w
 795  0x00005A00:   umin r0.w, r0.w, l(4607)
 796  0x00005A1C:   ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r2.w, r0.w, l(252), t19.xxxx
 797  0x00005A48:   umin r2.w, r2.w, l(63)
 798  0x00005A64:   mov r10.xyzw, l(0,0,0,0)
 799  0x00005A84:   loop 
 800  0x00005A88:     uge r5.z, r10.w, r2.w
 801  0x00005AA4:     breakc_nz r5.z
 802  0x00005AB0:     ishl r5.z, r10.w, l(2)
 803  0x00005ACC:     ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r5.z, r0.w, r5.z, t19.xxxx
 804  0x00005AF8:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r11.xyz, r5.z, l(0), t18.xyzx
 805  0x00005B24:     add r11.xyz, -r1.xyzx, r11.xyzx
 806  0x00005B44:     dp3 r5.w, r11.xyzx, r11.xyzx
 807  0x00005B60:     sqrt r6.x, r5.w
 808  0x00005B74:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.y, r5.z, l(28), t18.xxxx
 809  0x00005BA0:     mul r6.x, r6.y, r6.x
 810  0x00005BBC:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.y, r5.z, l(44), t18.xxxx
 811  0x00005BE8:     log r6.x, |r6.x|
 812  0x00005C00:     mul r6.x, r6.x, r6.y
 813  0x00005C1C:     exp r6.x, r6.x
 814  0x00005C30:     add r6.x, -r6.x, l(1.000000)
 815  0x00005C50:     max r6.x, r6.x, l(0.000000)
 816  0x00005C6C:     lt r6.y, l(0.000000), r6.x
 817  0x00005C88:     if_nz r6.y
 818  0x00005C94:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.y, r5.z, l(96), t18.xxxx
 819  0x00005CC0:       rsq r5.w, r5.w
 820  0x00005CD4:       mul r11.xyz, r5.wwww, r11.xyzx
 821  0x00005CF0:       dp3 r5.w, r11.xyzx, r7.xzwx
 822  0x00005D0C:       max r5.w, r5.w, r6.y
 823  0x00005D28:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r11.xyz, r5.z, l(16), t18.xyzx
 824  0x00005D54:       mul r11.xyz, r6.xxxx, r11.xyzx
 825  0x00005D70:       mad r10.xyz, r11.xyzx, r5.wwww, r10.xyzx
 826  0x00005D94:     endif 
 827  0x00005D98:     iadd r10.w, r10.w, l(1)
 828  0x00005DB4:   endloop 
 829  0x00005DB8:   mad r8.xyz, r10.xyzx, r13.wwww, r8.xyzx
 830  0x00005DDC:   ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r2.w, r0.w, l(508), t19.xxxx
 831  0x00005E08:   umin r2.w, r2.w, l(63)
 832  0x00005E24:   mov r10.xyzw, l(0,0,0,0)
 833  0x00005E44:   loop 
 834  0x00005E48:     uge r5.z, r10.w, r2.w
 835  0x00005E64:     breakc_nz r5.z
 836  0x00005E70:     ishl r5.z, r10.w, l(2)
 837  0x00005E8C:     iadd r5.z, r5.z, l(256)
 838  0x00005EA8:     ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r5.z, r0.w, r5.z, t19.xxxx
 839  0x00005ED4:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r11.xyz, r5.z, l(0), t18.xyzx
 840  0x00005F00:     add r11.xyz, -r1.xyzx, r11.xyzx
 841  0x00005F20:     dp3 r5.w, r11.xyzx, r11.xyzx
 842  0x00005F3C:     rsq r6.x, r5.w
 843  0x00005F50:     mul r11.xyz, r6.xxxx, r11.xyzx
 844  0x00005F6C:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r12.xyzw, r5.z, l(48), t18.xyzw
 845  0x00005F98:     dp3 r6.x, r11.xyzx, r12.xyzx
 846  0x00005FB4:     max r6.x, r6.x, l(0.000000)
 847  0x00005FD0:     add r6.x, -r6.x, l(1.000000)
 848  0x00005FF0:     mul r6.x, r12.w, r6.x
 849  0x0000600C:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.y, r5.z, l(64), t18.xxxx
 850  0x00006038:     log r6.x, r6.x
 851  0x0000604C:     mul r6.x, r6.x, r6.y
 852  0x00006068:     exp r6.x, r6.x
 853  0x0000607C:     add r6.x, -r6.x, l(1.000000)
 854  0x0000609C:     max r6.x, r6.x, l(0.000000)
 855  0x000060B8:     lt r6.y, l(0.000000), r6.x
 856  0x000060D4:     if_nz r6.y
 857  0x000060E0:       sqrt r5.w, r5.w
 858  0x000060F4:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.y, r5.z, l(28), t18.xxxx
 859  0x00006120:       mul r5.w, r5.w, r6.y
 860  0x0000613C:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.y, r5.z, l(44), t18.xxxx
 861  0x00006168:       log r5.w, |r5.w|
 862  0x00006180:       mul r5.w, r5.w, r6.y
 863  0x0000619C:       exp r5.w, r5.w
 864  0x000061B0:       add r5.w, -r5.w, l(1.000000)
 865  0x000061D0:       max r5.w, r5.w, l(0.000000)
 866  0x000061EC:       mul r5.w, r5.w, r6.x
 867  0x00006208:       lt r6.x, l(0.000000), r5.w
 868  0x00006224:       if_nz r6.x
 869  0x00006230:         ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.xy, r5.z, l(96), t18.xyxx
 870  0x0000625C:         ine r11.w, r6.y, l(-1)
 871  0x00006278:         if_nz r11.w
 872  0x00006284:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r12.xyzw, r6.y, l(0), t25.xyzw
 873  0x000062B0:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r16.xyzw, r6.y, l(16), t25.xyzw
 874  0x000062DC:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r17.xyzw, r6.y, l(32), t25.xyzw
 875  0x00006308:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r20.xyzw, r6.y, l(48), t25.xyzw
 876  0x00006334:           dp4 r12.x, r1.xyzw, r12.xyzw
 877  0x00006350:           dp4 r12.y, r1.xyzw, r16.xyzw
 878  0x0000636C:           dp4 r12.z, r1.xyzw, r17.xyzw
 879  0x00006388:           dp4 r11.w, r1.xyzw, r20.xyzw
 880  0x000063A4:           div r12.xyz, r12.xyzx, r11.wwww
 881  0x000063C0:           itof r12.w, r6.y
 882  0x000063D4:           sample_c_lz_indexable(texture2darray)(float,float,float,float) r6.y, r12.xywx, t24.xxxx, s13, r12.z
 883  0x00006408:           mul r5.w, r5.w, r6.y
 884  0x00006424:         endif 
 885  0x00006428:         dp3 r6.y, r11.xyzx, r7.xzwx
 886  0x00006444:         max r6.x, r6.y, r6.x
 887  0x00006460:         ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r11.xyz, r5.z, l(16), t18.xyzx
 888  0x0000648C:         mul r11.xyz, r5.wwww, r11.xyzx
 889  0x000064A8:         mad r10.xyz, r11.xyzx, r6.xxxx, r10.xyzx
 890  0x000064CC:       endif 
 891  0x000064D0:     endif 
 892  0x000064D4:     iadd r10.w, r10.w, l(1)
 893  0x000064F0:   endloop 
 894  0x000064F4:   mad r4.xyw, r10.xyxz, r13.wwww, r8.xyxz
 895  0x00006518: endif 
 896  0x0000651C: mul r7.xzw, r4.zzzz, r9.xxyz
 897  0x00006538: mad r4.xyz, r19.xyzx, r4.xywx, r7.xzwx
 898  0x0000655C: lt r0.w, l(0.000000), r2.x
 899  0x00006578: dp3 r0.x, r0.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
 900  0x000065A0: add r0.x, -r2.x, r0.x
 901  0x000065C0: max r0.x, r0.x, l(0.000000)
 902  0x000065DC: div r0.x, r0.x, r2.x
 903  0x000065F8: min r0.x, r0.x, l(1.000000)
 904  0x00006614: movc r0.x, r0.w, r0.x, l(1.000000)
 905  0x00006638: mul r0.y, r8.w, r15.w
 906  0x00006654: mul r0.x, r0.x, r0.y
 907  0x00006670: add r0.y, r9.w, l(-1.000000)
 908  0x0000668C: mad r0.y, r2.y, r0.y, l(1.000000)
 909  0x000066B0: mul r0.x, r0.y, r0.x
 910  0x000066CC: add r0.y, -r3.w, -cb0[38].z
 911  0x000066F4: mul_sat r0.y, r0.y, cb0[38].w
 912  0x00006714: add r0.z, r1.y, -cb0[40].x
 913  0x00006738: mul_sat r0.z, r0.z, cb0[40].y
 914  0x00006758: mul r0.y, r0.z, r0.y
 915  0x00006774: mul r0.z, r0.y, cb0[39].w
 916  0x00006794: mul r0.z, r14.x, r0.z
 917  0x000067B0: add r2.xyw, -r4.xyxz, cb0[39].xyxz
 918  0x000067D4: mad r2.xyw, r0.zzzz, r2.xyxw, r4.xyxz
 919  0x000067F8: if_nz cb3[0].x
 920  0x00006808:   add r0.zw, r1.xxxz, -cb3[1].xxxy
 921  0x0000682C:   mul r0.zw, r0.zzzw, cb3[1].zzzw
 922  0x0000684C:   ge r4.xy, r0.zwzz, l(0.000000, 0.000000, 0.000000, 0.000000)
 923  0x00006874:   and r3.w, r4.y, r4.x
 924  0x00006890:   ge r4.xy, l(1.000000, 1.000000, 0.000000, 0.000000), r0.zwzz
 925  0x000068B8:   and r4.x, r4.y, r4.x
 926  0x000068D4:   and r3.w, r3.w, r4.x
 927  0x000068F0:   if_nz r3.w
 928  0x000068FC:     sample_l_indexable(texture2d)(float,float,float,float) r0.z, r0.zwzz, t5.yzxw, s1, l(0.000000)
 929  0x00006930:   else 
 930  0x00006934:     mov r0.z, l(1.000000)
 931  0x00006948:   endif 
 932  0x0000694C:   mov r1.w, l(1.000000)
 933  0x00006960:   mov r4.xyz, r2.xywx
 934  0x00006974:   mov r0.w, l(0)
 935  0x00006988:   loop 
 936  0x0000698C:     uge r3.w, r0.w, cb3[0].x
 937  0x000069AC:     breakc_nz r3.w
 938  0x000069B8:     ld_structured_indexable(structured_buffer, stride=128)(mixed,mixed,mixed,mixed) r8.xyzw, r0.w, l(96), t4.xyzw
 939  0x000069E4:     add r3.w, r1.y, -r8.y
 940  0x00006A04:     ge r4.w, r8.z, |r3.w|
 941  0x00006A24:     if_nz r4.w
 942  0x00006A30:       ld_structured_indexable(structured_buffer, stride=128)(mixed,mixed,mixed,mixed) r9.xyzw, r0.w, l(0), t4.xyzw
 943  0x00006A5C:       ld_structured_indexable(structured_buffer, stride=128)(mixed,mixed,mixed,mixed) r10.xyzw, r0.w, l(32), t4.xwyz
 944  0x00006A88:       ld_structured_indexable(structured_buffer, stride=128)(mixed,mixed,mixed,mixed) r11.xyzw, r0.w, l(64), t4.xyzw
 945  0x00006AB4:       ld_structured_indexable(structured_buffer, stride=128)(mixed,mixed,mixed,mixed) r12.xyzw, r0.w, l(80), t4.xyzw
 946  0x00006AE0:       add r4.w, r8.w, |r3.w|
 947  0x00006B00:       lt r4.w, r8.z, r4.w
 948  0x00006B1C:       add r3.w, -|r3.w|, r8.z
 949  0x00006B3C:       div r3.w, r3.w, r8.w
 950  0x00006B58:       movc r3.w, r4.w, r3.w, l(1.000000)
 951  0x00006B7C:       if_z r12.x
 952  0x00006B88:         mov r10.x, r9.w
 953  0x00006B9C:         add r5.zw, r1.xxxz, -r10.xxxy
 954  0x00006BBC:         dp2 r4.w, r5.zwzz, r5.zwzz
 955  0x00006BD8:         sqrt r4.w, r4.w
 956  0x00006BEC:         lt r5.z, r12.y, r4.w
 957  0x00006C08:         add r5.w, -r12.z, r12.y
 958  0x00006C28:         ge r6.x, r4.w, r5.w
 959  0x00006C44:         not r6.y, r6.x
 960  0x00006C58:         add r4.w, r4.w, -r5.w
 961  0x00006C78:         div r4.w, r4.w, r12.z
 962  0x00006C94:         and r4.w, r4.w, r6.x
 963  0x00006CB0:         movc r4.w, r5.z, l(0), r4.w
 964  0x00006CD4:         or r5.z, r5.z, r6.y
 965  0x00006CF0:       else 
 966  0x00006CF4:         ieq r5.w, r12.x, l(1)
 967  0x00006D10:         if_nz r5.w
 968  0x00006D1C:           ld_structured_indexable(structured_buffer, stride=128)(mixed,mixed,mixed,mixed) r5.w, r0.w, l(112), t4.xxxx
 969  0x00006D48:           mov r10.xz, r9.wwzw
 970  0x00006D5C:           add r6.xy, r1.xzxx, -r10.xyxx
 971  0x00006D7C:           dp2 r7.x, r6.xyxx, r6.xyxx
 972  0x00006D98:           sqrt r7.z, r7.x
 973  0x00006DAC:           lt r7.w, r12.y, r7.z
 974  0x00006DC8:           add r8.y, -r12.z, r12.y
 975  0x00006DE8:           rsq r7.x, r7.x
 976  0x00006DFC:           mul r6.xy, r6.xyxx, r7.xxxx
 977  0x00006E18:           dp2 r6.x, r10.zwzz, r6.xyxx
 978  0x00006E34:           add r6.y, -|r6.x|, l(1.000000)
 979  0x00006E54:           sqrt r6.y, r6.y
 980  0x00006E68:           mad r7.x, |r6.x|, l(-0.018729), l(0.074261)
 981  0x00006E90:           mad r7.x, r7.x, |r6.x|, l(-0.212114)
 982  0x00006EB8:           mad r7.x, r7.x, |r6.x|, l(1.570729)
 983  0x00006EE0:           mul r8.z, r6.y, r7.x
 984  0x00006EFC:           mad r8.z, r8.z, l(-2.000000), l(3.141593)
 985  0x00006F20:           lt r6.x, r6.x, -r6.x
 986  0x00006F40:           and r6.x, r6.x, r8.z
 987  0x00006F5C:           mad r6.x, r7.x, r6.y, r6.x
 988  0x00006F80:           ge r6.y, r5.w, r6.x
 989  0x00006F9C:           not r7.x, r6.y
 990  0x00006FB0:           mul r8.z, r7.z, l(6.283185)
 991  0x00006FCC:           mul r6.x, r6.x, r8.z
 992  0x00006FE8:           mul r6.x, r6.x, l(0.159155)
 993  0x00007004:           mul r5.w, r5.w, r8.z
 994  0x00007020:           mad r5.w, r5.w, l(0.159155), -r6.x
 995  0x00007048:           div r5.w, r5.w, r12.z
 996  0x00007064:           min r5.w, r5.w, l(1.000000)
 997  0x00007080:           add r5.w, -r5.w, l(1.000000)
 998  0x000070A0:           add r6.x, r7.z, -r8.y
 999  0x000070C0:           div r6.x, r6.x, r12.z
1000  0x000070DC:           min r6.x, r6.x, l(1.000000)
1001  0x000070F8:           max r5.w, r5.w, r6.x
1002  0x00007114:           and r5.w, r5.w, r6.y
1003  0x00007130:           movc r4.w, r7.w, l(0), r5.w
1004  0x00007154:           or r5.z, r7.w, r7.x
1005  0x00007170:         else 
1006  0x00007174:           ieq r5.w, r12.x, l(2)
1007  0x00007190:           dp4 r6.x, r1.xyzw, r9.xyzw
1008  0x000071AC:           dp4 r6.y, r1.xwyz, r10.xyzw
1009  0x000071C8:           lt r7.xz, r6.xxyx, l(0.500000, 0.000000, 0.500000, 0.000000)
1010  0x000071F0:           and r7.x, r7.z, r7.x
1011  0x0000720C:           lt r7.zw, l(0.000000, 0.000000, -0.500000, -0.500000), r6.xxxy
1012  0x00007234:           and r7.z, r7.w, r7.z
1013  0x00007250:           and r7.x, r7.z, r7.x
1014  0x0000726C:           add r7.zw, -r12.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000)
1015  0x00007298:           lt r8.yz, |r6.xxyx|, r7.zzwz
1016  0x000072B8:           and r8.y, r8.z, r8.y
1017  0x000072D4:           add r6.xy, |r6.xyxx|, -r7.zwzz
1018  0x000072F8:           div r6.xy, r6.xyxx, r12.zwzz
1019  0x00007314:           max r6.x, r6.y, r6.x
1020  0x00007330:           movc r6.x, r8.y, l(0), r6.x
1021  0x00007354:           and r6.x, r6.x, r7.x
1022  0x00007370:           movc r6.y, r7.x, r8.y, l(-1)
1023  0x00007394:           and r4.w, r5.w, r6.x
1024  0x000073B0:           and r5.z, r5.w, r6.y
1025  0x000073CC:         endif 
1026  0x000073D0:       endif 
1027  0x000073D4:       log r4.w, r4.w
1028  0x000073E8:       mul r4.w, r4.w, r8.x
1029  0x00007404:       exp r4.w, r4.w
1030  0x00007418:       mul r4.w, r4.w, r11.w
1031  0x00007434:       mul r4.w, r0.z, r4.w
1032  0x00007450:       mul r3.w, r3.w, r4.w
1033  0x0000746C:       add r7.xzw, -r4.xxyz, r11.xxyz
1034  0x0000748C:       mad r7.xzw, r3.wwww, r7.xxzw, r4.xxyz
1035  0x000074B0:       movc r4.xyz, r5.zzzz, r4.xyzx, r7.xzwx
1036  0x000074D4:     endif 
1037  0x000074D8:     iadd r0.w, r0.w, l(1)
1038  0x000074F4:   endloop 
1039  0x000074F8:   mov r2.xyw, r4.xyxz
1040  0x0000750C: endif 
1041  0x00007510: mad r0.y, -r0.y, cb0[39].w, l(1.000000)
1042  0x0000753C: mul r0.y, r0.y, r2.z
1043  0x00007558: ftou r0.zw, r6.zzzw
1044  0x0000756C: imad o1.x, r0.w, l(0x00010000), r0.z
1045  0x00007590: mul r0.zw, r5.xxxy, l(0.000000, 0.000000, 0.255000, 2.550000)
1046  0x000075B8: ftou r1.x, r7.y
1047  0x000075CC: ftou r0.zw, r0.zzzw
1048  0x000075E0: ishl r0.w, r0.w, l(24)
1049  0x000075FC: bfi r0.z, l(16), l(16), r0.z, r1.x
1050  0x00007628: or o1.y, r0.w, r0.z
1051  0x00007644: mul r0.y, r0.y, l(255.000000)
1052  0x00007660: ftou r3.xy, r0.yyyy
1053  0x00007674: ishl r0.yzw, r3.xxyz, l(0, 8, 16, 24)
1054  0x0000769C: or r0.y, r0.y, r3.y
1055  0x000076B8: or r0.y, r0.z, r0.y
1056  0x000076D4: or o1.z, r0.w, r0.y
1057  0x000076F0: mul_sat r0.x, r0.x, l(0.100000)
1058  0x0000770C: mul r0.x, r0.x, l(65535.000000)
1059  0x00007728: ftou r0.x, r0.x
1060  0x0000773C: ishl r0.x, r0.x, l(16)
1061  0x00007758: movc o1.w, r18.w, r0.x, l(0)
1062  0x0000777C: mov o0.xyz, r2.xywx
1063  0x00007790: mov o0.w, l(1.000000)
1064  0x000077A4: ret 
// Approximately 1065 instruction slots used
