//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cb_scene
// {
//
//   float4x4 view_g;                   // Offset:    0 Size:    64
//   float4x4 viewInv_g;                // Offset:   64 Size:    64
//   float4x4 proj_g;                   // Offset:  128 Size:    64 [unused]
//   float4x4 projInv_g;                // Offset:  192 Size:    64
//   float4x4 viewProj_g;               // Offset:  256 Size:    64 [unused]
//   float4x4 viewProjInv_g;            // Offset:  320 Size:    64
//   float2 vpSize_g;                   // Offset:  384 Size:     8 [unused]
//   float2 invVPSize_g;                // Offset:  392 Size:     8
//   float3 lightColor_g;               // Offset:  400 Size:    12
//   float disableMapObjNearFade_g;     // Offset:  412 Size:     4 [unused]
//   float3 lightDirection_g;           // Offset:  416 Size:    12
//   float gameTime_g;                  // Offset:  428 Size:     4 [unused]
//   float3 sceneShadowColor_g;         // Offset:  432 Size:    12
//   int shadowmapCascadeCount_g;       // Offset:  444 Size:     4 [unused]
//   float3 windDirection_g;            // Offset:  448 Size:    12 [unused]
//   float sceneTime_g;                 // Offset:  460 Size:     4 [unused]
//   float2 lightTileSizeInv_g;         // Offset:  464 Size:     8
//   float fogNearDistance_g;           // Offset:  472 Size:     4
//   float fogFadeRangeInv_g;           // Offset:  476 Size:     4
//   float3 fogColor_g;                 // Offset:  480 Size:    12
//   float fogIntensity_g;              // Offset:  492 Size:     4
//   float fogHeight_g;                 // Offset:  496 Size:     4
//   float fogHeightRangeInv_g;         // Offset:  500 Size:     4
//   float windWaveTime_g;              // Offset:  504 Size:     4 [unused]
//   float windWaveFrequency_g;         // Offset:  508 Size:     4 [unused]
//   float fogExp_g;                    // Offset:  512 Size:     4
//   float lightSpecularGlossiness_g;   // Offset:  516 Size:     4
//   float lightSpecularIntensity_g;    // Offset:  520 Size:     4
//   float localShadowResolutionInv_g;  // Offset:  524 Size:     4
//   float4x4 ditherMtx_g;              // Offset:  528 Size:    64 [unused]
//   float4 lightProbe_g[9];            // Offset:  592 Size:   144
//   float3 chrLightDir_g;              // Offset:  736 Size:    12 [unused]
//   float windForce_g;                 // Offset:  748 Size:     4 [unused]
//   float4 mapColor_g;                 // Offset:  752 Size:    16 [unused]
//   float4 clipPlane_g;                // Offset:  768 Size:    16 [unused]
//   float2 resolutionScaling_g;        // Offset:  784 Size:     8
//   float2 invShadowSize_g;            // Offset:  792 Size:     8 [unused]
//   float3 chrShadowColor_g;           // Offset:  800 Size:    12 [unused]
//   float shadowFadeNear_g;            // Offset:  812 Size:     4 [unused]
//   float4 frustumPlanes_g[6];         // Offset:  816 Size:    96 [unused]
//   float3 shadowSplitDistance_g;      // Offset:  912 Size:    12 [unused]
//   float shadowFadeRangeInv_g;        // Offset:  924 Size:     4 [unused]
//   float4x4 shadowMtx_g[4];           // Offset:  928 Size:   256 [unused]
//   float2 cloudShadowOffset_g;        // Offset: 1184 Size:     8
//   float cloudShadowScale_g;          // Offset: 1192 Size:     4
//   float4x4 prevViewProj_g;           // Offset: 1200 Size:    64 [unused]
//   float2 jitterDiff_g;               // Offset: 1264 Size:     8 [unused]
//   float4 shadowBlurRadius_g;         // Offset: 1280 Size:    16 [unused]
//
// }
//
// cbuffer cb_local
// {
//
//   float4 fadeBeginDistance_g;        // Offset:    0 Size:    16
//   float4 fadeRangeInv_g;             // Offset:   16 Size:    16
//   float density_g;                   // Offset:   32 Size:     4
//   float maxThickness_g;              // Offset:   36 Size:     4
//   float depthThresholdNear_g;        // Offset:   40 Size:     4
//   float depthThresholdFar_g;         // Offset:   44 Size:     4
//   float densityByDepthDiffNear_g;    // Offset:   48 Size:     4
//   float densityByDepthDiffFar_g;     // Offset:   52 Size:     4
//   float2 uvClamp_g;                  // Offset:   56 Size:     8
//   float4 offsetsAndWeights[8];       // Offset:   64 Size:   128
//
// }
//
// cbuffer cb_post_sky
// {
//
//   float3 incomingLight_g;            // Offset:    0 Size:    12 [unused]
//   float3 scatteringR_g;              // Offset:   16 Size:    12 [unused]
//   float3 scatteringM_g;              // Offset:   32 Size:    12 [unused]
//   float3 extinctionR_g;              // Offset:   48 Size:    12 [unused]
//   float3 extinctionM_g;              // Offset:   64 Size:    12 [unused]
//   float3 densityScaleHeight_g;       // Offset:   80 Size:    12 [unused]
//   float skyHorizonBottomLimit_g;     // Offset:   92 Size:     4 [unused]
//   float3 sunDirection_g;             // Offset:   96 Size:    12 [unused]
//   float skyHorizonTopLimit_g;        // Offset:  108 Size:     4 [unused]
//   float mieG_g;                      // Offset:  112 Size:     4 [unused]
//   float distanceScale_g;             // Offset:  116 Size:     4 [unused]
//   float planetRadius_g;              // Offset:  120 Size:     4 [unused]
//   float atmosphereHeight_g;          // Offset:  124 Size:     4 [unused]
//   float sunIntensity_g;              // Offset:  128 Size:     4 [unused]
//   float skyLutNearOverFarClip_g;     // Offset:  132 Size:     4
//   float skyLutCameraFarClip_g;       // Offset:  136 Size:     4
//   float skyBrightness_g;             // Offset:  140 Size:     4 [unused]
//
// }
//
// cbuffer cb_volume_fog
// {
//
//   float volumeLightBrightness_g;     // Offset:    0 Size:     4 [unused]
//   float volumeDensity_g;             // Offset:    4 Size:     4 [unused]
//   float volumeCameraFarOverMaxFar_g; // Offset:    8 Size:     4
//   float volumeCameraFarClip_g;       // Offset:   12 Size:     4
//   float volumeNearOverFarClip_g;     // Offset:   16 Size:     4
//   float volumeNearDistance_g;        // Offset:   20 Size:     4 [unused]
//   float volumeFarDistance_g;         // Offset:   24 Size:     4 [unused]
//   uint volumeShapeCount_g;           // Offset:   28 Size:     4 [unused]
//   float4 volumeColor_g;              // Offset:   32 Size:    16 [unused]
//   float2 voulumeLightTileSizeInv_g;  // Offset:   48 Size:     8 [unused]
//   float combineAlpha_g;              // Offset:   56 Size:     4
//   float temporalRatioMax_g;          // Offset:   60 Size:     4 [unused]
//   float2 prevScaling_g;              // Offset:   64 Size:     8 [unused]
//   float2 prevUVClamp_g;              // Offset:   72 Size:     8 [unused]
//   float volumeNearFadeInv_g;         // Offset:   80 Size:     4 [unused]
//   float volumeNearFadeValue_g;       // Offset:   84 Size:     4 [unused]
//   float temporalRatioMin_g;          // Offset:   88 Size:     4 [unused]
//   float densityScale_g;              // Offset:   92 Size:     4 [unused]
//
// }
//
// cbuffer cb_deferred
// {
//
//   float2 shadowUVClamp_g;            // Offset:    0 Size:     8
//   float3 mapAOColor_g;               // Offset:   16 Size:    12
//   float mapAOIntensity_g;            // Offset:   28 Size:     4
//   float3 shadowEdgeColor_g;          // Offset:   32 Size:    12
//   float shadowEdgeSharpness_g;       // Offset:   44 Size:     4
//
// }
//
// Resource bind info for deferredParams_g
// {
//
//   struct DeferredParam
//   {
//       
//       float3 shadowColor;            // Offset:    0
//       float emissive;                // Offset:   12
//       float3 specularColor;          // Offset:   16
//       float rimLightPower;           // Offset:   28
//       float3 rimLightColor;          // Offset:   32
//       float rimIntensity;            // Offset:   44
//       float3 fresnels;               // Offset:   48
//       float specularShadowFadeRatio; // Offset:   60
//       float3 specularGlossinesses;   // Offset:   64
//       float dynamicLightIntensity;   // Offset:   76
//       float materialFogIntensity;    // Offset:   80
//       float metalness;               // Offset:   84
//       float roughness;               // Offset:   88
//       float cryRefractionIndex;      // Offset:   92
//       float cryFresnel;              // Offset:   96
//       float cryBrightness;           // Offset:  100
//       float cryBrightnessPower;      // Offset:  104
//       float glowIntensity;           // Offset:  108
//       float glowLumThreshold;        // Offset:  112
//       float glowShadowFadeRatio;     // Offset:  116
//       float ssaoIntensity;           // Offset:  120
//       float translucency;            // Offset:  124
//       float ssrDistance;             // Offset:  128
//       float volumeFogIntensity;      // Offset:  132
//       uint flag;                     // Offset:  136
//       float reserve;                 // Offset:  140
//
//   } $Element;                        // Offset:    0 Size:   144
//
// }
//
// Resource bind info for dynamicLights_g
// {
//
//   struct LightParam
//   {
//       
//       float3 pos;                    // Offset:    0
//       float radius;                  // Offset:   12
//       float3 color;                  // Offset:   16
//       float radiusInv;               // Offset:   28
//       float3 charaColor;             // Offset:   32
//       float attenuation;             // Offset:   44
//       float3 vec;                    // Offset:   48
//       float spotAngleInv;            // Offset:   60
//       float attenuationAngle;        // Offset:   64
//       float specularIntensity;       // Offset:   68
//       float specularGlossiness;      // Offset:   72
//       float scatterAnisotropy;       // Offset:   76
//       float3 scatterColor;           // Offset:   80
//       float scatterDensity;          // Offset:   92
//       float translucency;            // Offset:   96
//       int shadowmapIndex;            // Offset:  100
//       float scatterOffset;           // Offset:  104
//       float userParam;               // Offset:  108
//
//   } $Element;                        // Offset:    0 Size:   112
//
// }
//
// Resource bind info for lightIndices_g
// {
//
//   struct LightIndexData
//   {
//       
//       int pointLightIndices[63];     // Offset:    0
//       uint pointLightCount;          // Offset:  252
//       int spotLightIndices[63];      // Offset:  256
//       uint spotLightCount;           // Offset:  508
//       int lightProbeIndices[14];     // Offset:  512
//       uint lightProbeCount;          // Offset:  568
//       float tileDepthInv;            // Offset:  572
//
//   } $Element;                        // Offset:    0 Size:   576
//
// }
//
// Resource bind info for spotShadowMatrices_g
// {
//
//   float4x4 $Element;                 // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// samPoint                          sampler      NA          NA             s0      1 
// samLinear                         sampler      NA          NA             s1      1 
// SmplLinearWrap                    sampler      NA          NA            s11      1 
// SmplShadow                      sampler_c      NA          NA            s13      1 
// SmplCube                          sampler      NA          NA            s14      1 
// SmplLinearClamp                   sampler      NA          NA            s15      1 
// colorTexture                      texture  float4          2d             t0      1 
// mrtTexture0                       texture   uint4          2d             t1      1 
// mrtTexture1                       texture   uint4          2d             t2      1 
// mrtTexture2                       texture   uint2          2d             t3      1 
// depthTexture                      texture  float4          2d             t4      1 
// ssaoTexture                       texture  float4          2d             t5      1 
// deferredParams_g                  texture  struct         r/o             t6      1 
// shadowTexture                     texture  float4          2d             t7      1 
// outlinePrepareTexture             texture  float4          2d             t8      1 
// dynamicLights_g                   texture  struct         r/o            t11      1 
// lightIndices_g                    texture  struct         r/o            t12      1 
// spotShadowMatrices_g              texture  struct         r/o            t14      1 
// texEnvMap_g                       texture  float4        cube            t17      1 
// spotShadowMaps                    texture  float4     2darray            t18      1 
// atmosphereInscatterLUT            texture  float4          3d            t19      1 
// atmosphereExtinctionLUT           texture  float4          3d            t20      1 
// texMirror_g                       texture  float4          2d            t21      1 
// texSSRMap_g                       texture  float4          2d            t24      1 
// volumeFogTexture_g                texture  float4          3d            t26      1 
// texCloudShadow                    texture  float4          2d            t27      1 
// cb_scene                          cbuffer      NA          NA            cb0      1 
// cb_local                          cbuffer      NA          NA            cb2      1 
// cb_deferred                       cbuffer      NA          NA            cb4      1 
// cb_post_sky                       cbuffer      NA          NA            cb6      1 
// cb_volume_fog                     cbuffer      NA          NA            cb7      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xy  
// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
// SV_Target                1   xyzw        1   TARGET    uint   xyzw
// SV_Target                2   xy          2   TARGET    uint   xy  
//
      0x00000000: ps_5_0
      0x00000008: dcl_globalFlags refactoringAllowed
      0x0000000C: dcl_constantbuffer CB0[75], immediateIndexed
      0x0000001C: dcl_constantbuffer CB2[12], immediateIndexed
      0x0000002C: dcl_constantbuffer CB6[9], immediateIndexed
      0x0000003C: dcl_constantbuffer CB7[4], immediateIndexed
      0x0000004C: dcl_constantbuffer CB4[3], immediateIndexed
      0x0000005C: dcl_sampler s0, mode_default
      0x00000068: dcl_sampler s1, mode_default
      0x00000074: dcl_sampler s11, mode_default
      0x00000080: dcl_sampler s13, mode_comparison
      0x0000008C: dcl_sampler s14, mode_default
      0x00000098: dcl_sampler s15, mode_default
      0x000000A4: dcl_resource_texture2d (float,float,float,float) t0
      0x000000B4: dcl_resource_texture2d (uint,uint,uint,uint) t1
      0x000000C4: dcl_resource_texture2d (uint,uint,uint,uint) t2
      0x000000D4: dcl_resource_texture2d (uint,uint,uint,uint) t3
      0x000000E4: dcl_resource_texture2d (float,float,float,float) t4
      0x000000F4: dcl_resource_texture2d (float,float,float,float) t5
      0x00000104: dcl_resource_structured t6, 144
      0x00000114: dcl_resource_texture2d (float,float,float,float) t7
      0x00000124: dcl_resource_texture2d (float,float,float,float) t8
      0x00000134: dcl_resource_structured t11, 112
      0x00000144: dcl_resource_structured t12, 576
      0x00000154: dcl_resource_structured t14, 64
      0x00000164: dcl_resource_texturecube (float,float,float,float) t17
      0x00000174: dcl_resource_texture2darray (float,float,float,float) t18
      0x00000184: dcl_resource_texture3d (float,float,float,float) t19
      0x00000194: dcl_resource_texture3d (float,float,float,float) t20
      0x000001A4: dcl_resource_texture2d (float,float,float,float) t21
      0x000001B4: dcl_resource_texture2d (float,float,float,float) t24
      0x000001C4: dcl_resource_texture3d (float,float,float,float) t26
      0x000001D4: dcl_resource_texture2d (float,float,float,float) t27
      0x000001E4: dcl_input_ps_siv linear noperspective v0.xy, position
      0x000001F4: dcl_input_ps linear v1.xyzw
      0x00000200: dcl_output o0.xyzw
      0x0000020C: dcl_output o1.xyzw
      0x00000218: dcl_output o2.xy
      0x00000224: dcl_temps 26
   0  0x0000022C: sample_l_indexable(texture2d)(float,float,float,float) r0.xyzw, v1.xyxx, t0.xyzw, s0, l(0.000000)
   1  0x00000260: resinfo_indexable(texture2d)(uint,uint,uint,uint) r1.xy, l(0), t1.xyzw
   2  0x00000284: mul r1.xy, r1.xyxx, v1.xyxx
   3  0x000002A0: ftoi r1.xy, r1.xyxx
   4  0x000002B4: mov r1.zw, l(0,0,0,0)
   5  0x000002D4: ld_indexable(texture2d)(uint,uint,uint,uint) r1.xyz, r1.xyzw, t1.xywz
   6  0x000002F8: resinfo_indexable(texture2d)(uint,uint,uint,uint) r2.xy, l(0), t2.xyzw
   7  0x0000031C: mul r2.xy, r2.xyxx, v1.xyxx
   8  0x00000338: ftoi r2.xy, r2.xyxx
   9  0x0000034C: mov r2.zw, l(0,0,0,0)
  10  0x0000036C: ld_indexable(texture2d)(uint,uint,uint,uint) r2.xyzw, r2.xyzw, t2.xyzw
  11  0x00000390: resinfo_indexable(texture2d)(uint,uint,uint,uint) r3.xy, l(0), t3.xyzw
  12  0x000003B4: mul r3.xy, r3.xyxx, v1.xyxx
  13  0x000003D0: ftoi r3.xy, r3.xyxx
  14  0x000003E4: mov r3.zw, l(0,0,0,0)
  15  0x00000404: ld_indexable(texture2d)(uint,uint,uint,uint) r3.xy, r3.xyzw, t3.xyzw
  16  0x00000428: sample_l_indexable(texture2d)(float,float,float,float) r4.z, v1.xyxx, t4.yzxw, s0, l(0.000000)
  17  0x0000045C: sample_l_indexable(texture2d)(float,float,float,float) r5.xyz, v1.xyxx, t5.xyzw, s1, l(0.000000)
  18  0x00000490: mad r4.xy, v1.zwzz, l(2.000000, -2.000000, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
  19  0x000004CC: mov r4.w, l(1.000000)
  20  0x000004E0: dp4 r6.x, r4.xyzw, cb0[20].xyzw
  21  0x00000500: dp4 r6.y, r4.xyzw, cb0[21].xyzw
  22  0x00000520: dp4 r6.z, r4.xyzw, cb0[22].xyzw
  23  0x00000540: dp4 r6.w, r4.xyzw, cb0[23].xyzw
  24  0x00000560: div r4.xyzw, r6.xyzw, r6.wwww
  25  0x0000057C: dp4 r1.w, cb0[2].xyzw, r4.xyzw
  26  0x0000059C: mul r6.xy, v0.xyxx, cb0[24].zwzz
  27  0x000005BC: div r3.z, -r1.w, cb7[0].w
  28  0x000005E0: mul r7.xy, r6.xyxx, cb0[49].xyxx
  29  0x00000600: mad r3.z, r3.z, cb7[0].z, -cb7[1].x
  30  0x00000630: add r3.w, l(1.000000), -cb7[1].x
  31  0x00000654: div r7.z, r3.z, r3.w
  32  0x00000670: sample_l_indexable(texture3d)(float,float,float,float) r7.xyzw, r7.xyzx, t26.xyzw, s15, l(0.000000)
  33  0x000006A4: and r3.z, r1.z, l(8)
  34  0x000006C0: if_z r3.z
  35  0x000006CC:   ushr r8.yz, r3.xxxx, l(0, 5, 10, 0)
  36  0x000006F4:   mov r8.x, r3.x
  37  0x00000708:   and r8.xyz, r8.xyzx, l(31, 31, 31, 0)
  38  0x00000730:   utof r8.xyz, r8.xyzx
  39  0x00000744:   mov r9.x, l(0.032258)
  40  0x00000758:   mov r9.yz, r0.yyzy
  41  0x0000076C:   mul r8.xyz, r8.xyzx, r9.xyzx
  42  0x00000788:   and r3.zw, r1.zzzz, l(0, 0, 1, 64)
  43  0x000007B0:   if_nz r3.z
  44  0x000007BC:     mov r9.x, r0.x
  45  0x000007D0:     mov r9.yz, l(0,0.032258,0.032258,0)
  46  0x000007F0:     mul r10.xyz, r8.xyzx, r9.xyzx
  47  0x0000080C:     mul r3.z, r5.z, r5.y
  48  0x00000828:     mad r5.yzw, -r9.xxyz, r8.xxyz, r0.xxyz
  49  0x00000850:     mad r9.xyz, r3.zzzz, r5.yzwy, r10.xyzx
  50  0x00000874:     and r3.z, r1.z, l(4)
  51  0x00000890:     if_z r3.z
  52  0x0000089C:       sample_l_indexable(texture2d)(float,float,float,float) r5.yz, v1.xyxx, t8.zxyw, s1, l(0.000000)
  53  0x000008D0:       mov r10.x, r5.y
  54  0x000008E4:       mov r10.yw, l(0,1.000000,0,1.000000)
  55  0x00000904:       dp2 r3.z, cb0[14].zwzz, r10.xyxx
  56  0x00000924:       dp2 r5.y, cb0[15].zwzz, r10.xyxx
  57  0x00000944:       div r3.z, r3.z, r5.y
  58  0x00000960:       add r11.xyzw, -r3.zzzz, -cb2[0].xyzw
  59  0x00000988:       mul_sat r11.xyzw, r11.xyzw, cb2[1].xyzw
  60  0x000009A8:       mov r12.xy, cb2[2].yzyy
  61  0x000009C0:       mov r12.z, cb2[3].x
  62  0x000009D8:       add r13.x, -r12.x, l(1.000000)
  63  0x000009F8:       add r13.y, -r12.y, cb2[2].w
  64  0x00000A1C:       add r13.z, -r12.z, cb2[3].y
  65  0x00000A40:       mad r8.yzw, r11.yyzw, r13.xxyz, r12.xxyz
  66  0x00000A64:       mad r5.yw, cb2[4].xxxy, r8.yyyy, v1.xxxy
  67  0x00000A8C:       min r5.yw, r5.yyyw, cb2[3].zzzw
  68  0x00000AAC:       mul r6.w, r8.y, l(0.500000)
  69  0x00000AC8:       max r6.w, r6.w, l(1.000000)
  70  0x00000AE4:       mad r10.xy, cb2[4].xyxx, r6.wwww, v1.xyxx
  71  0x00000B0C:       min r10.xy, r10.xyxx, cb2[3].zwzz
  72  0x00000B2C:       sample_l_indexable(texture2d)(float,float,float,float) r10.z, r5.ywyy, t8.yzxw, s1, l(0.000000)
  73  0x00000B60:       sample_l_indexable(texture2d)(float,float,float,float) r5.y, r10.xyxx, t8.xyzw, s1, l(0.000000)
  74  0x00000B94:       dp2 r5.w, cb0[14].zwzz, r10.zwzz
  75  0x00000BB4:       dp2 r10.x, cb0[15].zwzz, r10.zwzz
  76  0x00000BD4:       div r5.w, r5.w, r10.x
  77  0x00000BF0:       lt r10.x, r5.y, l(0.000000)
  78  0x00000C0C:       add r5.w, r3.z, -r5.w
  79  0x00000C2C:       ge r10.y, r5.w, l(0.000000)
  80  0x00000C48:       ge r10.z, r5.w, r8.z
  81  0x00000C64:       and r12.x, r10.z, l(0x3f800000)
  82  0x00000C80:       add r5.y, -r5.y, r5.z
  83  0x00000CA0:       ge r10.z, |r5.y|, l(0.030000)
  84  0x00000CC0:       and r10.yz, r10.yyzy, l(0, 0x3f800000, 0x3f800000, 0)
  85  0x00000CE8:       mad r12.y, r10.y, r10.z, r12.x
  86  0x00000D0C:       mov r10.z, |r5.w|
  87  0x00000D24:       mad r10.w, r10.y, |r5.y|, r10.z
  88  0x00000D4C:       mad r5.yw, cb2[5].xxxy, r8.yyyy, v1.xxxy
  89  0x00000D74:       min r5.yw, r5.yyyw, cb2[3].zzzw
  90  0x00000D94:       mad r11.yz, cb2[5].xxyx, r6.wwww, v1.xxyx
  91  0x00000DBC:       min r11.yz, r11.yyzy, cb2[3].zzwz
  92  0x00000DDC:       sample_l_indexable(texture2d)(float,float,float,float) r13.x, r5.ywyy, t8.xyzw, s1, l(0.000000)
  93  0x00000E10:       sample_l_indexable(texture2d)(float,float,float,float) r5.y, r11.yzyy, t8.xyzw, s1, l(0.000000)
  94  0x00000E44:       mov r13.yw, l(0,1.000000,0,1.000000)
  95  0x00000E64:       dp2 r5.w, cb0[14].zwzz, r13.xyxx
  96  0x00000E84:       dp2 r10.y, cb0[15].zwzz, r13.xyxx
  97  0x00000EA4:       div r5.w, r5.w, r10.y
  98  0x00000EC0:       lt r10.y, r5.y, l(0.000000)
  99  0x00000EDC:       or r10.x, r10.x, r10.y
 100  0x00000EF8:       add r5.w, r3.z, -r5.w
 101  0x00000F18:       ge r10.y, r5.w, l(0.000000)
 102  0x00000F34:       and r10.y, r10.y, l(0x3f800000)
 103  0x00000F50:       ge r11.y, r5.w, r8.z
 104  0x00000F6C:       and r13.x, r11.y, l(0x3f800000)
 105  0x00000F88:       add r5.y, -r5.y, r5.z
 106  0x00000FA8:       ge r11.y, |r5.y|, l(0.030000)
 107  0x00000FC8:       and r11.y, r11.y, l(0x3f800000)
 108  0x00000FE4:       mad r13.y, r10.y, r11.y, r13.x
 109  0x00001008:       mul r11.yz, r13.xxyx, cb2[5].zzzz
 110  0x00001028:       mad r11.yz, r12.xxyx, cb2[4].zzzz, r11.yyzy
 111  0x00001050:       mov r12.z, |r5.w|
 112  0x00001068:       mad r12.w, r10.y, |r5.y|, r12.z
 113  0x00001090:       max r5.yw, r10.zzzw, r12.zzzw
 114  0x000010AC:       mad r10.yz, cb2[6].xxyx, r8.yyyy, v1.xxyx
 115  0x000010D4:       min r10.yz, r10.yyzy, cb2[3].zzwz
 116  0x000010F4:       mad r12.xy, cb2[6].xyxx, r6.wwww, v1.xyxx
 117  0x0000111C:       min r12.xy, r12.xyxx, cb2[3].zwzz
 118  0x0000113C:       sample_l_indexable(texture2d)(float,float,float,float) r13.z, r10.yzyy, t8.yzxw, s1, l(0.000000)
 119  0x00001170:       sample_l_indexable(texture2d)(float,float,float,float) r10.y, r12.xyxx, t8.xyzw, s1, l(0.000000)
 120  0x000011A4:       dp2 r10.z, cb0[14].zwzz, r13.zwzz
 121  0x000011C4:       dp2 r10.w, cb0[15].zwzz, r13.zwzz
 122  0x000011E4:       div r10.z, r10.z, r10.w
 123  0x00001200:       lt r10.w, r10.y, l(0.000000)
 124  0x0000121C:       or r10.x, r10.x, r10.w
 125  0x00001238:       add r10.z, r3.z, -r10.z
 126  0x00001258:       ge r10.w, r10.z, l(0.000000)
 127  0x00001274:       and r10.w, r10.w, l(0x3f800000)
 128  0x00001290:       ge r11.w, r10.z, r8.z
 129  0x000012AC:       and r12.x, r11.w, l(0x3f800000)
 130  0x000012C8:       add r10.y, r5.z, -r10.y
 131  0x000012E8:       ge r11.w, |r10.y|, l(0.030000)
 132  0x00001308:       and r11.w, r11.w, l(0x3f800000)
 133  0x00001324:       mad r12.y, r10.w, r11.w, r12.x
 134  0x00001348:       mad r11.yz, r12.xxyx, cb2[6].zzzz, r11.yyzy
 135  0x00001370:       mov r12.z, |r10.z|
 136  0x00001388:       mad r12.w, r10.w, |r10.y|, r12.z
 137  0x000013B0:       max r5.yw, r5.yyyw, r12.zzzw
 138  0x000013CC:       mad r10.yz, cb2[7].xxyx, r8.yyyy, v1.xxyx
 139  0x000013F4:       min r10.yz, r10.yyzy, cb2[3].zzwz
 140  0x00001414:       mad r12.xy, cb2[7].xyxx, r6.wwww, v1.xyxx
 141  0x0000143C:       min r12.xy, r12.xyxx, cb2[3].zwzz
 142  0x0000145C:       sample_l_indexable(texture2d)(float,float,float,float) r13.x, r10.yzyy, t8.xyzw, s1, l(0.000000)
 143  0x00001490:       sample_l_indexable(texture2d)(float,float,float,float) r10.y, r12.xyxx, t8.xyzw, s1, l(0.000000)
 144  0x000014C4:       mov r13.yw, l(0,1.000000,0,1.000000)
 145  0x000014E4:       dp2 r10.z, cb0[14].zwzz, r13.xyxx
 146  0x00001504:       dp2 r10.w, cb0[15].zwzz, r13.xyxx
 147  0x00001524:       div r10.z, r10.z, r10.w
 148  0x00001540:       lt r10.w, r10.y, l(0.000000)
 149  0x0000155C:       or r10.x, r10.x, r10.w
 150  0x00001578:       add r10.z, r3.z, -r10.z
 151  0x00001598:       ge r10.w, r10.z, l(0.000000)
 152  0x000015B4:       and r10.w, r10.w, l(0x3f800000)
 153  0x000015D0:       ge r11.w, r10.z, r8.z
 154  0x000015EC:       and r12.x, r11.w, l(0x3f800000)
 155  0x00001608:       add r10.y, r5.z, -r10.y
 156  0x00001628:       ge r11.w, |r10.y|, l(0.030000)
 157  0x00001648:       and r11.w, r11.w, l(0x3f800000)
 158  0x00001664:       mad r12.y, r10.w, r11.w, r12.x
 159  0x00001688:       mad r11.yz, r12.xxyx, cb2[7].zzzz, r11.yyzy
 160  0x000016B0:       mov r12.z, |r10.z|
 161  0x000016C8:       mad r12.w, r10.w, |r10.y|, r12.z
 162  0x000016F0:       max r5.yw, r5.yyyw, r12.zzzw
 163  0x0000170C:       mad r10.yz, cb2[8].xxyx, r8.yyyy, v1.xxyx
 164  0x00001734:       min r10.yz, r10.yyzy, cb2[3].zzwz
 165  0x00001754:       mad r12.xy, cb2[8].xyxx, r6.wwww, v1.xyxx
 166  0x0000177C:       min r12.xy, r12.xyxx, cb2[3].zwzz
 167  0x0000179C:       sample_l_indexable(texture2d)(float,float,float,float) r13.z, r10.yzyy, t8.yzxw, s1, l(0.000000)
 168  0x000017D0:       sample_l_indexable(texture2d)(float,float,float,float) r10.y, r12.xyxx, t8.xyzw, s1, l(0.000000)
 169  0x00001804:       dp2 r10.z, cb0[14].zwzz, r13.zwzz
 170  0x00001824:       dp2 r10.w, cb0[15].zwzz, r13.zwzz
 171  0x00001844:       div r10.z, r10.z, r10.w
 172  0x00001860:       lt r10.w, r10.y, l(0.000000)
 173  0x0000187C:       or r10.x, r10.x, r10.w
 174  0x00001898:       add r10.z, r3.z, -r10.z
 175  0x000018B8:       ge r10.w, r10.z, l(0.000000)
 176  0x000018D4:       and r10.w, r10.w, l(0x3f800000)
 177  0x000018F0:       ge r11.w, r10.z, r8.z
 178  0x0000190C:       and r12.x, r11.w, l(0x3f800000)
 179  0x00001928:       add r10.y, r5.z, -r10.y
 180  0x00001948:       ge r11.w, |r10.y|, l(0.030000)
 181  0x00001968:       and r11.w, r11.w, l(0x3f800000)
 182  0x00001984:       mad r12.y, r10.w, r11.w, r12.x
 183  0x000019A8:       mad r11.yz, r12.xxyx, cb2[8].zzzz, r11.yyzy
 184  0x000019D0:       mov r12.z, |r10.z|
 185  0x000019E8:       mad r12.w, r10.w, |r10.y|, r12.z
 186  0x00001A10:       max r5.yw, r5.yyyw, r12.zzzw
 187  0x00001A2C:       mad r10.yz, cb2[9].xxyx, r8.yyyy, v1.xxyx
 188  0x00001A54:       min r10.yz, r10.yyzy, cb2[3].zzwz
 189  0x00001A74:       mad r12.xy, cb2[9].xyxx, r6.wwww, v1.xyxx
 190  0x00001A9C:       min r12.xy, r12.xyxx, cb2[3].zwzz
 191  0x00001ABC:       sample_l_indexable(texture2d)(float,float,float,float) r13.x, r10.yzyy, t8.xyzw, s1, l(0.000000)
 192  0x00001AF0:       sample_l_indexable(texture2d)(float,float,float,float) r10.y, r12.xyxx, t8.xyzw, s1, l(0.000000)
 193  0x00001B24:       mov r13.yw, l(0,1.000000,0,1.000000)
 194  0x00001B44:       dp2 r10.z, cb0[14].zwzz, r13.xyxx
 195  0x00001B64:       dp2 r10.w, cb0[15].zwzz, r13.xyxx
 196  0x00001B84:       div r10.z, r10.z, r10.w
 197  0x00001BA0:       lt r10.w, r10.y, l(0.000000)
 198  0x00001BBC:       or r10.x, r10.x, r10.w
 199  0x00001BD8:       add r10.z, r3.z, -r10.z
 200  0x00001BF8:       ge r10.w, r10.z, l(0.000000)
 201  0x00001C14:       and r10.w, r10.w, l(0x3f800000)
 202  0x00001C30:       ge r11.w, r10.z, r8.z
 203  0x00001C4C:       and r12.x, r11.w, l(0x3f800000)
 204  0x00001C68:       add r10.y, r5.z, -r10.y
 205  0x00001C88:       ge r11.w, |r10.y|, l(0.030000)
 206  0x00001CA8:       and r11.w, r11.w, l(0x3f800000)
 207  0x00001CC4:       mad r12.y, r10.w, r11.w, r12.x
 208  0x00001CE8:       mad r11.yz, r12.xxyx, cb2[9].zzzz, r11.yyzy
 209  0x00001D10:       mov r12.z, |r10.z|
 210  0x00001D28:       mad r12.w, r10.w, |r10.y|, r12.z
 211  0x00001D50:       max r5.yw, r5.yyyw, r12.zzzw
 212  0x00001D6C:       mad r10.yz, cb2[10].xxyx, r8.yyyy, v1.xxyx
 213  0x00001D94:       min r10.yz, r10.yyzy, cb2[3].zzwz
 214  0x00001DB4:       mad r12.xy, cb2[10].xyxx, r6.wwww, v1.xyxx
 215  0x00001DDC:       min r12.xy, r12.xyxx, cb2[3].zwzz
 216  0x00001DFC:       sample_l_indexable(texture2d)(float,float,float,float) r13.z, r10.yzyy, t8.yzxw, s1, l(0.000000)
 217  0x00001E30:       sample_l_indexable(texture2d)(float,float,float,float) r10.y, r12.xyxx, t8.xyzw, s1, l(0.000000)
 218  0x00001E64:       dp2 r10.z, cb0[14].zwzz, r13.zwzz
 219  0x00001E84:       dp2 r10.w, cb0[15].zwzz, r13.zwzz
 220  0x00001EA4:       div r10.z, r10.z, r10.w
 221  0x00001EC0:       lt r10.w, r10.y, l(0.000000)
 222  0x00001EDC:       or r10.x, r10.x, r10.w
 223  0x00001EF8:       add r10.z, r3.z, -r10.z
 224  0x00001F18:       ge r10.w, r10.z, l(0.000000)
 225  0x00001F34:       and r10.w, r10.w, l(0x3f800000)
 226  0x00001F50:       ge r11.w, r10.z, r8.z
 227  0x00001F6C:       and r12.x, r11.w, l(0x3f800000)
 228  0x00001F88:       add r10.y, r5.z, -r10.y
 229  0x00001FA8:       ge r11.w, |r10.y|, l(0.030000)
 230  0x00001FC8:       and r11.w, r11.w, l(0x3f800000)
 231  0x00001FE4:       mad r12.y, r10.w, r11.w, r12.x
 232  0x00002008:       mad r11.yz, r12.xxyx, cb2[10].zzzz, r11.yyzy
 233  0x00002030:       mov r12.z, |r10.z|
 234  0x00002048:       mad r12.w, r10.w, |r10.y|, r12.z
 235  0x00002070:       max r5.yw, r5.yyyw, r12.zzzw
 236  0x0000208C:       mad r10.yz, cb2[11].xxyx, r8.yyyy, v1.xxyx
 237  0x000020B4:       min r10.yz, r10.yyzy, cb2[3].zzwz
 238  0x000020D4:       mad r12.xy, cb2[11].xyxx, r6.wwww, v1.xyxx
 239  0x000020FC:       min r12.xy, r12.xyxx, cb2[3].zwzz
 240  0x0000211C:       sample_l_indexable(texture2d)(float,float,float,float) r10.y, r10.yzyy, t8.zxyw, s1, l(0.000000)
 241  0x00002150:       sample_l_indexable(texture2d)(float,float,float,float) r6.w, r12.xyxx, t8.xzwy, s1, l(0.000000)
 242  0x00002184:       mov r10.z, l(1.000000)
 243  0x00002198:       dp2 r8.y, cb0[14].zwzz, r10.yzyy
 244  0x000021B8:       dp2 r10.y, cb0[15].zwzz, r10.yzyy
 245  0x000021D8:       div r8.y, r8.y, r10.y
 246  0x000021F4:       lt r10.y, r6.w, l(0.000000)
 247  0x00002210:       or r10.x, r10.x, r10.y
 248  0x0000222C:       add r3.z, r3.z, -r8.y
 249  0x0000224C:       ge r8.y, r3.z, l(0.000000)
 250  0x00002268:       and r8.y, r8.y, l(0x3f800000)
 251  0x00002284:       ge r8.z, r3.z, r8.z
 252  0x000022A0:       and r12.x, r8.z, l(0x3f800000)
 253  0x000022BC:       add r5.z, r5.z, -r6.w
 254  0x000022DC:       ge r6.w, |r5.z|, l(0.030000)
 255  0x000022FC:       and r6.w, r6.w, l(0x3f800000)
 256  0x00002318:       mad r12.y, r8.y, r6.w, r12.x
 257  0x0000233C:       mad r12.xy, r12.xyxx, cb2[11].zzzz, r11.yzyy
 258  0x00002364:       mov r10.z, |r3.z|
 259  0x0000237C:       mad r10.w, r8.y, |r5.z|, r10.z
 260  0x000023A4:       max r12.zw, r5.yyyw, r10.zzzw
 261  0x000023C0:       movc r5.yz, r10.xxxx, r12.xxzx, r12.yywy
 262  0x000023E4:       ushr r10.yw, r2.zzzw, l(0, 4, 0, 4)
 263  0x0000240C:       mov r10.xz, r2.zzwz
 264  0x00002420:       and r10.xyzw, r10.xyzw, l(15, 15, 15, 15)
 265  0x00002448:       utof r10.xyzw, r10.xyzw
 266  0x0000245C:       mov r9.w, l(0.066667)
 267  0x00002470:       mul r12.xyzw, r9.xyzw, r10.xyzw
 268  0x0000248C:       lt r3.z, l(0.000000), r10.w
 269  0x000024A8:       min r5.z, r8.w, r5.z
 270  0x000024C4:       div r5.z, r5.z, r8.w
 271  0x000024E0:       log r5.z, r5.z
 272  0x000024F4:       mul r5.z, r5.z, l(1.250000)
 273  0x00002510:       exp r5.z, r5.z
 274  0x00002524:       mul r5.y, r5.y, r5.y
 275  0x00002540:       mul r5.y, r12.w, r5.y
 276  0x0000255C:       mul r5.y, r5.y, cb2[2].x
 277  0x0000257C:       min r5.y, r5.y, l(1.000000)
 278  0x00002598:       mul r5.y, r5.z, r5.y
 279  0x000025B4:       add r5.z, -r11.x, l(1.000000)
 280  0x000025D4:       mul r5.y, r5.z, r5.y
 281  0x000025F0:       mad r8.yzw, r12.xxyz, l(0.000000, 0.066667, 0.066667, 0.066667), -r9.xxyz
 282  0x00002624:       mad r5.yzw, r5.yyyy, r8.yyzw, r9.xxyz
 283  0x00002648:       movc r9.xyz, r3.zzzz, r5.yzwy, r9.xyzx
 284  0x0000266C:     endif 
 285  0x00002670:   else 
 286  0x00002674:     add r3.z, -r5.x, l(1.000000)
 287  0x00002694:     mul r3.z, r3.z, r8.x
 288  0x000026B0:     mad r5.yzw, r0.xxyz, cb4[1].xxyz, -r0.xxyz
 289  0x000026DC:     mad r9.xyz, r3.zzzz, r5.yzwy, r0.xyzx
 290  0x00002700:   endif 
 291  0x00002704:   mad r5.yzw, r9.xxyz, r7.wwww, r7.xxyz
 292  0x00002728:   add r5.yzw, -r9.xxyz, r5.yyzw
 293  0x00002748:   mad r5.yzw, cb7[3].zzzz, r5.yyzw, r9.xxyz
 294  0x00002770:   movc o0.xyz, r3.wwww, r9.xyzx, r5.yzwy
 295  0x00002794:   mov o0.w, r0.w
 296  0x000027A8:   mov o1.xyzw, r2.xyzw
 297  0x000027BC:   mov o2.xy, r3.xyxx
 298  0x000027D0:   ret 
 299  0x000027D4: endif 
 300  0x000027D8: mad r3.zw, r4.xxxz, cb0[74].zzzz, cb0[74].xxxy
 301  0x00002804: sample_l_indexable(texture2d)(float,float,float,float) r3.zw, r3.zwzz, t27.yzxw, s11, l(0.000000)
 302  0x00002838: add r0.w, r3.z, l(-1.000000)
 303  0x00002854: mad r0.w, r3.w, r0.w, l(1.000000)
 304  0x00002878: min r3.zw, v1.xxxy, cb4[0].xxxy
 305  0x00002898: sample_l_indexable(texture2d)(float,float,float,float) r3.z, r3.zwzz, t7.yzxw, s1, l(0.000000)
 306  0x000028CC: min r3.w, r0.w, r3.z
 307  0x000028E8: utof r1.xy, r1.xyxx
 308  0x000028FC: mad r8.zw, r1.xxxy, l(0.000000, 0.000000, 0.000031, 0.000031), l(0.000000, 0.000000, -1.000000, -1.000000)
 309  0x00002938: mul r1.x, r8.z, l(3.141593)
 310  0x00002954: sincos r1.x, r9.x, r1.x
 311  0x00002970: mul r1.y, r8.w, r8.w
 312  0x0000298C: mad r5.y, -r8.w, r8.w, l(1.000000)
 313  0x000029B4: sqrt r5.y, r5.y
 314  0x000029C8: mul r8.x, r5.y, r9.x
 315  0x000029E4: mul r8.y, r1.x, r5.y
 316  0x00002A00: utof r2.xyzw, r2.xyzw
 317  0x00002A14: mul r9.xyzw, r2.wxyz, l(0.003922, 0.003922, 0.003922, 0.003922)
 318  0x00002A3C: ushr r2.yz, r3.yyyy, l(0, 5, 10, 0)
 319  0x00002A64: mov r2.x, r3.y
 320  0x00002A78: and r2.xyz, r2.xyzx, l(31, 31, 31, 0)
 321  0x00002AA0: utof r2.xyz, r2.xyzx
 322  0x00002AB4: mul r5.yzw, r2.xxyz, l(0.000000, 0.032258, 0.032258, 0.032258)
 323  0x00002ADC: umin r1.x, r3.x, l(0x00004e1f)
 324  0x00002AF8: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r10.xyzw, r1.x, l(0), t6.xyzw
 325  0x00002B24: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r11.xyzw, r1.x, l(16), t6.xyzw
 326  0x00002B50: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r12.xyzw, r1.x, l(32), t6.xyzw
 327  0x00002B7C: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r13.xyz, r1.x, l(48), t6.xyzx
 328  0x00002BA8: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r14.xyzw, r1.x, l(64), t6.xyzw
 329  0x00002BD4: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r15.xyzw, r1.x, l(80), t6.xyzw
 330  0x00002C00: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r16.xyzw, r1.x, l(96), t6.xyzw
 331  0x00002C2C: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r17.xyz, r1.x, l(112), t6.xyzx
 332  0x00002C58: ld_structured_indexable(structured_buffer, stride=144)(mixed,mixed,mixed,mixed) r18.xyz, r1.x, l(128), t6.xyzx
 333  0x00002C84: mov r13.w, r14.x
 334  0x00002C98: mov r19.xz, r13.yyzy
 335  0x00002CAC: mov r19.yw, r14.yyyz
 336  0x00002CC0: add r2.xy, -r13.xwxx, r19.xyxx
 337  0x00002CE0: mad r2.xy, r5.yyyy, r2.xyxx, r13.xwxx
 338  0x00002D04: add r3.xy, -r2.xyxx, r19.zwzz
 339  0x00002D24: mad r2.xy, r5.zzzz, r3.xyxx, r2.xyxx
 340  0x00002D48: mul r3.xy, v0.xyxx, cb0[29].xyxx
 341  0x00002D68: ftou r3.xy, r3.xyxx
 342  0x00002D7C: ishl r1.x, r3.y, l(5)
 343  0x00002D98: iadd r3.y, r3.x, r1.x
 344  0x00002DB4: ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r3.y, r3.y, l(572), t12.xxxx
 345  0x00002DE0: mul r3.y, -r1.w, r3.y
 346  0x00002E00: min r3.y, r3.y, l(7.000000)
 347  0x00002E1C: max r3.y, r3.y, l(0.000000)
 348  0x00002E38: ftou r3.y, r3.y
 349  0x00002E4C: imad r1.x, r3.y, l(576), r1.x
 350  0x00002E70: iadd r1.x, r3.x, r1.x
 351  0x00002E8C: umin r1.x, r1.x, l(4607)
 352  0x00002EA8: mad r13.xyz, cb0[38].xyzx, r8.xxxx, cb0[37].xyzx
 353  0x00002ED4: mad r13.xyz, cb0[39].xyzx, r8.yyyy, r13.xyzx
 354  0x00002EFC: mad r13.xyz, cb0[40].xyzx, r8.wwww, r13.xyzx
 355  0x00002F24: mul r14.xyz, r8.wwww, cb0[41].xyzx
 356  0x00002F44: mad r13.xyz, r14.xyzx, r8.xxxx, r13.xyzx
 357  0x00002F68: mul r14.xyz, r8.yyyy, cb0[42].xyzx
 358  0x00002F88: mad r13.xyz, r14.xyzx, r8.wwww, r13.xyzx
 359  0x00002FAC: mul r14.xyz, r8.yyyy, cb0[43].xyzx
 360  0x00002FCC: mad r13.xyz, r14.xyzx, r8.xxxx, r13.xyzx
 361  0x00002FF0: mad r1.y, r1.y, l(3.000000), l(-1.000000)
 362  0x00003014: mad r13.xyz, cb0[44].xyzx, r1.yyyy, r13.xyzx
 363  0x0000303C: mul r1.y, r8.y, r8.y
 364  0x00003058: mad r1.y, r8.x, r8.x, -r1.y
 365  0x00003080: mad r13.xyz, cb0[45].xyzx, r1.yyyy, r13.xyzx
 366  0x000030A8: max r13.xyz, r13.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
 367  0x000030D0: add r14.x, -r4.x, cb0[4].w
 368  0x000030F4: add r14.y, -r4.y, cb0[5].w
 369  0x00003118: add r14.z, -r4.z, cb0[6].w
 370  0x0000313C: dp3 r1.y, r14.xyzx, r14.xyzx
 371  0x00003158: rsq r1.y, r1.y
 372  0x0000316C: mul r19.xyz, r1.yyyy, r14.xyzx
 373  0x00003188: add r10.xyz, r10.xyzx, cb0[27].xyzx
 374  0x000031A8: min r10.xyz, r10.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 375  0x000031D0: mul r3.x, r5.w, r10.w
 376  0x000031EC: dp3 r3.y, r8.xywx, r19.xyzx
 377  0x00003208: and r20.xyzw, r18.zzzz, l(1, 2, 4, 16)
 378  0x00003230: movc r3.w, r20.x, r3.w, l(1.000000)
 379  0x00003254: mad r21.xyz, r14.xyzx, r1.yyyy, -cb0[26].xyzx
 380  0x00003280: dp3 r5.y, r21.xyzx, r21.xyzx
 381  0x0000329C: rsq r5.y, r5.y
 382  0x000032B0: mul r21.xyz, r5.yyyy, r21.xyzx
 383  0x000032CC: mul r5.y, r2.y, cb0[32].y
 384  0x000032EC: dp3_sat r5.z, r21.xyzx, r8.xywx
 385  0x00003308: max r5.y, r5.y, l(0.001000)
 386  0x00003324: log r5.z, r5.z
 387  0x00003338: mul r5.y, r5.z, r5.y
 388  0x00003354: exp r5.y, r5.y
 389  0x00003368: mul r5.y, r3.w, r5.y
 390  0x00003384: mul r5.y, r5.y, cb0[32].z
 391  0x000033A4: movc r5.y, r20.y, r5.y, l(0)
 392  0x000033C8: mul r11.xyz, r11.xyzx, r5.yyyy
 393  0x000033E4: mul r11.xyz, r11.xyzx, cb0[25].xyzx
 394  0x00003404: if_nz r20.z
 395  0x00003410:   mul r5.yz, r9.yyzy, r15.yyzy
 396  0x0000342C:   and r6.w, r18.z, l(32)
 397  0x00003448:   if_nz r6.w
 398  0x00003454:     add r21.y, -v1.y, cb0[49].y
 399  0x00003478:     mov r21.x, v1.x
 400  0x0000348C:     sample_l_indexable(texture2d)(float,float,float,float) r21.xyz, r21.xyxx, t21.xyzw, s15, l(0.000000)
 401  0x000034C0:   else 
 402  0x000034C4:     add r8.z, r3.y, r3.y
 403  0x000034E0:     mad r22.xyz, r8.xywx, -r8.zzzz, r19.xyzx
 404  0x00003508:     resinfo_indexable(texturecube)(float,float,float,float)_uint r8.z, l(0), t17.xywz
 405  0x0000352C:     mul r22.xyz, r22.xyzx, l(1.000000, -1.000000, -1.000000, 0.000000)
 406  0x00003554:     iadd r8.z, r8.z, l(-1)
 407  0x00003570:     utof r8.z, r8.z
 408  0x00003584:     mul r8.z, r5.z, r8.z
 409  0x000035A0:     sample_l_indexable(texturecube)(float,float,float,float) r21.xyz, r22.xyzx, t17.xyzw, s14, r8.z
 410  0x000035D4:   endif 
 411  0x000035D8:   and r8.z, r1.z, l(2)
 412  0x000035F4:   if_nz r8.z
 413  0x00003600:     mul r20.xz, v1.zzwz, cb0[49].xxyx
 414  0x00003620:     sample_l_indexable(texture2d)(float,float,float,float) r22.xyzw, r20.xzxx, t24.xyzw, s15, l(0.000000)
 415  0x00003654:     add r22.xyz, -r21.xyzx, r22.xyzx
 416  0x00003674:     mad r21.xyz, r22.wwww, r22.xyzx, r21.xyzx
 417  0x00003698:   endif 
 418  0x0000369C:   lt r8.z, l(0.000000), r2.x
 419  0x000036B8:   add r9.y, -|r3.y|, l(1.000000)
 420  0x000036D8:   max r9.y, r9.y, l(0.000000)
 421  0x000036F4:   log r9.y, r9.y
 422  0x00003708:   mul r2.x, r2.x, r9.y
 423  0x00003724:   exp r2.x, r2.x
 424  0x00003738:   movc r2.x, r8.z, r2.x, l(1.000000)
 425  0x0000375C:   mul r8.z, r2.x, r5.y
 426  0x00003778:   mad r22.xyz, r0.xyzx, r21.xyzx, -r0.xyzx
 427  0x000037A0:   mad r22.xyz, r8.zzzz, r22.xyzx, r0.xyzx
 428  0x000037C4:   dp3 r8.z, r21.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
 429  0x000037EC:   mad r5.z, r5.z, l(-9.000000), l(10.000000)
 430  0x00003810:   log r8.z, r8.z
 431  0x00003824:   mul r5.z, r5.z, r8.z
 432  0x00003840:   exp r5.z, r5.z
 433  0x00003854:   add r8.z, -r5.z, l(1.000000)
 434  0x00003874:   mad r5.y, r5.y, r8.z, r5.z
 435  0x00003898:   mul r21.xyz, r5.yyyy, r21.xyzx
 436  0x000038B4:   mul r21.xyz, r2.xxxx, r21.xyzx
 437  0x000038D0:   mad r2.x, -r9.z, r15.z, l(1.000000)
 438  0x000038F8:   mad r21.xyz, r21.xyzx, r2.xxxx, r11.xyzx
 439  0x0000391C:   movc r11.xyz, r6.wwww, r11.xyzx, r21.xyzx
 440  0x00003940: else 
 441  0x00003944:   and r2.x, r18.z, l(8)
 442  0x00003960:   if_nz r2.x
 443  0x0000396C:     add r2.x, r3.y, r3.y
 444  0x00003988:     mad r21.xyz, r8.xywx, -r2.xxxx, r19.xyzx
 445  0x000039B0:     div r2.x, l(1.000000, 1.000000, 1.000000, 1.000000), r15.w
 446  0x000039D8:     dp3 r5.y, -r19.xyzx, r8.xywx
 447  0x000039F8:     mul r5.z, r2.x, r2.x
 448  0x00003A14:     mad r6.w, -r5.y, r5.y, l(1.000000)
 449  0x00003A3C:     mad r5.z, -r5.z, r6.w, l(1.000000)
 450  0x00003A64:     sqrt r6.w, r5.z
 451  0x00003A78:     mad r5.y, r2.x, r5.y, r6.w
 452  0x00003A9C:     ge r5.z, r5.z, l(0.000000)
 453  0x00003AB8:     mul r23.xyz, r8.xywx, r5.yyyy
 454  0x00003AD4:     mad r19.xyz, r2.xxxx, -r19.xyzx, -r23.xyzx
 455  0x00003B00:     and r19.xyz, r5.zzzz, r19.xyzx
 456  0x00003B1C:     mul r2.x, r9.z, r15.z
 457  0x00003B38:     resinfo_indexable(texturecube)(float,float,float,float)_uint r5.y, l(0), t17.xwyz
 458  0x00003B5C:     mul r21.xyz, r21.xyzx, l(1.000000, -1.000000, -1.000000, 0.000000)
 459  0x00003B84:     iadd r5.y, r5.y, l(-1)
 460  0x00003BA0:     utof r5.y, r5.y
 461  0x00003BB4:     mul r2.x, r2.x, r5.y
 462  0x00003BD0:     sample_l_indexable(texturecube)(float,float,float,float) r21.xyz, r21.xyzx, t17.xyzw, s14, r2.x
 463  0x00003C04:     and r5.y, r1.z, l(2)
 464  0x00003C20:     if_nz r5.y
 465  0x00003C2C:       mul r5.yz, v1.zzwz, cb0[49].xxyx
 466  0x00003C4C:       sample_l_indexable(texture2d)(float,float,float,float) r23.xyzw, r5.yzyy, t24.xyzw, s15, l(0.000000)
 467  0x00003C80:       add r23.xyz, -r21.xyzx, r23.xyzx
 468  0x00003CA0:       mad r21.xyz, r23.wwww, r23.xyzx, r21.xyzx
 469  0x00003CC4:     endif 
 470  0x00003CC8:     sample_l_indexable(texturecube)(float,float,float,float) r19.xyz, r19.xyzx, t17.xyzw, s14, r2.x
 471  0x00003CFC:     lt r2.x, l(0.000000), r16.x
 472  0x00003D18:     add r5.y, -|r3.y|, l(1.000000)
 473  0x00003D38:     max r5.y, r5.y, l(0.000000)
 474  0x00003D54:     log r5.y, r5.y
 475  0x00003D68:     mul r5.y, r5.y, r16.x
 476  0x00003D84:     exp r5.y, r5.y
 477  0x00003D98:     movc r2.x, r2.x, r5.y, l(1.000000)
 478  0x00003DBC:     mad r23.xyz, r0.xyzx, r21.xyzx, -r0.xyzx
 479  0x00003DE4:     mad r23.xyz, r2.xxxx, r23.xyzx, r0.xyzx
 480  0x00003E08:     mad r2.w, -r2.w, l(0.003922), l(1.000000)
 481  0x00003E30:     mad r9.x, r2.x, r2.w, r9.x
 482  0x00003E54:     mul r2.w, r16.y, |r3.y|
 483  0x00003E74:     log r2.w, r2.w
 484  0x00003E88:     mul r2.w, r2.w, r16.z
 485  0x00003EA4:     exp r2.w, r2.w
 486  0x00003EB8:     mul r16.xyz, r21.xyzx, r9.xxxx
 487  0x00003ED4:     mul r16.xyz, r2.xxxx, r16.xyzx
 488  0x00003EF0:     mad r2.x, -r9.z, r15.z, l(1.000000)
 489  0x00003F18:     mad r11.xyz, r16.xyzx, r2.xxxx, r11.xyzx
 490  0x00003F3C:     mul r15.yzw, r19.xxyz, r2.wwww
 491  0x00003F58:     mul r22.xyz, r15.yzwy, r23.xyzx
 492  0x00003F74:   else 
 493  0x00003F78:     mov r22.xyz, r0.xyzx
 494  0x00003F8C:   endif 
 495  0x00003F90: endif 
 496  0x00003F94: mul r2.x, r3.w, r9.x
 497  0x00003FB0: add r15.yzw, -r10.xxyz, l(0.000000, 1.000000, 1.000000, 1.000000)
 498  0x00003FDC: mad r10.xyz, r2.xxxx, r15.yzwy, r10.xyzx
 499  0x00004000: log r2.x, r3.z
 500  0x00004014: mul r2.x, r2.x, cb4[2].w
 501  0x00004034: exp r2.x, r2.x
 502  0x00004048: mul r15.yzw, r0.wwww, cb4[2].xxyz
 503  0x00004068: mad r16.xyz, -cb4[2].xyzx, r0.wwww, r10.xyzx
 504  0x00004094: mad r15.yzw, r3.zzzz, r16.xxyz, r15.yyzw
 505  0x000040B8: mul r0.w, r9.x, r2.x
 506  0x000040D4: add r9.xyz, -r10.xyzx, r15.yzwy
 507  0x000040F4: mad r9.xyz, r0.wwww, r9.xyzx, r10.xyzx
 508  0x00004118: mad r9.xyz, r9.xyzx, cb0[25].xyzx, r13.xyzx
 509  0x00004140: min r0.w, r3.x, l(1.000000)
 510  0x0000415C: add r10.xyz, -r9.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
 511  0x00004188: mad r9.xyz, r0.wwww, r10.xyzx, r9.xyzx
 512  0x000041AC: add r0.w, -|r3.y|, l(1.000000)
 513  0x000041CC: max r0.w, r0.w, l(0.000000)
 514  0x000041E8: mul r0.w, r12.w, r0.w
 515  0x00004204: log r0.w, r0.w
 516  0x00004218: mul r0.w, r0.w, r11.w
 517  0x00004234: exp r0.w, r0.w
 518  0x00004248: min r0.w, r0.w, l(1.000000)
 519  0x00004264: mad r3.xyz, r12.xyzx, r0.wwww, r11.xyzx
 520  0x00004288: if_nz r20.y
 521  0x00004294:   ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r0.w, r1.x, l(252), t12.xxxx
 522  0x000042C0:   umin r0.w, r0.w, l(63)
 523  0x000042DC:   mov r10.xyz, l(0,0,0,0)
 524  0x000042FC:   mov r11.xyz, l(0,0,0,0)
 525  0x0000431C:   mov r2.x, l(0)
 526  0x00004330:   loop 
 527  0x00004334:     uge r2.w, r2.x, r0.w
 528  0x00004350:     breakc_nz r2.w
 529  0x0000435C:     ishl r2.w, r2.x, l(2)
 530  0x00004378:     ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r2.w, r1.x, r2.w, t12.xxxx
 531  0x000043A4:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r12.xyz, r2.w, l(0), t11.xyzx
 532  0x000043D0:     add r12.xyz, -r4.xyzx, r12.xyzx
 533  0x000043F0:     dp3 r5.y, r12.xyzx, r12.xyzx
 534  0x0000440C:     sqrt r5.z, r5.y
 535  0x00004420:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.w, r2.w, l(28), t11.xxxx
 536  0x0000444C:     mul r5.z, r5.z, r6.w
 537  0x00004468:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.w, r2.w, l(44), t11.xxxx
 538  0x00004494:     log r5.z, |r5.z|
 539  0x000044AC:     mul r5.z, r5.z, r6.w
 540  0x000044C8:     exp r5.z, r5.z
 541  0x000044DC:     add r5.z, -r5.z, l(1.000000)
 542  0x000044FC:     max r5.z, r5.z, l(0.000000)
 543  0x00004518:     lt r6.w, l(0.000000), r5.z
 544  0x00004534:     if_nz r6.w
 545  0x00004540:       rsq r5.y, r5.y
 546  0x00004554:       mul r12.xyz, r5.yyyy, r12.xyzx
 547  0x00004570:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r5.y, r2.w, l(96), t11.xxxx
 548  0x0000459C:       dp3 r6.w, r12.xyzx, r8.xywx
 549  0x000045B8:       max r5.y, r5.y, r6.w
 550  0x000045D4:       mul r5.y, r5.y, r5.z
 551  0x000045F0:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r13.xyz, r2.w, l(16), t11.xyzx
 552  0x0000461C:       mad r11.xyz, r13.xyzx, r5.yyyy, r11.xyzx
 553  0x00004640:       mad r12.xyz, r14.xyzx, r1.yyyy, r12.xyzx
 554  0x00004664:       dp3 r5.z, r12.xyzx, r12.xyzx
 555  0x00004680:       rsq r5.z, r5.z
 556  0x00004694:       mul r12.xyz, r5.zzzz, r12.xyzx
 557  0x000046B0:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r15.yz, r2.w, l(68), t11.xxyx
 558  0x000046DC:       mul r2.w, r2.y, r15.z
 559  0x000046F8:       dp3_sat r5.z, r12.xyzx, r8.xywx
 560  0x00004714:       max r2.w, r2.w, l(0.001000)
 561  0x00004730:       log r5.z, r5.z
 562  0x00004744:       mul r2.w, r2.w, r5.z
 563  0x00004760:       exp r2.w, r2.w
 564  0x00004774:       mul r12.xyz, r2.wwww, r13.xyzx
 565  0x00004790:       mul r12.xyz, r5.yyyy, r12.xyzx
 566  0x000047AC:       mad r10.xyz, r12.xyzx, r15.yyyy, r10.xyzx
 567  0x000047D0:     endif 
 568  0x000047D4:     iadd r2.x, r2.x, l(1)
 569  0x000047F0:   endloop 
 570  0x000047F4:   mad r11.xyz, r11.xyzx, r14.wwww, r9.xyzx
 571  0x00004818:   ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r0.w, r1.x, l(508), t12.xxxx
 572  0x00004844:   umin r0.w, r0.w, l(63)
 573  0x00004860:   mul r12.yw, l(0.000000, 1.250000, 0.000000, -1.250000), cb0[32].wwww
 574  0x0000488C:   mov r12.xz, l(0,0,0,0)
 575  0x000048AC:   mov r13.xyz, r10.xyzx
 576  0x000048C0:   mov r15.yzw, l(0,0,0,0)
 577  0x000048E0:   mov r2.x, l(0)
 578  0x000048F4:   loop 
 579  0x000048F8:     uge r2.w, r2.x, r0.w
 580  0x00004914:     breakc_nz r2.w
 581  0x00004920:     ishl r2.w, r2.x, l(2)
 582  0x0000493C:     iadd r2.w, r2.w, l(256)
 583  0x00004958:     ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r2.w, r1.x, r2.w, t12.xxxx
 584  0x00004984:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r16.xyz, r2.w, l(0), t11.xyzx
 585  0x000049B0:     add r16.xyz, -r4.xyzx, r16.xyzx
 586  0x000049D0:     dp3 r5.y, r16.xyzx, r16.xyzx
 587  0x000049EC:     rsq r5.z, r5.y
 588  0x00004A00:     mul r16.xyz, r5.zzzz, r16.xyzx
 589  0x00004A1C:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r19.xyzw, r2.w, l(48), t11.xyzw
 590  0x00004A48:     dp3 r5.z, r16.xyzx, r19.xyzx
 591  0x00004A64:     max r5.z, r5.z, l(0.000000)
 592  0x00004A80:     add r5.z, -r5.z, l(1.000000)
 593  0x00004AA0:     mul r5.z, r19.w, r5.z
 594  0x00004ABC:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.w, r2.w, l(64), t11.xxxx
 595  0x00004AE8:     log r5.z, r5.z
 596  0x00004AFC:     mul r5.z, r5.z, r6.w
 597  0x00004B18:     exp r5.z, r5.z
 598  0x00004B2C:     add r5.z, -r5.z, l(1.000000)
 599  0x00004B4C:     max r5.z, r5.z, l(0.000000)
 600  0x00004B68:     lt r6.w, l(0.000000), r5.z
 601  0x00004B84:     if_nz r6.w
 602  0x00004B90:       sqrt r5.y, r5.y
 603  0x00004BA4:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.w, r2.w, l(28), t11.xxxx
 604  0x00004BD0:       mul r5.y, r5.y, r6.w
 605  0x00004BEC:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.w, r2.w, l(44), t11.xxxx
 606  0x00004C18:       log r5.y, |r5.y|
 607  0x00004C30:       mul r5.y, r5.y, r6.w
 608  0x00004C4C:       exp r5.y, r5.y
 609  0x00004C60:       add r5.y, -r5.y, l(1.000000)
 610  0x00004C80:       max r5.y, r5.y, l(0.000000)
 611  0x00004C9C:       mul r5.y, r5.y, r5.z
 612  0x00004CB8:       lt r5.z, l(0.000000), r5.y
 613  0x00004CD4:       if_nz r5.z
 614  0x00004CE0:         ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r19.xy, r2.w, l(96), t11.xyxx
 615  0x00004D0C:         ine r5.z, r19.y, l(-1)
 616  0x00004D28:         if_nz r5.z
 617  0x00004D34:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r21.xyzw, r19.y, l(0), t14.xyzw
 618  0x00004D60:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r23.xyzw, r19.y, l(16), t14.xyzw
 619  0x00004D8C:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r24.xyzw, r19.y, l(32), t14.xyzw
 620  0x00004DB8:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r25.xyzw, r19.y, l(48), t14.xyzw
 621  0x00004DE4:           dp4 r20.x, r4.xyzw, r21.xyzw
 622  0x00004E00:           dp4 r20.y, r4.xyzw, r23.xyzw
 623  0x00004E1C:           dp4 r20.z, r4.xyzw, r24.xyzw
 624  0x00004E38:           dp4 r5.z, r4.xyzw, r25.xyzw
 625  0x00004E54:           div r21.xyz, r20.xyzx, r5.zzzz
 626  0x00004E70:           utof r21.w, r19.y
 627  0x00004E84:           sample_c_lz_indexable(texture2darray)(float,float,float,float) r5.z, r21.xywx, t18.xxxx, s13, r21.z
 628  0x00004EB8:           add r20.xy, r12.yxyy, r21.xyxx
 629  0x00004ED4:           mov r20.z, r21.w
 630  0x00004EE8:           sample_c_lz_indexable(texture2darray)(float,float,float,float) r6.w, r20.xyzx, t18.xxxx, s13, r21.z
 631  0x00004F1C:           mul r6.w, r6.w, l(0.200000)
 632  0x00004F38:           mad r5.z, r5.z, l(0.200000), r6.w
 633  0x00004F5C:           add r20.xy, r12.wzww, r21.xyxx
 634  0x00004F78:           sample_c_lz_indexable(texture2darray)(float,float,float,float) r6.w, r20.xyzx, t18.xxxx, s13, r21.z
 635  0x00004FAC:           mad r5.z, r6.w, l(0.200000), r5.z
 636  0x00004FD0:           add r20.xy, r12.xyxx, r21.xyxx
 637  0x00004FEC:           sample_c_lz_indexable(texture2darray)(float,float,float,float) r6.w, r20.xyzx, t18.xxxx, s13, r21.z
 638  0x00005020:           mad r5.z, r6.w, l(0.200000), r5.z
 639  0x00005044:           add r20.xy, r12.zwzz, r21.xyxx
 640  0x00005060:           sample_c_lz_indexable(texture2darray)(float,float,float,float) r6.w, r20.xyzx, t18.xxxx, s13, r21.z
 641  0x00005094:           mad r5.z, r6.w, l(0.200000), r5.z
 642  0x000050B8:           mul r5.y, r5.z, r5.y
 643  0x000050D4:         endif 
 644  0x000050D8:         dp3 r5.z, r16.xyzx, r8.xywx
 645  0x000050F4:         max r5.z, r5.z, r19.x
 646  0x00005110:         mul r5.y, r5.z, r5.y
 647  0x0000512C:         ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r19.xyz, r2.w, l(16), t11.xyzx
 648  0x00005158:         mad r15.yzw, r19.xxyz, r5.yyyy, r15.yyzw
 649  0x0000517C:         mad r16.xyz, r14.xyzx, r1.yyyy, r16.xyzx
 650  0x000051A0:         dp3 r5.z, r16.xyzx, r16.xyzx
 651  0x000051BC:         rsq r5.z, r5.z
 652  0x000051D0:         mul r16.xyz, r5.zzzz, r16.xyzx
 653  0x000051EC:         ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r20.xy, r2.w, l(68), t11.xyxx
 654  0x00005218:         mul r2.w, r2.y, r20.y
 655  0x00005234:         dp3_sat r5.z, r16.xyzx, r8.xywx
 656  0x00005250:         max r2.w, r2.w, l(0.001000)
 657  0x0000526C:         log r5.z, r5.z
 658  0x00005280:         mul r2.w, r2.w, r5.z
 659  0x0000529C:         exp r2.w, r2.w
 660  0x000052B0:         mul r16.xyz, r2.wwww, r19.xyzx
 661  0x000052CC:         mul r16.xyz, r5.yyyy, r16.xyzx
 662  0x000052E8:         mad r13.xyz, r16.xyzx, r20.xxxx, r13.xyzx
 663  0x0000530C:       endif 
 664  0x00005310:     endif 
 665  0x00005314:     iadd r2.x, r2.x, l(1)
 666  0x00005330:   endloop 
 667  0x00005334:   mad r2.xyw, r15.yzyw, r14.wwww, r11.xyxz
 668  0x00005358:   mad r3.xyz, r13.xyzx, r14.wwww, r3.xyzx
 669  0x0000537C: else 
 670  0x00005380:   ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r0.w, r1.x, l(252), t12.xxxx
 671  0x000053AC:   umin r0.w, r0.w, l(63)
 672  0x000053C8:   mov r10.xyzw, l(0,0,0,0)
 673  0x000053E8:   loop 
 674  0x000053EC:     uge r1.y, r10.w, r0.w
 675  0x00005408:     breakc_nz r1.y
 676  0x00005414:     ishl r1.y, r10.w, l(2)
 677  0x00005430:     ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r1.y, r1.x, r1.y, t12.xxxx
 678  0x0000545C:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r11.xyz, r1.y, l(0), t11.xyzx
 679  0x00005488:     add r11.xyz, -r4.xyzx, r11.xyzx
 680  0x000054A8:     dp3 r5.y, r11.xyzx, r11.xyzx
 681  0x000054C4:     sqrt r5.z, r5.y
 682  0x000054D8:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.w, r1.y, l(28), t11.xxxx
 683  0x00005504:     mul r5.z, r5.z, r6.w
 684  0x00005520:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.w, r1.y, l(44), t11.xxxx
 685  0x0000554C:     log r5.z, |r5.z|
 686  0x00005564:     mul r5.z, r5.z, r6.w
 687  0x00005580:     exp r5.z, r5.z
 688  0x00005594:     add r5.z, -r5.z, l(1.000000)
 689  0x000055B4:     max r5.z, r5.z, l(0.000000)
 690  0x000055D0:     lt r6.w, l(0.000000), r5.z
 691  0x000055EC:     if_nz r6.w
 692  0x000055F8:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.w, r1.y, l(96), t11.xxxx
 693  0x00005624:       rsq r5.y, r5.y
 694  0x00005638:       mul r11.xyz, r5.yyyy, r11.xyzx
 695  0x00005654:       dp3 r5.y, r11.xyzx, r8.xywx
 696  0x00005670:       max r5.y, r5.y, r6.w
 697  0x0000568C:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r11.xyz, r1.y, l(16), t11.xyzx
 698  0x000056B8:       mul r11.xyz, r5.zzzz, r11.xyzx
 699  0x000056D4:       mad r10.xyz, r11.xyzx, r5.yyyy, r10.xyzx
 700  0x000056F8:     endif 
 701  0x000056FC:     iadd r10.w, r10.w, l(1)
 702  0x00005718:   endloop 
 703  0x0000571C:   mad r9.xyz, r10.xyzx, r14.wwww, r9.xyzx
 704  0x00005740:   ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r0.w, r1.x, l(508), t12.xxxx
 705  0x0000576C:   umin r0.w, r0.w, l(63)
 706  0x00005788:   mul r10.yw, l(0.000000, 1.250000, 0.000000, -1.250000), cb0[32].wwww
 707  0x000057B4:   mov r10.xz, l(0,0,0,0)
 708  0x000057D4:   mov r11.xyzw, l(0,0,0,0)
 709  0x000057F4:   loop 
 710  0x000057F8:     uge r1.y, r11.w, r0.w
 711  0x00005814:     breakc_nz r1.y
 712  0x00005820:     ishl r1.y, r11.w, l(2)
 713  0x0000583C:     iadd r1.y, r1.y, l(256)
 714  0x00005858:     ld_structured_indexable(structured_buffer, stride=576)(mixed,mixed,mixed,mixed) r1.y, r1.x, r1.y, t12.xxxx
 715  0x00005884:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r12.xyz, r1.y, l(0), t11.xyzx
 716  0x000058B0:     add r12.xyz, -r4.xyzx, r12.xyzx
 717  0x000058D0:     dp3 r5.y, r12.xyzx, r12.xyzx
 718  0x000058EC:     rsq r5.z, r5.y
 719  0x00005900:     mul r12.xyz, r5.zzzz, r12.xyzx
 720  0x0000591C:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r13.xyzw, r1.y, l(48), t11.xyzw
 721  0x00005948:     dp3 r5.z, r12.xyzx, r13.xyzx
 722  0x00005964:     max r5.z, r5.z, l(0.000000)
 723  0x00005980:     add r5.z, -r5.z, l(1.000000)
 724  0x000059A0:     mul r5.z, r13.w, r5.z
 725  0x000059BC:     ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.w, r1.y, l(64), t11.xxxx
 726  0x000059E8:     log r5.z, r5.z
 727  0x000059FC:     mul r5.z, r5.z, r6.w
 728  0x00005A18:     exp r5.z, r5.z
 729  0x00005A2C:     add r5.z, -r5.z, l(1.000000)
 730  0x00005A4C:     max r5.z, r5.z, l(0.000000)
 731  0x00005A68:     lt r6.w, l(0.000000), r5.z
 732  0x00005A84:     if_nz r6.w
 733  0x00005A90:       sqrt r5.y, r5.y
 734  0x00005AA4:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.w, r1.y, l(28), t11.xxxx
 735  0x00005AD0:       mul r5.y, r5.y, r6.w
 736  0x00005AEC:       ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r6.w, r1.y, l(44), t11.xxxx
 737  0x00005B18:       log r5.y, |r5.y|
 738  0x00005B30:       mul r5.y, r5.y, r6.w
 739  0x00005B4C:       exp r5.y, r5.y
 740  0x00005B60:       add r5.y, -r5.y, l(1.000000)
 741  0x00005B80:       max r5.y, r5.y, l(0.000000)
 742  0x00005B9C:       mul r5.y, r5.y, r5.z
 743  0x00005BB8:       lt r5.z, l(0.000000), r5.y
 744  0x00005BD4:       if_nz r5.z
 745  0x00005BE0:         ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r13.xy, r1.y, l(96), t11.xyxx
 746  0x00005C0C:         ine r5.z, r13.y, l(-1)
 747  0x00005C28:         if_nz r5.z
 748  0x00005C34:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r19.xyzw, r13.y, l(0), t14.xyzw
 749  0x00005C60:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r21.xyzw, r13.y, l(16), t14.xyzw
 750  0x00005C8C:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r23.xyzw, r13.y, l(32), t14.xyzw
 751  0x00005CB8:           ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r24.xyzw, r13.y, l(48), t14.xyzw
 752  0x00005CE4:           dp4 r14.x, r4.xyzw, r19.xyzw
 753  0x00005D00:           dp4 r14.y, r4.xyzw, r21.xyzw
 754  0x00005D1C:           dp4 r14.z, r4.xyzw, r23.xyzw
 755  0x00005D38:           dp4 r5.z, r4.xyzw, r24.xyzw
 756  0x00005D54:           div r19.xyz, r14.xyzx, r5.zzzz
 757  0x00005D70:           utof r19.w, r13.y
 758  0x00005D84:           sample_c_lz_indexable(texture2darray)(float,float,float,float) r5.z, r19.xywx, t18.xxxx, s13, r19.z
 759  0x00005DB8:           add r14.xy, r10.yxyy, r19.xyxx
 760  0x00005DD4:           mov r14.z, r19.w
 761  0x00005DE8:           sample_c_lz_indexable(texture2darray)(float,float,float,float) r6.w, r14.xyzx, t18.xxxx, s13, r19.z
 762  0x00005E1C:           mul r6.w, r6.w, l(0.200000)
 763  0x00005E38:           mad r5.z, r5.z, l(0.200000), r6.w
 764  0x00005E5C:           add r14.xy, r10.wzww, r19.xyxx
 765  0x00005E78:           sample_c_lz_indexable(texture2darray)(float,float,float,float) r6.w, r14.xyzx, t18.xxxx, s13, r19.z
 766  0x00005EAC:           mad r5.z, r6.w, l(0.200000), r5.z
 767  0x00005ED0:           add r14.xy, r10.xyxx, r19.xyxx
 768  0x00005EEC:           sample_c_lz_indexable(texture2darray)(float,float,float,float) r6.w, r14.xyzx, t18.xxxx, s13, r19.z
 769  0x00005F20:           mad r5.z, r6.w, l(0.200000), r5.z
 770  0x00005F44:           add r14.xy, r10.zwzz, r19.xyxx
 771  0x00005F60:           sample_c_lz_indexable(texture2darray)(float,float,float,float) r6.w, r14.xyzx, t18.xxxx, s13, r19.z
 772  0x00005F94:           mad r5.z, r6.w, l(0.200000), r5.z
 773  0x00005FB8:           mul r5.y, r5.z, r5.y
 774  0x00005FD4:         endif 
 775  0x00005FD8:         dp3 r5.z, r12.xyzx, r8.xywx
 776  0x00005FF4:         max r5.z, r5.z, r13.x
 777  0x00006010:         ld_structured_indexable(structured_buffer, stride=112)(mixed,mixed,mixed,mixed) r12.xyz, r1.y, l(16), t11.xyzx
 778  0x0000603C:         mul r12.xyz, r5.yyyy, r12.xyzx
 779  0x00006058:         mad r11.xyz, r12.xyzx, r5.zzzz, r11.xyzx
 780  0x0000607C:       endif 
 781  0x00006080:     endif 
 782  0x00006084:     iadd r11.w, r11.w, l(1)
 783  0x000060A0:   endloop 
 784  0x000060A4:   mad r2.xyw, r11.xyxz, r14.wwww, r9.xyxz
 785  0x000060C8: endif 
 786  0x000060CC: mul r3.xyz, r9.wwww, r3.xyzx
 787  0x000060E8: mad r8.xyz, r22.xyzx, r2.xywx, r3.xyzx
 788  0x0000610C: lt r0.w, l(0.000000), r17.x
 789  0x00006128: dp3 r1.x, r0.xyzx, l(0.299000, 0.587000, 0.114000, 0.000000)
 790  0x00006150: add r1.x, -r17.x, r1.x
 791  0x00006170: max r1.x, r1.x, l(0.000000)
 792  0x0000618C: div r1.x, r1.x, r17.x
 793  0x000061A8: min r1.x, r1.x, l(1.000000)
 794  0x000061C4: movc r0.w, r0.w, r1.x, l(1.000000)
 795  0x000061E8: mul r1.x, r5.w, r16.w
 796  0x00006204: mul r0.w, r0.w, r1.x
 797  0x00006220: add r1.x, r3.w, l(-1.000000)
 798  0x0000623C: mad r1.x, r17.y, r1.x, l(1.000000)
 799  0x00006260: mul r3.w, r0.w, r1.x
 800  0x0000627C: mad r3.xyz, r0.xyzx, r3.wwww, r8.xyzx
 801  0x000062A0: mov r8.w, l(0)
 802  0x000062B4: movc r0.xyzw, r20.wwww, r3.xyzw, r8.xyzw
 803  0x000062D8: add r1.x, -r5.x, l(1.000000)
 804  0x000062F8: mul r1.x, r1.x, r17.z
 805  0x00006314: mul r1.x, r1.x, cb4[1].w
 806  0x00006334: mad r2.xyw, r0.xyxz, cb4[1].xyxz, -r0.xyxz
 807  0x00006360: mad r0.xyz, r1.xxxx, r2.xywx, r0.xyzx
 808  0x00006384: add r1.x, -r1.w, -cb0[29].z
 809  0x000063AC: mul_sat r1.x, r1.x, cb0[29].w
 810  0x000063CC: add r1.x, -r1.x, l(1.000000)
 811  0x000063EC: log r1.x, r1.x
 812  0x00006400: mul r1.x, r1.x, cb0[32].x
 813  0x00006420: exp r1.x, r1.x
 814  0x00006434: add r1.x, -r1.x, l(1.000000)
 815  0x00006454: add r1.y, r4.y, -cb0[31].x
 816  0x00006478: mul_sat r1.y, r1.y, cb0[31].y
 817  0x00006498: mul r1.x, r1.y, r1.x
 818  0x000064B4: mul r1.x, r1.x, cb0[30].w
 819  0x000064D4: and r1.y, r1.z, l(16)
 820  0x000064F0: mad r2.x, -r2.z, l(0.032258), l(1.000000)
 821  0x00006518: add r1.z, -r2.x, l(1.000000)
 822  0x00006538: mad r2.y, r18.y, r1.z, r2.x
 823  0x0000655C: mov r18.w, l(1.000000)
 824  0x00006570: movc r1.yz, r1.yyyy, r2.xxyx, r18.wwyw
 825  0x00006594: mul r1.x, r15.x, r1.x
 826  0x000065B0: mul r1.x, r1.y, r1.x
 827  0x000065CC: add r2.xyz, -r0.xyzx, cb0[30].xyzx
 828  0x000065F0: mad r0.xyz, r1.xxxx, r2.xyzx, r0.xyzx
 829  0x00006614: div r1.x, -r1.w, cb6[8].z
 830  0x00006638: add r1.x, r1.x, -cb6[8].y
 831  0x0000665C: add r1.y, l(1.000000), -cb6[8].y
 832  0x00006680: div r6.z, r1.x, r1.y
 833  0x0000669C: sample_l_indexable(texture3d)(float,float,float,float) r1.xyw, r6.xyzx, t19.xywz, s1, l(0.000000)
 834  0x000066D0: sample_l_indexable(texture3d)(float,float,float,float) r2.xyz, r6.xyzx, t20.xyzw, s1, l(0.000000)
 835  0x00006704: mad r0.xyz, r0.xyzx, r2.xyzx, r1.xywx
 836  0x00006728: mad r1.xyw, r0.xyxz, r7.wwww, r7.xyxz
 837  0x0000674C: mul r1.z, r1.z, cb7[3].z
 838  0x0000676C: add r1.xyw, -r0.xyxz, r1.xyxw
 839  0x0000678C: mad o0.xyz, r1.zzzz, r1.xywx, r0.xyzx
 840  0x000067B0: mul_sat r0.y, r0.w, l(0.100000)
 841  0x000067CC: mov r0.xzw, l(255.000000,0,255.000000,255.000000)
 842  0x000067EC: mul r0.xyzw, r0.xyzw, l(0.000000, 255.000000, 0.000000, 0.000000)
 843  0x00006814: ftou o1.xyzw, r0.xyzw
 844  0x00006828: mul r0.x, r18.x, l(65.535004)
 845  0x00006844: ftou r0.x, r0.x
 846  0x00006858: umin o2.y, r0.x, l(0x0000ffff)
 847  0x00006874: mov o0.w, l(1.000000)
 848  0x00006888: mov o2.x, l(0)
 849  0x0000689C: ret 
// Approximately 850 instruction slots used